### ISSUE TITLE
Parts being generated in Fade colour when first displayed

### ISSUE THREAD

**Issue by d-j-m-0** [trevorsandy/lpub3d#100]
### Subject
There are occasions when the first time a part is displayed in the image, it is being displayed in the fade colour rather than the actual colour.

### Environment
* Version of LPub3D - 2.3.0 Revision 0 Build 887
* Operating system - Windows 10, x86_64

### Screenshots
Have a look on the second page in this PDF (generated with LPub3D version 2.2)
[snottingen_switch_left_v1.pdf](https://github.com/trevorsandy/lpub3d/files/2381884/snottingen_switch_left_v1.pdf)
and compare the same page in this PDF (as generated with LPub3D version 2.3.0)
[snottingen_switch_left_v1.pdf](https://github.com/trevorsandy/lpub3d/files/2381883/snottingen_switch_left_v1.pdf)

### Steps to reproduce
Open the mpd in the attached zip file.
Look in the second page of the instructions, step 3. The 1x5 yellow Technic Liftarm is shown in the assembly in the fade colour.
[snottingen_switch_left_v1.zip](https://github.com/trevorsandy/lpub3d/files/2381886/snottingen_switch_left_v1.zip)

### Expected behaviour
The part should be displayed in its designated colour for the first step in which it is displayed.

### Actual behaviour
Some, but not all, parts are being displayed using the fade colour.

### Workaround
No known workaround.

### Solution suggestion
No idea.

**Comment by d-j-m-0** [comment]
My fade previous step setting (via menu option Configuration/Preferences) has "Enable Fade Previous Steps" ticked, "Use Global Fade Colour" ticked and the colour is set to Trans_Very_Light_Blue.

My Log file is attached.

[LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/2387405/LPub3DLog.txt)

Regards,

David

**Comment by trevorsandy** [comment]
Excellent thanks. 

I'll take a look. 

Cheers,

**Comment by trevorsandy** [comment]
This may not be related to the behaviour you reported but it could be good to know that your log shows mapping to the LDraw unofficial 'parts' folder as a search path. This folder, and 'p' also, is forbidden to be included as search path for both official and unofficial parts. Just a reminder that LPub3D does not read the parts and p LDraw disc subfolders when loading 'custom' parts. This design is to reduce cycles. There is no reason to cycle through loading these items from your LDraw disc folder as it is expected the same files are loaded during startup when both archive libraries are placed in memory. 

What this means is that, against instructions to not place custom parts in these locations, if custom parts are indeed placed there, these parts will not be loaded into memory on model file load or or application startup. 

Your log shows over 2700 lines of this return:

```
ArchiveParts::RecurseAddDir(const class QDir &,class QStringList &) @ln 433 "Encountered excluded LDraw directory: C:\\Users\\Public\\Documents\\LDraw\\Unofficial\\parts\\003497g.dat." 
ArchiveParts::RecurseAddDir(const class QDir &,class QStringList &) @ln 433 "Encountered excluded LDraw directory: C:\\Users\\Public\\Documents\\LDraw\\Unofficial\\parts\\003497h.dat." 
```

Cheers,

**Comment by trevorsandy** [comment]
Corrected. This was caused by a single, misplaced line of code!

![screenshot - 18_09_2018 02_29_21](https://user-images.githubusercontent.com/13388970/45657437-ac433780-baea-11e8-9b52-0583797a6e45.png)

Cheers,
