### ISSUE TITLE
Checking Use alternative Draw LDConfig does not work

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#103]
### Subject
Checking Use alternative Draw LDConfig does not work.
Setting it has no result and the setting is not saved.
Closing LPub3D and restarting the setting is gone.

### Environment
* Version of LPub3D - 2.3.0 Revision 0 build 887 hash g1b66997
* Operating system - Windows x86_64

### Configuration

* LPub3D installation path
  - Windows: `C:\Program Files\LPub3D` [x86_64]

* Application data path
  - Windows: `%USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\`

* Registry Extract
  - Windows (installed): `reg export "HKEY_CURRENT_USER\Software\LPub3D Software" %USERPROFILE%\Desktop\LPub3D_Hive.reg`

* Renderer configuration files
  - `[Application data path]/3rdParty\ldview-4.3\config\ldview.ini`
  - `[Application data path]/3rdParty\ldview-4.3\config\ldviewPOV.ini`

### Steps to reproduce
Choosing Configuration > General > check Use alternative LDraw LDConfig > Point to file = c:\users\public\documents\ldraw\ldconfig.ldr and click OK.

### Expected behaviour
It should render with my settings in my ldconfig.ldr file

### Actual behaviour
Render is not with custom settings. Setting is not saved on closing and restarting.

**Comment by trevorsandy** [comment]
Thanks for reporting this behaviour Jaco. I'll take a look. 

Do you mind sharing your alternate LDConfig file if it can be useful and efficient to test with ? You can send it via email if you prefer.

Cheers,

**Comment by jacovandermolen** [comment]
Nothing really special in there. Only the line color of black bricks = white and white bricks are black.
I did notice an entry in the registry:
"AltLDConfigPath"="C:\\Users\\Public\\Documents\\LDraw\\LDConfig.ldr"
It seems it wrote it, but LPub3D does not pick it up.
I have sent you an e-mail to my last known gmail address from you.

**Comment by trevorsandy** [comment]
Corrected. The alternate LDConfig file is loaded during the LDraw folder preferences execution. The routine was exiting after successfully detecting the LDraw folder so never getting to the alternate LDConfig block. This was why 'nothing happens' after configuring the alternate path in Preferences.  

As the LDCoinfig file globally affect parts, a restart is requird to fully configue this option when initially selected. I've added the appropriate prompts for smart-restart which means LPub3D will remember where in your currently opened document your were before restarting.

Cheers,
