### ISSUE TITLE
Enable Highlight Current Step does not render a line around all new parts in a step

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#104]
### Subject
Enable Highlight Current Step does not render a line around all new parts in a step.

### Environment
* Version of LPub3D - 2.3.0 Revision 0 Build 887 Hash g1b66997

### Steps to reproduce
Check Preferences > General > Enable Highlight Current Step > Render page 1 and 2.

### Expected behaviour
A yellow line should be rendered around every new part in a step.

### Actual behavior
The first 3 steps on page 1 are OK. On page 2 step 4 two new bricks for that step do not have the line.
Next step on same page also has 2 new bricks without line

I have sent you an e-mail with LDraw file and Pdf for page 1 and 2.

**Comment by trevorsandy** [comment]
What renderer are you using, This feature is optimal with LDGLite and the new Native renderer based on the 3DViewer (LeoCAD) ?

Can you send a snapshot of your initial and renderer Preferences panes ?

Cheers,

**Comment by jacovandermolen** [comment]
I use LDView that comes with LPub.
I'll try to take some screenshots later.

**Comment by trevorsandy** [comment]
Understood - take a look at Issue #47 for some details around the implementation and capabilities of this feature.

Cheers,

**Comment by trevorsandy** [comment]
Corrected. 

Same as #100.

Cheers,

**Comment by jacovandermolen** [comment]
![preferences_general fw](https://user-images.githubusercontent.com/32261647/45688473-bcdac880-bb51-11e8-8fbe-6236da08d724.png)
![preferences_rendering fw](https://user-images.githubusercontent.com/32261647/45688482-c3694000-bb51-11e8-9b9a-844d1f344669.png)

I think these are the screenshots you need?
