### ISSUE TITLE
Does not download complete.zip

### ISSUE THREAD

**Issue by probonopd** [trevorsandy/lpub3d#11]
Says "Retrieving Download..." for a second, then closes the downloading window and does nothing. Application does not launch but only shows splash screen.

Build log:
https://s3.amazonaws.com/archive.travis-ci.org/jobs/203600807/log.txt

.travis.yml:
https://github.com/probonopd/lpub3d/blob/patch-1/.travis.yml

Linux [AppImage](http://appimage.org/) for 2014-ish and later distributions (just download, [set executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run):
https://transfer.sh/5uiIU/lpub3d-x86-64.appimage

**Comment by trevorsandy** [comment]
The complete.zip and lpub3dldrawunf.zip defined in .traxis.yml are incomplete 'test' files and are ONLY meant to facilitate the build process. 
If you want Travis to also perform make install, you must modify your  .travis.yml to use the actual, and much larger, .zip files. 
You can see the actual paths to the real zip files in any of the CreateXXX.sh scripts available at [/lpub3d/builds/linux](https://github.com/trevorsandy/lpub3d/tree/master/builds/linux) in the source

**Comment by probonopd** [comment]
Why doesn't it download the correct one then at runtime?

**Comment by probonopd** [comment]
And where in usr/... do I have to put/extract http://www.ldraw.org/library/unofficial/ldrawunf.zip and http://www.ldraw.org/library/updates/complete.zip?

**Comment by trevorsandy** [comment]
/usr/share/lpub3d see Install keyword in [mainApp.pro](https://github.com/trevorsandy/lpub3d/blob/master/mainApp/mainApp.pro)

**Comment by trevorsandy** [comment]
I haven't tested the LDraw archive download prompt at startup feature since producing the Linux distros, opting to package the archives instead. I'll take a look.

**Comment by trevorsandy** [comment]
Fixed at commit [9238499](https://github.com/trevorsandy/lpub3d/commit/9238499ee576ee71d4691d8132f93246c5a4e9a5)

**Comment by probonopd** [comment]
Thanks!

**Comment by probonopd** [comment]
Would you be interested in having Travis CI build and upload an AppImage on each run? If so, check out https://github.com/probonopd/lpub3d/blob/patch-1/.travis.yml

**Comment by trevorsandy** [comment]
Looks good. I'll give it a go. Thanks for offering. Cheers,
