### ISSUE TITLE
Bug: automatic call-out arrow placement does not take into account assembly rotation

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#110]
So this bug has been in LPub for a loooong time. I never took the time to submit it, plus I was (and still am) not sure if it is an actual bug or just a limitation of the software.
The (wrong) behavior is still in LPub3D 2.3 so I figured I'd post it here now.

The problem is quite simple: when creating a call-out LPub3D automatically adds an arrow pointing at the submodel in the parent model. However, it does not take into account any ROTSTEPs of the parent model, it always points the arrow towards were the submodel would be if the parent model has default (for example ROTSTEP END or ROTSTEP REL 0 0 0 ) rotation.

See the image below as an example. The arrow is LPub3D placed, I did not move it manually. I did add a red circle in the image to show where the submodel is (and where the arrow should point).

![image](https://user-images.githubusercontent.com/12005521/45697377-fc131480-bb65-11e8-84b8-84f9f051e703.png)

**Comment by trevorsandy** [comment]
Nice catch. And thanks for the clear and precise write-up. I'll add take a look but any correction will likely be after 2.3.1. 

Of course for anyone else reading this, the workaround is to manually drag the arrow to the desired location, but  indeed, this should and could be corrected.

Cheers,

**Comment by trevorsandy** [comment]
I took a quick look and noticed that, indeed, the pointer tip placement function does apply the parent ROTSTEP transform before calculating the tip's point. Can you share an exmple model file that produces the behaviour you illustrate in the snapshot?

Cheers,

**Comment by Landcross** [comment]
I don't have an example file at hand (I can't share the model from the above image), but I'm pretty sure it happened to me with basically every model and every rotation I ever used the past 1 or 2 years. Though I have to say I got used to the arrow being wrong so maybe I didn't noticed them being right in some cases.

Maybe worth noting is that in the case of the image above, the parent model is a submodel of the main model. No idea if that matters. I can do some testing (and if necessary sharing test-models) tomorrow evening. Thanks!

**Comment by trevorsandy** [comment]
Ok - thanks! 

You don't have to share an entire model file. A simple block showing the step before, step, step after is usually enough for me.

Cheers,

**Comment by Landcross** [comment]
Ok, a little earlier then expected, but I've got a sample model for you:
[sample.zip](https://github.com/trevorsandy/lpub3d/files/2395843/sample.zip)

There are 4 submodels in the main model for 4 different rotations (0, 90, 180 en 270/-90 degrees). You have to create the callouts yourself; I explicitly didn't include any LPub3D metadata to compare your results against mine. For me, LPub3D behaved exactly like I described above: the arrow-placement did not take into account the rotation of the parent model (except for the first callout of course, as that has no extra rotation besides default) and placed the arrow exactly where the submodel would be if the parent model had no rotation.

**Comment by trevorsandy** [comment]
Excellent - thanks. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected. 
Indeed, after a lot of digging I confirm the ROTSTEP value was not being accessed during the construction of the callout white/blue image (special image used to determine the optimal position point of the pointer tip - using an offset point). I've corrected this behaviour but there is still some disconnect between the rendered image, it's rotation and the position of the pointer tip. I believe, the issue there is in the algorithm to determine the offset point. 

Cheers,
