### ISSUE TITLE
Call-out placement 'relative to ...' dropdown is a bit broken

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#112]
The relative to ... placement options for call-outs is wrong. Currently it shows these options:
![image](https://user-images.githubusercontent.com/12005521/45865556-348d3b00-bd7e-11e8-82a6-9a56ac062337.png)

I'm not sure which options it should have, but I'm pretty sure that at least something's going wrong there. First of all, there is no 'Assembly' option to place relative to assembly which should be the default option. 

Secondly, if you open up the dialog window for a not yet explicitly placed call-out, the default option is Parts List. Yet, when you select a placement location without changing that it adds META comments for placement according to... ASSEM (thus assembly). If you, however, select another option (such as 'Plug') and then go back to Parts List it does correctly place according to parts list.

As a sidenote, I'm thinking that LPub3D doesn't properly place call-outs relative to Assembly in regards to INSIDE and OUTSIDE for quite a while now but I never looked into it. I'll take a look at that and will report my findings (if any) in a separate issue.

**Comment by trevorsandy** [comment]
Confirmed bug and regression. Taking a look...
