### ISSUE TITLE
Bug: export to pdf dialog is not limited to 1 option

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#114]
When opening the export to pdf dialog, I get to see this:
![image](https://user-images.githubusercontent.com/12005521/46023161-5838e400-c0e4-11e8-8aa8-5eec2c0d1e10.png)

I don't think that's supposed to happen ;)

Furthermore, I can even select the third one without deselecting the others:
![image](https://user-images.githubusercontent.com/12005521/46023187-6a1a8700-c0e4-11e8-8f16-08fa1422a671.png)

In fact, I can select any combination of options; I'm pretty sure it should be limited to just one option.

**Comment by trevorsandy** [comment]
Already captured in the tickets below and treated in 2.3.1, 
see:
- #107
- #99
