### ISSUE TITLE
General standardization

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#116]
A bit mugging maybe, but I'd like to see some more standardization in GUI, terms and jargon.

The Page Globals Setup is too small. I have to pull the window to see all options.

The word "color" is spelled "colour" on Preferences > Use Global Fade Colour . I'd use either color or colour, preferably "color". Maybe on other locations? Other words, typo's, spelling? If I see one, I'd let you know.

Parts are sometimes referred to as Pieces. I'd like to see either word, preferably Part or Brick.

**Comment by trevorsandy** [comment]
Treated.
