### ISSUE TITLE
Page navigation gives multiple errors

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#117]
### Subject
Page navigation gives multiple errors

### Environment
* Version of LPub3D - 2.3.1
* Operating system - Windows (x86,x86_64)

### Logs
* Application Log: `[Application data path]/logs/LPub3DLog.txt`

2018-09-28T07:58:21.150 ERROR "Did not receive 3DViewer CSI path for ." 
2018-09-28T07:58:21.997 ERROR "Could not 3DViewer with ." 
2018-09-28T07:58:22.511 ERROR "Could not load 3D Viewer with CSI name: pyramid.dat;2;1" 

### Screenshots
![1](https://user-images.githubusercontent.com/32261647/46190645-ba683380-c2f4-11e8-8015-66c744656e21.png)
![2](https://user-images.githubusercontent.com/32261647/46190646-bcca8d80-c2f4-11e8-82e7-89472d955fae.png)
![3](https://user-images.githubusercontent.com/32261647/46190648-be945100-c2f4-11e8-97d8-8520c1b621f6.png)

### Steps to reproduce
Open pyramid.dat
Navigate from page 1 to 4
Navigate back to page 1

### Expected behaviour
No errors should occur?

### Actual behaviour
I get 3 dialogs with errors

### Workaround
Not found

**Comment by trevorsandy** [comment]
Something is definitely broken. I'll take a look.

**Comment by jacovandermolen** [comment]
Yep. Continues Page Processing gives errors too.

Op vr 28 sep. 2018 om 08:27 schreef Trevor SANDY <notifications@github.com>:

**Comment by jacovandermolen** [comment]
Yep. Continues Page Processing gives these kind of errors too.

**Comment by trevorsandy** [comment]
Looks like some bad plumbing is raising it's head. It's a bit surprising because the block causing the trouble wasn't even supposed to be enabled until 2.4.0. 

Anyway, I've revoked 2.3.1 until I fix this behaviour. Shouldn't take more than a few minutes but it'll take some time to run all the regression tests.

Cheers,

**Comment by trevorsandy** [comment]
Corrected
