### ISSUE TITLE
Batch generating export to pdf

### ISSUE THREAD

**Issue by TheRoby** [trevorsandy/lpub3d#12]
Hi,

Is it possible to add a new option that generates a list of pdf ?

I have a lot of ldr file to convert ...

if it's possible to use lpub3d_x64.exe test.ldr /pdf test.pdf (or in the gui ?)

Thanks :)

**Comment by trevorsandy** [comment]
Yes, it is possible. I've added the request to the enhancement queue. Cheers,

**Comment by TheRoby** [comment]
Thank you :)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        De: Trevor SANDYEnvoyé: vendredi 24 février 2017 16:54À: trevorsandy/lpub3dRépondre à: trevorsandy/lpub3dCc: TheRoby; AuthorObjet: Re: [trevorsandy/lpub3d] Batch generating export to pdf (#12)Yes, it is possible. I've added the request to the enhancement queue. Cheers,

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/trevorsandy/lpub3d","title":"trevorsandy/lpub3d","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/trevorsandy/lpub3d"}},"updates":{"snippets":[{"icon":"PERSON","message":"@trevorsandy in #12: Yes, it is possible. I've added the request to the enhancement queue. Cheers,"}],"action":{"name":"View Issue","url":"https://github.com/trevorsandy/lpub3d/issues/12#issuecomment-282326250"}}}

**Comment by TheRoby** [comment]
Why do you have removed this ? :(

Thank's for all :)

**Comment by trevorsandy** [comment]
Actually, I moved it to LPub3DNext

**Comment by TheRoby** [comment]
Thank you !:)                                                                                                                                                                                                                                                                                                                                                   De: notifications@github.comEnvoyé: 28 avril 2018 16:21À: lpub3d@noreply.github.comRépondre à: reply@reply.github.comCc: github@macuba.net; author@noreply.github.comObjet: Re: [trevorsandy/lpub3d] Batch generating export to pdf (#12)  Console command flags enabled:
Usage:
<application name> [options] [ldraw file]
[ldraw file]:
Absolute file path and name with .ldr, .mpd or .dat extension.
[options]:
Process ldraw file and generate images in png format.
-pf, --process-file
Export instruction document or page images. Used with export-option. Default is pdf document.
-pe, --process-export
Turn of reset the LDraw file and image caches. Used with export-option change. Default is off.
-x, --clear-cache
Set page range - e.g. 1,2,9,10-42. Default is all pages.
-r, --range <page range>
Set output format pdf, png, jpeg or bmp. Used with process-export. Default is pdf.
-o, --export-option <option>
Designate the pdf document save file using absolute path.
-f, --pdf-output-file <path>
Designate the png, jpg or bmp save folder using absolute path.
-d, --image-output-directory <directory>
Set renderer ldglite, ldview, ldview-sc or povray. Default is ldview.
-p, --preferred-renderer <renderer>
Cheers,

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by trevorsandy** [comment]
Complete list of console commands for v2.3.0.

```
// LPub3D commands
-pf,  --process-file: Process ldraw file and generate images in png format.
-pe,  --process-export: Export instruction document or images. Used with export-option. Default is pdf document.
-fs,  --fade-steps: Turn on fade previous steps. Default is off.
-fc,  --fade-steps-colour <LDraw colour code>: Set the global fade colour. Overridden by fade opacity - if opacity not 100 percent. Default is Very_Light_Bluish_Grey
-fo,  --fade-step-opacity <percent>: Set the fade steps opacity percent. Overrides fade colour - if opacity not 100 percent. Default is 50 percent.
-icr, --ignore-console-redirect: Turn off automatic launch of command console session if one does not exist - batch mode only. Default is off.
-hs,  --highlight-step: Turn on highlight current step. Default is off.
-hc,  --highlight-step-colour <Hex colour code>: Set the step highlight colour. Colour code optional. Format is #RRGGBB. Default is Bright Yellow (#FFFF00)
-of,  --pdf-output-file <path>: Designate the pdf document save file using absolute path.
-rs,  --reset-search-dirs: Reset the LDraw parts directories to those searched by default. Default is off.
-x,   --clear-cache: Turn off reset the LDraw file and image caches. Used with export-option change. Default is off.
-r,   --range <page range>: Set page range - e.g. 1,2,9,10-42. Default is all pages.
-o,   --export-option <option>: Set output format pdf, png, jpeg or bmp. Used with process-export. Default is pdf.
-d,   --image-output-directory <directory>: Designate the png, jpg or bmp save folder using absolute path.
-p,   --preferred-renderer <renderer>: Set renderer native, ldglite, ldview, ldview-sc or povray. Default is native.
-v,   --version: Output LPub3D version information and exit.

// 3DViewer (LeoCAD) commands [not tested]
-i,   --image <outfile.ext>: Save a picture in the format specified by ext.
-w,   --width <width>: Set the picture width.
-h,   --height <height>: Set the picture height.
-f,   --from <time>: Set the first step to save pictures.
-t,   --to <time>: Set the last step to save pictures.
-s,   --submodel <submodel>: Set the active submodel.
-c,   --camera <camera>: Set the active camera.
-obj, --export-wavefront <outfile.obj>: Export the model to Wavefront OBJ format.
-3ds, --export-3ds <outfile.3ds>: Export the model to 3D Studio 3DS format.
-dae, --export-collada <outfile.dae>: Export the model to COLLADA DAE format.
-html,--export-html <folder>: Create an HTML page for the model.
--viewpoint <front|back|left|right|top|bottom|home>: Set the viewpoint.
--camera-angles <latitude> <longitude>: Set the camera angles in degrees around the model.
--orthographic: Make the view orthographic.
--highlight: Highlight pieces in the steps they appear.
--shading <wireframe|flat|default|full>: Select shading mode for rendering.
--line-width <width>: Set the with of the edge lines.
--html-parts-width <width>: Set the HTML part pictures width.
--html-parts-height <height>: Set the HTML part pictures height.
-vv, --viewer-version: Output 3DViewer - by LeoCAD version information and exit.

// Help
-?,  --help: Display this help message and exit.
```
