### ISSUE TITLE
Native renderer seems to swap PLI and assembly scales

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#125]
I haven't looked into this very well as I don't use the native render and I'm sinking all my time into trying to get LPub3D's output to be again like it used to be before I upgraded to 2.3 as I need a final render for a 'customer'. But, from a quick look it looks like the native renderer swaps the scales of the PLI and the assembly renderings. Or at least it does something wrong as my PLI images were larger than my assembly images which should be (and is using LDView) the other way around.

LPub3D 2.3.2
Windows 10 Pro x64

**Comment by trevorsandy** [comment]
Merlijn - the Native renderer uses the PLI and CSI configuration settings to render the respective content. However, the camera distance setting does not follow the L3P-based algorithm used by the other renderers. 

You can get some more insight from the ticket “[Feature] Add "Native" renderer based on 3DViewer (LeoCAD library) #71.”

Cheers,
