### ISSUE TITLE
LPub3D-specific LDView settings still don't work

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#126]
So there was issue #98 which you said was solved. However, with 2.3.1 and 2.3.2 the LDView settings still don't work for me. No matter what I do in LPub3D's LDView settings, nothing changes in the images. Not after a refresh, not after a restart. Never.

Furthermore, I need to render a final product for someone and I just can't anymore (at least not with the quality I used to use for years). I tried installing 2.1, but I can't change the render settings in there either, nor can I point LPub3D to my own instance of LDView. And in fact, it produces the exact same images as with 2.3.2 which really baffles me. It seems like no matter what settings I choose, no matter what version I even install (I tried 2.1 until 2.3.2) I can't change the damn image quality anymore :(

**Comment by trevorsandy** [comment]
Ok, help me understand a bit more what is going on with your LPub3D instance (check if ok):
- [ ] Are you able to ‘persist’ your settings in the LDView configuration dialogue ?
- [ ] Can you confirm (review before and after settings) that your settings are captured in LDView.ini ?
- [ ] Looking at the log, can you see that your LDView.ini file is ‘passed’ to the renderer ?
- [ ] Can you render an image (using the renderer command captured from the log) from a console session ?
- [ ] Are you able to modify your rendered image from a console session - i.e. without using the GUI ?
- [ ] Do you know the version of LPub3D, and the specific settings that did produce the desired image quality ?

Cheers,

**Comment by Landcross** [comment]
Below is all tested using LPub3D 2.3.2 on Windows 10 Pro x64.

* [x]  **Are you able to ‘persist’ your settings in the LDView configuration dialogue ?** If you mean that the settings stay what they are in the settings screen in LPub3D's LDView settings dialog: then yes.
* [ ]  **Can you confirm (review before and after settings) that your settings are captured in LDView.ini ?** There are two ldview.ini files, when I change settings in LPub3D, it looks like they don't change at all. Also, I'm not sure why EdgeThickness is passed as separate parameter to LDView and not in the .ini file, but it also seems to stay at 1 no matter what I select in the dialog (edge thickness is also a setting I want to change).
* [ ]  **Looking at the log, can you see that your LDView.ini file is ‘passed’ to the renderer ?** Yes.
* [ ]  **Can you render an image (using the renderer command captured from the log) from a console session ?** Yes.
* [ ]  **Are you able to modify your rendered image from a console session - i.e. without using the GUI ?** Not sure how to interpret your question. I can manually change the .ini file and the output does change in LPub3D.
* [x]  **Do you know the version of LPub3D, and the specific settings that did produce the desired image quality?** Not 100%, it must've been either 2.1 or 2.2(.2) but I think 2.2. It was an install that I had for quite some time and every now and then I just updated it (automatically, not manually), I never completely uninstalled it. I do know that back in the day when I installed it I had to set my own path to my own LDView installation and that LPub3D didn't come with an included LDView. I do remember reading something late last year or earlier this year that someone thought it was weird that LPub3D came with its own LDView nowadays and I was kinda confused as I didn't notice any changes. Maybe somehow my own LDView instance stayed in use through all the updates until I upgraded to 2.3. I believe I did uninstall my previous version of LPub3D before installing 2.3 to start with a clean slate after all those year(s) but again, I'm pretty bad at remembering things :(

But... Even if I finally get back my image quality, there's still issue #102 which still kinda prevents me from rendering the final product :P

**Comment by trevorsandy** [comment]
* [x]  **Are you able to modify your rendered image from a console session - i.e. without using the GUI ?** The point of this question is to determine if you are able to change the quality of the rendered image from a console session - using either a stock LPub3D-generated command or one that has been modified. And yes, modifying the LDView.ini file does count as modifying the command.

> But... Even if I finally get back my image quality, there's still issue #102 which still kinda prevents me from rendering the final product :P

Ok, if #102 was not treated with the updates in v2.3.1/2.3.2, the next option is to share an example file that produces the unexpected behaviour as discussed before:

> I can't share the file here in public, so if you want to take a look at the LDraw file I need to send it to you (Trevor) personally.

You can see my email address at Help->About LPub3D->Credits...

Cheers,

**Comment by trevorsandy** [comment]
After some more investigating, it looks like there are still some Gremlins in the LPub3D LDView settings panel on Windows. Some settings - e.g. Antialiasing are updated with the wrong value and other setting appear to be set elsewhere (not in LDView.ini) - I haven't tracked down exactly where yet, although the registry seems like the likely destination.

### Solution [Windows]

So until the I correct the LDView preferences dialogue in LPub3D, follow the steps below to definitively edit and update your settings in the LDView.ini (or LDViewPOV.ini for POV generation). Run the following command from a console session to launch the LPub3D instance of LDView (or your installed instance - it does not matter) **attached to the LPub3D LDView.ini** (or LDViewPOV.ini for POV generation settings). Once launched, you can use the GUI to set your preferences in the ini file. 

**[Windows] Launch LDView connected to LDraw.ini:**
`<LPub3D Path>\3rdParty\ldview-4.3\bin\LDView.exe -LDrawDir=<LDraw Path> -IniFile=<LPub3D Path>\3rdParty\ldview-4.3\config\ldview.ini`

It may be helpful to also open your LDView.ini settings file and review the settings as you apply your changes.

Steps:
1. Launch console session and enter LDView launch command.
![screenshot - 08_10_2018 09_17_36](https://user-images.githubusercontent.com/13388970/46596017-42132680-cadb-11e8-8976-03808f0d2c8d.png)

2. Cancel  the 'Select an LDraw model file' dialogue window
![screenshot - 08_10_2018 09_22_36](https://user-images.githubusercontent.com/13388970/46596138-c1085f00-cadb-11e8-8963-4d497c69aa00.png)

3. Launch the Preferences dialogue
![screenshot - 08_10_2018 09_24_03](https://user-images.githubusercontent.com/13388970/46596228-0d539f00-cadc-11e8-9eee-847a160bae53.png)

4. Set and apply your preferences - when finished, select Ok to close and that it!
![screenshot - 08_10_2018 09_25_40](https://user-images.githubusercontent.com/13388970/46596278-4c81f000-cadc-11e8-9250-2ae61a3756f4.png)
 
Cheers,

**Comment by Landcross** [comment]
The workaround does not seem to work for me. The LDView instance that opens after the command prompt seems to use the same settings as my local installation of LDView and does not seem to update (or use) any settings from the .ini file.

I was able to manually alter the .ini settings to closely resemble what I'm looking for. One 'important'  thing that I'm not able to change is the edge thickness. No matter what I try, it stays the same in the image generated by LPub3D...

I noticed that in the logs, the render commands contain `-EdgeThickness=1`. Is that the same as Edge lines Thickness under the tab Geometry in LDView? If so; why is it a separate parameter and not included in the .ini file and secondly; how do I change it? I added an EdgeThickness=2 in my ini file to no avail.

**Comment by trevorsandy** [comment]
The -EdgeThickness behaviour for LDView is already corrected, See #129. -EdgeThickness, was moved to a LPub3D managed parameter for the “true” fade feature and made modifiable in Preferences (see ‘Highlight line width’ just under highlight colour). However, as the edge/line thickness capability is not yet standardised across all the renderers, updating the line width was only exposed for LDGLite highlighting.

I’ve removed this parameter from LPub3D management in 2.3.3 (until I figure out a complete solution) so it will no longer be overridden when set in the ini.

Cheers,

**Comment by trevorsandy** [comment]
> The workaround does not seem to work for me. The LDView instance that opens after the command prompt seems to use the same settings as my local installation of LDView and does not seem to update (or use) any settings from the .ini file.

The certainty about computer programs is that they do exactly what they are programmed to do, expectedly or unexpectedly. LDView is programmed to use an ini file when such is supplied on the command line with the `-IniFile=<ini file path>`.

Here is the documented behaviour description from the LDView manual:

> Specifying an INI file
You can use `-IniFile=<path>` to have LDView use the specified INI file for its settings. This only works from the command line.

> Example INI file:

[General]
LDrawDir=/home/travis/ldraw
LineSmoothing=1
UseQualityStuds=1
Seams=0
ShowHighlightLines=1

> Note: if running in a Unix-like operating system, you must put a space after the equals sign if you want to use a ~ path. For example:

	LDView -IniFile= ~/SpecialSettings.ini

Cheers,

**Comment by trevorsandy** [comment]
The command you show here doesn’t seem to be successfully runnable in a Windows console session.

Try...
`”C:\Users\Merlijn\AppData\Local\LPub3D Software\3rdParty\ldview-4.3\bin\LDView64.exe” -LDrawDir=C:\Users\Merlijn\LDraw\Parts -IniFile=“C:\Users\Merlijn\AppData\Local\LPub3D Software\LPub3D\3rdParty\ldview-4.3\config\ldview.ini”`

When you are successful to launch LDView using the LPub3D INI, your LDView GUI will have a black background, just as the example above, because the background colour is not defined in the INI - unless you have changed it of course. In any event, setting a different background colour for your INI session is a good way to immediately determine if you have indeed launched your session with the INI.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

I've finally tracked down the source of the unexpected behaviour updating LDView INI files on Windows. Setting the command line variable in the class constructor that interfaces with the LPub3D LDView library was supposed to set the 'flag' instructing the library to use the INI versus the registry. Well, it turns out that function call was not getting the job done so the LDView library was being initialized with the default settings repository - the Windows Registry. This behaviour is unique to the LPub3D installer distribution for Windows. The portable distribution incidentally behaves as expected.

I've updated the behaviour to directly call, and status check, which you can see in the log, the function to set the INI file. My tests definitively show the LPub3D LDView Preferences panel is now updating the INI. Furthermore, turning off the update also definitively show the INI file is NOT being updated.

The only remaining behaviour to correct on this topic of updating the LDView INI, is setting up and applying the proper antialiasing values and to remove invalid default INI values from the distribution file. As there is ticket #130 which specifically addresses antialiasing. I'll conclude this ticket and continue with the antialiasing fixing there.

Cheers,
