### ISSUE TITLE
LPub3D LDView Anti-Aliassing settings incomplete

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#130]
In issue #97 I mentioned that the anti-aliassing setting in LPub3D's LDView dialog was incomplete. Trevor mentioned that he did not have all the options that I did. Then I noticed that I was using an older version of LDview and then issue was closed.

However, I noticed that even with the newest version of LDView, I still have all options available. These are the options I get in LPub3D's included LDView:
![image](https://user-images.githubusercontent.com/12005521/46651062-15c0de00-cb9f-11e8-8295-17f795b60c52.png)

And these are the options I see in LPub3D:
![image](https://user-images.githubusercontent.com/12005521/46651091-31c47f80-cb9f-11e8-8d1b-292e76a04d23.png)

And for the record, the above screenshot was taken in LPub3D's included LDView, version 4.4 alpha 2.

**Comment by trevorsandy** [comment]
That's right. This is another of the Gremlins I spoke about in #126.

> After some more investigating, it looks like there are still some Gremlins in the LPub3D LDView settings panel on Windows. Some settings - e.g. Antialiasing are updated with the wrong values...

The Antialiasing dropdown values are based on your GP so the list is not static. The 'Native' LDView GUI (including the Preferences panel) uses the native Windows UI API, while LPub3D uses a Qt-derived version. This means a lot of the back-room processing is different between the two interfaces - if you recall the FOV was previously an integer on my panel while it's a decimal on the native GUI for example. 

Anyway, use the steps I outlined in #126 to update your INI files until I fully align my LDView panel. And there is also the ability to directly update INI file from within LPub3D as well.

**NOTE**: If you add a **Preference Set** to your INI file, keep in mind you will be responsible for updating the search directories for the added set. LPub3D does not (yet) treat Preference Sets in the INI and LDView will completely ignore your general settings if you define a preference set so having your search directories in the general settings will have no effect. The resulting behaviour if you attempt to use the fade or highlight part functionality with LDView, your faded and highlighted parts will not be found and; consequently, not be rendered for your PLI or CSI images.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

All the LDView GUI outstanding items are now corrected.

Cheers,
