### ISSUE TITLE
Part List Content Displayed using fade colour

### ISSUE THREAD

**Issue by d-j-m-0** [trevorsandy/lpub3d#131]
### Subject
All the parts in the parts list for a step are being displayed using the fade colour rather then the actual colour of the part.

### Environment
* Version of LPub3D - 2.3.2 Revision 0 Build 988
* Operating system - Windows 10, x86_64

### Configuration
* LPub3D installation path
  - Windows: D:\Program Files\LPub3D
* Application data path
  - Windows: %USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\
* Registry Extract
  - Windows (installed): 
[fade_part_list_reg.txt](https://github.com/trevorsandy/lpub3d/files/2485604/fade_part_list_reg.txt)
* Renderer configuration files
[ldview_ini.txt](https://github.com/trevorsandy/lpub3d/files/2485612/ldview_ini.txt)
[ldviewPOV_ini.txt](https://github.com/trevorsandy/lpub3d/files/2485614/ldviewPOV_ini.txt)

### Logs
[LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/2485617/LPub3DLog.txt)

### Screenshots
N/A

### Steps to reproduce
Open the attached mpd.
Navigate to the second page. Look at the parts list.
[snottingen_buffer_mpd.txt](https://github.com/trevorsandy/lpub3d/files/2485618/snottingen_buffer_mpd.txt)

See attached PDF generated by LPub3D. 
[snottingen_buffer_v1.pdf](https://github.com/trevorsandy/lpub3d/files/2485620/snottingen_buffer_v1.pdf)

### Expected behaviour
Parts in the parts list should be generated using the actual colour of the part.

### Actual behaviour
All parts in the part lists are displayed using the fade colour.

### Workaround
None.

### Solution suggestion
?

**Comment by trevorsandy** [comment]
Already reported and corrected. see #128

Cheers,
