### ISSUE TITLE
Enable support for alternative LDraw libraries

### ISSUE THREAD

**Issue by trevorsandy** [trevorsandy/lpub3d#132]
###  Subject
Add support for LDraw VEXIQ Robotics and TENTE Construction libraries.

### Environment
Version of LPub3D - 2.3.0
Operating system - All

### Expected behaviour
LPub3D should provide the same level of integration and convenience as the default LEGO LDraw library

### Actual behaviour
LPub3D currently require additional configuration and setup to allow alternative LDraw library.

### Solution
Bundle TENTE and VEXIQ LDraw archive libraries to enable the same 'built-in' functionality as that available
for the currently bundled LEGO LDraw libraries (official and unofficial). 
Enable the capability to launch and/or switch LPub3D into either of the bundled libraries.
Enable the full scope of functionality in LPub3D across all the bundled libraries.

**Comment by trevorsandy** [comment]
Implemented.

**Comment by jasoloz** [comment]
Hi, TENTE parts are outdated. You can find the link to the updated zip file in the first post of this topic: 
https://www.tenteros.land/foro/viewtopic.php?p=1121#p1121
It is a Dropbox link, but Dropbox changes the URL each time I update the content (in the future I will put the parts on Github or similar). Meanwhile it is better to use the link of that post.
