### ISSUE TITLE
Bug: LDraw directory gets reset

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#134]
### Subject
The issue is quite simple. My LDraw Library path in the LPub3D Preferences -> General keeps getting kind of reset after closing and re-opening LPub3D. My library is located at: C:\Users\[username]\LDraw\Parts but LPub3D keeps resetting it to C:\Users\[username]\LDraw

### Environment
**NOTE:** I'm using a non-final release from your LPub3D-CI Appveyor page.
* Version of LPub3D: 2.2.3 revision 172 build 1007
* Operating system: Windows 10 Pro 64bit

**Comment by trevorsandy** [comment]
As you know, functionality under development in the CI environment is not sure to be stable or complete. I was not able to reproduce this behaviour with the release candidate but after looking at the build you are using, I believe the behaviour you were experiencing was likely treated in development commit 3060d3330a3b0d59326567116e7022680a609733 - Dev - Convert ldrawLib to multi-library support. 

Please open tickets against development builds in the development repository - Thanks.

Cheers,
