### ISSUE TITLE
Bug: assembled callout has wrong rotation

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#135]
### Subject
When I add an assembled callout for a submodel to the parent model, the rotation is screwed up. It looks like it applies an ABS rotation of 0 0 0. In the past, the assembled callout would be rotated the same as the parent model.

Here's an example image of the current behavior:
![image](https://user-images.githubusercontent.com/12005521/47268886-b081cb00-d556-11e8-8c06-9988ec0ea647.png)

Note that I'm using LDView as renderer and have the new 'Apply Camera Angles' setting set to 'Locally'.

### Environment
**NOTE:** I'm using a non-final release from your LPub3D-CI Appveyor page.
* Version of LPub3D: 2.2.3 revision 172 build 1007
* Operating system: Windows 10 Pro 64bit

**Comment by trevorsandy** [comment]
Corrected. 

This behaviour was introduced by the incomplete coverage of #102. The original correction was implemented to treat #92. 

Cheers,
