### ISSUE TITLE
Enhancement: add multiple next steps

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#136]
I have a feature suggestion for LPub3D. Currently, a user can right-click on a page and choose 'Add Next Step' to add the next step on the same page. It would be incredibly useful to have a second option to add all next steps.

I frequently have small submodels for which all steps fit on a single page. Now I either have to press 'Add Next Step' multiple times (which is pretty annoying cause you have to wait for the rendering after each step) or I can manually place a MULTI STEP BEGIN and END. A feature to automatically position all **remaining** steps on the current page would be really useful.

**Comment by trevorsandy** [comment]
Thanks for sharing your suggestion. While the core capability requested is not significant in effort, the overall effort will be significantly more than what is reasonable for the overall benefit of this feature. Here we have the classic 80:20 rule where 80 percent of the effort to implement this feature will be spent on addressing exceptions and edge cases that, if not treated, would degrade the overall user experience. For example, what to do if a user elects to add all remaining content  to a page when the content far exceeds the page's real-estate? Another, example is positioning the steps on a page automatically requires a considerably complex algorithm - especially when taking into account the number of different page editing features and scenarios currently treated by LPub3D.

Cheers,

**Comment by Landcross** [comment]
I wasn't thinking about any more advanced stuff like checking if the steps fit on a page, automatic page layout etc. Just an automatic replace for clicking 'Add Next Step' a bunch of times.

So, say I have a model like this and I'm on step 1:
```
3001.dat
0 STEP
3001.dat
0 STEP
3001.dat
0 STEP
3001.dat
0 STEP
```

The suggested feature would just create this:
```
0 !LPUB MULTI_STEP BEGIN
3001.dat
0 STEP
3001.dat
0 STEP
3001.dat
0 STEP
3001.dat
0 STEP
0 !LPUB MULTI_STEP END
```

Instead of manually going through this:
```
0 !LPUB MULTI_STEP BEGIN
3001.dat
0 STEP
0 !LPUB MULTI_STEP END
3001.dat
0 STEP
3001.dat
0 STEP
3001.dat
0 STEP
```
```
0 !LPUB MULTI_STEP BEGIN
3001.dat
0 STEP
3001.dat
0 STEP
0 !LPUB MULTI_STEP END
3001.dat
0 STEP
3001.dat
0 STEP
```
```
0 !LPUB MULTI_STEP BEGIN
3001.dat
0 STEP
3001.dat
0 STEP
3001.dat
0 STEP
0 !LPUB MULTI_STEP END
3001.dat
0 STEP
```
```
0 !LPUB MULTI_STEP BEGIN
3001.dat
0 STEP
3001.dat
0 STEP
3001.dat
0 STEP
3001.dat
0 STEP
0 !LPUB MULTI_STEP END
```

Another example of the feature where there are already a few steps on a page. You start with this:
```
0 !LPUB MULTI_STEP BEGIN
3001.dat
0 STEP
3001.dat
0 STEP
0 !LPUB MULTI_STEP END
3001.dat
0 STEP
3001.dat
0 STEP
```
And the feature will create this if you're on the same page as the existing multi-step:
```
0 !LPUB MULTI_STEP BEGIN
3001.dat
0 STEP
3001.dat
0 STEP
3001.dat
0 STEP
3001.dat
0 STEP
0 !LPUB MULTI_STEP END
```
Or this if you're on the next page (step 3):
```
0 !LPUB MULTI_STEP BEGIN
3001.dat
0 STEP
3001.dat
0 STEP
0 !LPUB MULTI_STEP BEGIN
0 !LPUB MULTI_STEP END
3001.dat
0 STEP
3001.dat
0 STEP
0 !LPUB MULTI_STEP END
```

So any formatting and layout and whatever still have to be done by the user, just like with clicking Add Next Step Multiple times. It would just save a lot of clicking and waiting. Hope that makes sense :)

**Comment by trevorsandy** [comment]
Ok, would a dialogue prompt “How many steps forward to append to this page ?” fit your expectation ?

**Comment by Landcross** [comment]
Hmm, I think that's even better than just adding all remaining steps :) Nice idea!
Though, it would only be useful if the dialog would also show how many steps there are remaining (both for error checking; you can't more steps than there are and for usability e.g. adding all steps, or splitting the steps evenly over 2 pages etc.).

**Comment by trevorsandy** [comment]
Certainly validating the model/submodel steps is part of the necessary exception handling.

Cheers,

**Comment by trevorsandy** [comment]
Et voila!

New page context menu item
![screenshot - 24_10_2018 23_23_48](https://user-images.githubusercontent.com/13388970/47462829-cefcf600-d7e4-11e8-99f8-51ed3ab259b7.png)

The number of steps presented is the number of steps available in the sub/model
![screenshot - 24_10_2018 23_24_19](https://user-images.githubusercontent.com/13388970/47462830-cefcf600-d7e4-11e8-9d83-ba98c9b78769.png)

Of course you should select the appropriate number of steps to fit your page's real estate
![screenshot - 24_10_2018 23_24_43](https://user-images.githubusercontent.com/13388970/47462831-cefcf600-d7e4-11e8-9e37-76d6ec222ff5.png)

Here we see the two steps specified are automatically added to the page
![screenshot - 24_10_2018 23_25_27](https://user-images.githubusercontent.com/13388970/47462832-cefcf600-d7e4-11e8-94fc-43e920f367d4.png)

We can continue to add steps to the page
![screenshot - 24_10_2018 23_26_22](https://user-images.githubusercontent.com/13388970/47462833-cefcf600-d7e4-11e8-8831-f6d245c5102c.png)

Here I add one more
![screenshot - 24_10_2018 23_26_49](https://user-images.githubusercontent.com/13388970/47462834-cefcf600-d7e4-11e8-8f09-13f39ad15623.png)

And the result
![screenshot - 24_10_2018 23_27_22](https://user-images.githubusercontent.com/13388970/47462836-cf958c80-d7e4-11e8-871e-e4b5e20177f7.png)

Cheers,
