### ISSUE TITLE
Export range dialog progress has a small mistake

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#144]
Nothing serious whatsoever ;) I think the image speaks for itself:
![image](https://user-images.githubusercontent.com/12005521/47614566-30052200-daa2-11e8-92e2-9250c0f2ee2e.png)
![image](https://user-images.githubusercontent.com/12005521/47614570-3d221100-daa2-11e8-9bc4-031dbda68d82.png)

I suppose the first number need to change. E.g."Exporting page 38 of 66 for range 300-365".

**Comment by trevorsandy** [comment]
Nope - I just forgot to add the 2nd incrementing count variable to the string. This is what it should have been and now is:

![screenshot - 05_11_2018 07_47_18](https://user-images.githubusercontent.com/13388970/47982209-319c9e80-e0cf-11e8-8178-84f8e48b8429.png)

![screenshot - 05_11_2018 07_47_51](https://user-images.githubusercontent.com/13388970/47982211-34978f00-e0cf-11e8-9cba-d6a857f748eb.png)


Cheers,
