### ISSUE TITLE
v2.3.3 - Arch Linux (4.18.16) - Submodels appear missing in publish view.

### ISSUE THREAD

**Issue by jorgevasquezp** [trevorsandy/lpub3d#147]
### Subject
Submodels appear as missing parts on publish view, but appear correctly in 3d viewer.

### Environment
LPub3D 2.3.3 Revision 0 Build 1024 Hash g41ae7de0
OS: Arch Linux x86_64 (4.18.16-arch1-1-ARCH)
OpenGL: 4.6.0 NVIDIA 410.66
GeForce GTX 1070/PCIe/SSE2 - NVIDIA Corporation

### Steps to reproduce
Open file LpubBugReport/SampleFile/BugReport.ldr

### Expected behaviour
Submodels should appear rendered in the publish view.

### Actual behaviour
Submodels appear as missing pieces ( Red boxes ) in publish view although they show up correctly in the 3dview.

### Workaround
I've found none so far.
I'v tried with ldglite, with which I'm having other problems, and that might solve my issue, but the native renderer I haven't been able to use.

### Solution suggestion
No idea, [sorry.]

( @url
[LpubBugReport.zip](https://github.com/trevorsandy/lpub3d/files/2531484/LpubBugReport.zip)
)

**Comment by trevorsandy** [comment]
Hi Jorge,
Thank you for reporting this behaviour. It's good to see someone using Arch! I'll take a look at the bundle you prepared as soon as I can.

Cheers,

**Comment by jorgevasquezp** [comment]
Absolutely, It's an awesome program your working on here. I'm so glad I'm not having to use wine to run Lpub4 any more. ;).

I think I deleted everything before starting the bugreport, but maybe I didn't clear the caches, do you think that might have prevented the stderr logs from being generated ? Ill try again and append them as soon as I can.

Cheers,

**Comment by trevorsandy** [comment]
Very well, 

It's not critical but it could be helpful if the source of the abnormal behaviour is the renderer - like LDGLite which I broke in 2.3.3:-(

Cheers,

**Comment by jorgevasquezp** [comment]
Hmmmmm.... 
I tried again, but still I get no stderr logs.
Is it possible that I disabled a preference for that ?
I know I've randomly seen them from time to time in different project folders. But now I'm not getting them.

**Comment by trevorsandy** [comment]
No, the std... logs are automatically touched when when the renderer is called. but the rendere is only called if an image to be rendered does not already exist or is out of date from the model file.

**Comment by trevorsandy** [comment]
Jorge - I took a quick look at the example file and noticed there is a reserved character `#` (and space) in the name. Normally, having spaces in the file path is not a problem so I'm not sure the space is contributing to the unexpected behaviour. Then again, space in the path on Unix systems are always precarious Nevertheless, when I load the example file as-is, the callout images are not loaded. When I remove the special character (and space). the model file loads as expected.

Here are some shots (fade previous steps is On); first, with special character and space in the name...

![screenshot - 03_11_2018 09_50_51](https://user-images.githubusercontent.com/13388970/47955299-593c1b80-df96-11e8-9b23-458d17b9321a.png)

And without...

![screenshot - 03_11_2018 09_56_54](https://user-images.githubusercontent.com/13388970/47955307-812b7f00-df96-11e8-8436-d3158ae64c14.png)

Cheers,

**Comment by jorgevasquezp** [comment]
Great I'll try that, as soon as I can. 
I think the pound signs come automatically from leocad whenever O create a new sub model.
Thanks for looking into it.

**Comment by trevorsandy** [comment]
Corrected. 

The origin of the unexpected behaviour relative to having a pound sign ‘#’ in the submodel name is described and treated in #157.

Cheers,
