### ISSUE TITLE
Add Next Steps on page with multiple steps results in nested multistep error

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#150]
### Subject
When using the new Add Next Steps feature on a page which is already a multi-step page, it adds a second MULTI_STEP BEGIN command which results in LPub3D showing a 'Nested Multi-Step not allowed' error.

### Environment
* Version of LPub3D - Lpub3D 2.3.3 Rev. 0 Build 1024
* Operating system - Windows 10 Pro x64

### Screenshots
Before adding next steps:
![image](https://user-images.githubusercontent.com/12005521/47962910-e4172780-e023-11e8-9e9f-5341c9f7a1c0.png)
![image](https://user-images.githubusercontent.com/12005521/47962915-eb3e3580-e023-11e8-879b-52829758c673.png)

After adding (6) next steps:
![image](https://user-images.githubusercontent.com/12005521/47962906-cfd32a80-e023-11e8-8e0c-5ac0a9732b83.png)
![image](https://user-images.githubusercontent.com/12005521/47962927-4c660900-e024-11e8-8332-eff61a4559b7.png)

Other than the error message, LPub3D does not crash and it shows the 8 steps total perfectly fine on the page which is nice error handling I think.

### Steps to reproduce
Add a few steps on a page, then add more steps using the Add Next Steps feature.

### Expected behaviour
All the selected steps on a page, but without errors.

### Actual behaviour
All the selected steps on a page, but with errors.

**Comment by trevorsandy** [comment]
Corrected.
