### ISSUE TITLE
Part files in excludedParts.lst are excluded from the PLI?

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#151]
### Subject
Parts in excludedParts.lst are shown in the PLI. 

Although the current implementation of the excludedParts.lst is to support part count during model file load, there is a one to one correlation between excluding parts from the part count and also excluding them from the PLI. Therefore, parts defined in excludedParts.lst should also automatically be excluded from the PLI.

### Environment
LPub3D 2.3.3

### Steps to reproduce
I have downloaded and used helper files (arrows).
These are standard in the excludedParts.lst file

### Expected behaviour
Parts defined in excludedParts.lst should also automatically be excluded from the PLI.

### Actual behaviour
The parts show up in the PLI by default.
Ignore the parts in the PLI like this:
```
0 !LPUB PLI BEGIN IGN
1 4 50 0 -20 0 0 1 0.707 0.707 0 -0.707 0.707 0 HashL3.dat
0 !LPUB PLI END
```

### Solution suggestion
When one puts a file in the excludedParts.lst it should not be shown in the PLI (or BOM).

**Comment by trevorsandy** [comment]
Jaco, the excludedParts.lst use case and implementation was solely to support achieving a more accurate part count at model file load. There was no intention to duplicate the currently available PLI management functionality. 

Cheers,

**Comment by jacovandermolen** [comment]
Ah, OK. Then I misunderstood its usage.

**Comment by trevorsandy** [comment]
Considering your expectation, it may make sense to extend the “excluded” functionality to automatically exclude from the PLI, parts defined in excludedPart.lst. 

If you agree, I’ll update this ticket to a change.

Cheers,

**Comment by jacovandermolen** [comment]
That would be a very nice addition to the features! Agreed ;-)

**Comment by trevorsandy** [comment]
Implemented.

Cheers,
