### ISSUE TITLE
Wish: add a thin line in choosen color around pointers

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#154]
### Subject
I have a wish: add a thin line in chosen color around pointers.

The reason for this is that the most convenient color for the border of a callout is black.
Hence, the pointers (lines and arrowhead) are black too.
In models with black parts, where the pointer runs over these black parts it can be hard to see the line and arrowhead.

A solution to this would be to draw a one-pixel line around the line and arrowhead.
Most convenient too would be a white line, but even better is to be able to define a color.
Would this be possible? As I understand these pointers are generated or drawn by QT?

LEGO uses this all the time in its instructions.
I came across a good PDF for example in another thread/issue here:
https://www.lego.com/biassets/bi/6187733.pdf
Step 5 page 6 shows a black pointer with a thin white line around it. The arrow head is over the black beam and clearly visible.
I have mad a quick and dirty LDraw model for this.
Here you can hardly see the arrowhead
![42061_page_3](https://user-images.githubusercontent.com/32261647/48093471-b7276800-e20f-11e8-835c-39471112e076.png)
Sure we can position it otherwise, but there are many occasions where this is not possible.

**Comment by jacovandermolen** [comment]
I've given this some thought and have a suggestion about how to perhaps achieve this.
If QT is not able to draw a line around, you can add two arrows?
One white (or specified color) that is 1 pixel or point larger than a second one on top that is black (or specified callout border color)
This is what I am aiming at:
![afbeelding](https://user-images.githubusercontent.com/32261647/48129177-0362be80-e289-11e8-966d-8e62f8fb14b5.png)

Original:
![afbeelding](https://user-images.githubusercontent.com/32261647/48129209-11b0da80-e289-11e8-9ac7-f258a4ed7545.png)

**Comment by trevorsandy** [comment]
Jaco, I've added this request to the queue. Others have also asked for this capability and I did take an initial look at implementing it some time ago. The only challenge is the amount of time and code required to get things like the segment joints, pointer shaft and pointer tip to properly display the border.

Cheers,

**Comment by jacovandermolen** [comment]
OK, great. I can indeed imagine this requires quite some coding and programming.
Pitty I am not a programmer and cannot help you there.

**Comment by trevorsandy** [comment]
Implemented.

Modify pointer Line and Border attributes from the context menu available at the arrowhead.
![screenshot - 01_12_2018 17_55_43](https://user-images.githubusercontent.com/13388970/49330685-5e3ebb80-f592-11e8-9315-b92b94287f6c.png)

Modify border attributes.
![screenshot - 01_12_2018 17_25_47](https://user-images.githubusercontent.com/13388970/49330608-3f8bf500-f591-11e8-84b7-c59a82c4f979.png)

Modify Line attributes.
![screenshot - 01_12_2018 17_26_28](https://user-images.githubusercontent.com/13388970/49330609-3f8bf500-f591-11e8-88c7-10f617c82545.png)

Example showing white border on black line.
![screenshot - 01_12_2018 17_32_00](https://user-images.githubusercontent.com/13388970/49330611-40248b80-f591-11e8-8f7f-8907bf303a32.png)

Example showing page pointers. Left pointer illustrates hidden tip and right pointer illustrates red border on yellow line.
![screenshot - 01_12_2018 17_32_34](https://user-images.githubusercontent.com/13388970/49330612-40248b80-f591-11e8-910a-e960b47a66d9.png)

It is not possible to add a pointer originating from a divider line.
![screenshot - 01_12_2018 18_02_36](https://user-images.githubusercontent.com/13388970/49330749-4d427a00-f593-11e8-9493-eba7d4acb2eb.png)

Example divider pointer.
![screenshot - 01_12_2018 17_34_28](https://user-images.githubusercontent.com/13388970/49330613-40248b80-f591-11e8-9485-82a9de8b67af.png)

Cheers,

**Comment by jacovandermolen** [comment]
Oh great! That looks very good!

**Comment by jacovandermolen** [comment]
Great feature! Love it.
Do I understand correctly that the border thickness of the callout no longer affects the thickness of the pointer, since now the pointer has it's own attributes. And that this goes for the color too?
This is very nice too!

**Comment by trevorsandy** [comment]
Hi Jaco, 
Yes, your understanding is accurate.

Cheers,

**Comment by jacovandermolen** [comment]
Hi Trevor,

Here is the progress of the instructions I am working on as a sort of
showcase for LDraw / LPub3D.
https://drive.google.com/open?id=1Fbv-PzhiQD2ZzpV6MfMhaB5GljS0qKrL


Op do 13 dec. 2018 om 13:32 schreef Trevor SANDY <notifications@github.com>

**Comment by trevorsandy** [comment]
Jaco,

Looks very good.

I am working on to following capabilities that I think you will appreciate:

- Vertical and horizontal dividers within a step group
- Pretty PLI part identifiers
- LEGO or BrickLink BOM part numbers
- Sticker identifier
- General Illustration
- 1:1 Illustration
- Right/Wrong illustration

Cheers,

**Comment by jacovandermolen** [comment]
OK, exciting!
I am curious what you mean by "Pretty PLI part identifiers" ;-)
