### ISSUE TITLE
Rendering with LDView is completely blank (OS X only)

### ISSUE THREAD

**Issue by welsmore** [trevorsandy/lpub3d#159]
Subject
When rendering a model in LPub3D on OS X, I get a completely blank window - but only on OS X and only with LDView.

Environment
* Version of LPub3D - 2.3.3 Revision 0 Build 1024 hash g41ae7de0
* Operating system - OS X Mojave 10.14.1

Configuration
* LPub3D installation path
  - macOS: `/Applications/LPub3D.app`
* Application data path
  - macOS: `~/Library/Application Support/LPub3D Software/LPub3D/`
* Registry Extract
  - macOS: Attached
[LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/2575995/LPub3DLog.txt)

* Renderer configuration files
Attached

### Logs
Attached

### Screenshots
Attached
<img width="543" alt="screenshot 2018-11-13 at 11 24 15" src="https://user-images.githubusercontent.com/3843590/48410509-afe3eb00-e736-11e8-8c72-79dd5bf620ef.png">
<img width="541" alt="screenshot 2018-11-13 at 11 24 11" src="https://user-images.githubusercontent.com/3843590/48410510-afe3eb00-e736-11e8-8c7a-c28332624ab6.png">
<img width="543" alt="screenshot 2018-11-13 at 11 24 00" src="https://user-images.githubusercontent.com/3843590/48410512-b07c8180-e736-11e8-86b4-4ae6d82fe10a.png">
<img width="545" alt="screenshot 2018-11-13 at 11 23 55" src="https://user-images.githubusercontent.com/3843590/48410513-b07c8180-e736-11e8-8008-683598f422a3.png">
<img width="1440" alt="screenshot 2018-11-13 at 11 23 56" src="https://user-images.githubusercontent.com/3843590/48410514-b1151800-e736-11e8-850c-037b298a6a76.png">
<img width="1484" alt="screenshot 2018-11-13 at 11 15 32" src="https://user-images.githubusercontent.com/3843590/48410515-b1151800-e736-11e8-9ba1-7a6c5dff380a.png">

### Steps to reproduce
Tell me how to reproduce this issue.
Provide a sample mpd/ldr file that reproduces the problem.
[Bowler Hat.zip](https://github.com/trevorsandy/lpub3d/files/2576016/Bowler.Hat.zip)

Very simple - open file and select LDView as a renderer and... no render! Change to ldglite or native and it's fine. Open the same LDR in LPub3D on Windows 10 with LDView - also fine. I've tried a couple of files and they are both the same. 
Libraries installed via Homebrew and LPub3D starts with no issues. LeoCAD 3D viewer shows the file, but does not render any textured parts (not sure if that's connected or an issue at all)

### Expected behaviour
Render ;-)

### Actual behaviour
No Render ;-)

### Workaround
Windows 10 at present

### Solution suggestion
I suspect this might be an LDView configuration or install bug? I'm happy to debug and provide any logging I can.

**Comment by trevorsandy** [comment]
Hi, Thanks for sharing this unexpected behaviour. 

Please have a look at #146 and let me know if the guidance described there corrects the behaviour.

Cheers,

**Comment by welsmore** [comment]
Hi Trevor. 

Installing XQuartz has indeed fixed this :-) Please feel free to close this one as a duplicate and thankyou!!!

Warren

**Comment by trevorsandy** [comment]
Excellent!

Cheers,
