### ISSUE TITLE
Bug: rotstep REL/END after rotstep ABS in a multi-step results in wrong rotation

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#160]
### Subject
This is a pretty specific issue, but I have been able to reproduce it in a test-model so it's definitely not a bug in my model META commands. The issue is as follows: if a multi-step contains an ABS rotstep and after that a ROTSTEP REL or ROTSTEP END, the resulting image is not rotated and seems to be ABS 0 0 0. See screenshots for examples.

### Environment
* Version of LPub3D: LPub 2.3.3
* Operating system: Windows 10 Pro x64

### Screenshots
This is an ABS rotstep, nothing wrong:
![image](https://user-images.githubusercontent.com/12005521/48775938-c528be80-ecce-11e8-9f5b-d238a878e90b.png)

Next step is a ROTSTEP END, also nothing wrong:
![image](https://user-images.githubusercontent.com/12005521/48775956-d1ad1700-ecce-11e8-87d6-17c486072dcf.png)

But when I put them in a multi-step, the second step's rotation becomes ABS 0 0 0 even though it's ROTSTEP END:
![image](https://user-images.githubusercontent.com/12005521/48775980-de316f80-ecce-11e8-9fc8-550ddb037bd2.png)

It happens with all steps in the multi-step after the ABS rotation, not just the one directly after the ABS rotation:
![image](https://user-images.githubusercontent.com/12005521/48776052-1173fe80-eccf-11e8-89d5-8f8e6bcf6475.png)

Also, sidenote: and ABS rotation after another ABS rotation in a multi-step does work fine.

### Steps to reproduce
Here's the test file I've been using. It's maybe bit of a mess cause I was trying things out, which combinations of steps did and did not work.

[test.zip](https://github.com/trevorsandy/lpub3d/files/2599861/test.zip)

**Comment by trevorsandy** [comment]
Corrected.

![screenshot - 02_12_2018 07_46_09](https://user-images.githubusercontent.com/13388970/49336684-68e76800-f607-11e8-8c07-9181fc8ea1f3.png)

![screenshot - 02_12_2018 07_46_19](https://user-images.githubusercontent.com/13388970/49336685-68e76800-f607-11e8-835b-3b149e5e34cc.png)

![screenshot - 02_12_2018 07_46_27](https://user-images.githubusercontent.com/13388970/49336686-697ffe80-f607-11e8-9b92-7c0a13fde7e2.png)

![screenshot - 02_12_2018 07_46_43](https://user-images.githubusercontent.com/13388970/49336687-697ffe80-f607-11e8-902b-f85f3880e973.png)

![screenshot - 02_12_2018 07_46_56](https://user-images.githubusercontent.com/13388970/49336688-697ffe80-f607-11e8-896e-91c27d7859fd.png)

![screenshot - 02_12_2018 07_47_04](https://user-images.githubusercontent.com/13388970/49336689-697ffe80-f607-11e8-9c2f-ec69a5209c55.png)

![screenshot - 02_12_2018 07_47_14](https://user-images.githubusercontent.com/13388970/49336693-6e44b280-f607-11e8-805a-d5f61345c813.png)

![screenshot - 02_12_2018 07_47_27](https://user-images.githubusercontent.com/13388970/49336694-6e44b280-f607-11e8-981f-35667db3352b.png)

Cheers,
