### ISSUE TITLE
Callout not changin the color if modified

### ISSUE THREAD

**Issue by vdirienzo** [trevorsandy/lpub3d#162]
### Subject
Describe your issue here.
If you make a callout the default color is beige in the first level (change sub model level color) . if you moddify the color using the following command it does not change any color of the callout.
0 !LPUB PAGE SUBMODEL_BACKGROUND_COLOR GLOBAL "#f55fff" "#55ff7f" "#ffcfcc" "#cfccff" 

i have to force a solid color only on the callout to make it change. the following command works.
0 !LPUB CALLOUT BACKGROUND GLOBAL COLOR "#ff0000"

### Environment
* Version of LPub3D - see Help->About LPub3D
2.3.3 
* Operating system - OS Name, Processor Architecture (x86,x86_64)
windows 1 0 x64

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  - Windows: `C:\Program Files\LPub3D` [x86_64]
  - macOS: `/Applications/LPub3D.app`
  - Linux:  `/usr/share/lpub3d`
  - AppImage (Linux): `/tmp/.mount_LPub3D<UniqueID>/usr/share/lpub3d`
* Application data path
  - Windows: `%USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\`
  - macOS: `~/Library/Application Support/LPub3D Software/LPub3D/`
  - Linux: `~/.local/share/LPub3D Software/LPub3D/`
  - AppImage (Linux): `~/.local/share/LPub3D Software/<AppImage File Name>/`
* Registry Extract
  - Windows (installed): `reg export "HKEY_CURRENT_USER\Software\LPub3D Software" %USERPROFILE%\Desktop\LPub3D_Hive.reg`
  - Windows (portable): `<application path>\config\LPub3D Software\LPub3D.ini`
  - macOS: ` ~/Library/Preferences/com.lpub3d-software.LPub3D.plist`
  - Linux: `~/.config/LPub3D Software/LPub3D.conf`
  - AppImage (Linux): `~/.config/LPub3D Software/<AppImage File Name>.conf`
* Renderer configuration files
  - `[Application data path]/ldv/ldvPOV.ini`
  - `[Application data path]/3rdParty/ldglite-1.3/config/ldglite.ini`
  - `[Application data path]/3rdParty/ldview-4.3/config/ldview.ini`
  - `[Application data path]/3rdParty/ldview-4.3/config/ldviewPOV.ini`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.conf`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.ini`

### Logs
* Application Log: `[Application data path]/logs/LPub3DLog.txt`
* Renderer Log: `[LDraw model path]/stdout-ldglite`
* Renderer Log: `[LDraw model path]/stdout-povray`
* Renderer Log: `[LDraw model path]/stderr-ldglite`
* Renderer Log: `[LDraw model path]/stderr-povray`

### Screenshots
* Configuration->Preferences->General
* Configuration->Preferences->Rendering
* Configuration->Preferences->Publishing
* Configuration->Preferences->Logging
* Configuration->Preferences->Other

### Steps to reproduce
Tell me how to reproduce this issue.
Provide a sample mpd/ldr file that reproduces the problem.

### Expected behaviour
Tell me what should happen

### Actual behaviour
Tell me what happens instead

### Workaround
Share your work around if available

### Solution suggestion
Share your opinion on how to achieve the expected behaviour

**Comment by trevorsandy** [comment]
Corrected. 

While I did discover, and corrected, a bug where the context menu failed to generate the background meta command, that behaviour is NOT the cause of the behaviour described in this ticket.

![screenshot - 01_12_2018 17_03_43](https://user-images.githubusercontent.com/13388970/49330268-7f041280-f58c-11e8-9d07-c8a00e2ed923.png)

![screenshot - 01_12_2018 17_02_30](https://user-images.githubusercontent.com/13388970/49330269-81ff0300-f58c-11e8-8229-efa0af422c59.png)

> If you make a callout the default color is beige in the first level (change sub model level color) . if you moddify the color using the following command it does not change any color of the callout.
`0 !LPUB PAGE SUBMODEL_BACKGROUND_COLOR GLOBAL "#f55fff" "#55ff7f" "#ffcfcc" "#cfccff"`

The behaviour resulting from the meta command in the excerpt above is as designed. The `PAGE` meta will not update the `CALLOUT` background. The correct `GLOBAL` submodel colour meta command for Callouts is `0 !LPUB CALLOUT SUBMODEL_BACKGROUND_COLOR GLOBAL "#00ff00" "#ffffcc" "#ffcccc" "#ccccff" ` See ticket #69 for additional details.

![screenshot - 01_12_2018 16_59_34](https://user-images.githubusercontent.com/13388970/49330259-6dbb0600-f58c-11e8-9558-34987ff26a92.png)

Cheers,
