### ISSUE TITLE
Font Settings not updating

### ISSUE THREAD

**Issue by trdoolan** [trevorsandy/lpub3d#164]
### Subject
Page and Font settings not updating/parsing into Ldraw File

### Environment
* Version of LPub3D - v2.3.3
* Operating system - MacOS 10.12.6, Macbook Pro 2012

### Steps to reproduce

Normal change of settings process.
Font settings in "Configuration" > "Build Instruction Setup" 
Changing font details in any of these fails to update the code in the LDraw file. Selected font does not appear in the settings screen after selection and clicking 'ok' in the dialog box.

Alternatively, right clicking on any number/title (step number, qty of part, PLI details) and trying to change font detail results in the same.

Changing files makes no difference. Error occurs with any LDR file used.

### Expected behaviour
Font should be updated to selected details

### Actual behaviour
No update/change to settings.

### Workaround
Direct editing of code in the LDraw Editor window
[Archive.zip](https://github.com/trevorsandy/lpub3d/files/2643331/Archive.zip)

### Solution suggestion
Fix it.

**Comment by trevorsandy** [comment]
Corrected. 

Thanks for reporting this behaviour.

Cheers,
