### ISSUE TITLE
Add LSynth parts to LPub3D archive

### ISSUE THREAD

**Issue by trevorsandy** [trevorsandy/lpub3d#165]
###  Subject
Automatically load LPub3D LSynth parts.

### Environment
Version of LPub3D - 2.3.3
Operating system - All

### Expected behaviour
Add LSynth parts to LPub3D archive with one click.
Also add LSynth parts to LDraw search directories with one click, enabling parts access to the LPub3D renderers.

### Actual behaviour
Current behaviour requires the user to manually add the parts to a subfolder under unofficial
parts and add that location to the LPub3D search directories under Preferences.

### Solution
This enhancement adds LSynth parts to the LPub3D application resource bundle.

Preferences checkbox 'Archive LSynth Parts' added allowing the user to automatically add LSynth parts to the LPub3D archive file. This capability allows LPub3D to validate LSynth parts in the model
file without having to add the LSynth path to the LPub3D search directories This action 
requires the user to have already installed the LSynth parts under the LDraw disk library location,
enabling parts access to the LPub3D renderers.

In the event LSynth parts are not currently installed under the LDraw disk library, a second Preferences checkbox 'Add LSynth Search Directory' added to allow the user to add the LPub3D LSynth path to the search directories, enabling parts access to the LPub3D renderers.

**Comment by trevorsandy** [comment]
Implemented.

![image](https://app.gitkraken.com/api/glo/boards/5b248f78dd21bf100044c350/attachments/5c078437e5457c002eb5a465)

Cheers,

**Comment by Scharnvirk** [comment]
Hello, where did this option end up in 2.3.9? I cannot find it there, or anywhere else.

**Comment by trevorsandy** [comment]
Hi - In v2.3.4. However, the setting was moved to the Rendering tab. The ticket graphic was not updated until now.

Cheers,

**Comment by Scharnvirk** [comment]
Thanks. I managed to find it eventually, but thanks anyway!
