### ISSUE TITLE
Rotate Icon Placement Dialog incorrect "Relative to" options in a Step Group

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#166]
### Subject
Rotate Icon Placement Dialog incorrect "Relative to" options in a Step Group

### Environment
* LPub3D 2.3.3
* Windows

### Screenshots
![afbeelding](https://user-images.githubusercontent.com/32261647/49577495-d10bb600-f947-11e8-9fcb-d00403e91204.png)

### Steps to reproduce
Add a Rotation icon to a step on a Step group page
Right-click the icon and choose Move Rotation icon
Dialog dropdown Relative to options are Page and Page number

### Expected behavior
The word Page in the dialog should be Assembly

### Actual behavior
If you choose Page and then a position of choice, the icon is placed relative to the Assembly

### Workaround
None. It just works the way it should, but the option Page is wrong

### Solution suggestion
Correct the options for the drop-down.

**Comment by trevorsandy** [comment]
Corrected.

![screenshot - 07_12_2018 03_41_06](https://user-images.githubusercontent.com/13388970/49624524-0c52c700-f9d2-11e8-9e45-94ca654a5d6d.png)

Cheers,

**Comment by jacovandermolen** [comment]
Great. That was fast ;-)
