### ISSUE TITLE
Wrong label for changing assembly margins on right menù

### ISSUE THREAD

**Issue by zero0n3** [trevorsandy/lpub3d#167]
### Subject
When you click with right button on an assembly to change assembly margins, the label for that command is wrong. The yellow highlighted (in screenshot) is "Change Assembly Scale" but it is Change Assembly Margins. The right scale command is the one near red arrow.

### Environment
* Version of LPub3D - 2.3.2 and up
* Operating system - Win and MacOs

### Screenshots
![wrong_label](https://user-images.githubusercontent.com/1552296/49935385-307e3e80-fed1-11e8-96de-af5f33c4fae4.jpg)

**Comment by trevorsandy** [comment]
Corrected.

![screenshot - 14_12_2018 15_59_19](https://user-images.githubusercontent.com/13388970/50010274-3fd8b700-ffb9-11e8-92d4-95a64f1af751.png)

Cheers,

**Comment by zero0n3** [comment]
> Corrected.
> 
> ![screenshot - 14_12_2018 15_59_19](https://user-images.githubusercontent.com/13388970/50010274-3fd8b700-ffb9-11e8-92d4-95a64f1af751.png)
> 
> Cheers,

Thanks :-D
