### ISSUE TITLE
Wrong CALLOUT placement when it is inside a MULTI_STEP page

### ISSUE THREAD

**Issue by zero0n3** [trevorsandy/lpub3d#168]
### Subject
Place a CALLOUT command and change placement with BOTTOM CENTER ASSEM.
If the callout is inside a SINGLE STEP, LPub places it correctly at the bottom, relative to Assembly.
If the same step with the same callout is inside a MULTI_STEP page, the BOTTOM position not work and the callout is placed at the TOP of the assembly.

### Environment
* Version of LPub3D - 2.3.4
* Operating system - Win and MacOs

### Configuration
Standard configuration. Clean installation on Win and Mac

### Screenshots
* Working area without MULTI_STEP -> the CALLOUT is correctly at the BOTTOM relative to assembly
![ok](https://user-images.githubusercontent.com/1552296/49936128-68868100-fed3-11e8-8c3a-e9bb0e1b87d3.jpg)

* Working area with MULTI_STEP -> the CALLOUT it is wrongly placed at the TOP
![wrong](https://user-images.githubusercontent.com/1552296/49936169-89e76d00-fed3-11e8-8932-509698355448.jpg)

### Steps to reproduce
I attached 2 samples. One without MULTI_STEP that works and one with that generates the bug.

[placement.sample.zip](https://github.com/trevorsandy/lpub3d/files/2675771/placement.sample.zip)

**Comment by trevorsandy** [comment]
Simone - Thanks for reporting this behaviour. I’ll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

![screenshot - 15_12_2018 23_00_44](https://user-images.githubusercontent.com/13388970/50047858-6af8fe80-00be-11e9-9e44-9ddad25bdd3f.png)
![screenshot - 15_12_2018 23_02_13](https://user-images.githubusercontent.com/13388970/50047859-6b919500-00be-11e9-9a9f-226ee7fcb1de.png)
![screenshot - 15_12_2018 23_02_45](https://user-images.githubusercontent.com/13388970/50047860-6b919500-00be-11e9-8bc0-d8c05548640a.png)
![screenshot - 15_12_2018 23_02_57](https://user-images.githubusercontent.com/13388970/50047861-6b919500-00be-11e9-91eb-4fdb12f4a211.png)

Cheers,
