### ISSUE TITLE
Add text \ (forward slash I believe?) gives an error.

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#170]
### Subject
Insert text \ (forward slash I believe?) gives an error.

### Environment
* Version of LPub3D 2.3.4
* Operating system - Windows 10 

### Screenshots
![afbeelding](https://user-images.githubusercontent.com/32261647/49998198-f2961e80-ff93-11e8-988a-ddb48702c230.png)

### Steps to reproduce
Choose to Add text and input \

### Expected behaviour
A \ should appear as inserted text

### Actual behavior
I get an error dialog (see screenshot)

### Workaround
None that I know of.

### Solution suggestion
Enable escape for special characters like \

**Comment by trevorsandy** [comment]
Updated.

The '\' character was reserved for support escaping double quotes. For example, when writing `This is a \"quoted\" string.` I've changed the behaviour to programmatically insert and remove this character so, with this update, **_it is not longer necessary to 'escape'  quoted strings in the dialog_**. In fact, if you enter 
`Is it still possible to enter \"Quoted\" strings?`, the displayed text will be exactly `Is it still possible to enter \"Quoted\" strings?`.

New multiline text entry:
![screenshot - 17_12_2018 00_54_37](https://user-images.githubusercontent.com/13388970/50060744-07db9a80-0198-11e9-9625-2c9578d7b15d.png)

Text meta example:
![screenshot - 17_12_2018 00_55_22](https://user-images.githubusercontent.com/13388970/50060745-0c07b800-0198-11e9-8eb8-ad567a8750d1.png)

Cheers,
