### ISSUE TITLE
Command to change pointer attributes seems to be buggy

### ISSUE THREAD

**Issue by zero0n3** [trevorsandy/lpub3d#171]
### Subject
I have a pointer without attributes:
```
0 !LPUB CALLOUT BEGIN
1 19 40 -24 0 1 0 0 0 1 0 0 0 1 callout.ldr
0 !LPUB CALLOUT POINTER TOP 0.535 0.590 0.429 0.000 0.000 0.000 0.000 0.000 0.000 0 1
0 !LPUB CALLOUT PLACEMENT BOTTOM CENTER ASSEM OUTSIDE -2.91505e-16 0.797661
0 !LPUB CALLOUT ALLOC HORIZONTAL
0 !LPUB CALLOUT END
```

I click with right button on pointer and use Set Line Attributes;
i change the color, for example, and it adds this line and it's ok:
`0 !LPUB CALLOUT POINTER_ATTRIBUTE LINE 1 #ff0000 0.03125 0 1 `
then i click on Set Border Attributes, i change also here the color but it add again the same code of the line attributes.

If I add manually BORDER attribute LPub crash.
`0 !LPUB CALLOUT POINTER_ATTRIBUTE BORDER 1 #FF0000 0.01 0 1`

You can find attached a sample with error on page 2. Error that causes crash.
I also attached log but nothing is written about error. And i have enabled all log levels in preferences.

### Environment
* Version of LPub3D - 2.3.5 1092
* Operating system - Windows 7

### Configuration
Default after clean installation

### Screenshots
![1-pointer default](https://user-images.githubusercontent.com/1552296/50082285-d9d67480-01f0-11e9-9d60-a93ac524d8be.jpg)
![2-change pointer line](https://user-images.githubusercontent.com/1552296/50082289-db07a180-01f0-11e9-9d16-53687384a9b5.jpg)
![3-code added](https://user-images.githubusercontent.com/1552296/50082290-dcd16500-01f0-11e9-9c93-b406cc8d7ed4.jpg)
![4-change pointer border](https://user-images.githubusercontent.com/1552296/50082291-dd69fb80-01f0-11e9-8338-68ed1bcd0461.jpg)
![5-same code added](https://user-images.githubusercontent.com/1552296/50082294-df33bf00-01f0-11e9-956f-bb3eef921302.jpg)

[default.unit.zip](https://github.com/trevorsandy/lpub3d/files/2685678/default.unit.zip)
[LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/2685692/LPub3DLog.txt)

**Comment by trevorsandy** [comment]
Hi Simone, 
Thanks for reporting this behaviour and taking the time to prepare an example. 

Are you using cm or in units ? 

The pointer capability is quite complex and, it seems, easy to break as it is affected by many variables. This is precisely why I was hesitant to I implement it initially. Anyway, the “cat is now out of the bag” so we will work with it. I imagine it will take a few iterations to work out all the issues. 

Do not hesitate to report any unexpected behaviour.

Cheers,

**Comment by zero0n3** [comment]
> Are you using cm or in units ?
Same behaviour if i use cm or inches. It adds line codeline if i add border attributes and if i add border code manually it crashes.


> The pointer capability is quite complex and, it seems, easy to break as it is affected by many variables. This is precisely why I was hesitant to I implement it initially. Anyway, the “cat is now out of the bag” so we will work with it. I imagine it will take a few iterations to work out all the issues.

Why do not you try initially by setting a default white border that is not editable and meanwhile try to make the part of the line attributes working.
Later when that is ok you could also start developing the part of the border attribute.
Just a suggestion.

Cheers

**Comment by zero0n3** [comment]
I uploaded here a video starting from zero.
https://youtu.be/GlB1QiCHMhQ
I open sample and make some modifications so you can check what happens exactly.
Another strange behaviour is at 1.20 minute. I change line thickness, then i change again but instead of changing the old value, it adds a new line before the old line.

In the end, when i enter in the page where there is BORDER attribute codeline it crashes. If I am in a page without that code, then i add it manually and reload page it chrashes.

**Comment by trevorsandy** [comment]
Corrected.

Cheers,

**Comment by zero0n3** [comment]
>  I have added an `Update` button 

I love you man! I used redraw because it's a simple model. Usually i do what you suggested because using redraw with a more complex model is like a suicide. But the UPDATE button is really welcome!
