### ISSUE TITLE
Windows Defender Reporting Trojan:Win32/Cloxer.D!cl

### ISSUE THREAD

**Issue by StormsofVogue** [trevorsandy/lpub3d#174]
I'm assuming this is just a false positive, but Windows Defender is reporting LPub3D as a trojan when I try to update to v2.3.6 from v2.3.5.  

I downloaded the LPub3D-2.3.6.0.1101_20181219.exe install file from Github, but can't install it due to this Window's Defender error.  

![lpub3derror](https://user-images.githubusercontent.com/32054771/50458206-3be05980-0916-11e9-8b53-7c7ab2454790.PNG)

* Version of LPub3D - v2.3.6 
* Operating system - Windows 10, x86_64

**Comment by trevorsandy** [comment]
Thanks for reporting this behaviour. 

To progress, perhaps you can try the portable distribution (*.zip) which do not require installation.

On the Microsoft Defender site, they state “This detection uses artificial intelligence (AI) to identify new and emerging malware.” It looks like their results are as artificial as their intelligence. I will submit LPub3D to their portal for analysis, as they have offered, and, hopefully, they can update their “machine learning” input to give more accurate results 

It is disappointing that there are no open source options for Windows code signing so I currently do not perform this action on my builds. Furthermore, my Windows distros are built using the Cloud CI platform AppVeyor and I’m not sure how to transfer to the build server, the latest certificates that require hardware (crypto-enabled USB key) to properly function. However, I don’t know if the code not being signed is a driver for MS’s “latest” machine learning powered AI.

Cheers,

**Comment by qwertychouskie** [comment]
> On the Microsoft Defender site, they state “This detection uses artificial intelligence (AI) to identify new and emerging malware.” It looks like their results are as artificial as their intelligence.

Best MS burn!  You just made my day! :D
