### ISSUE TITLE
Question on Perspective Effect of Drawings

### ISSUE THREAD

**Issue by zeglove** [trevorsandy/lpub3d#175]
I am a Chinese Lego fan.I often make Lego drawings, so I use your software frequently.
    I am confused about the three-dimensional perspective of the model.
    It's well known that perspective can make objects look Near the far smaller.
    Now the model rendered by LDpub3D has no perspective effect. It always gives people a near-small and far-large illusion.
    At first I thought the problem was caused by LDview, and then I asked LDview. Travis Cobbs responded by saying that LDview has perspective effect, but the problem is LPub3D.
![image](https://user-images.githubusercontent.com/38724077/50805932-82c74980-132f-11e9-9bfe-82ab412f8ac9.png)
     In the LPub3D 3D 3D viewer, we can choose projection - > perspective, and the three-dimensional model on the right side will also change significantly.
![image](https://user-images.githubusercontent.com/38724077/50806003-ce79f300-132f-11e9-9ea6-a0f76702e4e8.png)
Orthographic
![image](https://user-images.githubusercontent.com/38724077/50806027-eea9b200-132f-11e9-8ccc-79dd02593175.png)
Perspective

      But in rendering drawings, there seems to be no such settings, which can be improved? Or it could have been in LPub3D, but I don't know yet.

**Comment by zeglove** [comment]
Sorry，It took a long time to reply to you. I worked a lot of overtime.
You're right. I hope LPub3D can add perspective options for rendering.
I usually model in LDcad and use LPub 3D to produce drawings. Now I use the latest version 2.3.6. I usually use these in Windows 10.
I also hope that after LPub 2.3, the options for converting to obj format will be available. LPub used to have this function, but it didn't. I don't know why.  Sometimes I need to import the model into C4D.
Thank you very much. Thank you for your contribution to Lego World.

**Comment by zeglove** [comment]
>           Hi, Thank you for reporting this behaviour.
> If I well understand your remarks, you are asking to enable switching the renderers between orthographic and perspective views ? This behaviour is not currently available but I can add it to the list of future enhancements if you describe your use case.
> Cheers,

**Comment by trevorsandy** [comment]
Implemented.

It is now possible to switch renderer projection in Preferences.

![Screenshot - 28_03_2019 , 17_43_28](https://user-images.githubusercontent.com/13388970/55176394-58906580-5181-11e9-9b68-d89b4566a745.png)

As it was possible to do for the 3D Viewer. 

**Note:** The label is misleading. Instead of '**Renderer projection**,' it should be '**Viewer projection**'. I'll update the label in the next release.

![Screenshot - 28_03_2019 , 17_47_06](https://user-images.githubusercontent.com/13388970/55176666-d94f6180-5181-11e9-807b-dcaacc9d5fb1.png)

Cheers,
