### ISSUE TITLE
Continuous Step Numbering for Submodels and unassembled Callouts [enhancement]

### ISSUE THREAD

**Issue by cameronmiller1988** [trevorsandy/lpub3d#179]
I would like the option to have the step numbering be continuous throughout the model. I have noticed that LEGO does this in many recent instructions. It would still be renumbered for callouts but for non-callout submodels, I would like to have the step numbers be continuous. 

Currently on 2.3.6 on mac and windows

**Comment by trevorsandy** [comment]
Very well. I will add your request to the queue. However, you're going to have to help me, a bit more, to help you...

Can you provide a brief illustration, using screenshots, of the current behaviour and the expected behaviour ?

Cheers,

**Comment by cameronmiller1988** [comment]
Hey Trevor, Was this not the way to request a feature? I can go about it differently in the future. 

I can explain this better with a couple photos from a recent LEGO instruction manual. 

The photos show that callout have number starting at 1 but a submodel that is not a callout, continues the step numbers from the parent model. This is seen starting at step 17. I am not requesting the ability to show a submodel on same page as if I was just adding it to a multi step. 

![img_2181](https://user-images.githubusercontent.com/43015030/52176863-32001080-2776-11e9-9d85-70eee63db4f4.JPG)
![img_2182](https://user-images.githubusercontent.com/43015030/52176865-3298a700-2776-11e9-9170-e79b5d2f0685.JPG)

My particular use case for this currently is to have a modular building that is split up by each floor. The main model with be 3 steps, first floor, second floor, roof. 

This will allow me to have them all in the same file but I will start the first floor at step 1, which would be a part of submodel 1. When the first floor is complete I would start the second floor but instead of building it on top of the first floor, I am building it as a sub-model so its a separate build. When I get to the end of the second floor the main model will show through buff exchange how to place the second floor on the first floor. 

I hope this makes sense. 

Thanks,
Cameron

**Comment by trevorsandy** [comment]
Hello Cameron,

Understood. Thank you. 

Hints for useful (issue, enhancement,...) information are presented when you click the “new issue” button. Of course, not all suggestions are necessary.

Cheers,

**Comment by trevorsandy** [comment]
Implemented.

![screenshot - 04_03_2019 09_29_00](https://user-images.githubusercontent.com/13388970/53720217-79a2b680-3e60-11e9-85fc-89614f758f4a.png)
![screenshot - 04_03_2019 09_30_12](https://user-images.githubusercontent.com/13388970/53720219-79a2b680-3e60-11e9-97ed-78cf5ad4a49e.png)
![screenshot - 04_03_2019 09_30_21](https://user-images.githubusercontent.com/13388970/53720220-79a2b680-3e60-11e9-91be-104fc8e3a25c.png)
![screenshot - 04_03_2019 09_30_31](https://user-images.githubusercontent.com/13388970/53720221-7a3b4d00-3e60-11e9-829e-4652a9b38d58.png)
![screenshot - 04_03_2019 09_30_40](https://user-images.githubusercontent.com/13388970/53720223-7a3b4d00-3e60-11e9-822b-688e4fbe725a.png)
![screenshot - 04_03_2019 09_30_51](https://user-images.githubusercontent.com/13388970/53720224-7a3b4d00-3e60-11e9-9022-a71c2a4bf9bc.png)
![screenshot - 04_03_2019 09_31_01](https://user-images.githubusercontent.com/13388970/53720225-7a3b4d00-3e60-11e9-983b-97f69ce141e1.png)
![screenshot - 04_03_2019 09_31_10](https://user-images.githubusercontent.com/13388970/53720226-7a3b4d00-3e60-11e9-94da-750ab2b5b35c.png)
Cheers,

**Comment by cameronmiller1988** [comment]
Thank you!!

**Comment by jacovandermolen** [comment]
Great feature! Many thanks.
