### ISSUE TITLE
LDView AutoCrop bug

### ISSUE THREAD

**Issue by remittor** [trevorsandy/lpub3d#180]
Incorrect crop LDView ouput image.

LPub3D 2.3.6 (Win7 x64)

Buggest LPub3D:
![sh_0438](https://user-images.githubusercontent.com/9350115/52198339-8ccb6200-2873-11e9-8bd5-1060e213d7b2.png)

For fix need change this line: https://github.com/trevorsandy/lpub3d/blob/1c651eabd0b96c5fc1d4348906030b3cc61e1bb5/mainApp/render.cpp#L1138

Patched LPub3D (AutoCrop=0):
![sh_0439](https://user-images.githubusercontent.com/9350115/52198356-9c4aab00-2873-11e9-9749-8e0b9ec9f15c.png)

**Comment by trevorsandy** [comment]
Hello, 

The behaviour you present is currently as designed. 

To fit your image, try manipulating the page size or reducing the image scale.

For your information, in the next release (v2.3.7) it is possible to “turn off” the mandatory `-AutoCrop=1` flag and optionally specify it “on” or “off” in the LDView INI file. 

Cheers,
