### ISSUE TITLE
Wrong highlighting parts in steps with Buffer Exchange

### ISSUE THREAD

**Issue by zero0n3** [trevorsandy/lpub3d#181]
### Subject
Lpub3D doesn't highlight all the parts when there is a buffer exchange in a step. It highlights only moving parts.

### Environment
* Version of LPub3D - last one
* Operating system - MacOs Mojave 10.14.13

### Configuration
fresh installation. Default configuration. I use ldview as render engine with default parameters.

### Steps to reproduce
Open ldr attached. On step 3 you will see a buffer exchange but the parts not inside buffer exchange are not highlighted.
<img width="322" alt="issue" src="https://user-images.githubusercontent.com/1552296/52874087-ddcf3600-3150-11e9-80d7-8f31ab672661.png">

### Expected behaviour
Highlight all the parts during buffer exchange. Also ones already in the right position.

[buffer_highlight.ldr.zip](https://github.com/trevorsandy/lpub3d/files/2870177/buffer_highlight.ldr.zip)

**Comment by trevorsandy** [comment]
Thanks for reporting this behaviour Simone. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.
The screenshot shows both fade previous steps and highlight current step enabled.
![screenshot - 03_03_2019 02_04_35](https://user-images.githubusercontent.com/13388970/53689530-b8e5e000-3d58-11e9-917b-c1f781af33a2.png)
Cheers,
