### ISSUE TITLE
Part file not found in when using fade previous steps...

### ISSUE THREAD

**Issue by scumpy0815** [trevorsandy/lpub3d#182]
### Subject
I want to generate instructions with faded steps. The ldr has motors, trainwheels and connectors which are all not able to be faded. Every time I load the ldr, I get the message, that the part was not found in official library. I deleted my whole LDraw and Lpub installation and made a clean one. Still no luck. I can't even find the files of faded parts which can be faded. At the moment I think it has got something to do with parts with multiple colours (like the batterybox 84599.dat, the trainwheel 55423.dat or the motor 99499.dat). Parts with only one colour work perfectly.

### Environment
* Version of LPub3D - 2.3.6 Revision 0 Build 1101
* Operating system - Windows 10 1809, x64

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  - C:\LDraw\LPub3D
* Application data path
  - Windows: '%USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\'

### Steps to reproduce
Upload doesn't work so I paste the ldr:
0 STEP
1 71 -230 -40 0 1 0 0 0 1 0 0 0 1 99499.dat
1 71 -230 56 0 1 0 0 0 1 0 0 0 1 84599.dat
0 STEP
1 71 -190 40 0 1 0 0 0 1 0 0 0 1 58124c02.dat
0 STEP
1 72 -190 24 0 1 0 0 0 1 0 0 0 1 58124c01.dat
0 STEP
0 STEP
1 0 120 -8 0 1 0 0 0 1 0 0 0 1 73092.dat
0 STEP
1 0 0 0 0 1 0 0 0 1 0 0 0 1 55423.dat
0 STEP
1 0 360 -319 -291 1 0 0 0 1 0 0 0 1 32013.dat

Instead of the parts there are only faded blocks in the next step.
i would provide the pdf, but I can't upload anything.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

Please attach the following logs, screenshots and generated content:

### Logs (include stdout/err logs if your preferred renderer is ldglite or povray)
* Application Log: `[Application data path]/logs/LPub3DLog.txt`
* Renderer Log: `[LDraw model path]/stdout-ldglite`
* Renderer Log: `[LDraw model path]/stdout-povray`
* Renderer Log: `[LDraw model path]/stderr-ldglite`
* Renderer Log: `[LDraw model path]/stderr-povray`

### Screenshots
* Configuration->Preferences->General
* Configuration->Preferences->Rendering
* Configuration->Preferences->Other

### Steps to reproduce
Tell me how to reproduce this issue.
If the model file content you posted is all the data contained in your `.ldr` file, then it would be better to include the minimum file header information i.e. `0 FILE foo.ldr`, `0 Name:  foo` before attempting to use the fade or highlight step features.

Cheers,

**Comment by scumpy0815** [comment]
[Test.zip](https://github.com/trevorsandy/lpub3d/files/2881315/Test.zip)

There were no logs generated in the model path. So I only added the rest you wanted. The header didn't change my problem though.

**Comment by trevorsandy** [comment]
Corrected.
![screenshot - 02_03_2019 05_36_10](https://user-images.githubusercontent.com/13388970/53677291-ca25e280-3cad-11e9-8063-09afa4715138.png)

![screenshot - 02_03_2019 05_36_26](https://user-images.githubusercontent.com/13388970/53677294-d27e1d80-3cad-11e9-8fcb-58bc5ce17dac.png)

Cheers,
