### ISSUE TITLE
FadeStepColorParts.lst doesn't work

### ISSUE THREAD

**Issue by ReneFrijhoff** [trevorsandy/lpub3d#183]
### Subject
Errors on all parts contained in the FadeStepColorParts.lst

### Environment
* Version of LPub3D - see Help->About LPub3D 2.3.6. rev. 0 Build 1101
* Operating system - Windows 7 64 bit

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  - Windows: F:\Program Files\Lego\LPub3D
* Application data path
  - Windows: %USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\
* Registry Extract
  - Windows (installed): reg export "HKEY_CURRENT_USER\Software\LPub3D Software
.[lpub 3d.reg.txt](https://github.com/trevorsandy/lpub3d/files/2924915/lpub.3d.reg.txt)

Entries also exists in HKEY_USERS
[lpub 3d.reg HKEY_USERS.txt](https://github.com/trevorsandy/lpub3d/files/2924960/lpub.3d.reg.HKEY_USERS.txt)

%USERPROFILE%\Desktop\LPub3D_Hive.reg
  - Windows (portable): <application path>\config\LPub3D Software\LPub3D.ini
Does not exists if also for normal windows.

* Renderer configuration files
[ldvPOV.ini.txt](https://github.com/trevorsandy/lpub3d/files/2924989/ldvPOV.ini.txt)
[ldglite.ini.txt](https://github.com/trevorsandy/lpub3d/files/2924991/ldglite.ini.txt)
[ldviewPOV.ini.txt](https://github.com/trevorsandy/lpub3d/files/2924994/ldviewPOV.ini.txt)
[ldview.ini.txt](https://github.com/trevorsandy/lpub3d/files/2924995/ldview.ini.txt)
[povray.conf.txt](https://github.com/trevorsandy/lpub3d/files/2925000/povray.conf.txt)
[povray.ini.txt](https://github.com/trevorsandy/lpub3d/files/2925001/povray.ini.txt)

### Logs
[LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/2925018/LPub3DLog.txt)
No render logs as it happens during loading of files

### Screenshots
![screenshot 2019-03-04 10 09 29](https://user-images.githubusercontent.com/37920537/53722408-c50b9380-3e65-11e9-8faf-5ca8bdbb236a.png)
![screenshot 2019-03-04 10 11 01](https://user-images.githubusercontent.com/37920537/53722456-e2406200-3e65-11e9-9b2e-55848ad6ac95.png)
![screenshot 2019-03-04 10 11 46](https://user-images.githubusercontent.com/37920537/53722492-f97f4f80-3e65-11e9-958f-6073e4393564.png)
![screenshot 2019-03-04 10 12 25](https://user-images.githubusercontent.com/37920537/53722531-12880080-3e66-11e9-98e1-6fc10d2788d3.png)
![screenshot 2019-03-04 10 22 35](https://user-images.githubusercontent.com/37920537/53723210-7fe86100-3e67-11e9-87c9-43d7c970a53d.png)

### Steps to reproduce
Just load the file
[test fade part.ldr.txt](https://github.com/trevorsandy/lpub3d/files/2925653/test.fade.part.ldr.txt)

### Expected behaviour
Shouldn't give the part file xxxxxx.dat not found in official library errors as everything seems ok

### Actual behaviour
Gives error part file xxxxxx.dat not found in official library even when it should look in the unofficial library.
Even when the entry is defined as u in the FadeStepColorParts.lst it's still looking in the official library.

### Workaround
None

### Solution suggestion
Don't kmow what the problem is, therefor also no solution.

**Comment by trevorsandy** [comment]
Rene, thank you for reporting this behaviour. 

This is the same behaviour as reported in #182 - which has already been corrected in, soon to be released, v2.3.7.

Cheers,

**Comment by ReneFrijhoff** [comment]
Hi Trevor, thanks for the update.

Cheers, René

Op ma 4 mrt. 2019 om 16:06 schreef Trevor SANDY <notifications@github.com>:
