### ISSUE TITLE
Bug: undo after an 'add next steps' only removes the MULTI_STEP BEGIN

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#184]
### Subject
When I'm in a submodel and I add multiple next steps via right-mouse-button -> Add Next Steps, it succesfully puts the next steps into a multi-step:

Before:
![image](https://user-images.githubusercontent.com/12005521/54372005-bcdc0100-467a-11e9-9c94-c1fcf4201b8b.png)

After:
![image](https://user-images.githubusercontent.com/12005521/54372025-c82f2c80-467a-11e9-8195-81b2e9ed4bbd.png)

But, if I'm not satisfied with the displayed steps and I press Undo or ctrl+z, LPub only removes the MULTISTEP BEGIN and leaves the MULTI_STEP END:
![image](https://user-images.githubusercontent.com/12005521/54372054-daa96600-467a-11e9-9467-8f4f9ff04533.png)

### Environment
* Version of LPub3D - Lpub 2.3.6
* Operating system - Windows 10 Pro x64

**Comment by trevorsandy** [comment]
Merlijn,
Thanks for reporting this behaviour. I'll take a look.

Cheers,

**Comment by Landcross** [comment]
I just realized I forgot to mention that this bug only happens when I add **all** (remaining?) steps in a **single** go. If I only add e.g. the first 4 of 8 steps or add all 8 steps in 2 pairs of 4, the undo works fine.

**Comment by trevorsandy** [comment]
Corrected.

The `MULTI_STEP END` meta was inserted before the `MULTI_STEP BEGIN` meta so the `MULTI_STEP END` undo command lost the line number when the `MULTI_STEP BEGIN` meta was inserted.

Cheers,
