### ISSUE TITLE
Add range divider - divide steps in a range

### ISSUE THREAD

**Issue by trevorsandy** [trevorsandy/lpub3d#185]
###  Subject
Add range divider - divide steps in a range.

### Environment
Version of LPub3D - 2.3.7
Operating system - All

**Comment by trevorsandy** [comment]
### Add range divider - divide steps in a range

### Environment
Version of LPub3D - 2.3.7
Operating system - All

### Expected behaviour

### Actual behaviour

### Solution

**Comment by jacovandermolen** [comment]
Do you have an example?

**Comment by trevorsandy** [comment]
Jaco,

I've added some content to the initial ticket post that describes this enhancement setup and execution.

**Comment by jacovandermolen** [comment]
Ah yes, that makes things much clearer! Thanks.
