### ISSUE TITLE
Pretty PLI/BOM annotation

### ISSUE THREAD

**Issue by trevorsandy** [trevorsandy/lpub3d#186]
###  Subject
Add LEGO style annotation formatting

### Environment
Version of LPub3D - 2.3.7
Operating system - All

### Solution

**Comment by jacovandermolen** [comment]
Same as CSCI: any hints on how this works?

**Comment by jacovandermolen** [comment]
OK, so I am playing around a bit with this feature.
I seem to miss the annotation styles for technic bricks?
Beams and Axles seem fine, but when I want to change the font, LPub3D crashes.

**Comment by trevorsandy** [comment]
Hi Jaco,

I've added some content to the initial ticket post that describes this enhancement setup and execution. 

Cheers,
