### ISSUE TITLE
Pretty CSI annotation

### ISSUE THREAD

**Issue by trevorsandy** [trevorsandy/lpub3d#187]
###  Subject
Add LEGO style CSI annotation formatting

### Environment
Version of LPub3D - 2.3.7
Operating system - All

### Solution

**Comment by jacovandermolen** [comment]
Any hints on how this works? I cannot figure it out, sorry.

**Comment by jacovandermolen** [comment]
Never mind, I think I found it. I will incorporate this in the manual.

**Comment by trevorsandy** [comment]
Jaco,

I've added some content to the initial ticket post that describes this enhancement setup and execution. Also take a look at #222 to see the annotation update after v2.3.7 release.

Cheers,

**Comment by jacovandermolen** [comment]
Thanks so much. That helps ;-)
I will try to implement in the manual ASAP.
