### ISSUE TITLE
Extend native export - Enable HTML Part List

### ISSUE THREAD

**Issue by trevorsandy** [trevorsandy/lpub3d#196]
###  Subject
Extend native export - Enable HTML Part List.

### Environment
Version of LPub3D - 2.3.7
Operating system - All

**Comment by jacovandermolen** [comment]
When I use this option an error occurs:
ERROR "Command line file was not loaded."

**Comment by trevorsandy** [comment]
Jaco - The 'Command line file was not loaded.' return means the HTML snapshot model file (.ldr) was not found in the <model root dir>/LPub3D/tmp subdirectory.  This file can be identified with by name .<model file name>_snapshot.ldr.

There was a problem where the displayed image was not properly rotated and submodel(s), if any, were duplicated. This behaviour has been corrected in #215. 
 
Cheers,

**Comment by trevorsandy** [comment]
Jaco,

> ERROR "Command line file was not loaded."

See #220 for an explanation of the source of this behaviour and the correction.

Cheers,
