### ISSUE TITLE
Error message: PLI BEGIN then STEP. Expected PLI END

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#211]
### Subject
In a file created with 2.3.6 I supplemented a build minifig torso (t1) like this:

0 !LPUB PLI BEGIN SUB t1.ldr 15
0 !LPUB PART BEGIN IGN
1 15 0 -72 0 1 0 0 0 1 0 0 0 1 t1.ldr
0 !LPUB PLI END
0 !LPUB PART END

In 2.3.7 I get this error:

2019-03-28T13:48:59.901 ERROR void __cdecl Gui::parseError(class QString,class Where &) @ln 4073 PLI BEGIN then STEP. Expected PLI END (file: abt.ldr, line: 21) 

### Environment
* 2.3.7
* Windows 64

### Steps to reproduce
Opening the file in 2.3.7

### Expected behavior
2.3.7 should behave like 2.3.6?

### Actual behavior
Error message.

### Workaround
Renders just fine, only error message.
I clicked to not show it again. How to turn that back on?

A new blank file created with 2.3.7 does not show this error?

I cannot share the file here but can mail you a copy.

**Comment by trevorsandy** [comment]
Hi Jaco,

See #80.

If you unchecked 'Model Meta Parse Errors->Show all' in Preferences in your last version (v2.3.6), this may explain why you did not see the message before.

Cheers,

**Comment by jacovandermolen** [comment]
Ah! I see... tnx,

But what does the error say, in fact?
I always found the order of these lines a bit strange:

0 !LPUB PLI BEGIN SUB t1.ldr 15
0 !LPUB PART BEGIN IGN
1 15 0 -72 0 1 0 0 0 1 0 0 0 1 t1.ldr
0 !LPUB PLI END
0 !LPUB PART END

The nesting seems not right.

Still, it works fine.

**Comment by trevorsandy** [comment]
As the message states, PLI BEGIN followed by STEP was encountered but PLI END was expected.

The STEP encountered was likely from the t1.ldr model file. Basically, there is no logic in place to handle .ldr substitute files in the PLI only .dat files. 

Cheers,

**Comment by jacovandermolen** [comment]
Ah, OK, right. There is no step in t1.ldr, but since the render is just fine, I'll keep ignoring it ;-)
Thanks!
