### ISSUE TITLE
GHOST command bypassed by highlight preferences

### ISSUE THREAD

**Issue by zero0n3** [trevorsandy/lpub3d#212]
### Subject
With LDview render, when i eneble highlight current step, parts with 0 GHOST command return visible.

### Environment
* Version of LPub3D - 2.3.6 - 2.3.7
* Operating system - Windows-MacOS

### Configuration
Fresh installation

### Steps to reproduce
On attached file, on step 2, no buffer exchanges, there is a command to show a part like callout but just a single part i want to show but i dont want to show that part in PLI or in assembly because (for example) i want to show a part used in that step but with a different color so i dont want to add it to PLI but just see the alternative part with a text like "you can use same part with different color". I found a wordaround using callout ASSEMBLED to show the callout square and using 0 GHOST on the submodel to not show that part in the assembly step.
On 2.3.6 maybe i was just lucky i never noticed it. I tried now and it seems also on 2.3.6 i got the same result.
~~Until 2.3.6 all works also with highlight enabled. From 2.3.7 (maybe to solve the issue #181 ) if i enable highlight, the part becomes visible again on assembly step, as you can see in step 2.~~

### Expected behaviour
Still hiding the part with 0 GHOST command

Thanks

[ghost not working.ldr.zip](https://github.com/trevorsandy/lpub3d/files/3020292/ghost.not.working.ldr.zip)

**Comment by trevorsandy** [comment]
Hi Simone,

Many thanks for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

Cheers,

**Comment by zero0n3** [comment]
Thanks Trevor
