### ISSUE TITLE
Default PLI/BOM annotation on?

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#213]
### Subject
Default PLI/BOM annotation on?

### Environment
* Version of LPub3D 2.3.7
* Windows

### Screenshots
Annotation is not setup:
![afbeelding](https://user-images.githubusercontent.com/32261647/55225637-5ecf2200-5213-11e9-9c5e-ba1c5665a7c1.png)

### Steps to reproduce
Open attached test model file in 2.3.7. to see annotation for the axels and beams, though I did not set that up.

### Expected behaviour
Since I did not configure or setup annotation I expected to see no annotation at all.

### Actual behaviour
Without setting it up, annotation for some parts is displayed in the PLI.

### Workaround
Unchecking some checkboxes here completely disables annotation.
But that is not what I want.

### Solution suggestion
Setup like this to only show annotation at the parts I want configured in the freeformAnnotations.lst (renamed here to be able to upload)

[freeformAnnotations.lst.txt](https://github.com/trevorsandy/lpub3d/files/3022133/freeformAnnotations.lst.txt)

![afbeelding](https://user-images.githubusercontent.com/32261647/55225782-b2417000-5213-11e9-9abb-f812dcaffa1e.png)

**Comment by jacovandermolen** [comment]
Test files

[annotationtest.ldr.txt](https://github.com/trevorsandy/lpub3d/files/3022147/annotationtest.ldr.txt)
[annotationtest.pdf](https://github.com/trevorsandy/lpub3d/files/3022145/annotationtest.pdf)

**Comment by trevorsandy** [comment]
Corrected.

Cheers,
