### ISSUE TITLE
Error Message: "LDView console output"

### ISSUE THREAD

**Issue by LiononBricks** [trevorsandy/lpub3d#22]
### Subject of the issue
Get an error message when trying to open any file. The title of the message box is "LDView console output". The message is "Critical Error: Could not find LDraw directory." [Enter] "File: C:Users/user/Documents/LiononBricksCustomModelWorks/In Progress/MW-4--- 5-Wide Light Duty Maintenance Truck/LPub3D/tmp/csi.ldr" [Enter] "Unknown Line". It could be a possibility that the LDraw parts library path is throwing it off, it is installed in my "Documents" folder in a folder titled "Bricks" instead of the standard location (Unless I am mistaken and that is the default location). However, during the install I directed the installer to the proper folder, and LDraw is using that for parts reference just fine. There are no unofficial parts in this particular model. This message error comes up with leaving the project defaults, including the render at POV-Ray. If I change the render to LDGlite, then no 3d file renders will show in the publishing preview (the LeoCAD 3D viewer is unaffected). I had this same issue with the previous version of the install version 2.0.20, but I was able to switch to LDView as a workaround. Switching it back to POV-Ray does nothing and give the same error message (it earlier crashed the program, but the file may have been corrupted, so ya). I can keep on testing with different files but all other applications using the LDraw parts library are fine (LDCad, LDView, POV-Ray). The message box also does not allow a single time close, but will keep on coming up even if a window is opened on top, it will come to the top about once every minute or so.

I did just realize at this point that I was running LDView 4.2. To check if that was the issue, I updated to 4.3, and reinstalled LPub3D (I did not manually uninstall and reinstall, but ran the installer, which said it removed the previous version). However the same issues still persist even with a new .ldr file. 

LPub3D, when initially opening a file, sit for awhile not responding, but when it loads, it gives a sequence of 3 error messages. The first is this: Header: "LPub3D", Body: "LDView POV file generation failed with exit code 0". The second has the same header but has the message body of "Render CSI part failed for: C:/Users/user/Documents/LiononBricksCustomModelWorks/In Progress/MW-4--- 5-Wide Light Duty Maintenance Truck/LPub3D/assem/mian_1_0_0_0_1_0_0_0_1_1_1240_150_DPCM_1.png.". And the third has the same header with the body message of "Failed to create CSI.". These three error messages will repeat when attempting to load a different step.

I also created a new file to test if the age of the file (created before or after install) would make any difference, it had none.

The only thing I have not done that I think could maybe fix the issue is to reinstall everything using the LDraw All-In-One-Installer. That could get complicated as my install is somewhat manually done.

### Your environment
* Version of LPub3D - 2.1.0
* Operating system - Windows 10, Intel i7-3770 (Quad Core, 3.4 ghz), x86_64

### Configuration
[Note: Provide content below as needed with appropriate redactions]
* LPub3D installation path
	- Windows: `C:\Program Files\LPub3D` [x86_64]
* Application data path
	- Windows: `%USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\`
* Renderer configuration files
	- `[Application data path]/3rdParty\ldview-4.3\config\ldview.ini`
	- `[Application data path]/3rdParty\ldview-4.3\config\ldviewPOV.ini`
	- `[Application data path]/3rdParty\lpub3d_trace_cui-3.8\config\povray.conf`
	- `[Application data path]/3rdParty\lpub3d_trace_cui-3.8\config\povray.ini`
* Registry Extract
	- Windows: `reg export "HKEY_CURRENT_USER\Software\LPub3D Software" LPub3D_Hive.reg`
Ran command (assuming it is a Command Prompt command), unsure what to do after.

### Logging
* Application Log: `[Application data path]/logs/LPub3DLog.txt` 
[LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/1739032/LPub3DLog.txt)

* Renderer Log: `[LDraw model path]/stdout-ldglite`
[File Type Unsupported Error]

* Renderer Log: `[LDraw model path]/stdout-povray`
[File Type Unsupported Error]

* Renderer Log: `[LDraw model path]/stderr-ldglite`
[File Type Unsupported Error]

* Renderer Log: `[LDraw model path]/stderr-povray`
[File Type Unsupported Error]

### Screenshots
* Configuration->Preferences->General
![screenshot 17](https://user-images.githubusercontent.com/36654297/36410077-362b94f2-15cc-11e8-91c7-d8395f4813df.png)

* Configuration->Preferences->Rendering
![screenshot 18](https://user-images.githubusercontent.com/36654297/36410082-38767844-15cc-11e8-8e40-d7e4f2e96f90.png)

* Configuration->Preferences->Publishing
![screenshot 19](https://user-images.githubusercontent.com/36654297/36410099-489c2a70-15cc-11e8-96dc-45343d7f66ab.png)

* Configuration->Preferences->Logging
![screenshot 20](https://user-images.githubusercontent.com/36654297/36410104-4b753980-15cc-11e8-8a20-b234542440ef.png)

* Configuration->Preferences->Other
![screenshot 21](https://user-images.githubusercontent.com/36654297/36410105-4f804e5c-15cc-11e8-86e0-8d86d3681d92.png)

### Steps to reproduce
Use above described situation to test.

### Expected behaviour
File should open with a preview of the model and the specific step in the preview window.

### Actual behaviour
First error message given pops up and LPub3D can take up to 10 minutes to load a file (not responding in meantime).

### Workaround
No known workaround, I have a bit but very limited experience with the deeper "manual" side of the LDraw environment.

### Solution suggestion
Again, I am a noob, so I guess do what is needed to make it work? (That should not sound demanding, I just have no clue).

**Comment by trevorsandy** [comment]
My goodness, you seem to be in little mess here.

Somehow the instance of LDView used by LPub3D is no able to resolve some lines in your model file - Hence the message:
```
The message is "Critical Error: Could not find LDraw directory." 
"File: C:Users/user/Documents/LiononBricksCustomModelWorks/In Progress/MW-4--- 5-Wide Light Duty Maintenance Truck/LPub3D/tmp/csi.ldr"
"Unknown Line". 
```
A good start would be to take a look at the content in the **csi.ldr** file referenced by the message - on the Step the message is thrown from.

It sounds like you have installed LPub3D in an environment that previously had the LDraw.org AIOI? As the AIOI also has LPub3D. I think it is best to completely uninstall the AIOI instance of LPub3D. As that program uses its own install approach, I'm not sure what steps are necessary to uninstall just LPub3D.

For LPub3D v2.1.0, a good start is to read the LPub3D Release notes to understand the new capabilities and architecture. For example LPub3D brings its own instances of LDView, POV-Ray and LDGLite - as you can see in the 'renderers' section of the Preferences dialogue.

Your log look good except your LDView.ini/LDView Raytracer.ini files do not have a  [ExtraSearchDirs] section - I'm not sure how you managed to have that. Anyway, you can edit/correct these files from the UI->Configuration->Edit Parameter Files

For the Registry Extract above, the file `LPub3D_Hive.reg` should exist in the directory from which you ran the command. Find the file and attach it just as you did for the attached log.

For the stderr.out logs, add a .txt extension and attach if the file is not empty. LDView does not produce stderr/stdout logs so I actually don't think this step will be helpful for you.

**Comment by LiononBricks** [comment]
Alright, I'll run through each section above and see if I can get anything to work. I can tell you that the install of anything related to the LDraw Library was done is this order: I moved the parts library from a old computer in which I knew the location as I had a few unoffical parts I wanted in there, and to my knowledge that should do little to throw anything off since all the applications you can and sometimes have to guide to the parts library. At which point the AIOI came along, installing LDCad 1.6a beta, LDView 4.2, and POV-Ray 3.7. At a later time I updated LDCad to 1.6a. Awhile after that a install of LPub3D 2.0.10 was completed separately from the AIOI. Then yesterday during testing, LPub3D 2.1.0 was installed (after 2.0.10 was manually uninstalled, the 2.1.0 installer failed to do so, appears to be a known issue). After which LDView 4.3 was manually updated in an attempt to see if that related at all to the issue. I know that LPub3D 2.1.0 has their own versions of LDGlite, LDView, and POV-Ray built in, I was just not sure if there were any external dependencies. 

But whatever. I may end up having to tear up the whole library just to get it working. Too bad POV-Ray 3.7.1 is in beta (although I may give it a shot), and Roland Melkert has not finished a version of LDCad 2.0 yet enough to share a test version as he at least makes it sound that he is rebuilding it from the ground up. Ah well, life is life.

I'm just glad this issue is not as bad as my attempts to install POV-Ray any version on Linux. I have tried Mint Cinnamon 18.2, 18.3, KDE 18.3, and Ubuntu KDE/Plasma (Kubuntu). No matter what I do, the install process says that it works, but the application does not show up anywhere. I think even the package dependencies show up, but no actual application.

Alright then, time to give my keyboard and mouse a workout with logs and configuration files.

**Comment by LiononBricks** [comment]
Oh, I guess I just found the reg file (had to zip):
[LPub3D_Hive.zip](https://github.com/trevorsandy/lpub3d/files/1740314/LPub3D_Hive.zip)

**Comment by trevorsandy** [comment]
Looking at what you've shared. Your LPub3D install looks ok. with the exception of missing the [ExtraSearchDirs] header in your LDView ini files.  I'm going to close this issue. Feel free to reopen it if you have some more information to share.
