### ISSUE TITLE
HTML Part list error: Could not load command line file

### ISSUE THREAD

**Issue by trevorsandy** [trevorsandy/lpub3d#220]
###  Subject
HTML part list error: Could not load command line file.

### Environment
Version of LPub3D - 2.3.7
Operating system - All

### Expected behaviour
Successfully generate HTML part list

### Actual behaviour
![image](https://app.gitkraken.com/api/glo/boards/5b248f78dd21bf100044c350/attachments/5ca6d516925dd8000f8c6731)
![image](https://app.gitkraken.com/api/glo/boards/5b248f78dd21bf100044c350/attachments/5ca6d517925dd8000f8c6737)
![image](https://app.gitkraken.com/api/glo/boards/5b248f78dd21bf100044c350/attachments/5ca6d516925dd8000f8c6734)

As you can see in the return message, the 'removegroup' component of the filename is not captured.  The snapshot input file is not found because, when the filename contains spaces, only the last component of the name is captured.

### Solution
Place snapshot input filename in quotes.

See #196 for details on generating HTML part list

![image](https://app.gitkraken.com/api/glo/boards/5b248f78dd21bf100044c350/attachments/5ca6d77a8c7a3a0011c9fecd)

**Comment by trevorsandy** [comment]
Corrected.

Cheers,

**Comment by jacovandermolen** [comment]
Unfortunately 2.3.8 crashes on some models during generation of the HTML Parts list.
A simple model (like pyramid.ldr) works like a charm, but larger more complex models fail at some percentage of generation.  

[40252.mpd.txt](https://github.com/trevorsandy/lpub3d/files/3054605/40252.mpd.txt)
Attached models fails after 2%. LPub3D crashes.

**Comment by trevorsandy** [comment]
Hi Jaco - Very well. I'll take a look with the file you attached.

Cheers,

**Comment by trevorsandy** [comment]
> When there is no element ID defined for a part, the HTML part list generator abends.

This behaviour has been corrected - See #226.

Cheers,
