### ISSUE TITLE
Refactor annotations, add 'Fixed' annotation type

### ISSUE THREAD

**Issue by trevorsandy** [trevorsandy/lpub3d#222]
###  Subject
Refactor annotations and add new **Fixed* annotation type, which include axle, beam, cable, connector, hose and panel annotation styles.

### Environment
Version of LPub3D - 2.3.7
Operating system - All

### Solution
Part List (PLI) Annotation Options settings
![image](https://app.gitkraken.com/api/glo/boards/5b248f78dd21bf100044c350/attachments/5ca83653925dd8000f8c8a59)

Bill Of Materials (BOM) Annotation Options settings
![image](https://app.gitkraken.com/api/glo/boards/5b248f78dd21bf100044c350/attachments/5ca8374096ab06000fb1b7f4)

Assembly (CSI) Annotation Display settigns
![image](https://app.gitkraken.com/api/glo/boards/5b248f78dd21bf100044c350/attachments/5ca837dac6c3bd001269e3eb)

See #186 for Part List (PLI)  and  Bill Of Materials (BOM) Annotation setup and use details
See  #187 Assembly (CSI) Annotation setupo and use details

**Comment by trevorsandy** [comment]
Implemented.

Cheers,

**Comment by jacovandermolen** [comment]
Thank you. I'll implement this in the manual.
