### ISSUE TITLE
Toggling logging in preferences with GUI

### ISSUE THREAD

**Issue by 6638** [trevorsandy/lpub3d#223]
### Subject
Toggling Logging in preferences reverts back after restart of LPub3D.

### Environment
* 2.3.6 (install), 2.3.8 (portable)
* Windows 7 x64

### Configuration
N/A

### Logs
N/A

### Screenshots
N/A

### Steps to reproduce
Select Menu > Configuration > Preferences
Go to "Theme/Logging" tab
Toggle checkbox for "Logging"
Restart LPub3D
Select Menu > Configuration > Preferences
Go to "Theme/Logging" tab
Checkbox reverted back to the previous state

### Expected behaviour
Changing the preference with GUI works

### Actual behaviour
Changing the preference with GUI doesn't work

### Workaround
Upon toggling the logging, LPub3D adds the following line to LPub3D.ini:
**Logging=false**
or
**Logging=true**
But when LPub3D reads configuration it looks for the line:
**Logging%20=false**
or
**Logging%20=true**
The redundant space character causes the issue.
Workaround is to manually modify LPub3D.ini

### Solution suggestion
Normally, make LPub3D to read "Logging" option instead of "Logging%20".
Alternatively, make LPub3D to write "Logging%20" option instead of just "Logging".

**Comment by 6638** [comment]
### Workaround
The portable version also gave a hint on how to solve it in the installed version:
- Navigate to the "Logging " entry (with space in the end) in the registry and modify it manually.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

Indeed, there were trailing spaces in the Settings code. I have removed them.

To confirm the correction (in v2.3.9 - Windows Portable distribution) open your LPub3D.ini file and confirm the logging entry is correctly formatted.

Menu item
![Screenshot - 14_04_2019 , 08_17_54](https://user-images.githubusercontent.com/13388970/56089134-828a9d00-5e8e-11e9-9dfc-9f4d10e97304.png)

LPub3D.ini - Good format: **Logging=true** , Bad format: **Logging%20=true** 
![Screenshot - 14_04_2019 , 08_19_02](https://user-images.githubusercontent.com/13388970/56089135-83233380-5e8e-11e9-8b8f-36dd389b0493.png)

For all other distributions:

Select Menu > Configuration > Preferences
Go to "Theme/Logging" tab
Toggle checkbox for "Logging" and select some additional logging options

Default Logging settings
![Screenshot - 14_04_2019 , 08_25_32](https://user-images.githubusercontent.com/13388970/56089166-4dcb1580-5e8f-11e9-8492-3f466d375a5b.png)

Restart LPub3D
Select Menu > Configuration > Preferences
Go to "Theme/Logging" tab
Confirm checkbox state preserved

Modified Logging state preserved after shutdown
![Screenshot - 14_04_2019 , 08_26_41](https://user-images.githubusercontent.com/13388970/56089175-70f5c500-5e8f-11e9-84c7-bb660c4c93aa.png)

Cheers,
