### ISSUE TITLE
App hangs on changing font/color of annotations in Edit Annotation Style

### ISSUE THREAD

**Issue by 6638** [trevorsandy/lpub3d#224]
### Subject
LPub3D stops to respond upon a click on "Change" button for font or color in "Annotation Text Format" group in an Annotation Style.
The problem occurs on changing annotation styles for PLI as well as for BOM.
The problem occurs for all styles: Square, Circle, etc
The problem does not occur upon changing a font/color in "Default Text Format" for annotations, for Part Counts, Page Number etc.

### Environment
* 2.3.8 (portable)
* Windows 7 x64

### Configuration
N/A

### Logs
N/A

### Screenshots
N/A

### Steps to reproduce
The problem seem to occur in any file. It can be reproduced even with an empty file.
Go to Menu > Configuration > Build Instructions Setup > Parts List Setup
Switch to "Annotations" tab.
Check the  "Display Part List (PLI) Annotations" option.
Switch to "Edit styles"
Select to edit the "Square" style.
Press either of two buttons "Change" in "Square Annotation Text Format" group.

### Expected behaviour
Font/color dialog opened.

### Actual behaviour
Application stops to respond.

### Workaround
1. add metacommands manually
    0 !LPUB BOM SQUARE_STYLE FONT
    0 !LPUB BOM SQUARE_STYLE FONT_COLOR

2. Right click on annotation in building instructions, modify font/color and then refuse to apply to the current page only.

### Solution suggestion
A bug?

**Comment by trevorsandy** [comment]
Indeed, this is a bug. I must have broken something. I'll take a look.

Cheers,

**Comment by 6638** [comment]
Thanks, Trevor.

I guess, metacommand can be added manually as a workaround. Though, since it was introduced just recently, it is not documented yet (or say, I couldn't find it myself). Also I couldn't find a way for GUI to show the command in Editor or write it into the file. Could you please tell it, so that not to wait for the fix?

**Comment by 6638** [comment]
###Workaround
1. add metacommands manually
0 !LPUB BOM SQUARE_STYLE FONT
0 !LPUB BOM SQUARE_STYLE FONT_COLOR

2. Right click annotation in building instructions, modify font/color and then refuse to apply to the current page only.

**Comment by trevorsandy** [comment]
Corrected.

The text format type for annotation styles was going out of scope after initialization. Moving the type declaration to the class header solved this behaviour.

Menu item
![Screenshot - 14_04_2019 , 06_54_49](https://user-images.githubusercontent.com/13388970/56088500-74cf1a80-5e82-11e9-9a94-01f9aec811c5.png)

Parts List Globals Setup - Dialogue is the same for Bill of Materials Globals Setup
![Screenshot - 14_04_2019 , 06_55_21](https://user-images.githubusercontent.com/13388970/56088501-74cf1a80-5e82-11e9-9a89-ad3686eeb114.png)

Select Font
![Screenshot - 14_04_2019 , 06_55_51](https://user-images.githubusercontent.com/13388970/56088502-7567b100-5e82-11e9-8b36-6b4989887da5.png)

Select Color
![Screenshot - 14_04_2019 , 06_56_10](https://user-images.githubusercontent.com/13388970/56088503-7567b100-5e82-11e9-9791-ddc3b3c8b5be.png)

Cheers,
