### ISSUE TITLE
Disabling PLI/BOM sorting has no effect

### ISSUE THREAD

**Issue by 6638** [trevorsandy/lpub3d#225]
### Subject
Generally, it is almost impossible to control order of parts in PLI/BOM. There are commands to disable sorting for PLI and BOM:
0 !LPUB PLI|BOM SORT GLOBAL|LOCAL FALSE
Though, LPub3D always reorders parts in some way. Would it be possible to display parts in exactly the same order as they appear in the ldr/mpd, when sorting is disabled?

### Environment
2.3.8

### Configuration
N/A

### Logs
N/A

### Screenshots
N/A

### Steps to reproduce
0 FILE main.ldr
0 SAMPLE
0 !LPUB PLI SORT GLOBAL FALSE
1 1 20 -8.749 -50 1 0 0 0 1 0 0 0 1 32123a.dat
1 14 20 -8.749 -50 1 0 0 0 1 0 0 0 1 32123a.dat
1 71 40 -9.499 -50 0 0 -1 0 1 0 1 0 0 3713.dat

### Expected behaviour
Parts to appear in the PLI in exactly the same order as in the model:
- Blue half-bush
- Yellow half-bush
- Gray bush

### Actual behaviour
LPub3D changes the order of parts in PLI.

### Workaround
None :(

### Solution suggestion
N/A

**Comment by trevorsandy** [comment]
Thanks for reporting this behaviour. I'm not sure I want to change the packing routine to list parts in the order they appear in the model file. 

Can you prepare a use-case using a graphic illustration of the steps and outcome you expect. Currently, it is possible to sort the BOM - is this functionality not working for you ? I have not implemented the capability to sort the PLI and there is not request on the queue to do so. 

As you may have experienced, even after sorting the BOM, resizing it may alter the position of parts based on the packing routine's logic to optimize available space. You'll have to play with the new size to get your desired layout.

Cheers,

**Comment by trevorsandy** [comment]
Changing to “enhancement” as this ticket is requesting the option to suspend PLI packing optimisation.

Cheers,

**Comment by 6638** [comment]
Hello, Trevor.

Sometimes, I post process PLI in GIMP to reposition parts, as I want. I already got accustomed to that, and it is not critical.

But parts are ordered totally unpredictably in BOMs. For example, it would be best to have all types of axles listed in the BOM together. Though, I have some some other part types injected between different types of axles, even when sorting is set to "Part Category":

0 !LPUB BOM SORT_BY SORT_OPTION GLOBAL "Part Category"
0 !LPUB BOM CONSTRAIN GLOBAL COLS 3
0 !LPUB INSERT BOM
0 !LPUB INSERT PAGE
0 STEP
1 0 210 -5.624 90 0 0 1 0 1 0 -1 0 0 3707.dat
1 0 80 -5.625 50 0 0 1 0 1 0 -1 0 0 3705.dat
1 0 -310 -9.499 60 0 0 1 -1 0 0 0 -1 0 6629.dat
1 71 250 -5.624 100 0 0 1 0 1 0 -1 0 0 60485.dat
1 71 135 -5.625 60 0 0 1 0 1 0 -1 0 0 32073.dat
1 72 155 -7.499 65 0 0 -1 0 1 0 1 0 0 32209.dat
1 0 270 -5.624 110 0 0 1 0 1 0 -1 0 0 3737.dat
1 0 290 -5.624 130 0 0 1 0 1 0 -1 0 0 3708.dat
1 72 100 -7.5 50 0 0 -1 0 1 0 1 0 0 87083.dat
1 0 50 -29.999 10 0 -1 0 0 0 -1 1 0 0 32014.dat
1 28 65 -6 60 0 0 1 0 -1 0 1 0 0 6587.dat
1 72 230 -7.749 90 0 0 -1 0 1 0 1 0 0 55013.dat
1 71 -210 -29.5 385 0 0 1 0 1 0 -1 0 0 92910.dat
1 71 50 -5.625 60 0 0 1 0 1 0 -1 0 0 4519.dat
1 19 120 -7.624 50 0 0 1 0 1 0 -1 0 0 99008.dat
1 0 170 -5.624 70 0 0 1 0 1 0 -1 0 0 3706.dat
1 71 190 -5.624 80 0 0 1 0 1 0 -1 0 0 44294.dat
1 4 90 -5.625 -10 -1 0 0 0 1 0 0 0 -1 32062.dat
1 71 -270 -9.248 -85 0 0 1 1 0 0 0 1 0 41677.dat
1 71 -85 -10.028 -10 -1 0 0 0 1 0 0 0 -1 87082.dat
1 72 60.5 -9.248 135 0 -1 0 0 0 1 -1 0 0 10197.dat

<img width="960" alt="bom" src="https://user-images.githubusercontent.com/49516540/56098887-f7e58480-5f05-11e9-82f9-53c1ef128840.png">

And modifying it in GIMP would be like creating the BOM manually from scratch.

I thought that if sorting would be disabled, I could create a mock file, where I would put the parts in exactly the same order, as I want them to appear in the BOM.

**Comment by 6638** [comment]
Hello, Trevor.

And here is the use case with PLI:

```
0 FILE main.ldr
0 !LPUB PLI ANNOTATION DISPLAY GLOBAL TRUE
0 !LPUB PLI ANNOTATION STYLES GLOBAL TRUE
1 71 120.049 -9.489 -610.12 -1 0.001 0 0 0 1 0.001 1 0 48989.dat
1 71 -119.951 -9.489 -609.88 -1 0.001 0 0 0 1 0.001 1 0 48989.dat
1 71 0.069 10.651 -590 -0.001 0 1 0 1 0 -1 0 -0.001 41239.dat
1 71 0.029 10.511 -630 -0.001 0 1 0 1 0 -1 0 -0.001 41239.dat
1 4 120.049 -61.489 -590.12 0 0.5 -0.866 -1 0.001 0 0.001 0.866 0.5 arrow75.ldr
1 4 -119.951 -61.489 -590.12 0 0.5 -0.866 -1 0.001 0 0.001 0.866 0.5 arrow75.ldr
1 0 0.069 -99.489 -590 -1 0 -0.001 0 1 0 0.001 0 -1 64781.dat
0 STEP
1 0 0.069 -29.489 -590 -1 0 -0.001 0 1 0 0.001 0 -1 64781.dat
0 FILE arrow75.ldr
0 !LPUB NOSTEP
3 16 -24 0 0 4 -6 0 -2 0 0
3 16 -24 0 0 4 6 0 -2 0 0
3 16 -2 0 0 0 -2 0 0 2 0
4 16 0 -2 0 75 -2 0 75 2 0 0 2 0
```

I would like to swap the beam and the gear rack, but to keep cross block as it is. None of the sorting option works, but the order would be exactly as I need without the sorting.

Cheers!

**Comment by trevorsandy** [comment]
> I would like to swap the beam and the gear rack, but to keep cross block as it is.

I was able to achieve the above requirement by sorting the list by color and then adjusting the PLI size to reposition the cross block. You can see the steps in the following shots:

![Screenshot - 03_05_2019 , 01_14_11](https://user-images.githubusercontent.com/13388970/57123627-c3d1e680-6d82-11e9-9da8-52f1437eef79.png)
![Screenshot - 03_05_2019 , 01_14_52](https://user-images.githubusercontent.com/13388970/57123628-c3d1e680-6d82-11e9-9ed8-01e1a15c0076.png)
![Screenshot - 03_05_2019 , 01_15_41](https://user-images.githubusercontent.com/13388970/57123630-c46a7d00-6d82-11e9-9cd7-2f60b24072c8.png)
![Screenshot - 03_05_2019 , 01_16_24](https://user-images.githubusercontent.com/13388970/57123632-c46a7d00-6d82-11e9-9e9c-54b3d8aed51b.png)
![Screenshot - 03_05_2019 , 01_16_52](https://user-images.githubusercontent.com/13388970/57123633-c46a7d00-6d82-11e9-83ce-4e3a578e3dcd.png)
![Screenshot - 03_05_2019 , 01_17_46](https://user-images.githubusercontent.com/13388970/57123634-c46a7d00-6d82-11e9-991a-5402ab3c7163.png)

Cheers,

**Comment by 6638** [comment]
Hello, Trevor.

Thanks for your desire to help. Though, I was thinking of swapping the parts, while keeping the exactly same layout. I had to better express myself.

On the other hand, I am not sure that the layout would stay the same without the sorting, since you say that it would "suspend PLI packing optimisation", meaning that the parts would be displayed more loosely.

However, I still believe that the option could be extremely useful for BOMs.

Cheers.

**Comment by trevorsandy** [comment]
Very well.

I've extended the PLI/BOM sorting functionality by adding the ability to configure up to 3 options of multi-sorting and the sort direction (ascending / descending) for each option.

![Screenshot - 10_05_2019 , 22_58_30](https://user-images.githubusercontent.com/13388970/57558830-8fac8600-737f-11e9-8a6b-6e25fb4d04a4.png)

Cheers,

**Comment by 6638** [comment]
Wow! Hello, Trevor. It looks very promising. I look forward to the next version very much :)
Let me also express my deep respect to your passion of this project and your attention to its users.
Cheers!

**Comment by trevorsandy** [comment]
With pleasure. Many thanks.

I've added a quite large update to allow PLI/BOM part groups (part image, annotations, and instance count) to be manually dragged to any position on the display. See #260 for complete details. 

![Screenshot - 17_05_2019 , 04_09_06](https://user-images.githubusercontent.com/13388970/57899264-a6118080-785c-11e9-9094-c1fe203a6ae3.png)

With this last update, there is now complete flexibility to reposition PLI/BOM parts as desired. Additional, capabilities like scene guide, ruler tracking and snap-to-grid complement this capability allowing the user to manually reposition items with high precision. With these new capabilities in place, I will close this ticket.

Cheers,
