### ISSUE TITLE
Parts displayed suboptimally in PLI/BOM by default

### ISSUE THREAD

**Issue by 6638** [trevorsandy/lpub3d#228]
### Subject
Some technics parts are not included in pli.mpd and are displayed suboptimally in PLI/BOM by default.
I have updated pli.mpd with all necessary parts from Mindstorms EV3 (see attached):
6587
87083
55013
60483
64179
64178
6536
42003
44809
33299
99773
57585
59443
32013
6589
32498
92911
88323
64680
64393
64682
11946
64394
87086
64391
64681
64392
11947
87080
64683
99141c01
99143
95656
99455
95658
95652
95648
95650
99380
3749
43093
99008
32002
6641
6539
55982
61903
98989
32557
32291
92908
92910
48452
48168
99009
99010
62821
10197
6553
32005
92906
11478
11954
87408
10288
32123a
92909
2654
u9284
(some ~3-5 more parts are also added to pli.mpd, but may be missing in the list)

### Environment
LPub3D 2.3.6

### Configuration
N/A

### Logs
N/A

### Screenshots
N/A

### Steps to reproduce
N/A

### Expected behaviour
Parts are rotated in PLI/BOM

### Actual behaviour
Parts are not rotated in PLI/BOM

### Workaround
Update pli.mpd in every release

### Solution suggestion
Add the attached pli.mpd to the program package.
[pli.zip](https://github.com/trevorsandy/lpub3d/files/3076324/pli.zip)

**Comment by trevorsandy** [comment]
Excellent - many thanks for your contribution. 

I have always left the pli.mdp update to the user. As you know, users have this discretion and introducing a new pli.mpd may 'break' their existing instructions. However, I'm happy to add an updated pli.mpd that only includes new entries - original entries remain untouched.

Cheers,

**Comment by 6638** [comment]
Ups... Hello, Trevor. No, indeed, I also modified placement of some existing parts (they are also in the list above). If this doesn't fit your concept, please feel free to ignore this file -- I perfectly understand your approach to leave it to users.

**Comment by trevorsandy** [comment]
New parts were added to the LPub3D Pli.ldr control file.

Cheers,
