### ISSUE TITLE
Styling annotations

### ISSUE THREAD

**Issue by 6638** [trevorsandy/lpub3d#229]
### Subject
1. Annotations with decimal values wrap at the position of the decimal point.
2. Annotations are not centered within the box.
3. Altering font size is ignored for some annotations.
4. Margins to Element Annotations are applied to instance count -- no way to reduce margins between instance count and the Element Annotations.

### Environment
* LPub3D 2.3.8 x64 (portable)
* Windows 7 x 64

### Configuration
Default

### Logs
N/A

### Screenshots
<img width="130" alt="page_1" src="https://user-images.githubusercontent.com/49516540/56059873-866ed000-5d65-11e9-9988-0ccbe132de4c.png">
<img width="132" alt="page_2" src="https://user-images.githubusercontent.com/49516540/56059875-866ed000-5d65-11e9-919c-5ebb57c4ffcf.png">

### Steps to reproduce
1. The first screenshot
0 !LPUB BOM INSTANCE_COUNT FONT GLOBAL "Arial,10,-1,5,50,0,0,0,0,0"
0 !LPUB BOM ANNOTATION DISPLAY GLOBAL TRUE
0 !LPUB BOM CIRCLE_STYLE FONT GLOBAL "Arial,6,-1,5,50,0,0,0,0,0"
0 !LPUB BOM CIRCLE_STYLE SIZE GLOBAL 0.2 0.2
0 !LPUB BOM PART_ELEMENTS DISPLAY GLOBAL TRUE
0 !LPUB BOM ELEMENT_STYLE MARGINS GLOBAL 0 0
0 !LPUB BOM ELEMENT_STYLE FONT GLOBAL "Arial,10,-1,5,50,0,0,0,0,0"
0 !LPUB INSERT BOM
0 !LPUB INSERT PAGE
0 STEP
1 72 155 -7.499 65 0 0 -1 0 1 0 1 0 0 32209.dat

2. The second screenshot:
0 !LPUB BOM INSTANCE_COUNT FONT GLOBAL "Arial,10,-1,5,50,0,0,0,0,0"
0 !LPUB BOM ANNOTATION DISPLAY GLOBAL TRUE
0 !LPUB BOM CIRCLE_STYLE FONT GLOBAL "Arial,50,-1,5,50,0,0,0,0,0"
0 !LPUB BOM CIRCLE_STYLE SIZE GLOBAL 0.6 0.6
0 !LPUB BOM PART_ELEMENTS DISPLAY GLOBAL TRUE
0 !LPUB BOM ELEMENT_STYLE MARGINS GLOBAL 1 1
0 !LPUB BOM ELEMENT_STYLE FONT GLOBAL "Arial,10,-1,5,50,0,0,0,0,0"
0 !LPUB INSERT BOM
0 !LPUB INSERT PAGE
0 STEP
1 72 155 -7.499 65 0 0 -1 0 1 0 1 0 0 32209.dat

### Expected behaviour
- In the first screenshot, annotation shall not wrap.
- In the first schreenshot, there shall be no spacing between instance count and element annotations.
- In the second screenshot, annotation shall be centered in its content box
- In the second screenshot, margin shall be between instance count and element annotations.
- In both screenshots, annotation shall respect font size definition.

### Actual behaviour
Annotation wraps.
Annotation is aligned to the top of the content box
Content box of the Element Annotation comprises instance count.
Annotation ignores font size definition.

### Workaround
None.

### Solution suggestion
As described above.

**Comment by trevorsandy** [comment]
This is on my TODO list. I did try but a reliable solution with Qt is a bit complicated and quite time-consuming so I pushed in onto the queue. In the meantime, you'll have to use a font style and size that does not wrap its characters when placed in the style shape. Alternatively, you could increase the shape size in the Global Setup.

Cheers,

**Comment by 6638** [comment]
Hello, Trever.

It is neither critical to me -- I just wanted to log it for your information.

Though, your propose to change the font size. Please pay attention that in some reason it is not possible to change the font size for this specific part (it is problem #3 in the subject).

Thanks for your awesome work!

**Comment by trevorsandy** [comment]
Very well.

I think the font behaviour is linked to #224. I'll take a look when I get to that ticket.

Cheers,

**Comment by trevorsandy** [comment]
I’ve taken a look and updated my initial response.

I’ll reference this ticket when I’ve put in place a solution to automatically resize text with more than 2 characters to the size of the style shape.

Cheers,

**Comment by trevorsandy** [comment]
### Solution
Automatically size and align fixed style annotation font.

![Screenshot - 18_04_2019 , 02_49_05](https://user-images.githubusercontent.com/13388970/56330305-c380fb00-6187-11e9-8b9e-641131cf4e8d.png)

Cheers,
