### ISSUE TITLE
Annotation styles stop working with LEGOAnnotationStyle.lst

### ISSUE THREAD

**Issue by 6638** [trevorsandy/lpub3d#230]
### Subject
Annotation styles stop working, after LPub3D exports LEGOAnnotationStyle.lst.

### Environment
* 2.3.8 x64 portable
* Windows 7 x 64

### Configuration
Default

### Logs
N/A

### Screenshots
See below.

### Steps to reproduce
1. Open an .ldr file in LPub3d:
0 !LPUB PLI ANNOTATION DISPLAY GLOBAL TRUE
1 71 50 -5.625 60 0 0 1 0 1 0 -1 0 0 4519.dat
Annotation styles work as expected:
<img width="80" alt="page_1" src="https://user-images.githubusercontent.com/49516540/56080682-4e6a9a00-5e04-11e9-917b-28fb2b526954.png">

2. Select: Menu > Edit Parameter Files > Edit Part Annotation Style reference
3. Restart LPub3D.
4. Open the .ldr file again.
5. Annotation styles stopped working:
<img width="79" alt="page_2" src="https://user-images.githubusercontent.com/49516540/56080652-fb90e280-5e03-11e9-8b55-590bfa565443.png">

6. Remove LEGOAnnotationStyle.lst
7. Restart LPub3D.
8. Open the .ldr file.
9. Annotation styles work as expected.

### Expected behaviour
The styles to respect custom references

### Actual behaviour
The styles stop to working with manual references.

### Workaround
None

### Solution suggestion
A bug?

**Comment by trevorsandy** [comment]
This is a known issue for the AnnotationStyle.lst and has already been corrected in v2.3.9

### Workaround

**NOTE** in v2.3.8, the wrong Part Annotation Style Reference regular expression is exported. 
Replace line: `# The Regular Expression used is: ^([^\t]+)\t+\s*([^\t]+)\t+\s*([^\t]+).*$`
With line: `# The Regular Expression used is: ^(\b[^=]+\b)=([1|2])\s+([1-6])?\s*([^\s]+).*$`

see #196 for full details.

Cheers,
