### ISSUE TITLE
LEGO Elements file (name, location, format)

### ISSUE THREAD

**Issue by 6638** [trevorsandy/lpub3d#231]
### Subject
How to define local Lego elements file? What should be the name of the file? Where should it be located? What is the expected format?

### Environment
* 2.3.8 x64 portable
* Windows 7 x64

### Configuration
Default

### Logs
N/A

### Screenshots
N/A

### Steps to reproduce
0 !LPUB BOM ANNOTATION DISPLAY GLOBAL TRUE
0 !LPUB BOM PART_ELEMENTS DISPLAY GLOBAL TRUE
0 !LPUB BOM PART_ELEMENTS LEGO GLOBAL TRUE
0 !LPUB BOM PART_ELEMENTS LOCAL_LEGO_ELEMENTS_FILE GLOBAL TRUE
0 !LPUB INSERT BOM
0 !LPUB INSERT PAGE
0 STEP
1 71 50 -5.625 60 0 0 1 0 1 0 -1 0 0 4519.dat

### Expected behaviour
- Local file with Element ids is used.
- If part is missing locally, its id to be included to the error text.

### Actual behaviour
- An error occurs.
- Error text doesn't contain part number, which causes the problem:
"LEGO Elements file was not found :"

### Workaround
None

### Solution suggestion
Could you please tell name and location of the file? Could you please share a sample file to learn its expected format.

**Comment by trevorsandy** [comment]
See ADVANCED SETUP in #196

Cheers,
