### ISSUE TITLE
LDGLite Crashing

### ISSUE THREAD

**Issue by cameronmiller1988** [trevorsandy/lpub3d#232]
### Subject
I have used LPub 2.2.2 on a Win 7 32-bit VM for a long time. I have found that the LDGLite picture quality far surpasses all the others for printing instructions. Any time I try a new version on the VM (always the portable copy instead of an install) I am met with a crash of LDGLite for each model assembly step that I need to render. I am hoping to continue to use LDGLite but I am open to others if I can get some pointers on how to make the rendered images turn out in a similar quality.
Here is the screen cap of the about page for the version that works:
https://imgur.com/gKcS65W

I also have tried to use LDGLite on a Windows Laptop (64 bit) I recently purchased and even on version 2.2.2 I have the same issue. 
Here is a screen shot of version 2.2.2:
https://imgur.com/f2hzpWZ

I have also tried 2.3.8 (portable) on this laptop:
https://imgur.com/9gYsY1p

There is no change in the behavior on the laptop

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
Win7 VM 
C:\Program Files\LPub3D
Win7 Laptop
2.2.2 - C:\Program Files\LPub3D
2.3.8 - C:\Users\Home\Downloads\LPub3D Portable\LPub3D_x86_64-2.3.8\LPub3D_x86_64

* Registry Extract
Win7 VM
https://drive.google.com/open?id=186aNHuoaOohaA-EDxzGERbjMUiUK6W8T
Laptop 2.2.2
https://drive.google.com/open?id=1mc6OCXsP8nKMe02w6nT0b86gdfu4hLck
Laptop 2.3.8 Portable
https://drive.google.com/open?id=1p3N4PUDgVGWkq_MGhX--1yB0CkwXs1Po

* Renderer configuration files
Win7 VM
https://drive.google.com/open?id=1UHdmR3RXpoA7xbwxe5-tHfKtUZOl3AXM
Laptop 2.2.2
https://drive.google.com/open?id=1Ykf6DNWftVSYkIY2NgUVi2efj4lOAV0E
Laptop 2.3.8 Portable
https://drive.google.com/open?id=13P-RBV3neR3aRoMMQd7OUipuPUEfavr3

### Logs
Win7 VM
Cannot locate Application log for V2.2.2
STDERR - https://drive.google.com/open?id=1rBenuAW-yDQEhXVmbqa2cLwzdY0aljWg
STDOUT - https://drive.google.com/open?id=11Lyg1Q5gVP7w0w5T3pQd_OUVkai0HOGL
Laptop 2.2.2
Cannot locate Application log for V2.2.2
STDERR - https://drive.google.com/open?id=1w6s9kW45_6PbI3qDo2MdxAKI26G2Fq0k
STDOUT - https://drive.google.com/open?id=1DoUbtkdBd1T7a0cIOuZiHena3Do2ikcD
Laptop 2.3.8 Portable
App Log - https://drive.google.com/open?id=1Bb7-2U1eiksYeX0GwZ_FUJqIphVrlQSl
STDERR - https://drive.google.com/open?id=1aIrFDBu9-LJUevjt7n1Ud5fX22U2xJSY
STDOUT - https://drive.google.com/open?id=1ZWXK_ZTBWL38MEiPy2t2mRI3yNtX4IH_

### Screenshots
All these configurations have not been altered except to select the LDGLite Renderer

### Steps to reproduce
Here is a link to a file that will produce the error but it has been any file I open
https://drive.google.com/open?id=1kDYqgQe41eIHOh_Ma1IdM0LBvddMiIn8

### Expected behaviour
Pages are rendered without issue.

### Actual behaviour
There is a crash between eash page that needs to be re-rendered

### Workaround
Don't upgrade my version of LPub3D

### Solution suggestion
I would like to see the "crash" happen in the background because even clicking cancel on the error message passes the image along with no issues. 

Additionally this behavior all happens on both of my Mac installs of any version of LPub but the error does not stop the processing of rendered images. 

Also for 2.3.8 The step number is rendered on top of the assembly for a single step on a page regardless of settings.

**Comment by cameronmiller1988** [comment]
I would like to add that since I had all this open, I have also now started experiencing the issue on the once working VM.

**Comment by trevorsandy** [comment]
Cameron, 

Thank you for reporting this behaviour. 
I’m not able to access the assets placed on google drive - instead I’m prompted to “request access” from the account owner . 
Could you bundle the items into a .zip file and attach it to this ticket?

Cheers,

**Comment by cameronmiller1988** [comment]
Ok okay here is a zip with subfolders for each version and the LDraw file I used for the logs. 
[LDGLite Issues.zip](https://github.com/trevorsandy/lpub3d/files/3091254/LDGLite.Issues.zip)

**Comment by trevorsandy** [comment]
Cameron,

The source of the abnormal behaviour is the naming convention you are using. I was able to generate two AbEnd occurrences with your default file. Basically, LDGLite renders the part but it is never written to the parts subfolder - likely because of a stumble in the generated path name. As no image is written to parts subfolder, on the attempt to insert the part into the instruction document, the NULL image condition forces an AbEnd.

After closing the unconventional naming patterns in your file, there were no AbEnd occurrences. All seven pages, all parts and all assemblies were generated without issue. 

You can see the naming changes I've made to your file in the attached instance. 

[40_Container_02_LPub3D.zip](https://github.com/trevorsandy/lpub3d/files/3092269/40_Container_02_LPub3D.zip)

You can also see similar behaviour in these other tickets were models designed in Stud.io are using naming patterns that conflict with LPub3D - #152, #208 . As I encounter these inconsistencies, I will attempt to correct them but, in the meantime, you can easily avoid abnormal behaviour by adhering to LDraw naming patterns.

Cheers,

**Comment by cameronmiller1988** [comment]
Hey Trevor,
Much appreciate your time to dig into this. 
Just to be sure I understand, I would need to add .ldr to each sub model name and then add that for each time that call out is used and then also use the correct header?

**Comment by cameronmiller1988** [comment]
Hello Again,
I believe I corrected this file but I am still having the crashing. The only other change I made was to uninstall everything LDraw related and reinstall including 2.3.8
[GE U25B V3 Conrail test 2.zip](https://github.com/trevorsandy/lpub3d/files/3093079/GE.U25B.V3.Conrail.test.2.zip)

**Comment by trevorsandy** [comment]
Cameron, try removing the spaces in the submodel names - i.e, replace “ “ with “_” or “-“. Furthermore, try placing the model file locally on your computer and in a folder that does not have any spaces in the name - e.g. c:\test\my-model-without-spaces-in-the-path.mpd.

Cheers,
