### ISSUE TITLE
CSI margins applied to PLI

### ISSUE THREAD

**Issue by 6638** [trevorsandy/lpub3d#238]
### Subject
Assembly margins are applied to PLIs; PLI margins are ignored.

### Environment
* LPub3D 2.3.9 x64 (portable)
* Windows 7 x64

### Configuration
Default

### Logs
N/A

### Screenshots
N/A

### Steps to reproduce
0 !LPUB STEP_NUMBER MARGINS 0 0
0 !LPUB PLI MARGINS GLOBAL 0 0 
0 !LPUB ASSEM MARGINS GLOBAL 2 2
0 !LPUB PLI PLACEMENT TOP_LEFT PAGE_HEADER INSIDE
1 71 0 0 0 0 0 1 0 1 0 -1 0 0 64179.dat
0 STEP
1 71 0 0 0 0 0 1 0 1 0 -1 0 0 64179.dat

Outcome:
<img width="960" alt="1" src="https://user-images.githubusercontent.com/49516540/56460622-c5280a00-63a5-11e9-9ae9-98fab2beee8c.png">

0 !LPUB STEP_NUMBER MARGINS 0 0
0 !LPUB PLI MARGINS GLOBAL 2 2
0 !LPUB ASSEM MARGINS GLOBAL 0 0
0 !LPUB PLI PLACEMENT TOP_LEFT PAGE_HEADER INSIDE
1 71 0 0 0 0 0 1 0 1 0 -1 0 0 64179.dat
0 STEP
1 71 0 0 0 0 0 1 0 1 0 -1 0 0 64179.dat

Outcome:
<img width="960" alt="2" src="https://user-images.githubusercontent.com/49516540/56460627-d5d88000-63a5-11e9-9afb-1d350e55e96e.png">

### Expected behaviour
PLI margins to be applied to PLI; Assembly margins to affect only assembly.

### Actual behaviour
Assembly margins are applied to the assembly as well as to the PLI; PLI margins definition is ignored.

### Workaround
Define PLI margins using assembly margins; Then position assembly using offsets.

### Solution suggestion
Looks like a bug.

**Comment by trevorsandy** [comment]
Thanks for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

This was an old LPub bug.

2" (300px @ 150 DPI) margin applied to CSI
![Screenshot - 23_04_2019 , 03_10_37](https://user-images.githubusercontent.com/13388970/56544652-6a450d00-6575-11e9-80b8-6af0bd5fa98c.png)

2" (300px @ 150 DPI) margin applied to PLI
![Screenshot - 23_04_2019 , 03_13_07](https://user-images.githubusercontent.com/13388970/56544836-edfef980-6575-11e9-80d4-62e6b0ca6918.png)

Cheers,
