### ISSUE TITLE
Assembly overlaps the PLI

### ISSUE THREAD

**Issue by zero0n3** [trevorsandy/lpub3d#243]
### Subject
The assembly overlaps the PLI (or the PLI remains below assembly)
![Screenshot - 25_04_2019 , 03_32_05](https://user-images.githubusercontent.com/13388970/56704954-651bc580-670f-11e9-92c1-aed7e04c324d.png)

### Environment
* Version of LPub3D - 2.3.10
* Operating system - MacOs

### Steps to reproduce
Open ldr. I moved the PLI in the middle to show the issue.

### Expected behaviour
Like in 2.3.9, PLI should stay over the assembly

[overlap_PLI.ldr.zip](https://github.com/trevorsandy/lpub3d/files/3113846/overlap_PLI.ldr.zip)

**Comment by trevorsandy** [comment]
Updated.

Opps, I forgot to place the PLI on top in the update for #241. 
![Screenshot - 25_04_2019 , 03_48_38](https://user-images.githubusercontent.com/13388970/56704979-7533a500-670f-11e9-8d56-24b16c22b1c1.png)

Cheers,
