### ISSUE TITLE
Step number counted from zero

### ISSUE THREAD

**Issue by 6638** [trevorsandy/lpub3d#245]
### Subject
The very first step is displayed as "0" in some cases.

### Environment
* LPub3D 2.3.10 x64 (portable)
* Windows7 x64

### Configuration
Default

### Logs
N/A

### Screenshots
<img width="960" alt="2" src="https://user-images.githubusercontent.com/49516540/56831637-e8512e80-6869-11e9-8a02-470694b32f9d.png">

### Steps to reproduce
```
0 FILE main.ldr
0 !LPUB CONTINUOUS_STEP_NUMBERS GLOBAL TRUE
1 71 0.069 10.651 -590 -0.001 0 1 0 1 0 -1 0 -0.001 41239.dat
1 71 0.029 10.511 -630 -0.001 0 1 0 1 0 -1 0 -0.001 41239.dat
1 71 120.049 -9.489 -610.12 -1 0.001 0 0 0 1 0.001 1 0 48989.dat
1 71 -119.951 -9.489 -609.88 -1 0.001 0 0 0 1 0.001 1 0 48989.dat
1 4 120.049 -61.489 -590.12 0 0.5 -0.866 -1 0.001 0 0.001 0.866 0.5 arrow75.ldr
1 4 -119.951 -61.489 -590.12 0 0.5 -0.866 -1 0.001 0 0.001 0.866 0.5 arrow75.ldr
1 0 0.069 -99.489 -590 -1 0 -0.001 0 1 0 0.001 0 -1 64781.dat
0 STEP
1 0 0.069 -29.489 -590 -1 0 -0.001 0 1 0 0.001 0 -1 64781.dat
0 FILE arrow75.ldr
0 !LPUB NOSTEP
3 16 -24 0 0 4 -6 0 -2 0 0
3 16 -24 0 0 4 6 0 -2 0 0
3 16 -2 0 0 0 -2 0 0 2 0
4 16 0 -2 0 75 -2 0 75 2 0 0 2 0
```

### Expected behaviour
Should be step 1

### Actual behaviour
Step is 0

### Workaround
Not known

### Solution suggestion
Bug

**Comment by trevorsandy** [comment]
Thanks for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

![Screenshot - 03_05_2019 , 08_17_08](https://user-images.githubusercontent.com/13388970/57122240-a69a1980-6d7c-11e9-877f-f68f2fe95f51.png)

![Screenshot - 03_05_2019 , 08_17_23](https://user-images.githubusercontent.com/13388970/57122244-ae59be00-6d7c-11e9-9c59-10ec9c256008.png)
 
Cheers,
