### ISSUE TITLE
Parts List Annotation Styles font can't be edited separately; always changes Rectangle style

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#246]
I was fiddling around with the new Annotation styles and I can't seem to edit the Square/Circle font styles. It always saves as Rectangle. In fact, just opening the color or font selection menus show the Rectangle settings.

See these images:

This is what the settings menu for Sqaure (or Circle) looks like. Take note of the font and font-color:
![image](https://user-images.githubusercontent.com/12005521/57093157-6cddfa00-6d0d-11e9-8c05-11f3dd1a9fee.png)

But when I open e.g. the color menu:
![image](https://user-images.githubusercontent.com/12005521/57093217-8f701300-6d0d-11e9-970e-d4f8e34a0f97.png)

It suddenly shows a different selected color (it's maybe a bit difficult to see since they're both blue, but it's a different blue). In fact, it's the blue that is already select at the Rectangle:
![image](https://user-images.githubusercontent.com/12005521/57093265-b2022c00-6d0d-11e9-9326-f389d30047f1.png)

And it also saves as Rectangle when I change the color, even though I'm in the Square or Circle menu.

Hope that makes sense :)

LPub3D Version: 2.3.10 Revision 0 Build 1240

**Comment by trevorsandy** [comment]
Corrected.

![Screenshot - 03_05_2019 , 08_32_21](https://user-images.githubusercontent.com/13388970/57122545-3b514700-6d7e-11e9-93fc-ed21eba58fdd.png)

![Screenshot - 03_05_2019 , 08_32_04](https://user-images.githubusercontent.com/13388970/57122549-3ee4ce00-6d7e-11e9-843e-adebd0bd49f1.png)

Cheers,
