### ISSUE TITLE
DPI incorrectly saved as DPC when having default units at Centimeters

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#247]
This bug is really old. It might even be from when LPub3D was just LPub, not sure.

It's pretty straightforward. In the Project Globals Setup one can choose between 'Dots Per Inch' and 'Dots Per Centimeter'. When I have my LPub3D set to Centimeters as default units, the Dots Per Inch will actually save the value for Dots Per Centimeter... as Dots Per Inch.

So, example: I have Default Units at Centimeter. I go to the Project Globals and specifically select Dots Per **Inch**. I then fill in 300 and press save. In the META commands, LPub stores a DPI of 118, which is the 300 dpi converted to dpc. That's all great, but it saves as DPI (thus, Inch!). So, it's converting the value though it's not necessary. In fact, it's not only not necessary but just plain wrong. I already selected that I'm filling in DPI and not DPC.

I hope that explanation makes sense haha.

**Comment by trevorsandy** [comment]
Corrected. Indeed this was a legacy bug - good catch.

![Screenshot - 03_05_2019 , 05_28_03](https://user-images.githubusercontent.com/13388970/57122622-7f444c00-6d7e-11e9-9790-df0c5e932573.png)

![Screenshot - 03_05_2019 , 05_30_06](https://user-images.githubusercontent.com/13388970/57122623-7f444c00-6d7e-11e9-8355-0c3cded57b8e.png)

![Screenshot - 03_05_2019 , 05_30_47](https://user-images.githubusercontent.com/13388970/57122624-7f444c00-6d7e-11e9-9aa7-e39886abd430.png)

![Screenshot - 03_05_2019 , 05_31_14](https://user-images.githubusercontent.com/13388970/57122625-7fdce280-6d7e-11e9-9107-2e4db634cc25.png)

![Screenshot - 03_05_2019 , 05_31_43](https://user-images.githubusercontent.com/13388970/57122626-7fdce280-6d7e-11e9-89fb-601c985588ce.png)

Cheers,
