### ISSUE TITLE
Option to show Part Title/Freeform PLI annotations with fixed annotation styles

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#248]
Is there a way to display Part Title/Freeform PLI annotations as either square/circle PLI annotations? If there is, could you please tell me how to do that. If there isn't, then make please considerg this a feature request :)

Thanks!

**Comment by trevorsandy** [comment]
Yes. See ADVANCED SETUP section in #196.

Fixed annotation styles are intended to display the LEGO annotations associated with Technic parts. These annotations are usually between 1-2 characters with the exceptions of the 5.5 Axle. When the specified font exceeds the size of the fixed bounding, the font size is automatically scaled down until the specified text fits into the bounds. The font size will not scale lower than 1 point. There is also the possibility to edit the fixed style bounding size in PLI global setup. 

The Extended style [Rectangle shape] is intended for annotations with more than 3 characters. It provides the same level of customization as is available for fixed styles. For example, rounded edges can be specified. This style automatically scales to the size of the specified text.

Cheers,

**Comment by Landcross** [comment]
Ah, the 'Part Annotation Style reference' ini file is exactly what I was looking for. I was already looking for. Thanks! :)
