### ISSUE TITLE
Step Group Setup -> Divider tab has no ok/cancel buttons

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#249]
This one's pretty straightforward. The Step Group settings menu, Divider tab has no OK/Cancel buttons. The 'Content' tab has buttons and they work fine saving the divider settings, so it's a really minor issue. But I figured I'd report it anyway.

![image](https://user-images.githubusercontent.com/12005521/57103054-167cb580-6d25-11e9-826b-5f3e2befa811.png)

**Comment by trevorsandy** [comment]
Corrected.
![Screenshot - 03_05_2019 , 08_39_42](https://user-images.githubusercontent.com/13388970/57122745-1dd0ad00-6d7f-11e9-9169-76b9ed964d81.png)

Cheers,
