### ISSUE TITLE
Part list is hidden by model in front

### ISSUE THREAD

**Issue by jensbruehl** [trevorsandy/lpub3d#250]
### Subject
In v2.3.10 the part list may be hidden by the model itself. In previous versions the part list was displayed on top of the model.

### Environment
LPub3D v2.3.10 with LDView Renderer
Windows 10 x64

### Steps to reproduce
Open [42056-1 - Porsche 911 GT3 RS.mpd](https://bricksafe.com/files/jb70/42056-pimp-up-my-porsche/42056-1%20-%20Porsche%20911%20GT3%20RS.mpd) in LPub3D v2.3.10 and go to page 10

### Expected behaviour
Compare to [42056-1 - Porsche 911 GT3 RS.pdf](https://bricksafe.com/files/jb70/42056-pimp-up-my-porsche/42056-1%20-%20Porsche%20911%20GT3%20RS.pdf) which was made with earlier versions of LPub3D

### Actual behaviour
Part list is hidden by model in front

### Solution suggestion
Display part list on top of model as in previous versions

**Comment by trevorsandy** [comment]
Thanks for reporting this behavior. It has been corrected in #243 and will be released in the next update.

Cheers,
