### ISSUE TITLE
Submodel callout does not rotate as the parent image

### ISSUE THREAD

**Issue by jensbruehl** [trevorsandy/lpub3d#251]
### Subject
When I use the function "Add assembled image to parent page" for a sub model, the submodel is not rotated as the parent image. Instead it displays a rotate icon in the submodel frame. 

![Screenshot - 04_05_2019 , 04_56_56](https://user-images.githubusercontent.com/13388970/57177577-5a76d400-6e65-11e9-8ec7-e334cc97a682.png)

### Environment
LPub3D v2.3.10 with LDView renderer
Windows 10 x64

### Steps to reproduce
Load [42056-1 - Porsche 911 GT3 RS.mpd](https://bricksafe.com/files/jb70/42056-pimp-up-my-porsche/42056-1%20-%20Porsche%20911%20GT3%20RS.mpd) in LPub3d v2.3.10 and go to page 17.

### Expected behaviour
See [42056-1 - Porsche 911 GT3 RS.pdf](https://bricksafe.com/files/jb70/42056-pimp-up-my-porsche/42056-1%20-%20Porsche%20911%20GT3%20RS.pdf) which was created with a previous version of LPub3D:
Sub model image should be rotated as the parent image

### Actual behaviour
Sub model is rotated wrong and displays a rotate icon

**Comment by trevorsandy** [comment]
Jens - Thanks for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

![Screenshot - 04_05_2019 , 12_06_48](https://user-images.githubusercontent.com/13388970/57177543-1f74a080-6e65-11e9-9709-1fd0d0934851.png)

Cheers,
