### ISSUE TITLE
Export Bricklink XML and CSV part list not working

### ISSUE THREAD

**Issue by riazanovskiy** [trevorsandy/lpub3d#258]
### Subject
Nothing happens when I click "Export as Bricklink XML part list". 

I can find file `LPub3D\tmp\test6_parts.ldr`. But nothing happens in the LPub itself

### Environment
LPub3D 2.3.10 (downloaded from Github releases)
Windows 10 

### Configuration
* LPub3D installation path `C:\Program Files\LPub3D` [x86_64]
* Application data path `%USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\`
* Registry [LPub3D_Hive.txt](https://github.com/trevorsandy/lpub3d/files/3166924/LPub3D_Hive.txt)

### Logs
* https://pastebin.com/Kktnb9Kv

### Screenshots
* ![General](https://user-images.githubusercontent.com/11013917/57535299-9a005d00-734a-11e9-9fae-bc0d103acf59.png)
* ![Rendering](https://user-images.githubusercontent.com/11013917/57535331-abe20000-734a-11e9-9687-782700e29246.png)
* ![Publishing](https://user-images.githubusercontent.com/11013917/57535365-c025fd00-734a-11e9-99c8-34a30f4c684e.png)
* ![Logging ](https://user-images.githubusercontent.com/11013917/57535397-d207a000-734a-11e9-8334-3b9c10ba1f15.png)
* ![Other ](https://user-images.githubusercontent.com/11013917/57535437-e3e94300-734a-11e9-8c8e-d8a95201b7d9.png)

### Steps to reproduce
[test6.ldr.txt](https://github.com/trevorsandy/lpub3d/files/3166928/test6.ldr.txt)

Export to Bricklink XML and CSV part list does not work, while export to HTML works

**Comment by trevorsandy** [comment]
Thanks for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

BRICKLINK XML Export
![Screenshot - 10_05_2019 , 22_39_21](https://user-images.githubusercontent.com/13388970/57555749-68e95200-7375-11e9-9232-906c4b649ef7.png)
![creenshot - 10_05_2019 , 22_40_17](https://user-images.githubusercontent.com/13388970/57555750-6981e880-7375-11e9-9a0a-a51ae068849a.png)
![Screenshot - 10_05_2019 , 22_42_39](https://user-images.githubusercontent.com/13388970/57555751-6981e880-7375-11e9-91fb-26dfb6c5f92d.png)
![Screenshot - 10_05_2019 , 22_43_12](https://user-images.githubusercontent.com/13388970/57555752-6981e880-7375-11e9-9c4c-c24ec692a4b7.png)

CSV Export
![Screenshot - 10_05_2019 , 22_48_12](https://user-images.githubusercontent.com/13388970/57555887-c382ae00-7375-11e9-8e50-5debab9c84a2.png)
![Screenshot - 10_05_2019 , 22_43_58](https://user-images.githubusercontent.com/13388970/57555753-6981e880-7375-11e9-9db7-aaa96ada9ad0.png)
![Screenshot - 10_05_2019 , 22_44_36](https://user-images.githubusercontent.com/13388970/57555754-6981e880-7375-11e9-9765-19ae007aa9e1.png)
![Screenshot - 10_05_2019 , 22_45_10](https://user-images.githubusercontent.com/13388970/57555755-6a1a7f00-7375-11e9-8309-8ecc110f9a71.png)

Cheers,
