### ISSUE TITLE
Shortcut to open and close documents are the same

### ISSUE THREAD

**Issue by snakebyte73** [trevorsandy/lpub3d#259]
### Subject
The keyboard shortcut to open and close a document in LPUB 3D is the same: CTRL+O
Closing a document via CTRL+O does not work.
Neither does Opening a document via CTRL+O when a document is allready open.
This is not a new behavior.

### Environment
* Version of LPub3D - 2.3.9 Rev 0 Build 1228
* Operating system - Windows 10 x64 17134

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  - Windows: `C:\Program Files\LPub3D`
* Application data path
  - Windows: `%USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\`

* Registry Extract
  - no need
%USERPROFILE%\Desktop\LPub3D_Hive.reg`
  - no need
* Renderer configuration files
  - no need

### Logs
  - no need

### Screenshots
![LPUB3D](https://user-images.githubusercontent.com/38093610/57565178-04e87d00-73b9-11e9-97d2-9742af7ff3d3.png)

### Steps to reproduce
Open a ldr/mpd file i LPub3D, the try using the keyboard shortcuts to open and close a document CTRL+O

### Expected behaviour
CTRL+O to open a document
CTRL+W to close a document

### Actual behaviour
Nothing happens when using CTRL+O when a document is allready open, and it is not possible to close an open document via keyboard

### Workaround
Share your work around if available

### Solution suggestion
change keyboard shortcut for closing a document from CTRL+O to CTRL+W

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I’ll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

Cheers,
