### ISSUE TITLE
Multiple page BOM sorting is scrambled

### ISSUE THREAD

**Issue by jensbruehl** [trevorsandy/lpub3d#262]
### Subject
The new BOM sorting features in LPub v2.3.11 are pretty fine. But, when you have a lot of parts in your build, they may not fit on one BOM page. LPub has a feature to spread BOM to several pages. In v2.3.11 the sorting is scrambled, if you have more than 1 page of BOM.

### Environment
* Version of LPub3D: v2.3.11
* Operating system: Windows 10 64

### Steps to reproduce
Simply add several pages of BOM like this:

0 !LPUB INSERT PAGE
0 !LPUB INSERT BOM
0 STEP
0 !LPUB INSERT PAGE
0 !LPUB INSERT BOM
0 STEP

### Expected behaviour
In previous versions of LPub the sorting of BOM was not changeble, but working over several pages.

### Actual behaviour
Sorting works fine with only 1 BOM page, but is scrambled when you have more than 1 BOM page.

**Comment by trevorsandy** [comment]
Thanks for reporting this behaviour. I’ll take a look. 

Can you share a screenshot of the “scrambled” multi-BOM display? It would be good to see an example of the expected and unexpected displays.

Cheers,

**Comment by jensbruehl** [comment]
Before v2.3.11 it looked like this
![LPub Multi BOM1](https://user-images.githubusercontent.com/50247249/57968698-24117c80-796e-11e9-8e16-4aa41013a5e0.jpg)

With v2.3.11 the sorting is scrambled:
![LPub Multi BOM2](https://user-images.githubusercontent.com/50247249/57968705-37bce300-796e-11e9-8a06-71ed616105ae.jpg)

**Comment by trevorsandy** [comment]
Corrected.
![Screenshot - 19_05_2019 , 03_30_40](https://user-images.githubusercontent.com/13388970/57976750-cfaae300-79e7-11e9-845f-927040722327.png)

![Screenshot - 19_05_2019 , 03_27_18](https://user-images.githubusercontent.com/13388970/57976752-d2a5d380-79e7-11e9-93b3-48c0b7ce2345.png)

Cheers,
