### ISSUE TITLE
Continuous step numbers cause multiple problems with submodels

### ISSUE THREAD

**Issue by 6638** [trevorsandy/lpub3d#263]
### Subject
1. The metacommand CONSOLIDATE_INSTANCE_COUNT GLOBAL FALSE is ignored.
2. Step number is not incremented at the last step of the submodel.
3. Submodel is displayed again at the last step of the submodel.
4. Wrong CSI rendering at the last step of the submodel.

### Environment
* LPub3D v2.3.11 x64 portable
* Windows 7 x64

### Configuration
Default, except as rendering engine is set to LDGLite.

### Steps to reproduce
[LDraw file](https://github.com/trevorsandy/lpub3d/files/3194389/1.zip)

Item 1.
CONSOLIDATE_INSTANCE_COUNT is set to false globally.
<img width="960" alt="1" src="https://user-images.githubusercontent.com/49516540/57973992-6f00b380-79b1-11e9-8ea7-6a29c7ef1420.png">

But instance count is consolidated for the submodel anyway.
<img width="960" alt="2" src="https://user-images.githubusercontent.com/49516540/57974040-44fbc100-79b2-11e9-8015-f68e8330db04.png">

Items 2, 3, 4
- Step number shows 3 at the 4th step.
- Submodel is displayed again at the last step.
- CSI from the previous step is displayed (but PLI is correct).

<img width="960" alt="3" src="https://user-images.githubusercontent.com/49516540/57974072-bb98be80-79b2-11e9-9a68-a2edc5986c80.png">

**Comment by trevorsandy** [comment]
Many thanks for reporting this behaviour.

The test file you supplied was quite helpful in tracking down the behaviour for your scenario.

There were two sources for the behaviour you described:
1. Continuous step numbers produces abnormal renderings and step numbers
2. Consolidate submodel instance count flag ignored - see 264 

Both items have been corrected. The behaviour for v2.3.12 can be seen in the following shots:

![Screenshot - 20_05_2019 , 22_58_32](https://user-images.githubusercontent.com/13388970/58052249-9643b600-7b54-11e9-8f8b-f333bc5d87a7.png)

![Screenshot - 20_05_2019 , 23_00_48](https://user-images.githubusercontent.com/13388970/58052250-96dc4c80-7b54-11e9-9a93-f2471b086a24.png)

![Screenshot - 20_05_2019 , 23_01_27](https://user-images.githubusercontent.com/13388970/58052252-96dc4c80-7b54-11e9-8707-5817e9a9a408.png)

![Screenshot - 20_05_2019 , 23_03_22](https://user-images.githubusercontent.com/13388970/58052253-96dc4c80-7b54-11e9-9106-bdfc1d6b1bc9.png)

![Screenshot - 20_05_2019 , 23_04_42](https://user-images.githubusercontent.com/13388970/58052255-9774e300-7b54-11e9-969d-4337ce97e533.png)

![Screenshot - 20_05_2019 , 23_05_11](https://user-images.githubusercontent.com/13388970/58052256-9774e300-7b54-11e9-8206-d3d977eae952.png)

![Screenshot - 20_05_2019 , 23_05_42](https://user-images.githubusercontent.com/13388970/58052257-9774e300-7b54-11e9-9e4b-22932701ce12.png)

Cheers,
