### ISSUE TITLE
No Submodel preview with LDView option "use multiple file single call"

### ISSUE THREAD

**Issue by jensbruehl** [trevorsandy/lpub3d#265]
### Subject
I always had problems in previous LPub3D releases to enable the new feature !LPUB SUBMODEL_DISPLAY SHOW. In my models I only saw a small empty square, but no submodel image. Now I think, there is some dependancy with the LDView option "use multiple file single call". When I activate this option, I see the empty square, but no submodel. When I deselect this option, the submodel image appears as it should, but rendering pages takes much more time.

### Environment
* Version of LPub3D v2.3.11
* Operating system - Windows 10 x64

### Configuration
Renderer LDView with option "use multiple file single call" enabled

### Steps to reproduce
Load this file into LPub3D:

0 FILE main.ldr
0 Name: Main
0 !LPUB SUBMODEL_DISPLAY SHOW_TOP_MODEL GLOBAL TRUE
0 !LPUB SUBMODEL_DISPLAY SHOW GLOBAL TRUE
1 2 0 0 0 1 0 0 0 1 0 0 0 1 3865.dat
0 STEP
1 16 0 -24 0 1 0 0 0 1 0 0 0 1 subModel-1.ldr
0 STEP
0 NOFILE 
0 FILE submodel-1.ldr
1 4 0 0 0 1 0 0 0 1 0 0 0 1 3001.dat
1 4 0 -24 0 1 0 0 0 1 0 0 0 1 3001.dat
1 4 0 -48 0 1 0 0 0 1 0 0 0 1 3001.dat
1 4 0 -72 0 1 0 0 0 1 0 0 0 1 3001.dat
0 NOFILE 

### Expected behaviour
![Submodel2](https://user-images.githubusercontent.com/50247249/58050805-a35ea600-7b50-11e9-8630-03bb62c92742.jpg)

### Actual behaviour
![Submodel1](https://user-images.githubusercontent.com/50247249/58050813-abb6e100-7b50-11e9-8786-d38a3156dd37.jpg)

### Workaround
Deactivate LDView option "use multiple file single call" and accept slower performance

**Comment by trevorsandy** [comment]
Thanks for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

![Screenshot - 21_05_2019 , 15_15_16](https://user-images.githubusercontent.com/13388970/58099217-802d0880-7bdb-11e9-9b92-cc9d965f957d.png)

Cheers,
