### ISSUE TITLE
Callout origin placement is wrong

### ISSUE THREAD

**Issue by riazanovskiy** [trevorsandy/lpub3d#268]
### Subject
Callout arrow behaves weirdly during callout drag-and-drop movement.

### Environment and
LPub3D 2.3.11, same as in #267

See video
https://imgur.com/m0zWOi4

I suppose the pointer vector itself is calculated correctly and only the offset (vector origin) is wrong

```
0 FILE main.ldr
0 Name: submodel-test
0 Author: LDraw
1 71 -50 40 0 1 0 0 0 1 0 0 0 1 3033.dat
0 STEP
1 16 -60 -32 -10 1 0 0 0 1 0 0 0 1 sub.ldr
0 FILE sub.ldr
0 Author: LDraw
1 4 0 0 0 1 0 0 0 1 0 0 0 1 14716.dat
```

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

The positioning of the pointer while the callout is being dragged is as designed - or rather lack of design. Basically, the pointer base is moving to the optimal position of the original callout placement. At the same time, the pointer tip is moving to the optimal position based on the new position of the base.

Certainly it is possible, and may look better during object drag, to manage the pointer position during mouse drag but I have not gotten around to doing it as there is little value other than aesthetics. My focus regarding this capability was where the pointer is placed on mouse release. From your video and my test using the file you provided, this behaviour is as designed and as expected.

However, at some point, I may take a look at the pointer position during mouse drag and implement a change.

Cheers,
