### ISSUE TITLE
[Installation] macOS Installation not working properly (v2.1.0.0.775_20180213)

### ISSUE THREAD

**Issue by KurtPfeifle** [trevorsandy/lpub3d#27]
### Issue

The installation process on macOS (mine is "Sierra") does not work as expected. It required me to manually create the missing subdirectory *'libraries'* in (existing) directory *"~/Library/Application\ Support/LPub3D\ Software/LPub3D/"*.

A less experienced user would not be able to do that and hence could not enjoy the great looking LPub3D app. (Congrats, BTW, to the new release -- after fixing this it will surely be great and rocking!)

### Environment

* Version of LPub3D:
**v2.1.0.0.775_20180213**
The image you posted was for the 3DViewer not LPub3D so I removed it.

* macOS version

macOS Sierra 10.12.6 running on Intel Core i7

### Configuration

* LPub3D installation path
	- macOS: `/Applications/LPub3D.app`
* Application data path
	- macOS: `~/Library/Application Support/LPub3D Software/LPub3D/`

### Installation Process in Screenshots

1. Initial dialog

![lpub3d-insta-on-mac---shot1](https://user-images.githubusercontent.com/4747960/36629486-8200e872-1956-11e8-9fa5-f4e6a2fa53d1.jpeg)

Choosing *'Extract Archive'*...

2. Doesn't find the archive...

![image](https://user-images.githubusercontent.com/4747960/36629504-d3823e80-1956-11e8-8b4d-8f7b12f56cd0.png)

Note: there is also a typo in the text here: *attmpted*

3. Investigating...

I find that the requested directory structure is only present in part:

* *"~/Library/Application\ Support/LPub3D\ Software/LPub3D/"* is present and contains only subdirs *"extras"* and *"logs"*, but not *"libraries"*.

![image](https://user-images.githubusercontent.com/4747960/36629564-8bc84ac0-1957-11e8-83c7-647a4bc2bf5a.png)

So I proceed to create the missing directory...

4. Create missing directory

![image](https://user-images.githubusercontent.com/4747960/36629565-9a5a4bce-1957-11e8-8f8d-a67dfb2e7a12.png)

5. Re-attempting the *'Extract Archive'* step now completes and LPub3d.app can be started.

### Steps to reproduce

Try to install [this DMG](https://github.com/trevorsandy/lpub3d/releases/download/v2.1.0/LPub3D-2.1.0.0.775_20180213-macos.dmg) on a MacBook.

### Expected behaviour

I should not have to manually create the missing directory.

### Actual behaviour

The installation procedure should create the missing directory automatically.

### Workaround

Create the missing directory manually.

### Solution suggestion

Fix the installation procedure so that it creates the missing directory itself.

**Comment by trevorsandy** [comment]
Many thanks for reporting this behaviour. I'll take a look.

**Comment by trevorsandy** [comment]
Fixed - see milestone for deployment version
