### ISSUE TITLE
Native render fails with camera FOV command

### ISSUE THREAD

**Issue by riazanovskiy** [trevorsandy/lpub3d#270]
### Subject
Render fails only with Native engine, ok with LDView or any other

![Screenshot_2019-05-23_17-01-43](https://user-images.githubusercontent.com/11013917/58259069-7c84b780-7d7c-11e9-8c3e-350a77b65bb1.png)
![Screenshot_2019-05-23_17-01-28](https://user-images.githubusercontent.com/11013917/58259070-7d1d4e00-7d7c-11e9-9487-e516d4eb537c.png)

### Configuration
LPub3D 2.3.11 under Arch LInux

### Logs 
https://gist.github.com/riazanovskiy/75d0b597b6cdad7e588e92a098f67ecf

### Steps to reproduce
```
0 FILE main.ldr
0 !LPUB ASSEM CAMERA_FOV 0.0060
1 0 -171.058 82.97 159.955 -1 0 0.007 -0.007 -0.003 -1 0 -1 0.003 32054.dat
```

**Comment by riazanovskiy** [comment]
Same on Windows 10

**Comment by trevorsandy** [comment]
Thanks for reporting this behaviour, I’ll take a look.

Cheers,

**Comment by trevorsandy** [comment]
The Native renderer, based on LeoCAD, uses a completely different projection framework than the l3P based projection uses for LDGLite and LDView. The standard Native FOV is 30 degrees. Using .006 degrees presents a FOV so small that the image is less than 1px x 1px; hence the returned message, the image is empty. When using the Native renderer, you should adjust your FOV accordingly. 

I’ll adjust the range control so a more intuitive message is returned when the specified FOV is unsuitable. The current range is 0 to 360 degrees. Using 0 degrees will likely produce unintended results.

Cheers,

**Comment by riazanovskiy** [comment]
Is there any easy mean to rescale this parameter between the two renderers?
Then it would be possible to enforce one scale (for example, 0–360) for the
` !LPUB ASSEM CAMERA_FOV` command and then feed the renderer the value it requires.

The choice of a renderer is a LPub3D level setting, it is not embedded in the file. So I would expect that change of a renderer (or introduction of a new rendering engine) would only affect how rendered parts look like, not qualitatively change the whole instruction.

The current settings model, which separates application-level settings, which affect rendering backend, performance, logging etc and file-level settings, which are stored in every instruction file and affect the appearance of that instruction, seems very reasonable, and this different format of FOV angle diverges from it.

**Comment by trevorsandy** [comment]
The different renderers have slightly different characteristics and configuration parameters. While the 3rd party renderers LDView and LDGLite both respect the L3P "camera globe" settings architecture where camera distance is calculated from a ratio based on LDraw units (LDU). The Native renderer (based on LeoCAD) uses a different framework where camera distance, for example, uses an arbitrary unit to calculate camera distance. The default Native distance is 260 units for CSI assemblies and 100 for PLI parts. The camera distance for LDView and LDGLite is dynamically calculated based on several factors including page size, image scale etc...
If you wish to switch between native and 3rd party renderers, you must take into account the different characteristics between renderers.

**Comment by trevorsandy** [comment]
Implemented.

![Screenshot - 25_05_2019 , 01_33_31](https://user-images.githubusercontent.com/13388970/58361184-26ec0000-7e8d-11e9-982e-23da5c685805.png)

Cheers,
