### ISSUE TITLE
Load LDCad generated flex parts that use LDraw subparts

### ISSUE THREAD

**Issue by riazanovskiy** [trevorsandy/lpub3d#272]
### Subject
An error dialog appears every time I open a file which contains `s\....dat` parts

![image](https://user-images.githubusercontent.com/11013917/58291904-d9598f80-7dc7-11e9-9023-bdcbe7637f1f.png)

All these parts ("s\58124s03.dat", "s\faxle1.dat" etc) are old parts and are in fact present in local library.

### Environment
LPub3D 2.3.11, Windows 10

### Logs
* Application Log: https://gist.github.com/riazanovskiy/d17de7f844d5073d93b1aae5bc46f48b

### Steps to reproduce
[flex-axle-test.mpd](https://github.com/trevorsandy/lpub3d/files/3214420/flex-axle-test.mpd.txt)

**Comment by trevorsandy** [comment]
Thanks for reporting this behaviour.

The part validation routine that runs on the model file load reports an error when part design oriented subparts are detected in the model file. I haven’t written any logic to validate subparts assuming these part components are entirely unlikely to be included in instructions for obvious reasons.

Cheers,

**Comment by riazanovskiy** [comment]
That's a reasonable assumption, but my case doesn't seem to be very rare: faxle parts come from using a Technic flexible axle template from this forum thread https://forums.ldraw.org/thread-23006.html
and `58124s03.dat` comes, I suppose, from using Power functions LDCad template and then placing the wire and the connector by hand

**Comment by trevorsandy** [comment]
You are correct. 
The current LPub3D design targets the LSynth flex-part architecture. 
I’m integrating LDCad as requests come in.

**Comment by trevorsandy** [comment]
Philo is detailing how to port LDCad generated flex parts to BrickLink’s Studio in the referenced forum post. I imagine you would like LPub3D to join the party 😄

**Comment by trevorsandy** [comment]
Implemented.

![Screenshot - 25_05_2019 , 09_28_18](https://user-images.githubusercontent.com/13388970/58366231-77844d00-7ecf-11e9-9480-1f194e0311f3.png)

Cheers,
