### ISSUE TITLE
installer has typo "Dektop Icon"

### ISSUE THREAD

**Issue by MinnieTheMoocher** [trevorsandy/lpub3d#277]
LPub3D installer contains the typo "Dektop Icon"

![LPub3D 2 3 11 Screenshot01](https://user-images.githubusercontent.com/3216359/58436303-f0002f00-80c4-11e9-9299-285103c1182c.png)

**Comment by trevorsandy** [comment]
Corrected. Thanks for reporting this item.

Cheers,
