### ISSUE TITLE
HTML export uses Native renderer image naming convention

### ISSUE THREAD

**Issue by riazanovskiy** [trevorsandy/lpub3d#278]
### Subject
Suppose I use "Export as HTML part list" on following file
```
1 1 0 -16 -80 1 0 0 0 1 0 0 0 1 3006.dat
1 1 160 -40 -80 1 0 0 0 1 0 0 0 1 3006.dat
1 1 340 -16 -80 1 0 0 0 1 0 0 0 1 3006.dat
1 1 520 -40 -80 1 0 0 0 1 0 0 0 1 3006.dat
1 1 660 -16 -80 1 0 0 0 1 0 0 0 1 3006.dat
0 STEP
1 4 720 -40 -90 0 0 -1 0 1 0 1 0 0 3002.dat
```

The generated HTML has following line:
```
<td class="image"><a href="https://www.bricklink.com/v2/catalog/catalogitem.page?P=3002&idColor=5"><img alt="View on Bricklink.com" title="View on Bricklink.com" src="LPub3D\parts\3002_4_1240_150_DPCM_-260_30_23_-45.png"></a></td>
```
Now, if I used Native renderer, this would look just fine. But if I used LDView renderer (I have used it due to the #273, but I believe people may use it for any reason) the files generated in the LPub3D directory are
```
3002_4_1240_150_DPCM_1_0.01_23_-45.png
3006_1_1240_150_DPCM_1_0.01_23_-45.png
```
which use different convention for camera FOV and scale instead of distance.
So naturally, HTML renders as following, without images:
![image](https://user-images.githubusercontent.com/11013917/58506434-f9a69700-8197-11e9-8bc6-af9edbbc677c.png)

### Environment and configuration
LPub3D 2.3.11 on Windows 10

### Solution suggestion
Perhaps the HTML generation routine should choose image naming convention considering the current renderer in settings. Unfortunately, this is another case of renderer abstraction leaking which I mentioned in [another issue](https://github.com/trevorsandy/lpub3d/issues/270#issuecomment-495640557)

**Comment by trevorsandy** [comment]
Thanks for reporting this behaviour. 

The HTML generated naming convention should follow the renderer. I must have overlooked implementing the logic because it is the design I put in place when I switched from using the Peeron images.

**Workaround**

Open the generated HTML file in your favourite plain-text editor, **find** `DPCM_-260_30_23_-45.png` and **replace** it with `DPCM_1_0.01_23_-45.png`.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

![Screenshot - 29_05_2019 , 03_38_32](https://user-images.githubusercontent.com/13388970/58523123-9a5e7c00-81c3-11e9-97b6-deb044d412f2.png)
![Screenshot - 29_05_2019 , 03_55_51](https://user-images.githubusercontent.com/13388970/58523672-b5ca8680-81c5-11e9-8f4d-1bd17b86a565.png)
![Screenshot - 29_05_2019 , 03_40_15](https://user-images.githubusercontent.com/13388970/58523125-9af71280-81c3-11e9-9e1a-c16569aed7ed.png)

Cheers,
