### ISSUE TITLE
[Enhancement suggestion] Make text field panes in re-sizeable dialog windows also re-sizeable

### ISSUE THREAD

**Issue by KurtPfeifle** [trevorsandy/lpub3d#28]
I hate it on Windows when dialog boxes meant to display important info are small, rigid and fixed-sized with no chance to re-size it.

It's good to see LPub3D to have a re-sizeable *'Preferences'* dialog box. However....

![image](https://user-images.githubusercontent.com/4747960/36629709-2484ff18-195a-11e8-954d-8d0085694bba.png)

...when really re-sizing it, the embedded fields still stay on the same size and rigid. Especially the "Change log" box should re-adapt and give more space to read the change log.

*(Also note: the button for* 'Check for Updates' *could do with a bigger width...)*

**Comment by trevorsandy** [comment]
Sounds good. I'll take a look

**Comment by trevorsandy** [comment]
Added to LPub3DNext feature requests
