### ISSUE TITLE
Add substitute part from context menu

### ISSUE THREAD

**Issue by trevorsandy** [trevorsandy/lpub3d#280]
###  Subject
Add an option when you right click on the PLI "brick" to add Substitute part, with a dialogue to also change color,  scale, camara angels etc. 

The aim is to automate the following manually entered meta commands:

~~~
0 !LPUB PLI BEGIN SUB 20844c01.dat 15
0 !LPUB PART BEGIN IGN
1 15 -160 -24 20 0 0 1 0 1 0 -1 0 0 powerfunc2distsens-1.ldr
0 !LPUB PLI END
0 !LPUB PART END
~~~

![image](https://app.gitkraken.com/api/glo/boards/5b248f78dd21bf100044c350/attachments/5cf259053881ae000f738b3b)

### Environment
Version of LPub3D - 2.3.12
Operating system - All

### Solution
Insert, update or remove part substitution meta commands via the PLI part context menu (right-click) with a dialogue to configure the following:

**Primary Arguments**: 
- Part type, 
- Part colour, 

**Extended Arguments**: 
- Scale
- Field of View
- Camera angle latitude
- Camera angle longitude
- Part rotation - Using ROTSTEP arguments 

**NOTE:** _Extended Arguments_ are disabled when LDView '_Single Call_' render option is enabled. As this option processes multiple part model files simultaneously (i.e. on a single command call), it is not currently possible to individually apply the extended arguments to each part.

![Screenshot - 12_06_2019 , 02_27_42](https://user-images.githubusercontent.com/13388970/59317748-96068880-8cc4-11e9-9df0-bc8c01638309.png)

![Screenshot - 12_06_2019 , 02_29_20](https://user-images.githubusercontent.com/13388970/59317749-96068880-8cc4-11e9-8792-ab7bf08fc19c.png)

![Screenshot - 12_06_2019 , 02_30_37](https://user-images.githubusercontent.com/13388970/59317750-969f1f00-8cc4-11e9-9cb0-e879ab9e8d80.png)

![Screenshot - 12_06_2019 , 02_32_16](https://user-images.githubusercontent.com/13388970/59317751-969f1f00-8cc4-11e9-80df-d95741532479.png)

![Screenshot - 12_06_2019 , 02_32_57](https://user-images.githubusercontent.com/13388970/59317754-969f1f00-8cc4-11e9-9706-e8f4379918e1.png)

![Screenshot - 12_06_2019 , 02_33_58](https://user-images.githubusercontent.com/13388970/59317755-9737b580-8cc4-11e9-9106-55a0d055aa7e.png)

![Screenshot - 12_06_2019 , 02_58_05](https://user-images.githubusercontent.com/13388970/59317757-9737b580-8cc4-11e9-977b-fcf61172e6b7.png)

![Screenshot - 12_06_2019 , 03_32_42](https://user-images.githubusercontent.com/13388970/59317758-9737b580-8cc4-11e9-9a5a-48b64b054117.png)

![Screenshot - 12_06_2019 , 03_52_34](https://user-images.githubusercontent.com/13388970/59317942-889dce00-8cc5-11e9-90de-18e0232c82c6.png)

![Screenshot - 12_06_2019 , 03_53_42](https://user-images.githubusercontent.com/13388970/59317981-b08d3180-8cc5-11e9-96ff-05ec73ca7045.png)

![Screenshot - 12_06_2019 , 03_54_24](https://user-images.githubusercontent.com/13388970/59318003-c864b580-8cc5-11e9-8d39-93ca4e17e410.png)

**Comment by trevorsandy** [comment]
Implemented.

Cheers,

**Comment by snakebyte73** [comment]
Hi Trevor
When I try to substitute a part in LPUB3D it crashes.
I am according to LPUB3D using latest version.
I have tried the following:
create a new file
add 2 bricks
save the file.
open it in LPub3D
right click one of the bricks an choose substitute part.
When the dialog comes up i enter the part number eg. 3010
tab out of the field and click ok
Now LPub3D chrashes.
/Knud
