### ISSUE TITLE
Submodel step is rotated without CAMERA_ANGLES command

### ISSUE THREAD

**Issue by riazanovskiy** [trevorsandy/lpub3d#281]
### Subject
See image:
![image](https://user-images.githubusercontent.com/11013917/58754348-b8cfba80-84d6-11e9-93f9-c3313bdf671e.png)

The _second_ step in the callout is rotated with no reason to be rotated

### Environment
LPub3D 2.3.11 under Windows 10

### Configuration
![image](https://user-images.githubusercontent.com/11013917/58754353-de5cc400-84d6-11e9-83e2-47f4755ef28b.png)

### Steps to reproduce
[submodel-rotation.mpd](https://github.com/trevorsandy/lpub3d/files/3244265/submodel-rotation.mpd.txt)

**Comment by trevorsandy** [comment]
Thanks for reporting this behaviour. I’ll take a look.

Cheers,

**Comment by trevorsandy** [comment]
The behaviour generated by the sample model file is as designed.

Explanation...

- The meta command at line 2 `0 !LPUB ASSEM CAMERA_ANGLES 23.0000 165` sets the camera angles for all following assemblies to **23**, **165**
- At step 2, the camera angles are overridden **only for this step** with the meta command `0 !LPUB ASSEM LOCAL CAMERA_ANGLES 23.0000 50.0000`
- As a result of the `LOCAL` scope defined for angles **23**, **50**, only the first step in step 2's Callout inherits these angles. The second step of the Callout reverts to the previously defined **23**, **165** camera angles.

If you remove the `LOCAL` designation from step 2's camera angles meta command, assemblies in all the called out steps will render using **23**, **50** as shown below.

![Screenshot - 04_06_2019 , 12_50_22](https://user-images.githubusercontent.com/13388970/58874339-d8c6d000-86c8-11e9-8ae0-ee1262094e31.png)

Cheers,

**Comment by riazanovskiy** [comment]
It is a bit unintuitive that the `LOCAL` command applies twice -- both to the current step and the callout first step. I genuinely thought this was a bug.

Thank you for explaining this.

**Comment by trevorsandy** [comment]
The CALLOUT BEGIN meta does not initiate a new step. So the Callout first step is the current step. A new step is designated with the STEP or ROTSTEP meta command.

Cheers,
