### ISSUE TITLE
Bricklink XML config ignored, some tags missing

### ISSUE THREAD

**Issue by riazanovskiy** [trevorsandy/lpub3d#282]
### Subject
Let's use file I linked in another issue (#281).
[submodel-rotation.mpd](https://github.com/trevorsandy/lpub3d/files/3244265/submodel-rotation.mpd.txt)
If I use "Export as Bricklink XML", following is 
generated:
```
<INVENTORY>
  <ITEM>
    <ITEMTYPE>P</ITEMTYPE>
    <ITEMID>32015</ITEMID>
    <COLOR>11</COLOR>
  </ITEM>
  <ITEM>
    <ITEMTYPE>P</ITEMTYPE>
    <ITEMID>4519</ITEMID>
  </ITEM>
  <ITEM>
    <ITEMTYPE>P</ITEMTYPE>
    <ITEMID>6536</ITEMID>
    <COLOR>11</COLOR>
  </ITEM>
  <ITEM>
    <ITEMTYPE>P</ITEMTYPE>
    <ITEMID>6538b</ITEMID>
    <COLOR>11</COLOR>
  </ITEM>
  <ITEM>
    <ITEMTYPE>P</ITEMTYPE>
    <ITEMID>43093</ITEMID>
    <COLOR>7</COLOR>
  </ITEM>
  <ITEM>
    <ITEMTYPE>P</ITEMTYPE>
    <ITEMID>87083</ITEMID>
    <MINQTY>2</MINQTY>
  </ITEM>
  <ITEM>
    <ITEMTYPE>P</ITEMTYPE>
    <ITEMID>58176</ITEMID>
    <COLOR>98</COLOR>
  </ITEM>
  <ITEM>
    <ITEMTYPE>P</ITEMTYPE>
    <ITEMID>59443</ITEMID>
    <MINQTY>2</MINQTY>
    <COLOR>11</COLOR>
  </ITEM>
</INVENTORY>
```

As you can see, some parts miss `COLOR` and `MINQTY` tag.

Moreover, I have following `ld2blcodesxref.lst` config (I'll create another issue about the need of having such file):
```
3245a	     3245b
32126	     44
3957a	     3957
76116	     98313
3819	      981
3818	      982
18575	      32269
19475-f1	19475c01
19478-f1	19467c01
26674-f1	bb875
32006	2825
32123a	4265c
3648b	3648
4032a	4032
47223d-f1	4694cc01
58120	58120c01
58121	58121c01
58123	58123c01
59426	32209
59443	6538c
6141	4073
61903	62520c01
61929	bb339c01
62821	62821b
6562	3749
6590	3713
75974	67c01
92693c01-f1	92693c01
99498	99498c01
```

The part number 59443 is mapped to 6538c in this config, but in the Bricklink XML I have `<ITEMID>59443</ITEMID>` , so the config is ignored.

### Environment and configuration
Same as in #281

**Comment by trevorsandy** [comment]
Thanks for reporting this behaviour. In fact, the Bricklink XML export is currently independent of the HTML export backend config files. The HTML export uses LDView as the renderer while the BL export uses the Native renderer (based on LeoCAD). The config files framework was put in place to power PLI and CSI annotations and has been extended to support the HTML export. It is my aim to converge the design so all the export routines use the same set of configuration files as appropriate. 

Cheers,

**Comment by riazanovskiy** [comment]
I created Bricklink XML by parsing the HTML generated by LPub and noticed that the only colors which are missing (no `<COLOR>` tag) are Light Bluish Gray and Dark Bluish Gray. Also the `<MINQTY>` tag is missing if the quantity is 1, but that's not entirely correct: Bricklink supports empty MINQTY field, so here explicit `<MINQTY>1</MINQTY>`  would be better

**Comment by trevorsandy** [comment]
Many thanks for sharing the updated `ld2blcodesxref.lst`. I've added the new entries to the coded static list.

> ...noticed that the only colors which are missing (no <COLOR> tag) are Light Bluish Gray and Dark Bluish Gray.

The Native renderer (based on LeoCAD) uses the colour name to compare BrickLink and LDraw Colour references. Unfortunately, the Bricklink colour Grey is spelled using the US format 'Gray' while the LDraw LDConfig.ldr entry uses the UK spelling 'Grey'. As you can imagine, this difference causes colours containing Grey in the name to return 0 (no colour).

### COLOUR Workaround
Change the name of the colour in LDConfig.ldr in your LPub3D LDraw archive library complete.zip to the US spelling.

> Also the <MINQTY> tag is missing if the quantity is 1, but that's not entirely correct: Bricklink supports empty MINQTY field, so here explicit <MINQTY>1</MINQTY> would be better.

I don't understand what is incorrect about the fact that the `<MINQTY>` tag is not required when the inventory item quantity is 1. That no tag is written at this condition is by design.

Cheers,

**Comment by trevorsandy** [comment]
I've updated the Native renderer (based on LeoCAD) BrickLink colour names.

Cheers,

**Comment by riazanovskiy** [comment]
The problem is, as I said, that Bricklink supports empty Quantity field, and the "empty" value is different from 1. For example, if I upload following XML to Bricklink
```
<INVENTORY>
  <ITEM>
    <ITEMTYPE>P</ITEMTYPE>
    <ITEMID>2444</ITEMID>
    <COLOR>11</COLOR>
  </ITEM>
</INVENTORY>
```
it looks like this
![image](https://user-images.githubusercontent.com/11013917/58945430-82bb6080-878c-11e9-922c-bac696b43c5b.png)

and I would expect to have 1 instead of - here:
![image](https://user-images.githubusercontent.com/11013917/58945517-abdbf100-878c-11e9-98a2-cdaa85f9a06c.png)

If I download that Wanted list from Bricklink, I get following:
```
<?xml version="1.0" encoding="UTF-8"?>
<INVENTORY>
<ITEM>
<ITEMTYPE>P</ITEMTYPE>
<ITEMID>2444</ITEMID>
<COLOR>11</COLOR>
<MAXPRICE>-1.0000</MAXPRICE>
<MINQTY>-1</MINQTY>
<CONDITION>X</CONDITION>
<NOTIFY>N</NOTIFY>
</ITEM>
</INVENTORY>
```

and if I upload this to Rebrickable, it complains about -1 being invalid quantity.

**Comment by trevorsandy** [comment]
Very well. Understood. Thank you for taking the time to detail the problem. I'll I'll correct the behaviour.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

Cheers,

**Comment by riazanovskiy** [comment]
Hi @trevorsandy! As the problem with `ld2blcodesxref.lst` begin ignored in XML export is still present in 2.3.12, maybe this issue should be left open, just as a reminder?

**Comment by trevorsandy** [comment]
> ...the problem with ld2blcodesxref.lst begin ignored in XML export is still present in 2.3.12

@riazanovskiy, what behaviour you are experiencing that indicate `ld2blcodesxref.lst` is being ignored ?

I updated the BrickLink XML export to use `ld2blcodesxref.lst` in ticket #290. This update shipped in v2.3.12. 

The BrickLink XML export on v2.3.12 does not show any abnormal behaviour for me. Here are the results I get when I export the example file from (#281) [submodel-rotation.mpd](https://github.com/trevorsandy/lpub3d/files/3244265/submodel-rotation.mpd.txt):

![Screenshot - 22_06_2019 , 22_59_32](https://user-images.githubusercontent.com/13388970/59968953-f4dcc500-9542-11e9-9074-4da170a7ab37.png)

![Screenshot - 22_06_2019 , 23_00_35](https://user-images.githubusercontent.com/13388970/59968954-f4dcc500-9542-11e9-8eb8-9a7e37e83b99.png)

![Screenshot - 22_06_2019 , 23_02_11](https://user-images.githubusercontent.com/13388970/59968955-f5755b80-9542-11e9-8257-17264c5f823c.png)

Cheers,

**Comment by riazanovskiy** [comment]
After your updates the default config contains line
```
59443	    6538c
```

The problem is that the mapping is ignored: your last screenshot contains `<ITEMID>59443</ITEMID>`

For instance, on file 
```
0 Author: LDraw
1 71 -230 40 0 1 0 0 0 1 0 0 0 1 92693c01-f1.dat
1 19 -70 40 -10 1 0 0 0 1 0 0 0 1 18575.dat
```

LPub now generates 
```
<INVENTORY>
  <ITEM>
    <ITEMTYPE>P</ITEMTYPE>
    <ITEMID>18575</ITEMID>
    <MINQTY>1</MINQTY>
    <COLOR>2</COLOR>
  </ITEM>
  <ITEM>
    <ITEMTYPE>P</ITEMTYPE>
    <ITEMID>92693c01-f1</ITEMID>
    <MINQTY>1</MINQTY>
    <COLOR>86</COLOR>
  </ITEM>
</INVENTORY>
```
even though both parts are mapped to other numbers 

(Irrelevant note: Bricklink now learned to recognize `92693c01-f1` as valid part but `18575` is still unknown)

**Comment by trevorsandy** [comment]
Oops - I’m completely mistaken!! 

The implementation completed in #290 is for **BrickLink Colors** not **Codes**.

I forgot about the codes because I meant to do those too.

I’ll correct this behaviour shortly. I’ve also just completed the continuous build framework so updates will be moved to production quicker.

Thank you for your patience and detailed explanation.

Cheers,

**Comment by trevorsandy** [comment]
Updated.

![Screenshot - 23_06_2019 , 22_09_27](https://user-images.githubusercontent.com/13388970/59981439-a3483f00-9603-11e9-8154-7f82bb67685c.png)

Cheers,

**Comment by riazanovskiy** [comment]
> Updated.
> ![Screenshot - 23_06_2019 , 22_09_27](https://user-images.githubusercontent.com/13388970/59981439-a3483f00-9603-11e9-8154-7f82bb67685c.png)

In the second XML entry another color tag is missing (it is color 71, another instance of gray)

Same on my computer with latest CI build

**Comment by trevorsandy** [comment]
Thanks for reporting this behaviour. 

The LDraw colour code was not translated from the 3DViewer colour index (apparently they are not always the same) so and invalid colour code was passed to the LD2BL-colours-xref. I've added the 3DViewer translation which should do the trick to consistently produce valid LDraw colour codes.

Cheers,
