### ISSUE TITLE
Add Bricklink alternate numbers to ld2blcodesxref.lst

### ISSUE THREAD

**Issue by riazanovskiy** [trevorsandy/lpub3d#283]
I discovered three sources of problems while exporting parts list from LPub to Bricklink:
* Some parts (mostly electric) just have different numbers
* LDraw uses `...-f1` convention for composite parts with extended/retracted states which obviously do not exist on Bricklink
* Bricklink uses Alternate Item No which does not always match with LDraw number. Sometimes this merges several molds (which are recognized by LDraw and Rebrickable, for example https://www.bricklink.com/v2/catalog/catalogitem.page?P=32269)

The last issue seems easy to fix automatically.  I [downloaded](https://gist.github.com/riazanovskiy/6f35971073d32fbdf818eecd715a5642) all such parts (except stickers and printed parts) and made the mapping

https://gist.github.com/riazanovskiy/642223899ec2d0af6f1c8cc379c13b41

It is a bit bigger than needed, as not every number in the left column is a valid LDraw part. I see no harm in merging them all, as such parts may be created later or maybe they are used by someone as custom parts. Anyway, I don't think it will create any collisions, as it seems unlikely that someone will reuse existing Bricklink part number for different part. But if you think that it is excessive, the mapping can be filtered to have only existing official and unofficial LDraw parts

**Comment by trevorsandy** [comment]
Excellent! 

Indeed, I expect there will be inconsistencies between part numbers across the different sources - LDraw.org, BrickLink, Rebrickable etc.. This is precisely why I created the exportable cross reference framework so users can have the flexibility to tailor their configuration as needed. 

That you have taken the time to build a comprehensive LDraw to BrickLink cross reference I'm sure will be appreciated by many. 

To not impact performance, I'd rather use a list of official and unofficial parts. Certainly, users can update their exported lists as they please.

If you can filter a list of valid LDraw-referenceable parts, I will add it to the existing `ld2blcodesxref.lst`.

Also, if you agree, you can send your full name and I'll add it and your email, if you agree, to the  CREDITS list. You can see my email in CREDITS if you prefer to send your details this way.

Cheers,

**Comment by riazanovskiy** [comment]
Ok, here is the filtered mapping

https://gist.github.com/riazanovskiy/a8b5b78841598f79c5f35b2fd36c4c32

**Comment by trevorsandy** [comment]
Added.

Cheers,
