### ISSUE TITLE
CALLOUT POINTER_ATTRIBUTE LINE id is not verified

### ISSUE THREAD

**Issue by riazanovskiy** [trevorsandy/lpub3d#284]
### Subject
LPub crashes on following file
[pointers.mpd](https://github.com/trevorsandy/lpub3d/files/3257187/pointers.mpd.txt)

The file is incorrect but the program should not crash.

### Environment
LPub3D 2.3.11 under Windows 10

[LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/3257195/LPub3DLog.txt)

I stumbled upon this accidentally while editing pointer attributes by hand.

**Comment by trevorsandy** [comment]
Corrected.

![Screenshot - 12_06_2019 , 06_17_20](https://user-images.githubusercontent.com/13388970/59323199-ed632380-8cd9-11e9-9634-3d48d651d740.png)

![Screenshot - 12_06_2019 , 06_17_55](https://user-images.githubusercontent.com/13388970/59323211-fd7b0300-8cd9-11e9-97aa-5924aa7ca1c6.png)

Cheers,
