### ISSUE TITLE
Part annotation border and background settings do not work if Extended annotation style is not enabled

### ISSUE THREAD

**Issue by riazanovskiy** [trevorsandy/lpub3d#285]
### Subject
If "Extended" here is enabled
![image](https://user-images.githubusercontent.com/11013917/58961902-b5784f80-87b2-11e9-925e-6fc21c935021.png)
then everything works as expected. If not, "Change part Annotation Border" context menu setting opens a menu where you can't select anything, and "Change part Annotation Background" inserts the selected color in the file without any meta command, resulting in an incorrect LDraw file

### Environment
LPub3D 2.3.11 under Windows 10

### Expected behavior
I don't expect them to work if they are supposed to change the Extended style. But maybe they should give an error message about it or just enable it (maybe with a message)

**Comment by trevorsandy** [comment]
Thanks for reporting this behaviour. However, I am not able to reproduce the output you are describing in my latest development build or release 2.3.11. 

Here is what I'm getting:

![Screenshot - 12_06_2019 , 16_53_42](https://user-images.githubusercontent.com/13388970/59363058-df8ebc00-8d34-11e9-8d04-3f01402916c4.png)
![Screenshot - 12_06_2019 , 16_54_02](https://user-images.githubusercontent.com/13388970/59363059-df8ebc00-8d34-11e9-8c3e-b2ce69260b12.png)
![Screenshot - 12_06_2019 , 16_54_28](https://user-images.githubusercontent.com/13388970/59363060-df8ebc00-8d34-11e9-8ae6-aea3998c2cbd.png)
![Screenshot - 12_06_2019 , 16_54_51](https://user-images.githubusercontent.com/13388970/59363061-df8ebc00-8d34-11e9-8e58-221689f26ce4.png)
![Screenshot - 12_06_2019 , 16_55_06](https://user-images.githubusercontent.com/13388970/59363062-e0275280-8d34-11e9-803c-26b1581a534e.png)
![Screenshot - 12_06_2019 , 16_55_21](https://user-images.githubusercontent.com/13388970/59363066-e0275280-8d34-11e9-93f6-d0fab7160a56.png)
![Screenshot - 12_06_2019 , 16_55_43](https://user-images.githubusercontent.com/13388970/59363067-e0275280-8d34-11e9-903c-19d5679f5d5b.png)
![Screenshot - 12_06_2019 , 16_55_58](https://user-images.githubusercontent.com/13388970/59363068-e0bfe900-8d34-11e9-87a1-3a3f6fe7b332.png)
![Screenshot - 12_06_2019 , 16_56_29](https://user-images.githubusercontent.com/13388970/59363069-e0bfe900-8d34-11e9-9263-b7507dd51da4.png)
![Screenshot - 12_06_2019 , 16_56_53](https://user-images.githubusercontent.com/13388970/59363070-e0bfe900-8d34-11e9-8fea-1a7cabbdf037.png)
![Screenshot - 12_06_2019 , 16_58_02](https://user-images.githubusercontent.com/13388970/59363071-e0bfe900-8d34-11e9-954e-640cddd00380.png)
![Screenshot - 12_06_2019 , 16_58_16](https://user-images.githubusercontent.com/13388970/59363074-e1587f80-8d34-11e9-8888-b47b05ce82b2.png)
![Screenshot - 12_06_2019 , 16_58_35](https://user-images.githubusercontent.com/13388970/59363076-e1587f80-8d34-11e9-9d5d-3c2d14828a3c.png)
![Screenshot - 12_06_2019 , 16_59_20](https://user-images.githubusercontent.com/13388970/59363077-e1f11600-8d34-11e9-8c49-bb410c510ef2.png)

... and with the official release.
![Screenshot - 12_06_2019 , 17_07_32](https://user-images.githubusercontent.com/13388970/59363079-e1f11600-8d34-11e9-980d-4d47730d1676.png)

Cheers,
