### ISSUE TITLE
Custom parts are not included in HTML export

### ISSUE THREAD

**Issue by riazanovskiy** [trevorsandy/lpub3d#286]
### Subject
Suppose I use HTML export on following file:
[sample.zip](https://github.com/trevorsandy/lpub3d/files/3257573/sample.zip)

It uses custom part which I put in `C:\Users\Public\Documents\LDraw\Unofficial\Custom`. I added that path to settings:
![image](https://user-images.githubusercontent.com/11013917/58963115-48b28480-87b5-11e9-95d2-8be76f728847.png)

The part does not appear in the generated HTML:
![image](https://user-images.githubusercontent.com/11013917/58963371-b2329300-87b5-11e9-858b-245c1f33d24f.png)

However, if I copy `26436.dat` to `C:\Users\Public\Documents\LDraw\parts`, HTML is generated correctly.
![image](https://user-images.githubusercontent.com/11013917/58963584-22d9af80-87b6-11e9-80fc-755b5f97601d.png)

Also Bricklink export works correctly in both cases.

### Environment
LPub3D 2.3.11 under Windows 10

**Comment by trevorsandy** [comment]
Thanks for reporting this behaviour. I will take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

![Screenshot - 13_06_2019 , 03_36_50](https://user-images.githubusercontent.com/13388970/59397437-e9dca480-8d8c-11e9-8f0b-5f4b10430726.png)

Cheers,
