### ISSUE TITLE
Bricklink XML export save path should be next to the file

### ISSUE THREAD

**Issue by riazanovskiy** [trevorsandy/lpub3d#287]
The default suggested path to save generated XML is `LPub3D\tmp\..._parts.xml`. 
![image](https://user-images.githubusercontent.com/11013917/58963789-73e9a380-87b6-11e9-9a58-1bf7c0326b5c.png)
It should rather be just next to the current file

**Comment by trevorsandy** [comment]
Implemented.

![Screenshot - 12_06_2019 , 05_13_45](https://user-images.githubusercontent.com/13388970/59321079-f26fa500-8cd0-11e9-8c9e-74f7f534b57f.png)

Cheers,
