### ISSUE TITLE
Add STRETCH option to cover image

### ISSUE THREAD

**Issue by riazanovskiy** [trevorsandy/lpub3d#288]
### Subject
There are 3 ways to add a cover image: to change page background, to add image with `INSERT PICTURE` and with `PAGE DOCUMENT_COVER_IMAGE FILE`. The last one, which looks most appropriate, doesn't have an option to stretch the picture to page.

I prepare cover image with correct A4 aspect ratio, so it would be nice if this settings dialog allowed to set an option to fill the page
![image](https://user-images.githubusercontent.com/11013917/58984312-71507380-87e1-11e9-84d0-751638b1a152.png)

**Comment by trevorsandy** [comment]
Implemented.

![Screenshot - 12_06_2019 , 09_18_42](https://user-images.githubusercontent.com/13388970/59330988-22c83b00-8cf3-11e9-9608-68f93609ba27.png)

Cheers,
