### ISSUE TITLE
Divider in callout not correct

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#289]
### Subject
Divider in callout not correct

### Environment
* Version of LPub3D: from 2.3.7 to 2.3.11
* Operating system - Windows 

### Steps to reproduce
Convert submodel to callout and add divider

### Expected behaviour
The divider should render in the callout box

### Actual behaviour
The divider renders outside the callout box

Here you can see the red divider outside the callout box

![75227 - Darth Vader bust - original_page_30](https://user-images.githubusercontent.com/32261647/59271151-81d67300-8c53-11e9-89b5-82498b2bc73c.png)

### Workaround
None

### Solution suggestion
The divider should render in the center within the callout box a bit shorter on either side.

**Comment by jacovandermolen** [comment]
Tested with a few versions back, I conclude the bug started to occur in 2.3.7
Compare images from 2.3.6 and earlier and 2.3.7

**2.3.6 and back:**
![75227 - Darth Vader bust - original_page_30 2 3 6](https://user-images.githubusercontent.com/32261647/59271876-fc53c280-8c54-11e9-9889-83a681da66ea.png)

**2.3.7 and on:**
![75227 - Darth Vader bust - original_page_30_v2 3 7](https://user-images.githubusercontent.com/32261647/59271877-fc53c280-8c54-11e9-9a25-ccab3270a8a6.png)

**Comment by trevorsandy** [comment]
Jaco - Thanks for reporting this behaviour. Indeed, I did encounter this a few days ago. It is corrected in v.2.3.12

Cheers,
