### ISSUE TITLE
[Packaging request] LPub3D for Raspberry Pi?

### ISSUE THREAD

**Issue by KurtPfeifle** [trevorsandy/lpub3d#29]
I am really glad about the effort you are putting into packaging LPub3D for many different Linux distros in their native formats, and that you also offer an AppImage. Also you are offering it for Windows and macOS. All this is really highly appreciated! I think there is hardly any other application developer who puts in so much effort into building and packaging for so many different platforms

Also I noticed that you seem to do most of your packaging on openSUSE's Open Build Service (OBS):

* https://build.opensuse.org/package/show/home:trevorsandy/lpub3d

     ![image](https://user-images.githubusercontent.com/4747960/36630022-837bfb3e-195f-11e8-8889-03126c853b0d.png)

Therefore I dare to ask: would LPub3D in general also build on ARM? Would it be possible for you to build AppImages for Raspberry Pi? Or are there any obstacles which prevent this (like, any dependencies not available, or viewer parts...)?

Because OBS already contains a build target which can spit out AppImages for ARM. So it may be very easy to add that option at almost no additional "cost" as well to your already impressive number of builds. The benefit would be to have LPub3D available on all the many Pi-targeting distros...

**Comment by trevorsandy** [comment]
Thanks for the kind words and ARM build suggestion. I'll take a look.

It's no fuss to add the ARM image to my OBS build catalogue; however as I develop mostly in the cloud, I don't have a Pi board to verify the build is consistent. If you can do that, it would be good.

Until the ARM build is verified, you can check my OBS dashboard for available builds,
