### ISSUE TITLE
Rubber part colors are not supported in export

### ISSUE THREAD

**Issue by riazanovskiy** [trevorsandy/lpub3d#290]
LDraw has rubber colors which are different from normal, for instance, Rubber Black (256) and Black (0).

If i try HTML export on following file:
```
0 FILE main.ldr
0 Author: LDraw
1 256 49.412 44.366 189.684 -0.926 -0.376 0 -0.376 0.926 0 0 0 -1 92912.dat
0 NOFILE
```
it looks like this
![image](https://user-images.githubusercontent.com/11013917/59632740-9505a900-9153-11e9-9d97-534075ec6d4d.png)

and Bricklink export generates following file:
```
<INVENTORY>
  <ITEM>
    <ITEMTYPE>P</ITEMTYPE>
    <ITEMID>92912</ITEMID>
  </ITEM>
</INVENTORY>
```

If the problem was only with Bricklink export, it could be solved by adding following 
```
65	3
66	19
67	12
256	11
273	7
324	5
350	4
375	9
406	63
449	24
490	34
496	86
504	95
511	1
```
to `ld2blcolorsxref.lst` (I prepared this tab-separated list from [this](https://wiki.ldraw.org/wiki/User:Owen_Burgoyne/LDraw_Colour_Comparison_Chart) table) 

I couldn't find any community-selected solution for rubber colors

**Comment by trevorsandy** [comment]
Updated. Thank you for reporting this behaviour. Indeed, there are many colour discrepancies between the different sources. I'll add your updates to the static static ld2blcolorsxref table. If any future updates are necessary, one can alwasy simply export the .lst file and make the required updates.

HTML Part List Export
![Screenshot - 18_06_2019 , 00_04_30](https://user-images.githubusercontent.com/13388970/59640631-f3845480-915e-11e9-875a-9e7a30ac6c4b.png)

BrickLink XML Export
```
<INVENTORY>
  <ITEM>
    <ITEMTYPE>P</ITEMTYPE>
    <ITEMID>92912</ITEMID>
    <MINQTY>1</MINQTY>
    <COLOR>11</COLOR>
  </ITEM>
</INVENTORY>
```


Cheers,
