### ISSUE TITLE
BOM annotation rectangle size setting seems to have no effect

### ISSUE THREAD

**Issue by riazanovskiy** [trevorsandy/lpub3d#293]
### Subject
I'd like to have small rectangle BOM annotations like in this 42043 instruction:
![image](https://user-images.githubusercontent.com/11013917/59967220-f3ee6800-952f-11e9-8de0-fa2428a48616.png)

I tried changing numbers in 
```
0 !LPUB BOM RECTANGLE_STYLE SIZE GLOBAL 0.3000 0.2800
```
setting but it didn't change the output:
![image](https://user-images.githubusercontent.com/11013917/59968226-15a31b80-953f-11e9-859f-30c65a0bf09d.png)

This is LPub3D 2.3.12 under Windows 10

Is there a lower bound on the box size?

**Comment by trevorsandy** [comment]
Thanks for reporting this behaviour. 

In fact, the rectangle style does not consume its size setting in Global Setup; instead it takes the size of the specified text rectangle. I should have disabled or hidden the size dialogue for the rectangle style.

On review of the feature, I can set the default width/height to the default fixed-size style values (0.28f,0.28f) and on application of the style size, check if the specified size has been changed from the default values. If yes, use the specified size values.

Cheers,

**Comment by trevorsandy** [comment]
Implemented.

The illustration below specifies a 1' x .20' setting.
![Screenshot - 24_06_2019 , 12_22_29](https://user-images.githubusercontent.com/13388970/60011768-cf52d700-967a-11e9-8e15-c7ef21e1bd04.png)

Cheers,
