### ISSUE TITLE
Segfault in substitute part dialog 

### ISSUE THREAD

**Issue by riazanovskiy** [trevorsandy/lpub3d#294]
### Subject
LPub crashes when I try to use "substitute part" feature:
 * This opens 
![Screenshot_2019-06-25_16-22-26](https://user-images.githubusercontent.com/11013917/60101975-71e78480-9765-11e9-884f-bfe1639244e6.png)
* Selection works ok
![Screenshot_2019-06-25_16-23-16](https://user-images.githubusercontent.com/11013917/60102029-93e10700-9765-11e9-9643-7951297dc1ba.png)
* Segfault on "OK" here
![Screenshot_2019-06-25_16-23-23](https://user-images.githubusercontent.com/11013917/60102041-9a6f7e80-9765-11e9-8763-964f81763231.png)

Log: https://gist.github.com/riazanovskiy/505e62708fc5b488ab1f8bf7d7372483

### Environment
LPub3D 2.3.12 under Arch Linux. Reproduces with both Native and LDView renderers. Also reproduces on CI build 2.3.12.10.1575_20190624

### Steps to reproduce
File from https://github.com/trevorsandy/lpub3d/issues/291

I see that it fails [here](https://github.com/trevorsandy/lpub3d/blob/fc0a5213d3df47466292ed87715b618ec0404bf9/mainApp/substitutepartdialog.cpp#L457) as `mDefaultAttributes` consists of only two elements.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Cheers,
