### ISSUE TITLE
Set focus to text field in search dialog

### ISSUE THREAD

**Issue by riazanovskiy** [trevorsandy/lpub3d#295]
This is a minor issue, but it would but nice to have it fixed.
Currently the find dialog, which is used in LDraw editor and in configuration files, has its focus on the "Find" button
![image](https://user-images.githubusercontent.com/11013917/60283955-0e02be80-9913-11e9-9fea-a41623cf7365.png)

while it would be useful to have focus on the text field, so that you can type the search query right after pressing `Ctrl+F`.

**Comment by trevorsandy** [comment]
Changed. Thank you for reporting this behaviour.

![Screenshot - 28_06_2019 , 03_02_29](https://user-images.githubusercontent.com/13388970/60310341-b8e69d00-9952-11e9-9bc9-29b61e1da29a.png)

Cheers,
