### ISSUE TITLE
Missing api-ms-win-crt-runtime-l1-1-0.dll 

### ISSUE THREAD

**Issue by ZPhilo** [trevorsandy/lpub3d#296]
### Subject
api-ms-win-crt-runtime-l1-1-0.dll is missing from my system, and for some reason I can't install it from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
Could it be possible to add it to LPub3D distribution?

### Environment
* Version of LPub3D -2.3.6.0.1101
* Win 7 ,x86_64

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I imagine #81 will not be helpful for you. I'll take a look.

Cheers,

**Comment by qwertychouskie** [comment]
Did you install both the X86 and X64 versions of the package?  And you tried the 2015/2017/2019 package, right?  I just checked and this DLL should indeed be part of this package.

**Comment by ZPhilo** [comment]
Following your email, I tried again to install the VCredist. So far I failed, because I _thought_ it failed, but actually it's only EXTREMELY slow (something like 20 minutes!!!).
The good news: it is now installed. The bad news: LPub3D still reports the same missing DLL :(

**Comment by trevorsandy** [comment]
Implemented. 

The Windows installer distribution will automatically attempt to silently install the MSVC 2015 Redistributable. The attempt will proceed if there is no currently installed instance of if the instance is older than MSVC 2013 update 2.

@ZPhilo - Other than the user access privileges, there is no material difference between manually installing the MSVC redistributable and having it done by the LPub3D installer so I'm not sure this change will address the behaviour on your system. From your feedback, it looks like the redistributable dlls are not being properly registered.

Cheers,

**Comment by ZPhilo** [comment]
Yes, that's what I fear... In this case I really need to reinstall my system!

**Comment by trevorsandy** [comment]
If you want to give the updated installer distribution a go, you can download the release at the [DevOps repo](https://github.com/trevorsandy/lpub3d-ci/releases/tag/continuous). Perhaps, the system user (used to perform the installation) could have a positive outcome.

Cheers,

**Comment by ZPhilo** [comment]
I did... and as we feared, the problem remains the same :( Thanks a lot anyway!

**Comment by qwertychouskie** [comment]
Doesn't this change run afoul of https://github.com/trevorsandy/lpub3d/issues/81#issuecomment-418928310?  Maybe it would be best to look into a MinGW build as it would avoid this issue completely.

**Comment by trevorsandy** [comment]
No it does not. I do not claim the _vc_redist_ to be part of LPub3D and it is not part of my body of code. The _vc_redist_ is downloaded and packaged during the distribution build and is not covered under open source license. It is covered under Microsoft's terms and conditions which allows redistribution.

Cheers,

**Comment by RexoWeb** [comment]
**How to Fix api-ms-win-crt-runtime-l1-1-0.dll Error**

Hi! if you are facing this **api-ms-win-crt-runtime-l1-1-0.dll problem** then don't worry. Here I am sharing 2 tricks about how you can **fix api-ms-win-crt-runtime-l1-1-0.dll Error** and a**pi-ms-win-crt-runtime-l1-1-0.dll Missing Error**.

First Error is Like **api-ms-win-crt-runtime-l1-1-0.dll Missing from Your Computer** and Second Error is **>procedure entry point ucrtbase.terminate could not be located in the dynamic link library api-ms-win-crt-runtime-l1-1-0.dll**.
 
So this error is not software or game error. This error is in your computer or laptop anything you are using.

**So here are two tricks that's you will try for solving these errors.**

**Read More:** [How to Fix api-ms-win-crt-runtime-l1-1-0.dll Error][1]


  [1]: https://www.rexoweb.com/2020/10/how-to-fix-api-ms-win-crt-runtime-l1-1-0.dll-error.html
