### ISSUE TITLE
[Enhancement] Manual override for instance counts

### ISSUE THREAD

**Issue by TrueMylenium** [trevorsandy/lpub3d#298]
I currently find myself working on a project where there is a bit of sub-versioning of different submodels is going on that results in a somewhat odd counting logic due to how the models are nested. I would therefore like to have a meta command for overriding the instance counts of these submodels in callouts, on the submodel page and possibly in the BOM/ PLI. Something like:

SUBMODEL_INSTANCE_COUNT NUMBER_OVERRIDE "x"

The workflow would be to IGN the redundant, unwanted parts and submodels or hide the pages entirely and then only show the ones that are actually meant to illustrate the variations compared to the primary build variant with a manually corrected count. In the long run it might also be useful to implement the override for basic elements in PLIs/ BOMs with this kind of branching builds (barring a native way to handle them better) so the user doesn't have to step through all submodels and insert endless IGN commands. Playing it dirty and just stripping the unnecessary pages from the output PDF might then in fact be a lot quicker.

**Comment by trevorsandy** [comment]
Have a look at #297 in the latest [Continuous Build](https://github.com/trevorsandy/lpub3d/releases/tag/continuous). It is almost always possible to design your build instructions in a manner that produces coherent instance counts without the need to manually override. This possibility has been made more realizable with the following capabilities: #52 #179 #263, #272, #279, #280. 

However, if you cannot get the desired instruction document configuration with the above capabilities, there are the substitute and excluded part lists that can take away some of the drudgery of manually inserting IGN statements

Cheers,

**Comment by TrueMylenium** [comment]
I'll have a look at this when I have worked through my file and have structured it in a way I can try this. I don't think it will work in my case, though. Using SUB might be an option, though it would likely only make things even more complicated. In fact I just seem to have stumbled over a bug where the kinda cyclic relations seem to prevent the program from detecting whether something has changed and it always botches the file as if it were auto-saving it. I'll keep you posted as things progress...

**Comment by trevorsandy** [comment]
Implemented.

Instance count context menu
![Screenshot - 22_07_2019 , 06_52_17](https://user-images.githubusercontent.com/13388970/61607173-c2aba980-ac4d-11e9-8a2b-5ca537870c39.png)

Instance count override dialogue
![Screenshot - 22_07_2019 , 06_53_00](https://user-images.githubusercontent.com/13388970/61607174-c2aba980-ac4d-11e9-8357-e9f9dce6c239.png)

Meta command is local by default
![Screenshot - 22_07_2019 , 06_53_32](https://user-images.githubusercontent.com/13388970/61607175-c2aba980-ac4d-11e9-984b-fd1797730fa2.png)

2 instances of reductor.ldr
![Screenshot - 22_07_2019 , 06_54_31](https://user-images.githubusercontent.com/13388970/61607176-c2aba980-ac4d-11e9-8c5d-2fd3cbbdf049.png)

Cheers,
