### ISSUE TITLE
Part Annotation broken in 2.3.12

### ISSUE THREAD

**Issue by ZPhilo** [trevorsandy/lpub3d#299]
### Subject
Part Annotation broken in 2.3.12, at least for axles and beams. Font is too small, and outside frame.

### Environment
* Version of LPub3D 2.3.12. Worked in 2.3.10
Win10 / 64bit

[axles2.3.10.pdf](https://github.com/trevorsandy/lpub3d/files/3342921/axles2.3.10.pdf)
[axles2.3.12.pdf](https://github.com/trevorsandy/lpub3d/files/3342922/axles2.3.12.pdf)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I am not able to reproduce it with the latest available build. 

Here is a shot of a freshly downloaded portable 2.3.12 r15 instance:

![Screenshot - 30_06_2019 , 16_57_15](https://user-images.githubusercontent.com/13388970/60398458-a2aa2e00-9b58-11e9-8e95-a99a769e9871.png)

... and here is the control file I used. 

```
0 styledpli.ldr
0 Name: styledpli.ldr
0 Author: LPub3D [foodoo]
0 !ldraw_org shortcut update 2012-01
0 !license redistributable under ccal version 2.0 : see careadme.txt
0
0 !LPUB BOM ANNOTATION EXTENDED GLOBAL TRUE
0 !LPUB BOM PART_ELEMENTS DISPLAY GLOBAL TRUE
0 !LPUB BOM ANNOTATION DISPLAY GLOBAL TRUE
0 !LPUB PLI ANNOTATION DISPLAY GLOBAL TRUE
0 // Enable this line the display CSI annotations
0 // !LPUB ASSEM ANNOTATION DISPLAY GLOBAL TRUE
0 !LPUB PLI CONSTRAIN LOCAL HEIGHT 1.42667
0 STEP
1 4 -10 -8 -120 1 0 0 0 1 0 0 0 1 4519.dat
1 4 -10 -8 -100 1 0 0 0 1 0 0 0 1 4519.dat
1 4 -10 -8 -150 1 0 0 0 1 0 0 0 1 4519.dat
1 14 -50 -8 -180 1 0 0 0 1 0 0 0 1 32073.dat
1 28 170 -8 -150 1 0 0 0 1 0 0 0 1 15462.dat
1 28 170 -8 -250 1 0 0 0 1 0 0 0 1 15462.dat
1 28 170 -8 -350 1 0 0 0 1 0 0 0 1 15462.dat
1 28 170 -8 -100 1 0 0 0 1 0 0 0 1 15462.dat
1 72 110 -8 -130 1 0 0 0 1 0 0 0 1 32209.dat
1 72 110 -8 -170 1 0 0 0 1 0 0 0 1 32209.dat
0 STEP
0 !LPUB PLI CONSTRAIN LOCAL HEIGHT 3.52
1 4 60 -56 -80 1 0 0 0 1 0 0 0 1 44350.dat
0 STEP
1 4 100 -56 -110 1 0 0 0 1 0 0 0 1 44351.dat
1 4 -130 -48 -140 1 0 0 0 1 0 0 0 1 3245a.dat
0 STEP
0 !LPUB PLI CONSTRAIN LOCAL HEIGHT 3.54
1 4 -120 -72 -140 1 0 0 0 1 0 0 0 1 3005.dat
1 4 -100 -56 -100 1 0 0 0 1 0 0 0 1 32188.dat
1 4 -50 -56 -80 1 0 0 0 1 0 0 0 1 32189.dat
0 STEP
0 !LPUB PLI CONSTRAIN LOCAL HEIGHT 3.63333
1 4 170 -8 -10 1 0 0 0 1 0 0 0 1 40490.dat
1 4 210 -8 10 1 0 0 0 1 0 0 0 1 32525.dat
1 4 250 -8 50 1 0 0 0 1 0 0 0 1 32278.dat
0 STEP
1 7 50 -8 -210 1 0 0 0 1 0 0 0 1 32013.dat
1 0 90 -8 -210 1 0 0 0 1 0 0 0 1 32014.dat
1 15 130 -8 -210 1 0 0 0 1 0 0 0 1 32015.dat
0 STEP
0 !LPUB BOM PLACEMENT LOCAL CENTER PAGE INSIDE 0.0159296 -0.00330149
0 !LPUB BOM CONSTRAIN LOCAL HEIGHT 10.8667
0 !LPUB INSERT PAGE
0 !LPUB INSERT BOM

```
Could you provide a sample file that produces the behaviour on your system ?

Cheers,

**Comment by ZPhilo** [comment]
Hi Trevor,
I tried your sample code, and it gives me the exact same behaviour :(
...So I ditched my 2.3.12 and reinstalled from fresh and it works... sorry for the fuss. I kept a copy of the byggy one in case you want to do some spelunking ;)

**Comment by trevorsandy** [comment]
Philio, excellent! Good to see you are progressing.

Cheers,
