### ISSUE TITLE
Tuning position of rotation icon

### ISSUE THREAD

**Issue by ZPhilo** [trevorsandy/lpub3d#300]
### Subject
In a multi-step page, position of rotation icon can't be tuned with mouse. Most of the time, standard locations are fine, but if the step also contain a big callout, standard locations end up either very far away from the model, or overlaps it.

### Environment
Lpub 3D 2.3.12 / Win10

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Changed. 

Starting with 2.3.13, it is now possible to select and drag the rotate icon using the mouse.

Default rotate icon location
![Screenshot - 02_07_2019 , 14_41_01](https://user-images.githubusercontent.com/13388970/60513636-0eff6b80-9cd8-11e9-9293-c80157e33614.png)

Rotate icon manually dragged to desired position
![Screenshot - 02_07_2019 , 14_42_40](https://user-images.githubusercontent.com/13388970/60513639-0eff6b80-9cd8-11e9-9349-e67df19c7767.png)

Cheers,

**Comment by ZPhilo** [comment]
Thanks Trevor!

**Comment by riazanovskiy** [comment]
That's great, I wanted to ask this one myself, thank you

Another issue, which happens on single step pages, is that sometimes the rotation icon ends up outside the page, so I have to unzoom the page to change the icon location.

Maybe in these cases LPub should add `ROTATE_ICON PLACEMENT` line automatically, to put the icon to closest position in the page to the original.

(I am not suggesting to change the default position calculation algorithm, only to insert this line as if the position was manually corrected by user)
