### ISSUE TITLE
Custom arrow parts and missing PLI END

### ISSUE THREAD

**Issue by ZPhilo** [trevorsandy/lpub3d#301]
I used Willy's arrows as custom parts, and they seem to be automatically ignored in PLI, which is a rather good thing... problemsis that after adding them, LPub3D complains that "PLI BEGIN then STEP. Expected PLI END". At first I ignored the warning and everything seemed fine... until I noticed that my BOM was missing a lot of parts! As a workaround, I added "0 !LPUB PLI END" right after the arrows, solved the problem.

### Environment
Lpub 3D 2.3.12 / Win10

Code exemple:
0 BUFEXCHG A STORE
1 15 -20 -271.628 -168.032 1 0 0 0 0.94 -0.342 0 0.342 0.94 ejector.ldr
1 4 -100 -90 -180 1 0 0 0 1 0 0 0 1 HasvL6.dat
1 4 100 -90 -180 1 0 0 0 1 0 0 0 1 HasvL6.dat
0 STEP
0 !LPUB INSERT ROTATE_ICON OFFSET 0.5 0.5
0 BUFEXCHG A RETRIEVE
0 !LPUB PART BEGIN IGN
1 15 -20 -175.628 -168.032 1 0 0 0 0.94 -0.342 0 0.342 0.94 ejector.ldr
0 !LPUB PART END
0 ROTSTEP 0 70 20 REL

**Comment by trevorsandy** [comment]
Corrected. Thank you for reporting this behaviour. This was an old bug from the early days of LPub3D - good catch! 

The ign[orePli] flag is set whenever a part (HasvL6.dat) on the excluded part list (excludedPart.lst) is encountered but never unset; hence the missing PLI END and the missing BOM parts.

Some shots of the corrected behaviour:

![Screenshot - 02_07_2019 , 04_26_37](https://user-images.githubusercontent.com/13388970/60478291-78548f80-9c82-11e9-84b6-231eb5de8b7e.png)

![Screenshot - 02_07_2019 , 04_27_07](https://user-images.githubusercontent.com/13388970/60478292-78548f80-9c82-11e9-9b1d-f0178285bd66.png)

![Screenshot - 02_07_2019 , 04_27_25](https://user-images.githubusercontent.com/13388970/60478294-78548f80-9c82-11e9-829c-8076f5667d3a.png)

Cheers,
