### ISSUE TITLE
Changed assembly margin behaviour

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#303]
Somewhere between the current version (2.3.12) and an earlier version (though, I'm afraid I'm not exactly sure which version, but probably around 2.3.6) something changed regarding step-group assembly margins.

I've worked on instructions earlier this year and I just wanted to rerender the instructions with a few minor fixes. But, a lot of pages are now looking wrong. Here's an example page:

Past version:
![image](https://user-images.githubusercontent.com/12005521/60588558-906a0300-9d97-11e9-93d6-2c5524cbdb4d.png)

Current version:
![image](https://user-images.githubusercontent.com/12005521/60588581-9c55c500-9d97-11e9-86d4-471a086c5b87.png)

Past version:
![image](https://user-images.githubusercontent.com/12005521/60588649-c5765580-9d97-11e9-83f5-f3dd06f31e78.png)

Current version:
![image](https://user-images.githubusercontent.com/12005521/60588610-ac6da480-9d97-11e9-8e3d-556f6e895983.png)

Past version:
![image](https://user-images.githubusercontent.com/12005521/60588830-433a6100-9d98-11e9-997a-7729df7cf076.png)

Current version:
![image](https://user-images.githubusercontent.com/12005521/60588844-49c8d880-9d98-11e9-901f-5d1c0464f6c6.png)

I'm not sure what has changed, but it seems to be related to margins. I don't know if it was a bugfix and that now the margin behavior is correct and I have to adjust my meta comments or if there's actually a bug now and the margin behavior was correct in previous versions.

As a sidenote: also rather curious is that the instructions rendered with the new version have 51 pages more than the ones rendered with the old version. I have no idea where that difference came from, I'll have to investigate that.

**Comment by Landcross** [comment]
Update: it seems something changed for the 2nd margin for the Step Group -> Assembly margin and the 2nd margin for the Line Divider (step group). Again, I'm not sure whether the behaviour was wrong and is now correct or whether it was correct and is now wrong. If it's the latter, it (obviously) has to be fixed. If it's the former, I'll have to update my standard meta-comments ;)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

Without having an example model file to precisely check where the difference is coming from, I can say it looks like two updates may be affecting your instructions. They are (corrections):

1. Divider update - #185, #193, (#289) -  This is possibly the source of why you are now experiencing a new behaviour around margins when used with dividers.
2. Extended sorting - #257, (#262) - The default sort order was updated in this enhancement. You should be able to implement the previous settings from the PLI/BOM Global Setup or Context Menu dialogues.

> As a sidenote: also rather curious is that the instructions rendered with the new version have 51 pages more than the ones rendered with the old version. I have no idea where that difference came from, I'll have to investigate that.

3. Expanded submodel consolidation - #264, (#291) - This is almost certainly the cause of the additional instruction pages. You should be able. Previously, the behaviour was incorrect. The correct behaviour is explained in the comments of #291.  In the upcoming 2.3.13, #297 will allow you to configure the submodel page generation and instance counts. You can currently download Continuous Build 2.3.12 r23 to validate the new behaviour.

Cheers,

**Comment by Landcross** [comment]
Thanks for the extensive reply. I did fiddle with the step-group divider and assembly margins a bit and I seem to have gotten the layout correct again. I don't really understand why the margins have changed, but I had to lower my margins quite a bit.

That leaves the extra pages issue. I was just comparing the old and new pdf to see where the first extra page(s) start to appear. And I found a culprit: there's a submodel being used 3 times (in a single step). But LPub3D 2.3.12 generated 3 exact same pages, all three adding a x3 at the bottom. It should either be 3 pages (which would be weird, but at the very least correct) or a single page with the x3 (which it was the in the past). Seems like a bug?

But, that's just 2 of the ~50 extra pages. I haven't yet checked for the other pages, but I assume they are similar situations. Seems a bit like a bug. I will see if I can try out the beta version you mentioned to see if the issue is fixed in there. The new submodel consolidation features sound pretty nice btw :)

**Comment by trevorsandy** [comment]
> That leaves the extra pages issue. I was just comparing the old and new pdf to see where the first extra page(s) start to appear. And I found a culprit: there's a submodel being used 3 times (in a single step). But LPub3D 2.3.12 generated 3 exact same pages, all three adding a x3 at the bottom. It should either be 3 pages (which would be weird, but at the very least correct) or a single page with the x3 (which it was the in the past). Seems like a bug?

Not having the "extra pages" behaviour in previous releases was due to the consolidate instance count logic being broken in those releases. Under all conditions, only the first occurrence of the submodel would render page instructions - See #264 and #263. Consequently in previous releases, the sample model below would generate 8 pages for the specified instance count consolidation command; however, the correct number of pages should be 12 as illustrated below in the comments. This behaviour was corrected in #264. Take a look at #297 for details on the how to use the forthcoming instance count management update. Setting your instance count flag to `Top` will result in the previous LPub3D behaviour.

For the specified instance count consolidation command in the following model file...
```
0 !LPUB CONTINUOUS_STEP_NUMBERS GLOBAL FALSE 
0 !LPUB CONSOLIDATE_INSTANCE_COUNT GLOBAL FALSE
```

I have commented the steps below to show the expected behaviour

```
0 FILE main.ldr
0 Author: LDraw
0 !LPUB CONTINUOUS_STEP_NUMBERS GLOBAL FALSE
0 !LPUB CONSOLIDATE_INSTANCE_COUNT GLOBAL FALSE
0 !LPUB RESOLUTION GLOBAL 150 DPI
0 // STEP 1: The base plate
1 0 20 0 -70 1 0 0 0 1 0 0 0 1 3958.dat
0 STEP
0 // STEP 2-6: (5 steps) 2 steps for each occurrence of subModel and the assembled main model
1 16 -30 -48 -120 1 0 0 0 1 0 0 0 1 subModel.ldr
1 16 -30 -48 -20 1 0 0 0 1 0 0 0 1 subModel.ldr
0 STEP
0 // STEP 7: Addition of three bricks
1 1 20 -8 -120 1 0 0 0 1 0 0 0 1 3794a.dat
1 1 20 -16 -70 0 0 1 0 1 0 -1 0 0 3666.dat
1 1 20 -8 -20 1 0 0 0 1 0 0 0 1 3794a.dat
0 STEP
0 // STEP 8-12: (5 steps) 2 steps for each occurrence of subModel and the assembled main model
1 16 70 -48 -120 1 0 0 0 1 0 0 0 1 subModel.ldr
1 16 70 -48 -20 1 0 0 0 1 0 0 0 1 subModel.ldr
0 NOFILE 
0 FILE submodel.ldr
0 Author: LDraw
1 4 0 24 0 1 0 0 0 1 0 0 0 1 3062b.dat
0 STEP
1 4 0 0 0 1 0 0 0 1 0 0 0 1 4589.dat
0 NOFILE 
```

As you can see, 12 pages is correct versus 8.

Cheers,

**Comment by Landcross** [comment]
I'm pretty sure that previous LPub3D behavior wasn't like the new 'Top' consolidate setting, but the 'At Step' setting. I couldn't quickly find an example of that though, so it could very well be that I'm mis-remembering it.

In any case, I downloaded the beta version with the new consolidate features and it seems to have fixed the extra pages problem (I used the At Step setting). Thanks again! :)

**Comment by trevorsandy** [comment]
My mistake! I meant to write `At Step`. Sorry about that - I've updated to entry.

Cheers,
