### ISSUE TITLE
Placement of disclaimer

### ISSUE THREAD

**Issue by ZPhilo** [trevorsandy/lpub3d#307]
### Subject
on page setup / disclaimer tab, there is a change placement button, but when you close the dialog nothing is done. No big deal since it can be moved with mouse.

### Environment
LPub3D 2.3.12 - Win10

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

Cheers,
