### ISSUE TITLE
Artifacts with native renderer at 1° fov

### ISSUE THREAD

**Issue by ZPhilo** [trevorsandy/lpub3d#308]
### Subject
There are lots of artifacts in assembly images when using 1° fov with native renderer. No big deal since these artifacts seem to disappear at as low as 2°

### Environment
* LPub3D 2.3.12 / Win10

Related question: while I like native renderer because it's damn fast, I fint it countre-intuitive to have to play with camera fov and/or distance to enlarge/reduce size of images. Or am I missing something?

**Comment by trevorsandy** [comment]
Thanks for reporting this behaviour.

> There are lots of artifacts in assembly images when using 1° fov with native renderer. No big deal since these artifacts seem to disappear at as low as 2°

Can you provide a screenshot to illustrate ?

> Related question: while I like native renderer because it's damn fast, I find it countre-intuitive to have to play with camera fov and/or distance to enlarge/reduce size of images. Or am I missing something?

Indeed, and it's not just 'countre-intuitive,' what I've put in place to accommodate positioning the Native renderer camera is pretty much a sophisticated hack.  Unlike LDView and LDGLite which uses the L3P scheme with defined camera positioning and distance routines  utilizing LDraw's LDU, the Native renderer based on LeoCAD uses a different system of arbitrary units to manage these capabilities. It is my intention to write something to enable the Native renderer to consume the L3P parameters but I haven't gotten around to do that at present.

Cheers,

**Comment by trevorsandy** [comment]
> Related question: while I like native renderer because it's damn fast, I fint it countre-intuitive to have to play with camera fov and/or distance to enlarge/reduce size of images. Or am I missing something?

It is now possible (actually since v2.4.0) to manipulate image size using the context menu _scale_ action.

![Screenshot - 14_01_2023 , 20_15_29](https://user-images.githubusercontent.com/13388970/212492301-781e9b2b-00bd-4d39-a821-24b164d673a0.png)

Cheers,
