### ISSUE TITLE
Bug: Callout divider messing with instance count margins

### ISSUE THREAD

**Issue by TrueMylenium** [trevorsandy/lpub3d#309]
Adding a callout divider messes up the margin calculations for the instance count number.

Steps:

1. Create callout from multi-stepped submodel
2. Right-click to insert horizontal divider somewhere
2. Modify instance count number margin manually or via dialog

Actual Result:

Callout box does not respect the margins. Instead the number is drawn in a whacky position over the box frame with what looks like a 0 0 margin. Additionally the divider itself extends beyond the bounds of the box in what looks like a miscalculation of the assembly bounding boxes.

![Callout_Divider_Instance_Count](https://user-images.githubusercontent.com/52353330/60759008-79891200-a01e-11e9-9df5-f7b2397b7799.jpg)

Expected Result:

Correct margin calculation and divider behavior.

Tech Info:

v2.3.12, Build 1356, 64 bit, Windows 10

Comments:

The issue appears specific to multi-line callouts. Removing the divider and thus reverting to a regular callout respects the formatting. On that note: Is CUSTOM_LENGTH for the divider not implemented yet? The dialog generates the code, but the parser doesn't recognize it.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look. 

It would be a big help if you could provide an example model file that produces the behaviour you are describing. If you do not wish to share the sample model file publicly, you can see my email in the CREDITS menu under Help -> About LPub3D.

Cheers,

**Comment by TrueMylenium** [comment]
Find a stripped down example of the work file below. This also clears the fog a bit. The issue seems to be related to how the placement is calculated when an uneven number of steps is distributed across rows/ columns. If you move the third step back and forth between the columns, the issues goes away if the last columns holds three steps and not just two, but reappears as soon as you reverse the situation. I would therefore conclude that the accumulated margin bounds are not calculated correctly unless the last row/ column is the largest one. Might need a fix/ change to calculate the whole area instead to work under every condition.

[Callout_Divider_Instance_Count_Example_00.zip](https://github.com/trevorsandy/lpub3d/files/3365903/Callout_Divider_Instance_Count_Example_00.zip)

**Comment by trevorsandy** [comment]
Thank you. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

![Screenshot - 04_08_2019 , 13_53_14](https://user-images.githubusercontent.com/13388970/62423278-5b670e00-b6bf-11e9-8332-43f5157e7509.png)

![Screenshot - 04_08_2019 , 13_53_41](https://user-images.githubusercontent.com/13388970/62423279-5bffa480-b6bf-11e9-8994-8ca8d3c18a0a.png)

Cheers,
