### ISSUE TITLE
Fade Previous Steps doesn't work in global mode

### ISSUE THREAD

**Issue by kejv** [trevorsandy/lpub3d#310]
### Subject
Fade Previous Steps doesn't work at all in global mode.

### Environment
* Version of LPub3D - 2.3.12
* Operating system - x86_64 GNU/Linux 4.4.0-38-generic Mint 18

### Steps to reproduce

Turn on global fade steps for any model (check Configuration->Preferences->General->Use Lego Parts Global Fade). This is what I get:

![lpub-fade-all](https://user-images.githubusercontent.com/2669718/60820876-ae25d680-a1a2-11e9-9599-552bc4d3674b.png)

On the other hand it works when fading using similar (lighter) colors (uncheck Configuration->Preferences->General->Use Lego Parts Global Fade):

![lpub-fade](https://user-images.githubusercontent.com/2669718/60820949-d7466700-a1a2-11e9-9450-9e3014bc78ff.png)

Just for completeness here's the version without any fade steps:

![lpub](https://user-images.githubusercontent.com/2669718/60820996-ee855480-a1a2-11e9-91e6-df33747b33e9.png)

### Expected behaviour

The global fading should work as it did in previous versions.

### Actual behaviour

Some garbage is displayed instead of actual faded parts.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

Corrected.

Cheers,
