### ISSUE TITLE
Assembly margins setting works strangely

### ISSUE THREAD

**Issue by kejv** [trevorsandy/lpub3d#311]
### Environment
* Version of LPub3D - 2.3.12
* Operating system - x86_64 GNU/Linux 4.4.0-38-generic Mint 18

### Steps to reproduce
I've recorded a video where the exact sequence is clearly (I hope) shown.
https://ufile.io/gwdvfeyc

### Expected behaviour
- When I set assembly margins for a particular step and the revisit the setting I expect I will see the same numbers as entered before.
- When I set assembly margins for some later step and then set them again for the previous one it should overwrite the previous value.
- Changing global assembly margins from Configuration menu actually does something.

### Actual behaviour
See the video.

### Solution suggestion
I'm not quite sure about the current intended way how to set assembly margins to be honest. My expectation, though, would be that there's a single global setting which manages all assemblies. Then there could be additional levels where to override this value, e.g. on a submodel or even particular assembly.

Current way of managing assembly margins seems to me quite counterintuitive, i.e. what exactly does "Change only this step?" dialog mean. I would suppose that this in fact implements the global setting but it actually applies the values to that and next steps, moreover in current submodel only!

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

This behaviour has always existed in LPub. It's a bit strange that this is the first time anyone has reported it. I imagine it must not be used all that much. Nevertheless, I'll take a look.

"Change only this step" means apply the specified meta command only to this step. A meta command may be specified with one of three application modes GLOBAL, LOCAL and "following".  The GLOBAL keyword will apply the meta command against the entire model file unless overridden by a subsequent instance of the same meta command line. The LOCAL keyword will apply the meta command only to the step in which it is specified. Lastly, the "following" meta command does not specify a LOCAL or GLOBAL keyword and will apply from the place in the model file where it is specified onward unless overridden by a subsequent instance of the same meta command.

As the Assembly Margins functionality is broken, it will not properly treat its meta command so it is understandable that, in these use cases, the behaviour seems convoluted and ineffective.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

![Screenshot - 01_08_2019 , 15_31_11](https://user-images.githubusercontent.com/13388970/62297413-793f3380-b471-11e9-92ca-2f2a7a5c785a.png)

Cheers,

**Comment by david-kubecka** [comment]
Tried latest build and works like a charm. Thanks! 

Also can you please have a look at the discussion at sourceforge.net? Esp. this post https://sourceforge.net/p/lpub3d/discussion/general/thread/41ac93ccf7/.

**Comment by trevorsandy** [comment]
@david-kubecka 

I took a look the sourceforge post. That behaviour was addressed in #323 

Let me know if you continue to experience the described behaviour with the latest [Continuous Build](https://github.com/trevorsandy/lpub3d/releases/tag/continuous) release.

Cheers,
