### ISSUE TITLE
Fields and dropdowns in Page Setup form are not rendered properly

### ISSUE THREAD

**Issue by ghost** [trevorsandy/lpub3d#312]
### Environment
* Version of LPub3D - 2.3.12
* Operating system - x86_64 GNU/Linux 4.4.0-38-generic Mint 18

### Steps to reproduce
Go to Configuration->Build Instructions Setup->Page Setup

### Expected behaviour
All fields and dropdowns are rendered correctly and can be manipulated easily.

### Actual behaviour
Some fields and dropdowns e.g. Background or Border are very small while other are rendered ok.

See picture:
![lpub-page-setup](https://user-images.githubusercontent.com/2669718/60831468-f3093780-a1b9-11e9-84f1-a35b18f7c74f.png)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

LPub3D is built with Qt which is a leading cross-platform "build once, run anywhere" development platform. Nevertheless, many platforms require specific developments to seamlessly integrate the application. As a result, LPub3D may behave unexpectedly on platforms that I do not specifically target (I do not currently build a Mint distro),

For the particular behaviour you show, it is possible to click and manually drag the dialogue bottom right edge to the dimensions required to properly see all settings.

Cheers,

**Comment by trevorsandy** [comment]
I can reproduce this behaviour and I know that is is linked to the “layout” object configuration when used with tabs; however, I’m still looking for the “trick” that addresses the malformed display. The settings I’ve tried don’t seem to work. Tabbed dialogues seem to be quite fragile.

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected - see #616

Cheers,
