### ISSUE TITLE
Issue: Callout pointers mess up with more than one intermediate points

### ISSUE THREAD

**Issue by TrueMylenium** [trevorsandy/lpub3d#313]
Trying to interactively edit pointers that have more than one intermediate point restricts the orientation of the lines and ultimately messes them up.

Steps:

1. Create Callout
2. Add Pointers (if not created automatically already)
3. Insert more than one extra intermediate points into pointer

Actual result:

Dragging one of the intermediate points will quantize the pointer lines to perpendicular directions in either one or all segments, depending on what is actually being dragged.

Expected result:

All points can be moved freely.

Tech Info:

v2.3.12, Build 1356, 64 bit, Windows 10

Comment:

See Issue #309 for test file you can use. Seems like the function forces the values of the currently active point and imprints them onto the other points without regard to their current position. It appears the function only ever calculates one absolute min/ max depending on the active state, hence things go belly up. Needs to be changed to encompass all points or have a "freeform" mode that suppresses the boundary check entirely.

**Comment by TrueMylenium** [comment]
Okay, seems like it isn't even  generating the coordinates for more than one intermediate point? not yet implemented or still a genuine issue?

**Comment by trevorsandy** [comment]
If I well understand what you are describing, it looks like this is the as-designed behaviour. 

 A segment’s base point is always adjusted to be parallel with its tip/mid-point when either point is dragged, as long as the base item size permits. This behaviour can be offset by dragging the tip to the desired position, then dragging the base.

Let me know if this is the behaviour you are referring to of if you are referring to some other behaviour?

Cheers,

**Comment by TrueMylenium** [comment]
Not really what I would consider "as designed". It's simply completely wonky and makes zero sense.

**Comment by trevorsandy** [comment]
To be sure we are discussing the same behaviour, perhaps you could create a short video and post it on  G-Docs or somewhere accessible. 

The behaviour I'm referring to is designed to position pointer segments perpendicular, and parallel when more than one segment, to the pointer's base (e.g. Callout, page border, divider etc...). Of course, the user can drag the pointer to any position along the base's perimeter accordingly.

Cheers,

**Comment by trevorsandy** [comment]
Stale.
