### ISSUE TITLE
Crash: Manually typing line in Editor

### ISSUE THREAD

**Issue by TrueMylenium** [trevorsandy/lpub3d#314]
The program crashes right away, if a line is manually typed into the editor beginning with 1, i.e. a visible/ evaluating entity.

Steps:

1. Open file
2. Insert empty line in editor with return
3. Begin to type on newly inserted line starting with a 1

Actual Result:

Program crashes right away.

Expected result:

No crash.

Tech Info:

v2.3.12, Build 1356, 64 bit, Windows 10

Comment:

See Issue #309 for test file you can use. Appears to be some attempt to evaluate the code and/ or create a preview in 3DViewer even though no actual model has been defined. Does not happen if the line is started with a 0 or copy&paste operation, but should not occur, regardless, as it hampers manually hacking around and inserting references.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Implemented.

The illustrated exception message is triggered when a line begins with a type 1 - 5 value but the number of line elements for the line type is not valid. For example, if a type 1 (subfile reference) line is entered, it must have 15 elements to not trigger the exception notice.

![Screenshot - 23_07_2019 , 10_20_21](https://user-images.githubusercontent.com/13388970/61696052-e72e8100-ad34-11e9-8140-b99f4b1d056f.png)

Cheers,
