### ISSUE TITLE
LPub Crashing when substituting 

### ISSUE THREAD

**Issue by snakebyte73** [trevorsandy/lpub3d#316]
### Subject
LPub3D crashes every time i try to substitute a part.

### Environment
* Version of LPub3D: 2.3.12 Revision 0 Build 1356
* Operating system: Windows 10 x64

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  - Windows: C:\Program Files\LPub3D\LPub3D.exe
* Application data path
  - Windows: %USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\

### Screenshots
* Configuration->Preferences->General
* Configuration->Preferences->Rendering
* Configuration->Preferences->Publishing
* Configuration->Preferences->Logging
* Configuration->Preferences->Other

### Steps to reproduce
Here is the file i testet on:
0 FILE main.ldr
0 Testing
0 Name: Testing
0 Author: Knud Ahrnell Albrechtsen [Snakebyte]
0 !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
0 ROTATION CENTER 0 0 0 1 "Custom"
0 ROTATION CONFIG 0 0
0 !LPUB MULTI_STEP BEGIN
1 15 0 0 0 1 0 0 0 1 0 0 0 1 3005.dat
0 STEP
1 15 0 -8 0 1 0 0 0 1 0 0 0 1 3024.dat
0 STEP
1 0 0 -16 0 1 0 0 0 1 0 0 0 1 3024.dat
0 STEP
1 15 0 -24 0 1 0 0 0 1 0 0 0 1 3024.dat
0 STEP
0 !LPUB MULTI_STEP END
1 15 0 56 -10 1 0 0 0 1 0 0 0 1 Sub01.ldr
1 15 20 16 10 1 0 0 0 1 0 0 0 1 Sub01.ldr
0 STEP
0 STEP
0 !LPUB INSERT MODEL
0 !LPUB INSERT PAGE
0 STEP
0 NOFILE 
0 FILE sub01.ldr
0 Sub01
0 Name: Sub01
0 Author: Knud Ahrnell Albrechtsen [Snakebyte]
0 !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
0 ROTATION CENTER 0 0 0 1 "Custom"
0 ROTATION CONFIG 0 0
0 STEP
0 !LPUB MULTI_STEP BEGIN
1 15 10 0 0 1 0 0 0 1 0 0 0 1 3022.dat
0 STEP
1 0 10 -8 0 1 0 0 0 1 0 0 0 1 3022.dat
0 STEP
1 15 10 -16 0 1 0 0 0 1 0 0 0 1 3022.dat
0 STEP
1 0 10 -24 0 1 0 0 0 1 0 0 0 1 3022.dat
0 STEP
1 15 10 -32 0 1 0 0 0 1 0 0 0 1 3022.dat
0 STEP
0 !LPUB MULTI_STEP END
0 NOFILE 

Ehen trying to substitute a part it crashes.
![billede](https://user-images.githubusercontent.com/38093610/61231105-ac708b80-a72b-11e9-9347-24907493faab.png)
When pressing "ok" LPub3D crashes with no warning
![billede](https://user-images.githubusercontent.com/38093610/61231137-bd210180-a72b-11e9-8a62-9be5035cba73.png)

### Workaround
Add the substitute steps manually via text editor
0 !LPUB PLI BEGIN SUB 85543.dat 15
0 !LPUB PART BEGIN IGN
1 15 0 0 0 1 0 0 0 1 0 0 0 1 3005.dat
0 !LPUB PLI END
0 !LPUB PART END
![lpub3d_substitute_part_01](https://user-images.githubusercontent.com/38093610/61231872-4ab12100-a72d-11e9-8130-75d7515789f3.png)
![lpub3d_substitute_part_02](https://user-images.githubusercontent.com/38093610/61231874-4d137b00-a72d-11e9-8763-cc8bcfca7bb1.png)

**Comment by trevorsandy** [comment]
Thanks for reporting this behaviour. This item has been corrected in #294 and is available in the latest pre-release build.

You can download the latest pre-release [Continuous Build](https://github.com/trevorsandy/lpub3d/releases/tag/continuous) for Windows (installed and portable distributions), Linux AppImage, Ubuntu, Arch, Fedora and macOS.

On the [LPub3D GitHub Page](https://trevorsandy.github.io/lpub3d/), you can see if there an available pre-release continuous build if the **Revision** badge is greater than 0. You can also see the list of latest commits (i.e. corrections) from the **Last Commit** badge.

Cheers,
