### ISSUE TITLE
submodel show twice.

### ISSUE THREAD

**Issue by snakebyte73** [trevorsandy/lpub3d#317]
### Subject
When adding the same submodel twice directly after eachother in the same step, the submodel assembly is show twice.
Normally it is only shown once.
I use LDView render

### Environment
* Version of LPub3D: 2.3.12 Revision 0 Build 1356
* Operating system: Windows 10 x64

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  - Windows: C:\Program Files\LPub3D\LPub3D.exe
* Application data path
  - Windows: %USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\

* Renderer configuration files
[ldview.zip](https://github.com/trevorsandy/lpub3d/files/3393231/ldview.zip)

### Screenshots
* Configuration->Preferences->General
* Configuration->Preferences->Rendering
* Configuration->Preferences->Publishing
* Configuration->Preferences->Logging
* Configuration->Preferences->Other
![billede](https://user-images.githubusercontent.com/38093610/61232188-096d4100-a72e-11e9-9a60-aec9053bf576.png)

![billede](https://user-images.githubusercontent.com/38093610/61232199-0ffbb880-a72e-11e9-9d10-00d0329be626.png)

![billede](https://user-images.githubusercontent.com/38093610/61232221-18ec8a00-a72e-11e9-891e-3a89d79530a4.png)

### Steps to reproduce
Try using this file:
0 FILE main.ldr
0 Testing
0 Name: Testing
0 Author: Knud Ahrnell Albrechtsen [Snakebyte]
0 !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
0 ROTATION CENTER 0 0 0 1 "Custom"
0 ROTATION CONFIG 0 0
0 !LPUB MULTI_STEP BEGIN
1 15 0 0 0 1 0 0 0 1 0 0 0 1 3005.dat
0 STEP
1 15 0 -8 0 1 0 0 0 1 0 0 0 1 3024.dat
0 STEP
1 0 0 -16 0 1 0 0 0 1 0 0 0 1 3024.dat
0 STEP
1 15 0 -24 0 1 0 0 0 1 0 0 0 1 3024.dat
0 STEP
0 !LPUB MULTI_STEP END
1 15 0 56 -10 1 0 0 0 1 0 0 0 1 Sub01.ldr
1 15 20 16 10 1 0 0 0 1 0 0 0 1 Sub01.ldr
0 STEP
0 STEP
0 !LPUB INSERT MODEL
0 !LPUB INSERT PAGE
0 STEP
0 NOFILE 
0 FILE sub01.ldr
0 Sub01
0 Name: Sub01
0 Author: Knud Ahrnell Albrechtsen [Snakebyte]
0 !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
0 ROTATION CENTER 0 0 0 1 "Custom"
0 ROTATION CONFIG 0 0
0 STEP
0 !LPUB MULTI_STEP BEGIN
1 15 10 0 0 1 0 0 0 1 0 0 0 1 3022.dat
0 STEP
1 0 10 -8 0 1 0 0 0 1 0 0 0 1 3022.dat
0 STEP
1 15 10 -16 0 1 0 0 0 1 0 0 0 1 3022.dat
0 STEP
1 0 10 -24 0 1 0 0 0 1 0 0 0 1 3022.dat
0 STEP
1 15 10 -32 0 1 0 0 0 1 0 0 0 1 3022.dat
0 STEP
0 !LPUB MULTI_STEP END
0 NOFILE 

### Expected behaviour
The submodel assembly should only be show once.
This used to be standard behavior

**Comment by trevorsandy** [comment]
Thanks for reporting this behaviour. 

To be sure I well understand what you are describing, are you saying there are 2 sets of instruction pages for the 2 submodel assemblies added in the same step ? 

If yes, then the new behaviour is attributed to the change in submodel consolidation - #264, (#291) - This is almost certainly the cause of the additional instruction pages. Previously, the behaviour was incorrect. The correct behaviour is explained in the [comments ](https://github.com/trevorsandy/lpub3d/issues/291#issuecomment-505072869)of #291. You can also consult #303 for additional details. In the upcoming 2.3.13, #297 will allow you to configure the submodel page generation and instance counts with expanded submodel consolidation.

You can download the latest pre-release [Continuous Build 2.3.12 r38](https://github.com/trevorsandy/lpub3d/releases/tag/continuous) for Windows (installed and portable distributions), Linux AppImage, Ubuntu, Arch, Fedora and macOS to validate the new behaviour.

On the [LPub3D GitHub Page](https://trevorsandy.github.io/lpub3d/), you can see if there an available pre-release continuous build if the **Revision** badge is greater than 0. You can also see the list of latest commits (i.e. corrections) from the **Last Commit** badge.

These shots show the current behaviour of the latest continuous build using the sample model file you supplied:

![Screenshot - 21_07_2019 , 04_38_28](https://user-images.githubusercontent.com/13388970/61586399-1dbc9e00-ab73-11e9-81d7-5b5f209db624.png)

![Screenshot - 21_07_2019 , 04_38_44](https://user-images.githubusercontent.com/13388970/61586400-1e553480-ab73-11e9-89fd-a751c3eda63f.png)

![Screenshot - 21_07_2019 , 04_38_59](https://user-images.githubusercontent.com/13388970/61586401-1e553480-ab73-11e9-968e-05dc1828fc17.png)

Cheers,

**Comment by snakebyte73** [comment]
Hi Trevor 
To you first question regarding the two submodels: Yes
I just downloaded the pre-release you suggested.
Now it only shows the two submodels assembly once. Thanks

/Knud
