### ISSUE TITLE
Callout between submodel instances prevents instance count from showing

### ISSUE THREAD

**Issue by riazanovskiy** [trevorsandy/lpub3d#321]
### Subject
I'm not entirely sure that this is a bug and there's a workaround. But I think this has changed from the previous version (2.3.11).

Consider following file
```
0 FILE main.ldr
0 sample missing instance count
0 !LPUB PAGE ORIENTATION GLOBAL LANDSCAPE
0 !LPUB CONSOLIDATE_INSTANCE_COUNT GLOBAL AT_STEP
1 16 29.268 45.208 -60.408 1 0 0 0 -1 0 0 0 -1 reductor.ldr
0 !LPUB CALLOUT BEGIN
1 16 89.233 44.799 19.926 1 0 0 0 1 0 0 0 1 submodel.ldr
0 !LPUB CALLOUT POINTER CENTER 0 0.859649 0.132 0 0 0 0 0 0 1
0 !LPUB CALLOUT END
1 16 29.268 44.389 100.261 1 0 0 0 1 0 0 0 1 reductor.ldr
0 NOFILE 
0 FILE reductor.ldr
0 Author: LDraw
1 72 19.966 0.163 69.416 0.921 0.389 0 0.389 -0.921 0 0 0 -1 92909.dat
0 STEP
1 72 99.964 0.701 -20.334 0.007 0 -1 -1 0 -0.007 0 1 0 60484.dat
0 NOFILE 
0 FILE submodel.ldr
0 Author: LDraw
1 25 0 0 0 1 0 0 0 1 0 0 0 1 2780.dat
0 NOFILE 
```

It has two instances of `reductor.ldr` submodel separated by a callout.
It renders to following pages
![072203184322 pdf-1](https://user-images.githubusercontent.com/11013917/61595916-b0a61880-ac05-11e9-852c-73b212cdbd18.png)

The submodel instance count ("x2") is missing. If I rearrange lines within the step so that all instances would be one after another
```
0 !LPUB CALLOUT BEGIN
1 16 89.233 44.799 19.926 1 0 0 0 1 0 0 0 1 submodel.ldr
0 !LPUB CALLOUT POINTER CENTER 0 0.859649 0.132 0 0 0 0 0 0 1
0 !LPUB CALLOUT END
1 16 29.268 45.208 -60.408 1 0 0 0 -1 0 0 0 -1 reductor.ldr
1 16 29.268 44.389 100.261 1 0 0 0 1 0 0 0 1 reductor.ldr
```
it would render correctly:
![072203235793 pdf-1](https://user-images.githubusercontent.com/11013917/61595975-5e192c00-ac06-11e9-8108-edd3d95b3ceb.png)

### Environment
LPub3D-2.3.12.40.1396_20190721 from CI under Windows 10

### Workaround
You can rearrange lines in the step to get the correct behavior

**Comment by trevorsandy** [comment]
Corrected.

![Screenshot - 22_07_2019 , 06_07_41](https://user-images.githubusercontent.com/13388970/61605778-57f76f80-ac47-11e9-9457-fa886f8cd0d5.png)

![Screenshot - 22_07_2019 , 06_07_58](https://user-images.githubusercontent.com/13388970/61605779-57f76f80-ac47-11e9-9626-146c96e6ed11.png)

![Screenshot - 22_07_2019 , 06_08_15](https://user-images.githubusercontent.com/13388970/61605780-57f76f80-ac47-11e9-8f3e-a650d264ae8d.png)

Cheers,
