### ISSUE TITLE
Native renderer save step image

### ISSUE THREAD

**Issue by trevorsandy** [trevorsandy/lpub3d#327]
###  Subject
Use the Nativer renderer  save image capability to manually update a step's CSI or Submodel Preview.

### Environment
Version of LPub3D - 2.3.13
Operating system - All

### Solution

This is the first pass to enable freeform image manipulation including cuszom zoom and custom lookat points.
At present, there are several limitations. The most notable is that images rendered using this capability will not be supported by a meta command and; therefore, will not be portable or persistable. This functionality is limited to the Native renderer at this moment.

Note that the generated image will persist as long as there is no need to update it. 

Here are some shots that show the steps to generate an image and automatically update the instructions document.

![image](https://app.gitkraken.com/api/glo/boards/5b248f78dd21bf100044c350/attachments/5d47a8cc647fd9000f1c2bc3)

![image](https://app.gitkraken.com/api/glo/boards/5b248f78dd21bf100044c350/attachments/5d47a8cc9fb43a000fe37c3d)

![image](https://app.gitkraken.com/api/glo/boards/5b248f78dd21bf100044c350/attachments/5d47a8cc2ba611000ff24bee)

Cheers,

**Comment by trevorsandy** [comment]
Implemented,

Cheers,

**Comment by kejv** [comment]
This is good progress but I'm not sure it will be usable for the custom zoom use case because typically you want to keep the zoom level for multiple following steps (similarly to ROTSTEP). Anyway, thanks for very quick action!

**Comment by trevorsandy** [comment]
This behaviour has been abandoned in favour of #412.

Cheers,
