### ISSUE TITLE
Strange behavior when resizing cover image

### ISSUE THREAD

**Issue by snakebyte73** [trevorsandy/lpub3d#329]
### Subject
I have added a cover image to my instructions:
![billede](https://user-images.githubusercontent.com/38093610/62754993-77c5ca80-ba72-11e9-82b2-d48bd07ba2b6.png)
When I try to resize it on the front page it has some strange behavior.
It creates a box that gets exponentially larger than the image when pulling on the corners.
![billede](https://user-images.githubusercontent.com/38093610/62755038-a5127880-ba72-11e9-872f-a2fd09849e96.png)
And it is almost impossible to place when it looks like this.

### Environment
* Version of LPub3D - 2.3.12 Revision  89 Build 1445
* Operating system - Windows 10 x64

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  - Windows: `C:\Program Files\LPub3D` [x86_64]
* Application data path
  - Windows: `%USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\`
* Registry Extract
  - Windows (installed): `reg export "HKEY_CURRENT_USER\Software\LPub3D Software" %USERPROFILE%\Desktop\LPub3D_Hive.reg`
  - Windows (portable): `<application path>\config\LPub3D Software\LPub3D.ini`
* Renderer configuration files

### Steps to reproduce
Add a cover picture.
Go close prefferences.
go to front page and resize the image by dragging in the corners of the image.

### Expected behaviour
Tell me what should happen

### Actual behaviour
Tell me what happens instead

### Workaround
Share your work around if available

### Solution suggestion
Share your opinion on how to achieve the expected behaviour

**Comment by trevorsandy** [comment]
Knud,
Thank you for reporting this behaviour. I imagine this disruption to the manual drag resize is related to the updates performed for #288. I will take a look at restoring the manual drag resize behaviour but, as an alternate workflow in the interim, perhaps you can use an image already aspected to your cover page size or simply select the stretch option to have LPub3D automatically scale (resize) the image for you.

Let me know if you are not able to progress with the new options from #288?

Cheers,

**Comment by snakebyte73** [comment]
Hi Trevor
I just tested the Strech option and it makes the image look wrong.
So I would like the option to manually resize the image as the images isn't allways the same size.
They have the same hight/width pixels but the zoom varies with the model.
So a bit of resizing is needed :)
Thanks

**Comment by trevorsandy** [comment]
Corrected.

![Screenshot - 20_08_2019 , 01_52_32](https://user-images.githubusercontent.com/13388970/63307047-37294500-c2ed-11e9-8eac-80e66852c4cd.png)

FYI, you could also use the Edit->Add Picture menu item.

Cheers,
