### ISSUE TITLE
Bug: Append page before a submodel, appends the page in the wrong location

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#330]
I just encountered the following problem:

I was on page of the parent model, just before a submodel (submodel on the next page).
I clicked on Edit -> Append Page. I expected the appended page between the current (parent model) page and the next (submodel) page. Instead, it was inserted between the end of the submodel page and the next parent model page.

I have to note that my submodel consisted of just a few steps and were grouped together on a single page. Thus, I'm not exactly sure whether LPub3D places the page at the end of the submodel, or after the first page of the submodel. Nevertheless, it's doing it wrong (or at least not as I expected).

It's also worth noting that LPub3D placed the Page metacommand within (and the end of) the submodel and not in the parent model after the submodel. If that sentence makes sense haha.

I'm using a pre-release build of Lpub3D from a few days ago. The About LPub3D dialog says: 2.3.12 Revision 68, Build 1424.

**Comment by trevorsandy** [comment]
Thanks for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

Cheers,
