### ISSUE TITLE
Add option to centre justify step group steps

### ISSUE THREAD

**Issue by trevorsandy** [trevorsandy/lpub3d#333]
###  Subject
Add option to centre justify Step Group and Callout steps.

### Environment
Version of LPub3D - 2.3.13
Operating system - All

### Expected behaviour
Have an option to automatically place steps in a Step Group or multi step Callout at the vertical centre, horizontal centre or dead centre of its bounding region.

### Current behaviour
Steps are justified left when vertical allocation is specified or towards the divider when divider is specified and the allocation is horizontal.

### Solution
Add ‘Justify’ drop-down and ‘Centre spacing’ dialogue to Step Group and Callout Setup dialogues. The Centre drop-down offers options to center justify steps vertically, horizontally and dead centre plus the default left justify - the behaviour before this enhancement.  

When a step is centred, all allocated margins are repurposed and applied as specified across the left, right, top or bottom regions of the step - minus the centre spacing value between items. 

Centre justify behaviour can be applied to Callouts and multiple steps within a Callout.

**Comment by trevorsandy** [comment]
Implemented.

Cheers,

**Comment by jacovandermolen** [comment]
Great feature!

**Comment by trevorsandy** [comment]
Hi Jaco, Indeed. 

This one was a little stinker to get right. 

Please be advised that some of the graphics in this ticket are not up to date. Specifically the Step Group Setup dialogue which now has a drop-down and double spinner dialogue. Moreover, the meta command shown to center items has changed. I’ll update the ticket graphics shortly.

Cheers,

**Comment by trevorsandy** [comment]
Implemented.

Cheers,
