### ISSUE TITLE
PLI placement is invalid, when SHOW_STEP_NUMBER is FALSE

### ISSUE THREAD

**Issue by 6638** [trevorsandy/lpub3d#335]
### Subject
When ASSEM SHOW_STEP_NUMBER is set to false, PLI placement doesn't work.

### Environment
* 2.3.12 rev 113 (portable)
* Windows 7 x64

### Configuration
Default; Renderer LDGLite

### Logs
N/A

### Screenshots
<img width="960" alt="1" src="https://user-images.githubusercontent.com/49516540/64081190-0a6a2a00-ccfe-11e9-8161-214074851fca.png">

### Steps to reproduce
0 FILE main.ldr
0 !LPUB ASSEM SHOW_STEP_NUMBER GLOBAL FALSE
0 !LPUB PLI SHOW GLOBAL TRUE
0 !LPUB PLI PLACEMENT GLOBAL BOTTOM LEFT SUBMODEL_DISPLAY OUTSIDE
0 !LPUB SUBMODEL_DISPLAY SHOW GLOBAL TRUE
0 !LPUB SUBMODEL_DISPLAY SHOW_TOP_MODEL GLOBAL TRUE
0 !LPUB SUBMODEL_DISPLAY PLACEMENT GLOBAL TOP_LEFT PAGE INSIDE
0 !LPUB CONTINUOUS_STEP_NUMBERS GLOBAL TRUE
1 0 -217.756 -54.863 186.004 0.005 1 0.003 -0.997 0.005 0.072 0.072 -0.004 0.997 6629.dat
0 STEP
1 1 -197.686 -53.313 205.874 1 -0.005 0.003 0.005 0.997 0.072 -0.004 -0.072 0.997 6558.dat
0 STEP
1 1 -197.616 -51.866 225.822 1 -0.005 0.003 0.005 0.997 0.072 -0.004 -0.072 0.997 6558.dat

### Expected behaviour
PLI to be placed under submodel (if present), and in the top left corner of the page (as submodel would consume no space) otherwise.

### Actual behaviour
PLI is probably placed relative to the page header.

### Workaround
Set SHOW_STEP_NUMBER to TRUE, and then place it outside of the page with
0 !LPUB STEP_NUMBER PLACEMENT GLOBAL TOP LEFT PLI OUTSIDE -1 -1

### Solution suggestion
Correction.

**Comment by trevorsandy** [comment]
Corrected.

With display submodel.
![Screenshot - 02_09_2019 , 02_47_09](https://user-images.githubusercontent.com/13388970/64084940-05be6980-cd30-11e9-8d7e-00e5f54e2fd8.png)

...and when there is no submodel - even if the placement meta command directs placement to submodel
![Screenshot - 02_09_2019 , 03_05_51](https://user-images.githubusercontent.com/13388970/64084955-27b7ec00-cd30-11e9-8c96-ece19f99f2c3.png)

Cheers,

**Comment by 6638** [comment]
Hello, Trevor.

Thanks for taking care of this problem. Though, I am afraid, your second screenshot testifies that the problem is only partially resolved.

When step numbers are enabled, PLI is placed at the top of the page (there is only a space due to a margin). And the PLI placement dialogue correctly shows that the placement is relative to the submodel.

<img width="960" alt="1" src="https://user-images.githubusercontent.com/49516540/64130770-c130dd80-cdc4-11e9-9fe5-35365f38f20f.png">

But when step numbers are disabled, PLI is placed lower, because it is aligned relative to the page header, as shown in the PLI placement dialogue. And independent of what you select in the dialogue, it will stay aligned to the page header:

<img width="960" alt="2" src="https://user-images.githubusercontent.com/49516540/64130833-300e3680-cdc5-11e9-884e-983a8db54583.png">

As a workaround, it is possible to manually realign it by adding an offset. For example:
<img width="960" alt="3" src="https://user-images.githubusercontent.com/49516540/64130864-5338e600-cdc5-11e9-8649-4914c71a4f47.png">

Cheers!

**Comment by trevorsandy** [comment]
Hi 6638,

> But when step numbers are disabled, PLI is placed lower, because it is aligned relative to the page header, as shown in the PLI placement dialogue. And independent of what you select in the dialogue, it will stay aligned to the page header:

Your explanation is precisely why I labelled this ticket a bug. The behaviour you described is what has been corrected including the originally reported incorrect placement of the PLI over the submodel. Here are some additional shots showing different placement options and the result:

![Screenshot - 02_09_2019 , 22_41_36](https://user-images.githubusercontent.com/13388970/64132941-75396500-cdd3-11e9-9705-ad3b7d40a53e.png)

![Screenshot - 02_09_2019 , 22_42_37](https://user-images.githubusercontent.com/13388970/64132942-75396500-cdd3-11e9-9280-d40c716c93fc.png)

To confirm on your side, you can download a portable instance (.zip) of the continuous development build available [here](https://github.com/trevorsandy/lpub3d-ci/releases/tag/continuous). Please note that development builds and not guaranteed to be fully stable. To see what checked in content are included see the [commit list](https://github.com/trevorsandy/lpub3d-ci/commits/master) - the WIP_CAM commit is a massive blob of new functionality including dynamic camera configuration and alignment of the Native renderer to use the same camera globe format as that of LDGLite and LDView. It is not yet 100%.


Cheers,

**Comment by 6638** [comment]
Hello, Trevor.

When step number is displayed, the behavior is different from when step numbers are disabled.

### Configuration
- Submodel is placed relative to the page.
```
0 !LPUB SUBMODEL_DISPLAY PLACEMENT GLOBAL TOP_LEFT PAGE INSIDE
```
- PLI is placed relative to the submodel.
```
0 !LPUB PLI PLACEMENT GLOBAL BOTTOM LEFT SUBMODEL_DISPLAY OUTSIDE
```
- When step number is displayed, it is placed relative to the PLI. Therefore, it has no influence on PLI placement.
```
0 !LPUB STEP_NUMBER PLACEMENT GLOBAL BOTTOM LEFT PLI OUTSIDE 0 0
```

### Result with step numbers
- When submodel is present, it is placed relative to the page and PLI is placed relative to the submodel.
- When submodel is absent, PLI is still placed relative to the submodel _as if submodel would take zero space_.

Without this behavior, you would need to globally set placement of the PLI relative to the page, and then hunt every step, where a submodel is introduced, and change placement of the PLI to be locally relative to the submodel.
What is cool of the existing behavior that you configure it globally once and it works throughout entire building instruction.

### Result with step numbers disabled
- When submodel is present, everything is fine after your recent fix.
- When submodel is absent, the global command (which mandates PLI placement relative to the submodel) is ignored and PLI gets placed relative to the page header. Yes, now you can reconfigure the placement locally. But then you would need to do it at every step. Or alternatively, you would need to place PLI relative to page globally, and then to redefine its placement at every step, where submodel is present.

### Comparison
Please pay attention that behavior changes when step numbers got enabled/disabled, even though step numbers don't play any role in placement of PLI in this configuration: _PLI is placed relative to the submodel, submodel relative to the page_.

### Final note
This inconsistency doesn't really hurt me personally, because there is a workaround (see my first message) that works perfectly well for me. However, I report it, because I believe it might be tricky for other users.

Cheers.

**Comment by trevorsandy** [comment]
Hi 6638,

Thank you for reporting this behaviour. Indeed, there is some inconsistency here.

There is automatic logic to redirect the Submodel and PLI placement when these items are placed relative to the Step Number and the Step Number is not displayed. Other Submodel and PLI global placements should hold throughout the document as expected.

Note that both the Submodel and PLI are set relative to the Step Number by default. The following-stated logic will sort out the dependency.

For single step page layout, the behaviour is...

[CONDITION 1] If page is single step and Step Number is displayed:

- If Submodel and PLI are both displayed and each is set relative to the Step Number, automatically redirect the PLI relative to the Submodel.

- If Submodel is not displayed, **do nothing**; hence, the PLI continues to be configured as relative to the Submodel. _This behaviour is unintentional. The condition to redirect the PLI to the Page Header should be added here._

[CONDITION 2] If Step Number is not displayed:

- If Submodel and PLI are both displayed and each is set relative to the Step Number, automatically redirect the Submodel relative to the Page Header and redirect the PLI relative to the Submodel.

- If the Submodel is not displayed, then automatically redirect the PLI relative to Page Header. 

> When submodel is absent, the global command (which mandates PLI placement relative to the submodel) is ignored and PLI gets placed relative to the page header.

 This condition is currently outside the `If (StepNum) {do this} else {do that}`; and therefore is firing every time, placing the PLI relative to the Page Header when it is relative to Submodel and the Submodel is not displayed. _This is the inconsistent behaviour_. This condition should be placed in the aforementioned CONDITION 1. 

Once moved to CONDITION 1, directly setting the PLI placement relative to Submodel should hold when the conditions outlined above do not apply.

Cheers,

**Comment by trevorsandy** [comment]
After running some sc

[CONDITION 1] If page is single step and Step Number is displayed:

- If Submodel is not displayed and PLI is displayed and is set relative to the Step Number, **do nothing** - allow assigned PLI placement

[CONDITION 2] If page is single step and Step Number is not displayed:

- If the Submodel is not displayed and PLI is displayed and is set relative to the Step Number, automatically redirect the PLI relative to Page Header. 

[CONDITION 3]  If page is single step and PLI is displayed and is set relative to Submodel

- If the Submodel is displayed, **do nothing** - allow assigned PLI placement

- If the Submodel is not displayed, automatically redirect the PLI relative to Page Header. 

> When submodel is absent, the global command (which mandates PLI placement relative to the submodel) is ignored and PLI gets placed relative to the page header.

CONDITION 3 will fire every time the PLI is relative to Submodel and the Submodel is not displayed. _This is the inconsistent behaviour_. I will suppress this block so globally setting the PLI placement relative to Submodel should hold throughout the instruction document. The new behaviour will be...

- If the Submodel is not displayed, **do nothing** - allow assigned PLI placement

Cheers,

**Comment by 6638** [comment]
Hello, Trevor.

I think, the main objective of LPub3D is to reduce the need for manual construction of page layout on every step. From this perspective, it is difficult to see the chosen solution as an improvement.

As I wrote before:
> What is cool of the existing behavior that you configure it globally once and it works throughout entire building instruction.

Previously, PLI could be placed relative to page boundaries using only the global commands
```
0 !LPUB PLI PLACEMENT GLOBAL BOTTOM LEFT SUBMODEL_DISPLAY OUTSIDE
0 !LPUB SUBMODEL_DISPLAY PLACEMENT GLOBAL TOP_LEFT PAGE INSIDE
```
and it worked on pages with or without submodels.

Now if submodel is absent, PLI gets aligned relative to the page header. Therefore, it is necessary to manually redefine PLI placement locally at every step, where submodel is present.

What is worth, it looks like header height cannot be set to 0. It looks like the command is ignored, when header height is set to something less then 0.1. It means that you cannot define global meta to place PLI and submodel at the edge of the page, as it used to be earlier.

Finally, models created for earlier versions of LPub3D will get regression -- their view will get changed.

I suspect that the following behavior was indeed intentional, made a great deal and will be beneficial also when step numbers are disabled:
> If Submodel is not displayed, do nothing; hence, the PLI continues to be configured as relative to the Submodel.

Cheers!

**Comment by trevorsandy** [comment]
Hello 6638,

I totally agree. If you well read [my last post](https://github.com/trevorsandy/lpub3d/issues/335#issuecomment-531603605) and take a look at the last set of screenshots I posted, you'll see that the implementation I have settled on does what you were expecting :-) 

Here again I will repeat what I have concluded above with the final implemented logic in **BOLD**:

> [CONDITION 3] If page is single step and PLI is displayed and is set relative to Submodel
...
> CONDITION 3 will fire every time the PLI is relative to Submodel and the Submodel is not displayed. _This is the inconsistent behaviour_. I will suppress this block so globally setting the PLI placement relative to Submodel should hold throughout the instruction document. The new behaviour will be...

- **If the Submodel is not displayed, do nothing - allow assigned PLI placement**

To you remark above...

> Previously, PLI could be placed relative to page boundaries using only the global commands

```
0 !LPUB PLI PLACEMENT GLOBAL BOTTOM LEFT SUBMODEL_DISPLAY OUTSIDE
0 !LPUB SUBMODEL_DISPLAY PLACEMENT GLOBAL TOP_LEFT PAGE INSIDE
```

> and it worked on pages with or without submodels.


This is precisely what I am displaying with the 2 last screenshots above - look a the meta commands tab and you will see exactly the example commands above.

Are you experiencing some sort of different behaviour with the latest [Continuous release](https://github.com/trevorsandy/lpub3d/releases/tag/continuous) ? 

Cheers,

**Comment by 6638** [comment]
Hello, Trevor.

After playing with the last build in continuous release, I confirm that you, indeed, got my considerations right. I am sorry for misinterpreting your explanations.

Cheers!

**Comment by trevorsandy** [comment]
Hi 6638 - No worries at all. 

Know that I really appreciate your feedback and the level of detail that supports it. It is users like you that make the biggest impact on improving the robustness of LPub3D.

Cheers,
