### ISSUE TITLE
Update and redraw save file to disk

### ISSUE THREAD

**Issue by 6638** [trevorsandy/lpub3d#336]
### Subject
When Update or Redraw icon is pressed in toolbar of the LDraw Editor sidebar, the opened file is saved to disk.

### Environment
* 2.3.12 rev 113 (portable)
* Windows 7 x64

### Configuration
Default

### Logs
N/A

### Screenshots
N/A

### Steps to reproduce
- Open any file in LPub3D
- modify the file in LDraw Editor sidebar
- click Update or Redraw button in the toolbar
- open the file in any 3rd party text editor and check changes are saved to the file, or check last modified time of the file.

### Expected behaviour
LPub3D doesn't save the file to disk, unless the save command is selected.

### Actual behaviour
LPub3D silently modifies open file on disk.

### Workaround
None.

### Solution suggestion
The rendering probably uses the opened file, hence the update/redraw requires saving changes to disk. Though, it would be better not to write any changes silently. It could be probably achieved by creating a temporary mpd file for rendering in LPub3D/tmp folder in the working directory.

**Comment by trevorsandy** [comment]
Thank you for your suggestion. I agree. It would be better to give the user full control of when changes are written to disc. The behaviour has been changed.

Preferences flags to enable automatic save on Update and Redraw.
![Screenshot - 02_09_2019 , 05_23_15](https://user-images.githubusercontent.com/13388970/64088517-1ed01600-cd42-11e9-9914-aa467ab29d52.png)

Cheers,

**Comment by 6638** [comment]
Hello, Trevor.

Update works fine, but redraw reverts data saved in the file, causing loss of all changes. Is it the expected behavior?

Cheers!

**Comment by trevorsandy** [comment]
> Redraw reverts data saved in the file, causing loss of all changes. Is it the expected behavior?

If `Save on Redraw` is **unchecked** in Preferences; yes, this behaviour is as designed. 
Note that both `Save on Update` and `Save on Redraw` are set checked by default. This is to preserve the previous behaviour.

Cheers,

**Comment by 6638** [comment]
Hello, Trevor.

> UPD - There should be a prompt to save your changes when the "Redraw" button is clicked and Save on Redraw is unchecked in Preferences. Is this not the case for you ?

No, I don't have any prompt. LPub3D v2.3.13 r0.

Cheers!

**Comment by trevorsandy** [comment]
Indeed. I performed a check and can confirm there is no prompt. I'll add this change shortly. 

Cheers.,

**Comment by 6638** [comment]
Hello, Trevor.

I played with the latest continuous release having both "Save on ..." checkboxes unchecked.

### Update

- Pressing **Update** and selecting yes in the dialog saves changes to the disk and updates page layout.
- Pressing **Update** and selecting no in the dialog doesn't save changes to the disk and updates page layout.

Though, is there really benefit in displaying a prompt in this case? One who got accustomed to the older way can set "Save on updates" in settings and the changes will get saved automatically. One who doesn't want to save changes implicitly, will uncheck the option; and once satisfied with outcome of manipulations, one will press Ctrl+S to save the changes. I.e. IMO dialog is redundant here.

### Redraw

- Pressing **Redraw** and selecting yes in the dialog saves changes to the disk, clears cash and updates page layout.
- Pressing **Redraw** and selecting no in the dialog reverts changes back, clears cash and doesn't update the layout (because there is effectively no change anymore).

So I either have to save the changes or loose them.

It would be best to have it as in case of "Update" (i.e. just to perform an action, without saving anything to disk). But if it is effort-intensive to redraw objects without saving the file, then the following actions seem to be more reasonable:

- Pressing **Redraw** and selecting yes in the dialog saves changes to the disk, clears cash and updates page layout.
- Pressing **Redraw** and selecting no in the dialog does nothing.

The dialog can say: "The action requires saving changes to the disk. Do you want to continue?"

Cheers!

**Comment by trevorsandy** [comment]
Hi 6638,

> Though, is there really benefit in displaying a prompt in this case? One who got accustomed to the older way can set "Save on updates" in settings and the changes will get saved automatically. One who doesn't want to save changes implicitly, will uncheck the option; and once satisfied with outcome of manipulations, one will press Ctrl+S to save the changes. I.e. IMO dialog is redundant here.

"The cat is already out of the bag" so I prefer not to remove the checkBox for "Save on updates". I have already added a "don't show this message again" check box to the dialogue. I was going to check it in with the next release but I imagine it won't hurt to check it in early.

> Pressing Redraw and selecting no in the dialogue reverts changes back, clears cash and doesn't update the layout (because there is effectively no change anymore).

Actually, nothing is reverted. This action simply abandons the currently loaded model file, without saving any changes when "save on redraw" is unchecked, and reloads the model file from disc. The aim of this function is to re-render images when configuration changes are made, noting that it is entirely possible that changes may be implemented without an update to the model file, for example if one was to directly edit a .ini file or change a preference setting etc... Moreover, if a change does not implicate the the image file name; hence triggering a redraw automatically, this function forces a redraw of all image files.

> It would be best to have it as in case of "Update" (i.e. just to perform an action, without saving anything to disk).

If there are changes to the model file when Redraw is clicked and "Save on Redraw" is unchecked, I prefer to prompt the user to save his/her changes. If the user wishes to suppress this prompt, the "don't show this message again" checkBox will be useful.

> Update: Btw two checkboxes in settings also seem too much for such a minor change. :)

Perhaps, but with thousands of users, I'd rather take the time to add the flexibility now than have users lose their work and have to visit the behaviour again later.

Cheers,

**Comment by 6638** [comment]
Hello, Trevor.

> "The cat is already out of the bag" so I prefer not to remove the checkBox for "Save on updates". I have already added a "don't show this message again" check box to the dialogue.

Actually, I was not thinking to remove the check box -- I understand your aspiration to preserve the legacy behavior. I was rather thinking to remove the _dialog_, which appears after clicking the update button. But your solution with "don't show again" option will also work perfectly well. 

And if with the "remove the check box" you mean what I wrote in P.S., then I was rather thinking that a single common checkbox in settings, like "Save on Update/Redraw", would be sufficient.

> Actually, nothing is reverted. This action simply abandons the currently loaded model file, without saving any changes when "save on redraw" is unchecked, and reloads the model file from disc.

Let's think of this use case: the user makes modifications in the "LDraw Editor" pane to adjust the step(s) layout. The user not only modifies LPub3D's metas, but also rearranges parts between steps. At some point the user notes that some drawings are wrong, because cashed images got outdated. At this point all the changes are not saved to disk. The user triggers Redraw action, the dialog appears. Since the user is not satisfied with outcome of his changes, he doesn't want to save them to disk yet, and therefore selects "No" in the dialog. What happens next? "This action simply abandons the currently loaded model file, without saving any changes <...> and reloads the model file from disc." This is what I mean with "reverted"  -- all the changes got reverted to the state saved on the disk. I.e. all unsaved changes get lost.

Cheers!

**Comment by trevorsandy** [comment]
Hi 6638,

> Let's think of this use case: the user makes modifications in the "LDraw Editor" pane to adjust the step(s) layout. The user not only modifies LPub3D's metas, but also rearranges parts between steps. At some point the user notes that some drawings are wrong, because cashed images got outdated. At this point all the changes are not saved to disk. The user triggers Redraw action, the dialog appears. Since the user is not satisfied with outcome of his changes, he doesn't want to save them to disk yet, and therefore selects "No" in the dialog. What happens next? "This action simply abandons the currently loaded model file, without saving any changes <...> and reloads the model file from disc." This is what I mean with "reverted" -- all the changes got reverted to the state saved on the disk. I.e. all unsaved changes get lost.

IMO, the user should use "Update" in this scenario. New images will be rendered for images where there is a change in the image's attributes. and his/her unsaved model changes will be applied to the regened layout. When the user is happy with the layout, s/he can then save to the model file. In fact, this scenario is very close to the what I was thinking when I added the Update button; moreover, the Update function is much faster than Redraw because of the following difference. The difference between Update and Redraw is that Redraw clears the tmp, parts and assem caches in order the regen all content where Update will only see images being regened when attributes captured in the image file name has changed or their date stamp is older than the model file.

> Therefore, one cannot close the window without saving the changes. This is, indeed, also not logical. Other applications have three options in the dialog: Save, Don't Save, Cancel. This probably would be the best solution.

Are you using v2.3.13 r33 - build 1544 ? This behaviour was unintended and resulted from the fact that I did not check in the code that prompts the user to not show the dialog again - the commit had the updated description but was empty.

Here is what you should be seeing when with r33. BTW, the reset the dialog, toggle the respective checkBox in Preferences. It does not matter if the toggle is off or on - although if you started with off, then you'll likely toggle twice to finish with off.

![Screenshot - 18_09_2019 , 05_04_50](https://user-images.githubusercontent.com/13388970/65180474-3c4cf180-da5d-11e9-9b51-d5cb9707cd43.png)

> I mean, when suggesting a solution for "Redraw", I proposed to do nothing, if "No" is pressed in the dialog. But this is exactly how close window works right now, and it doesn't seem a good solution either. Therefore, I come to the conclusion that it is best to have three buttons. And it applies to both dialogs: the one for "Redraw" action, and the one for application shutdown.

How should the behaviour be different between Close and Cancel ? I really don't see any difference so I've opted to use Yes/No for brevity. If you choose No your work is not saved and the Redraw/Update routine continues its execution.

Cheers,

**Comment by 6638** [comment]
Hello, Trevor.

> Are you using v2.3.13 r33 - build 1544 ? This behaviour was unintended and resulted from the fact that I did not check in the code that prompts the user to not show the dialog again - the commit had the updated description but was empty.

No, I was using v2.3.13 r32. In r33, the windows gets closed, upon selecting "No" in the prompt.

> How should the behaviour be different between Close and Cancel ? I really don't see any difference so I've opted to use Yes/No for brevity. If you choose No your work is not saved and the Redraw/Update routine continues its execution.

So in r33, if I have unsaved changes, while trying to close the window, I will have two options in the prompt:
- Save changes and close window
- Loose changes and close window

I was thinking of a third option:
- Don't close window; return back and decide what changes are there and what to do with them.

If you have Windows, open any MS application, like Paint or Word. Make some changes and close the window without saving them. You will have these three options.

These were my thoughts. But because I am sure that there are a lot of much more valuable improvements waiting in the queue, I don't really want to spend your time on this topic any more.

Thank you for listening.

Cheers!

**Comment by trevorsandy** [comment]
Hi 6638.

> Don't close window; return back and decide what changes are there and what to do with them.

This behaviour make sense so I implemented the change - it was trivial. 3 buttons have been restored to the dialogue.

![Screenshot - 21_09_2019 , 23_03_15](https://user-images.githubusercontent.com/13388970/65379277-0c545700-dcc6-11e9-87bd-def95aaea5b3.png)

Cheers,
