### ISSUE TITLE
Question: placement control in step groups

### ISSUE THREAD

**Issue by 6638** [trevorsandy/lpub3d#337]
Hello, Trevor.

Could you please explain the logic behind placement of objects in a multistep composition? Is there any way to control the layout?

Example:
```
0 !LPUB PAGE ORIENTATION LANDSCAPE
0 !LPUB PAGE DISPLAY_PAGE_NUMBER GLOBAL FALSE
0 !LPUB MULTI_STEP SEPARATOR PAGE_LENGTH 0.03 black 0.3 0.3
0 !LPUB MULTI_STEP PLI PLACEMENT GLOBAL TOP_LEFT PAGE INSIDE
0 !LPUB MULTI_STEP STEP_NUMBER PLACEMENT GLOBAL BOTTOM LEFT PLI OUTSIDE
0 !LPUB MULTI_STEP ASSEM PLACEMENT GLOBAL BOTTOM_RIGHT PAGE INSIDE
0 !LPUB MULTI_STEP BEGIN
1 0 -217.756 -54.863 186.004 0.005 1 0.003 -0.997 0.005 0.072 0.072 -0.004 0.997 6629.dat
0 STEP
0 !LPUB MULTI_STEP DIVIDER 
1 1 -197.686 -53.313 205.874 1 -0.005 0.003 0.005 0.997 0.072 -0.004 -0.072 0.997 6558.dat
0 STEP
0 !LPUB MULTI_STEP END
1 1 -197.616 -51.866 225.822 1 -0.005 0.003 0.005 0.997 0.072 -0.004 -0.072 0.997 6558.dat
```
<img width="960" alt="1" src="https://user-images.githubusercontent.com/49516540/64200034-f2c0ac00-ce8b-11e9-9db5-e0dabfed574a.png">

1. Is there any way to divide page into equal parts for every step? In the example above, page width is 1754 px, but the divider is placed at 958 px. Is it possible to put it just in the middle?
2. Is it possible to align objects in every step relative to the content box dedicated to that step? For example, PLI in the top left corner and assembly in the bottom right one.
3. Is it possible to crop objects, which do not fit to the context box dedicated to that step? For example, to crop assembly, which doesn't fit to the content box, and in this way to prevent obstruction of other objects in another step.

Thank you in advance!

**Comment by trevorsandy** [comment]
> 1. Is there any way to divide page into equal parts for every step? In the example above, page width is 1754 px, but the divider is placed at 958 px. Is it possible to put it just in the middle?

At this moment, there is no functionality that automatically divides a multistep page into equal parts. A multistep page "Ranges" will use the tallest or widest "Range" (a step) to define the width or height  (depending the the Ranges allocation - vertical or horizontal). This means steps in a multistep page will not be uniformly distributed on the page automatically. However, it is possible to achieve uniformity using margins or if the step's components are place such that the steps are essentially the same width or height. As of v2.3.13, there is the possibility to manipulate the height margin of steps in a multistep page - this capability was not previously available in LPub3D. Additionally, there is now the option to set the step towards the centre of its Range bounding box when a range divider is present and the allocation is horizontal. Before this enhancement, steps were justified towards the divider in such a configuration. See #333 for additional details.

> 2. Is it possible to align objects in every step relative to the content box dedicated to that step? For example, PLI in the top left corner and assembly in the bottom right one.

No, however this is a good enhancement. The key pieces are already in place to enable this behaviour. I would simply have to add a step's "Range" to the list of available "relative to" placement options. Do not hesitate to open a ticket requesting this behaviour.

> 3. Is it possible to crop objects, which do not fit to the context box dedicated to that step? For example, to crop assembly, which doesn't fit to the content box, and in this way to prevent obstruction of other objects in another step.

No, but I have good news on this one. For the next release (v2.3.14), there will be the ability to manipulate the 3DViewer camera, which, in turn, will generate the required meta command(s) to create the image specified. This will include the ability to zoom, and in the short future, crop images to a specified object size - for example the current CSI. You can see some preliminary details on this functionality in #331. Also, after the official release of v2.3.13, you will be able to access preliminary builds of #331 from the DevOps continuous release.

Cheers,

**Comment by 6638** [comment]
Hello, Trevor.

When step number is displayed, the behavior is different from when step numbers are disabled.

### Configuration
- Submodel is placed relative to the page.
```
0 !LPUB SUBMODEL_DISPLAY PLACEMENT GLOBAL TOP_LEFT PAGE INSIDE
```
- PLI is placed relative to the submodel.
```
0 !LPUB PLI PLACEMENT GLOBAL BOTTOM LEFT SUBMODEL_DISPLAY OUTSIDE
```
- When step number is displayed, it is placed relative to the PLI. Therefore, it has no influence on PLI placement.
```
0 !LPUB STEP_NUMBER PLACEMENT GLOBAL BOTTOM LEFT PLI OUTSIDE 0 0
```

### Result with step numbers
- When submodel is present, it is placed relative to the page and PLI is placed relative to the submodel.
- When submodel is absent, PLI is still placed relative to the submodel _as if submodel would take zero space_.

Without this behavior, you would need to globally set placement of the PLI relative to the page, and then change first step of every submodel with a local setting.

What is cool of the existing behavior that you configure it globally once and it works throughout entire building instruction.

### Result with step numbers disabled
- When submodel is present, everything is fine after your recent fix.
- When submodel is absent, the global command (which mandates PLI placement relative to the submodel) is ignored and PLI gets placed relative to the page header. Yes, now you can reconfigure the placement locally. But then you would need to do it at every step. Or alternatively, you would need to place PLI relative to page globally, and then to redefine its placement at every step, where submodel preview is present.

### Comparison
Please pay attention that behavior changes when step numbers got enabled/disabled, even though step numbers don't play any role in placement of PLI in this configuration: PLI is placed relative to the submodel, submodel -- relative to the page.

### Final note
This inconsistency doesn't really hurt me personally, because I am aware of the workaround (see my first post), which works perfectly well for me. Though, this might be tricky for other users.

Cheers.

**Comment by 6638** [comment]
Hello, Trevor.

1.
> At this moment, there is no functionality that automatically divides a multistep page into equal parts. <...> However, it is possible to achieve uniformity using margins or if the step's components are place such that the steps are essentially the same width or height.

It would require manual adjustments for every individual step. I was thinking, how to best configure it globally. How about introducing a new meta to define width/height for a step in a step group?
```
0 !LPUB MULTI_STEP STEP WIDTH|HEIGHT GLOBAL|LOCAL xxx
```

Cheers.

**Comment by trevorsandy** [comment]
I have noted this request.

Cheers,

**Comment by trevorsandy** [comment]
Hello 6638.

> How about introducing a new meta to define width/height for a step in a step group?

This capability has been implemented. See #358.

Cheers,
