### ISSUE TITLE
Resize handle on Parts List (PLI) has gone

### ISSUE THREAD

**Issue by d-j-m-0** [trevorsandy/lpub3d#339]
### Subject
Previously, when a parts list was selected, it would display a "handle" which could be used to resize the parts list by clicking the mouse and dragging. The handle has gone in the latest release. Resizing the parts list now requires the entry of some magical and meaningless numbers.

### Environment
* Version of LPub3D - 2.3.12 revision 113 build 1469
* Operating system - Windows 10 version 1903, 64 bit, 

### Steps to reproduce
Open an mpd. Click on any parts list. No resize "handle" is displayed.

### Expected behaviour
When the parts list is selected, the resize handle should be available for resizing the parts list.

### Screenshot
The screenshot shows how the parts list looks when selected in the most recent release (upper part of image) as compared to how it looked in the previous release (lower part of image)

![pli_resize_handle_gone](https://user-images.githubusercontent.com/37604323/64228333-97012c00-cf3a-11e9-925e-6f2a3656ef75.png).

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'm not sure when I broke it, or when it was corrected; however, the latest [DevOps build](https://github.com/trevorsandy/lpub3d-ci/releases/tag/continuous) does show the grabber when the PLI is selected.

![Screenshot - 04_09_2019 , 08_32_54](https://user-images.githubusercontent.com/13388970/64231105-f76a7c00-ceee-11e9-872c-71f0154a2a19.png)

Let me know if you can confirm this in your environment.

Cheers,

**Comment by d-j-m-0** [comment]
I think that the has disappeared on multi-step PLIs. The attached mpd does not show the handle on step 1 on page 1 (which is a multi-step) but does show the handle on page 4 (which is not a multi-step).

David
[moa _resize.mpd.txt](https://github.com/trevorsandy/lpub3d/files/3573218/moa._resize.mpd.txt)

**Comment by trevorsandy** [comment]
Ah, good additional informational. I can confirm this behaviour is still present. I'll take a look.  

Cheers,

**Comment by trevorsandy** [comment]
Restored.

![Screenshot - 04_09_2019 , 09_43_10](https://user-images.githubusercontent.com/13388970/64235437-a8c1df80-cef8-11e9-9a33-b47dea7f2819.png)
![Screenshot - 04_09_2019 , 09_43_59](https://user-images.githubusercontent.com/13388970/64235438-a95a7600-cef8-11e9-943e-bdff58ec55d5.png)

Cheers,
