### ISSUE TITLE
Export to pdf using page range generates single page

### ISSUE THREAD

**Issue by technicbasics** [trevorsandy/lpub3d#341]
### Subject
Export a range of pages to pdf only a single page with the last page in the range is generated

### Environment
* Version of LPub3D - LPub3D 2.3.13r0 (mobile version)
* Operating system - Win10 64 bit

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  - Mobile Version
* Application data path
  - Windows: `%USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\`

### Screenshots
![General](https://user-images.githubusercontent.com/49073781/64633361-61a58400-d3fb-11e9-9b51-1ccb5366bf9b.PNG)
![Other](https://user-images.githubusercontent.com/49073781/64633362-61a58400-d3fb-11e9-9d9f-e08c4d35246e.PNG)
![Publish](https://user-images.githubusercontent.com/49073781/64633364-61a58400-d3fb-11e9-8a15-f9c513543522.PNG)
![Rendering](https://user-images.githubusercontent.com/49073781/64633365-623e1a80-d3fb-11e9-99b0-0dcd79056855.PNG)
![Theme](https://user-images.githubusercontent.com/49073781/64633367-623e1a80-d3fb-11e9-828a-30e485bf1d0f.PNG)

### Steps to reproduce
OPen file
Export to pdf file
Set range
export

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

Cheers,
