### ISSUE TITLE
DPI and scale info is added to filename in PNG export

### ISSUE THREAD

**Issue by riazanovskiy** [trevorsandy/lpub3d#346]
### Subject
If I try to export instruction as PNG images I get following output
![image](https://user-images.githubusercontent.com/11013917/64985185-01b44f00-d8cd-11e9-8e80-8e45d4261042.png)

This disables the possibility to export large instruction due to Windows file path length limit (or maybe due to some other limitation)

### Environment
LPub3D 2.3.13 r 29 from Github Releases under Windows 10

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

![Screenshot - 16_09_2019 , 22_04_32](https://user-images.githubusercontent.com/13388970/64991735-b309b380-d8d2-11e9-8553-3b5e7fc59369.png)

Cheers,
