### ISSUE TITLE
Any changes in 3DViewer Preferences not saved

### ISSUE THREAD

**Issue by Symbian9** [trevorsandy/lpub3d#349]
### Subject

Any changes in 3DViewer Preferences not saved

### Environment

- Version of LPub3D - `LPub3D-2.3.13.36.1547_20190925-x86_64.AppImage`
- Operating system - *MX Linux MX-17.x* (*Debian 9.x*), x86_64

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
- LPub3D installation path
  - AppImage (Linux): `/tmp/.mount_LPub3D<UniqueID>/usr/share/lpub3d`
- Application data path
  - AppImage (Linux): `~/.local/share/LPub3D Software/<AppImage File Name>/`
- Registry Extract
  - AppImage (Linux): `~/.config/LPub3D Software/<AppImage File Name>.conf`
- Renderer configuration files
  - `[Application data path]/ldv/ldvExport.ini`
  - `[Application data path]/3rdParty/ldglite-1.3/config/ldglite.ini`
  - `[Application data path]/3rdParty/ldview-4.3/config/ldview.ini`
  - `[Application data path]/3rdParty/ldview-4.3/config/ldviewPOV.ini`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.conf`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.ini`

### Logs
* Application Log: `[Application data path]/logs/LPub3DLog.txt`
* Renderer Log: `[LDraw model path]/stdout-ldglite`
* Renderer Log: `[LDraw model path]/stdout-povray`
* Renderer Log: `[LDraw model path]/stderr-ldglite`
* Renderer Log: `[LDraw model path]/stderr-povray`

### Screenshots
* Configuration->Preferences->General
* Configuration->Preferences->Rendering
* Configuration->Preferences->Publishing
* Configuration->Preferences->Logging
* Configuration->Preferences->Other

### Steps to reproduce

1. Launch *LPub3D*;
2. Go to *"3DViewer > Preferences..."*;
3. Change *"Anti-aliasing"* (or any other) settings and press <kbd>OK</kbd>;
4. Restart *LPub3D* and check *"3DViewer > Preferences..."*.

### Expected behaviour

If change any settings in 3DViewer Preferences it should be saved just after click on <kbd>OK</kbd> button.

### Actual behaviour

*LPub3D* not save any manual changes in 3DViewer Preferences.

### Workaround
Share your work around if available

### Solution suggestion
Share your opinion on how to achieve the expected behaviour

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I’ll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Please take a look at the latest release. 

Closing this ticket. If you continue to experience this behaviour, do not hesitate to reopen.

Cheers,

**Comment by Symbian9** [comment]
> Please take a look at the latest release.

OK, I will look on it this week.
