### ISSUE TITLE
LDView does not render sub-modules in assamblies while Native Renderer does

### ISSUE THREAD

**Issue by swl2019** [trevorsandy/lpub3d#351]
### Subject
Using LDView results in 1 page step 4 and following that submodules are not rendered in the assmably picture while using the native rendere they are rendered. Having them as a callout or not does not influence anything. 

I guess this is due to some wrong / not-clever used naming conventions for submodels.

Interesting effect is that the pages rendereds by LDView look different to the ones rendered by the Native Renderer in Terms of placement and size of the individual items (for example step 1 Part List. This is not of any concern for me as I need LDView as I have in later staps custom parts with TEXTURE MAPs.

The submodel files LPub3D writes for ist own Purpose look good, i.e. the submodels are part of the files. - see attchatched files

### Environment
LPub3D 2.3.13.36.1547 (25 09 2019 02:19:17) 
Windows 10 x86

### Configuration
Default out of the box configuration, just added custom search pathes to own *.DAT files.
Renderer configuration files: see attachment

### Screenshots
see attachments

### Steps to reproduce
open attached ldr file and check page 1. Change in configuration the renderer.
[Render Issues with LDView.zip](https://github.com/trevorsandy/lpub3d/files/3691081/Render.Issues.with.LDView.zip)

### Expected behaviour
LDView renders the assambly including the submodles

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

I'm not able to reproduce this behaviour with the model file you provided. The naming convention used does not appear to be the problem. Moreover, there are many missing parts so I'm not sure the results will be consistent.

![Screenshot - 06_10_2019 , 09_55_37](https://user-images.githubusercontent.com/13388970/66266189-d95fa680-e821-11e9-8336-780b3a77fd71.png)

Can you post a few screenshots of the actual behaviour versus the expected behaviour ? 

In posting a shot, please capture the entire application with the Editor tab raised, as shown below, to show the point in the model file where the unexpected behaviour is present.

![Screenshot - 06_10_2019 , 10_15_27](https://user-images.githubusercontent.com/13388970/66266247-5428c180-e822-11e9-8e1c-d9ba799c1a5c.png)

Cheers,

**Comment by swl2019** [comment]
Hi Trevor,

sorry for the inconveniences. I simplified the large file to illustrate just the issue. I also checked if it is different when running LPub3D as Administrator or not. I also moved the files to a local storage point as well as tested it with a windows OneDrive. 

The issue is still there: Using LDView as renderer the submodels “001_gearbox_01.ldr” , “001_gearbox_02.ldr” and “001_gearbox_03.ldr” do not show up in the corresponding step’s assembly picture while their callouts are fine and complete.

If I change to the native renderer they show up as expected. 

However I need LDView as renderer as I use in later steps a lot of self-defined parts with TEXTURE MAP statements.

This is the screenshot using LDView as renderer:
![LDView Renderer](https://user-images.githubusercontent.com/48833324/66268391-42a0e300-e83d-11e9-99fb-a42d4c3c2970.PNG)

In the working folder “LPub3D” the file “stout-ldview” shows for the working file LPub/tmp/CSI.ldr for all above mentioned submodles a loading error
<img width="866" alt="stout-ldview" src="https://user-images.githubusercontent.com/48833324/66268393-492f5a80-e83d-11e9-8d46-9c8914b59eee.PNG">

But opening the LPub/tmp/CSI.ldr file directly in LDView ther is no issue with it and displayed correct.
<img width="481" alt="LPub3D_tmp_CSI ldr_LDView_Render" src="https://user-images.githubusercontent.com/48833324/66268395-4df40e80-e83d-11e9-9856-f57a19c2175f.PNG">

Her the screenshot using the native renderer.
<img width="1229" alt="Native Renderer" src="https://user-images.githubusercontent.com/48833324/66268398-52202c00-e83d-11e9-8ffc-00e2aac0fd21.PNG">

If you need any additional information, please do not hesitate to ask for. The installation is an out-of-the-box installation and no changes have been made to the configuration at all (except switching the renderer of cause)

Thank you
Best Regards
Jörg

**Comment by swl2019** [comment]
And here is the simplified *.LDR file, the LPub working directory and all screenshots in a ZIP.
[LDView Render Results.zip](https://github.com/trevorsandy/lpub3d/files/3694287/LDView.Render.Results.zip)

**Comment by trevorsandy** [comment]
Hello Jörg,

Thank you for the supporting content. As you have already seen, LDView, for some reason cannot find the subfiles on your system, even though they are available. 

In my environment, the subfiles are rendered by LDView as expected:

![Screenshot - 06_10_2019 , 16_38_07](https://user-images.githubusercontent.com/13388970/66270821-fb741b80-e857-11e9-9f85-c111edf6c7ee.png)

Try placing your model at a location with only ascii characters in the file path - for example "C:\mymodel\Render Issues with LDView Extract.ldr"

Take a look at this thread on the LDraw forum: [LPub3D - Submodel not shown in main model](https://forums.ldraw.org/thread-23315-post-31414.html?highlight=lpub3d+submodel#pid31414). It looks like you are experiencing the same behaviour ?

Cheers,

**Comment by trevorsandy** [comment]
Hi Jörg,

I placed the model file in a path that used "JörgSchwarzländer" in the path and, indeed, submodels were not rendered. 

![Screenshot - 06_10_2019 , 17_15_58](https://user-images.githubusercontent.com/13388970/66271393-c8348b00-e85d-11e9-8fde-1719fc8e5ba8.png)

This is exactly the behaviour highlighted in the LDraw forum post above. I'll take a look at updating my instance of LDView.

### Workaround
Until an update is released, you should be able to progress by placing your model file in a location without UTF-8 special characters in the file path.

Cheers,

**Comment by swl2019** [comment]
Hi Trevor,

thank you - simple but impacting root cause. I was forced to take the non ASCII characters into my user name :-( 

Best Regards
Jörg

**Comment by trevorsandy** [comment]
Hello Jörg - This behaviour has been corrected. 

You can return to your user name in the model file path.

Seet this ticket for details: https://github.com/tcobbs/ldview/issues/18  

Cheers,

**Comment by swl2019** [comment]
Hi Trevor.

 

Thank you - reading the details it was quite a piece of investigation and work. Thank you again.

 

Best Regards

Jörg

 

Gesendet: Mittwoch, 09. Oktober 2019 um 19:14 Uhr
Von: "Trevor SANDY" <notifications@github.com>
An: trevorsandy/lpub3d <lpub3d@noreply.github.com>
Cc: swl2019 <git@familie-schwarzlaender.de>, Author <author@noreply.github.com>
Betreff: Re: [trevorsandy/lpub3d] LDView does not render sub-modules in assamblies while Native Renderer does (#351)


Hello Jörg - This behaviour has been corrected.

You can return to your user name in the model file path.

Seet this ticket for details: tcobbs/ldview#18

Cheers,
