### ISSUE TITLE
Crash while editing text

### ISSUE THREAD

**Issue by ZPhilo** [trevorsandy/lpub3d#355]
### Subject
LDCad flexible parts don't get new parts per step highlighting

### Environment
* Version of LPub3D - 2.3.13/1511
* Operating system - Win10/64

I had several crashes that occured while editind free text (eg. model title) and moving it around. LPub3D closes without any warning. Unfortunately I have no detailed procedure to reproduce this issue for sure.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

I couldn't reproduce it on my system - even using the sample model file you provided.

I'll keep this ticket open however. Any additional context you can provide would be helpful.

cheers,

**Comment by ZPhilo** [comment]
Yes, I'll keep my eyes peeled and see if I can get something reproducible...

**Comment by trevorsandy** [comment]
Two text updates have been checked in #357 and #375. 

If you continue to experience unexpected behaviour, do not hesitate to add you findings to this ticket.

Cheers,

**Comment by ZPhilo** [comment]
Thanks Trevor!

**Comment by trevorsandy** [comment]
Hi Philo, 

With pleasure. 

Did you see #374  ?

Cheers,
