### ISSUE TITLE
Writing in PDF duplicated

### ISSUE THREAD

**Issue by scumpy0815** [trevorsandy/lpub3d#361]
### Subject
When using a specific font (ttf), the pdf has every character two times over each other resulting in a bold writing. If I use Adobe Acrobat and edit the pdf, I can remove the second set of characters, but this is pretty annoying. When using a font like arial, there is no such problem.

### Environment
* Version of LPub3D - v2.3.13 r36 (Release); but I've got that problem longer
* Operating system - Windows 10 1903, x64

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
C:\LDraw\Lpub3d

### Steps to reproduce
See description.
[Font.zip](https://github.com/trevorsandy/lpub3d/files/3725512/Font.zip)

### Expected behaviour
Every character should be only one time in the pdf.

### Actual behaviour
Double characters over another.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

I could not find any freely downloadable ttf for **Chalet fett** or **Chalet regular**. Please provide an appropriate sample or sample URL.

As I do not have either of the above fonts installed, I believe the Chalet font is substituted with _MS Shell Dlg 2_ which, for me, exports to PDF as expected.

![Screenshot - 21_10_2019 , 19_57_41](https://user-images.githubusercontent.com/13388970/67230229-302dc880-f43d-11e9-8afc-46bf7ad00335.png)

Cheers,

**Comment by scumpy0815** [comment]
[Font.zip](https://github.com/trevorsandy/lpub3d/files/3752255/Font.zip)

**Comment by trevorsandy** [comment]
Thank you. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Please take a look at the latest LPub3D release and let me know if this behaviour is still present.

Cheers,

**Comment by scumpy0815** [comment]
Will do. Downloaded it yesterday but I don't know when I find the time for
testing. Hopefully before next weekend.

Trevor SANDY ***@***.***> schrieb am Mo., 15. März 2021,
10:01:

**Comment by trevorsandy** [comment]
Excellent. 

Download again as I updated the release this morning without changing the version.

Cheers,

**Comment by scumpy0815** [comment]
Sorry for the late reply. I just tried it. No double text. Excellent.
Thanks a lot.

Just out of curiosity. What was the reason for that behaviour?

Regards

Ralf

Trevor SANDY ***@***.***> schrieb am Mo., 15. März 2021,
10:21:

**Comment by trevorsandy** [comment]
No worries.

> What was the reason for that behaviour?

I don't know but it appears to have been corrected after a Windows update

Cheers,
