### ISSUE TITLE
Annotations in PLI & BOM are displaced | Font size configuration does not work

### ISSUE THREAD

**Issue by swl2019** [trevorsandy/lpub3d#362]
### Subject
Using the annotation function for PLI and BOM does not show the expected results: The text is not placed in the center of the square or circle but below and changing the font size just moves the text down but does not scale it according to the selected font size.

### Environment
<img width="347" alt="LPub3D_Version_Info" src="https://user-images.githubusercontent.com/48833324/66825379-73260280-ef4a-11e9-9ea9-76b3c2c96e2e.PNG">

### Configuration
Windows 10 64bit
Out-of-the-box configuration with a folder containing customized parts *.dat files added to the LDraw search path
User path is with special character “ö” and “ä”, but LDraw path is without the non-ASCII characters.

### Logs
* Application Log: see attached ZIP
[BOM_PLI_Annotation_Issue.zip](https://github.com/trevorsandy/lpub3d/files/3728815/BOM_PLI_Annotation_Issue.zip)

### Screenshots
<img width="1229" alt="PLI_Annotation_Issue" src="https://user-images.githubusercontent.com/48833324/66825478-9fda1a00-ef4a-11e9-838e-bdf371ccd51a.PNG">
<img width="1229" alt="BOM_Annotation_Issue" src="https://user-images.githubusercontent.com/48833324/66825490-a49ece00-ef4a-11e9-9902-a074cf8ae873.PNG">
<img width="1229" alt="BOM_PLI_Annotation_FontSize_Issue" src="https://user-images.githubusercontent.com/48833324/66825502-a8325500-ef4a-11e9-8518-5ed51f5d1b73.PNG">

### Steps to reproduce
1)	Open *.LDR file in the attached ZIP and render the page  displaced text in circle and square in both PLI and BOM
2)	Change font size by marking the text (no matter if “7”or “6” in both cases the result is the same), opening the context menu and change font size to 48 or to any other size. 

### Expected behaviour
The “7” and the “6” should appear in the center of the square resp. circle in the PLI (rather than below of them) and BOM
Changing the font size changes the size of the text.

### Actual behavior
The “7” and the “6” are rendered below / outside of the square resp. circle in the PLI (rather than below of them)
Changing the font size DOES NOT change the size of the text BUT moves it according to the absolute font size number a bit more up or down.

### Workaround
I use the Free Form annotation

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

I've added a change to the PLI annotation behaviour at r56 - see last 2 commits to #229. Previously, LPub3D i.e. at r46, would automatically attempt to resize annotation text font to fit the specified style "fixed size" only if the text **width** exceeded the the specified fixed size width. This limit would cause the text to be malformed when the text font **height** exceeded the fixed height height. The change at r56 resizes the text font if either the fixed size width or height is exceeded by the font size.

You can access the latest build at [Continuous Build 1568 (r57)](https://github.com/trevorsandy/lpub3d/releases/tag/continuous).

If the behaviour you describe persists in r56, do not hesitate to add an update to this ticket.

Cheers,
