### ISSUE TITLE
LPub3D crashes when rendering multistep pages with LDView "multiple file single call"

### ISSUE THREAD

**Issue by jensbruehl** [trevorsandy/lpub3d#363]
### Subject
When LDView option "Use multiple file single call" is enabled, LPub3D crashes while rendering multistep pages.

### Environment
* Version of LPub3D: 2.3.13 r0
* Operating system: Windows 10 64bit 1903

### Steps to reproduce
Load this file in LPub3D:

0 FILE main.ldr
0 Name: Main
1 2 0 0 0 1 0 0 0 1 0 0 0 1 3865.dat
0 STEP
0 !LPUB MULTI_STEP BEGIN
1 4 0 -24 0 1 0 0 0 1 0 0 0 1 3001.dat
0 STEP
1 4 0 -48 0 1 0 0 0 1 0 0 0 1 3001.dat
0 STEP
1 4 0 -72 0 1 0 0 0 1 0 0 0 1 3001.dat
0 STEP
0 !LPUB MULTI_STEP END
0 NOFILE 

### Expected behaviour
Select LDView renderer, disable option "Use multiple file single call", goto page 2 => OK!

### Actual behaviour
Now enable LDView Renderer with option "Use multiple file single call" enabled, goto page 2 => Crash

### Workaround
Disable option "Use multiple file single call", but then performance will be slower.

**Comment by scumpy0815** [comment]
Same here with v2.3.13 r57

**Comment by trevorsandy** [comment]
Thank you  for reporting this behavior.

I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

![Screenshot - 21_10_2019 , 23_17_35](https://user-images.githubusercontent.com/13388970/67244220-8577d300-f459-11e9-87db-d570703fbfe2.png)

Cheers,
