### ISSUE TITLE
Image of submodel changes position in multisteps

### ISSUE THREAD

**Issue by scumpy0815** [trevorsandy/lpub3d#364]
### Subject
The image of the submodel is placed between the stepnumber and the pli. If I add a multistep, the position changes right of the pli. Nothing else is changed, only a step added.

### Environment
* Version of LPub3D v2.3.13 r57
* Operating system - Windows 10 x64, 1903

[wo_multi_steps.pdf](https://github.com/trevorsandy/lpub3d/files/3746536/wo_multi_steps.pdf)
[w_multi_steps.pdf](https://github.com/trevorsandy/lpub3d/files/3746539/w_multi_steps.pdf)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

The single step placement shown in the sample you provided seems to be the current design. I imagine the single step model file shows the PLI placement as _RightTopOutside_ of _SubModelType_.
 
The PLI default placement, _BottomLeftOutside_ of _SubModelType_ can be changed in Submodel Preview global setup. 

![Screenshot - 21_10_2019 , 20_18_51](https://user-images.githubusercontent.com/13388970/67232563-e7c4d980-f441-11e9-8f56-ec20d055ec25.png)

Cheers,
