### ISSUE TITLE
How to create an illustration in LPub3D

### ISSUE THREAD

**Issue by trevorsandy** [trevorsandy/lpub3d#366]
### Subject
Describe how to create an illustration in LPub3D.  
The following example present the steps to create a 1:1 illustration.
**Credit**: Jaco van der Molen

![Screenshot - 21_10_2019 , 17_26_22](https://user-images.githubusercontent.com/13388970/67219503-7298da80-f428-11e9-8aae-46b3de38e349.png)

### Environment
* Version of LPub3D - All
* Operating system - All

### Solution
1. Create an illustration submodel for the top view, _step_8_top.ldr_.
&nbsp;&nbsp;&nbsp;&nbsp;- The illustration submodel is in the model at exactly the same place as the original model. 
&nbsp;&nbsp;&nbsp;&nbsp;- The submodel parts can be all or a subset of the original model parts up to this point.
&nbsp;&nbsp;&nbsp;&nbsp;- The aim is to sufficiently reflect the model in the illustration.
2. Set the submodel **absolute rotation** step to show the model from the desired view point - e.g. top, left, right, front, back, bottom.
3. The submodel and all of its **parts are ignored** from the PLI.
4. Place the illustration submodel in a callout with or without pointer arrow.
5. Set the callout background and border to your preference.
6. Insert text as appropriate. The sample below shows 1:1 text.

```
0 !LPUB INSERT TEXT "1:1" "Arial,26,-1,5,75,0,0,0,0,0,Vet" "Black" OFFSET 0.605935 0.21978
1 72 60 0 -200 -1 0 0 0 0 1 0 1 0 6536.dat
1 72 -20 0 -100 -1 0 0 0 0 -1 0 -1 0 6536.dat
0 !LPUB CALLOUT BEGIN
1 16 -40 48 -100 1 0 0 0 1 0 0 0 1 step_8_top.ldr
0 !LPUB CALLOUT PLACEMENT TOP PAGE INSIDE
0 !LPUB CALLOUT BACKGROUND LOCAL COLOR "#ffffff"
0 !LPUB CALLOUT BORDER LOCAL ROUND 1 #ff0000 0.0312497 15 MARGINS 0.0499996 0.0499996
0 !LPUB CALLOUT END
0 STEP
...
0 FILE step_8_top.ldr
0 Submodel for topview step 8
0 Name: step_8_top.ldr
0 Author: Jaco van der Molen [Jaco van der Molen]
0 !LICENSE Free for non-commercial use.
0 ROTSTEP 89 90 0 ABS
0 !LPUB PLI BEGIN IGN
1 72 20 -48 0 -1 0 0 0 0 -1 0 -1 0 6536.dat
1 71 55 -48 40 0 1 0 -1 0 0 0 0 1 11478.dat
1 71 65 -48 40 0 1 0 -1 0 0 0 0 1 11478.dat
1 0 40 -48 -40 0 -1 0 1 0 0 0 0 1 40490.dat
1 1 60 -48 -120 1 0 0 0 1 0 0 0 1 6558.dat
1 1 60 -48 40 1 0 0 0 1 0 0 0 1 6558.dat
1 0 55 -48 -140 0 1 0 -1 0 0 0 0 1 11478.dat
1 0 65 -48 -140 0 1 0 -1 0 0 0 0 1 11478.dat
1 0 80 -48 -40 0 -1 0 1 0 0 0 0 1 40490.dat
1 4 50 -48 0 -1 0 0 0 1 0 0 0 -1 3706.dat
1 72 100 -48 0 1 0 0 0 0 1 0 -1 0 6536.dat
1 4 70 -48 -100 1 0 0 0 1 0 0 0 1 3706.dat
1 72 20 -48 -100 -1 0 0 0 0 1 0 1 0 6536.dat
1 72 100 -48 -100 -1 0 0 0 0 1 0 1 0 6536.dat
0 !LPUB PLI END
0 NOFILE 
```

Cheers,

**Comment by 6638** [comment]
Hello, Trevor.

Great feature and very useful instruction.

> 3. The illustration submodel and all of its parts are set to be ignored from the PLI.

This statement sounds like submodel parts are ignored from the PLI automatically. But then there is "PLI BEGIN IGN" meta in the example. Would be better to rephrase the statement in imperative mood:

> 3. Set to ignore all parts of the illustration submodel from the PLI .

Also, there are few issues with this solution:
a) You need to define illustration submodel separately. If the constructed model is complex, it may become complicated.
b) It becomes even more complicated, due to absence of a crop capability. If there are big elements, like wheels, they will need to be displayed completely.
c) The doubled model definition is prone to errors, when the constructed model changes. If the change comes into view of the illustration, one has to ensure that the illustration submodel is also updated.

I could think of an alternative solution. LPud3D could introduce an anchor meta, similar to "MLCAD BTG", and then call out of the anchored state, similar to "REMOVE GROUP". I.e. you place the anchor meta at a step, where you have the desired model state, and then you add illustration callout through referencing the anchored state of the model. When paired with the planned 3D camera manipulation (mentioned in #337), it will resolve all issues with the implemented solution.

Does it feel reasonable and feasible?

Cheers!

**Comment by trevorsandy** [comment]
Hi 6638,

> Great feature and very useful instruction.

No development has been done recently to enable the steps captured in this ticket. The fully automated capability for illustrations is in the queue for the next major release. The steps above simply allow users to progress until then. 

> b) It becomes even more complicated, due to absence of a crop capability. If there are big elements, like wheels, they will need to be displayed completely.

The user should take care to define appropriately sized submodels to best reflect the illustration. However, the automatic capability will include the ability to set width, height and illustration shape - circle, quad etc...

> c) The doubled model definition is prone to errors, when the constructed model changes. If the change comes into view of the illustration, one has to ensure that the illustration submodel is also updated.

Indeed, this condition will be treated in the automated capability. The illustration assembly will be dynamically created during page display parse.

> I could think of an alternative solution...

Thank you for your suggestion. My design, so far, includes a primary and optional creation meta command. The primary command will look something like `ILLUSTRATION <type>, <viewpoint>, [<scale>, <sizeX>, <sizeY>, <shape>]`. The optional command will look like `ILLUSTRATION BEGIN`. `[]` denotes optional parameters.

Both commands take into account the model and line number at which they are instantiated. The primary command will trigger routines that gather up the "illustration assembly" parts going back to the start of the current submodel if an optional ILLUSTRATION BEGIN command for said submodel is not specified. The last optional ILLUSTRATION BEGIN command before the primary ILLUSTRATION command is used and is "reset" after it is used. The type of illustration, its scale, size and viewpoint settings are applied the the image render settings. The submodel date-time stamp is checked against the rendered image to optimize the need to re-render the illustration when the submodel file changes.

Cheers,

**Comment by 6638** [comment]
Hello, Trevor.

Thanks for sharing your plans. Your solution is good and sufficient. Moreover, the two solutions (the one in the first post and the planned one) don't seem redundant anymore, but compliment each other very well. The solution in the first post may be very convenient for illustrations like this:
<img width="141" alt="Wheel" src="https://user-images.githubusercontent.com/49516540/67638657-547b2080-f8e7-11e9-9ef2-f4362c37aa8c.png">

Cheers.
