### ISSUE TITLE
Enhancement: IDML Export

### ISSUE THREAD

**Issue by TrueMylenium** [trevorsandy/lpub3d#367]
I figured I would open up a request to Export to IDML because LPub still frustrates the heck out of me even with a few months inbetween not touching it. If this became a reality, all I would need LPub for would be to generate a rough page and the rendered images with transparency placed in the respective boxes and could do all the rest in InDesign, QuarkXPress and other programs, in particular texts, callout arrows and the other fancies. That and of course I'd save a ton of work on workarounds like duplicating invisible model instances and buffer exchange mumbo-jumbo. Who needs that when you just can duplicate a page in ID, if you get my meaning? Am I dreaming and hoping too much? Has this thought in fact ever even occurred to anyone before?

**Comment by trevorsandy** [comment]
Thank you for your request. I'll take a look.

I don't know much about IDML so if you know of a good documentation/data model resource, it would be quite helpful.

Cheers,

**Comment by TrueMylenium** [comment]
The full specs can easily be found on Adobe's website:

https://wwwimages.adobe.com/content/dam/acom/en/devnet/indesign/sdk/cs6/idml/idml-specification.pdf

The basic goals for a v. 0.1 where LPub is concerned for me are:

- Render all images on a page with transparent background based on the layout, size etc. defined in the LPub file, including assemblies, callout images, PLI and BOM images.
- Export all images for all pages to a sub-folder with a sensible naming convention, e.g. Page_25_PLI_Image_3.tif
- Export LPub document with the necessary image box objects as IDML, respecting any sizing and margins defined in LPub already (if any) and the link info pointing to the exported images, naturally.

Of course in the long run it would be nice if this could be as feature-complete as it can and could/ should include any element like text objects and their content's strings as well, lines/ pointers and so on. However, it would not be necessary to actually fully translate and re-create the visual appearance. This stuff can be done relatively easily in ID, so you don't necessarily need to wreck your brain on how to translate e.g. rounded corners of a box. It would just be crucial that in order to facilitate workflows every object has a consistent "style" (in ID terms) and possibly additional "tags" (per-object metadata) to select and change these things globally/ en mass via the respective palettes and master pages in ID. The actual style definitions could likely even be void or just use some common default values.

**Comment by trevorsandy** [comment]
Thank you for the additional information. 

It looks like writing an Adobe InDesign IDML format export engine will not be trivial. However, I like to idea of exporting LPub3D content to a well-supported desktop publishing document representation format. 

I believe it would be better to implement the [XPS](https://en.wikipedia.org/wiki/Open_XML_Paper_Specification) open specification for page description export.

The free open-source desktop publishing (DTP) application [Scribus](scribus.net) can directly import XPS, and IDML if you are already working with InDesign. For those tied to Adobe's InDesign, the XPS format can be trivially converted to a Microsoft Word document whose pages can be manually placed in InDesign. There is also [PDF2ID](https://www.recosoft.com/products/pdf2id/) which converts XPS, PDF, and Adobe Illustrator files into fully editable InDesign (INDD) files. 

Cheers,

**Comment by TrueMylenium** [comment]
Nope. Sorry, this reasoning makes no sense whatsoever. Nobody is using XPS in professional publishing. That's wishful thinking on Microsoft's part and the only reason they are pushing the format is of course their drive to dominate markets, at which in this case they have failed.  Or have you ever actually heard of professional marketing materials, catalogs, magazines, newspapers and so on being done with MS Publisher? I haven't and I like to believe that due to having worked with several companies producing printing equipment (as in actual printing machines big like a truck) I have some insight into this and their clients' workflows. Never in my time have I ever seen anyone run anything other than QuarkXPress, ID and a slew of PDF tools.  Mixing up Office and genuine layout apps is not useful to anyone, also. Importing Word docs into ID has its own caveats and limitations. Similarly, converting a PDF back to an editable file has its limitations as you should well know. So with all due respect and apologies for the rant, XPS export would be pretty much useless in my world and you'd be wasting your time even writing the code.

**Comment by trevorsandy** [comment]
Indeed, it's disappointing that, considering that one must pay for their applications, Adobe does not have a reasonable path to import and make editable their own "portable" document format into their DTP application. Clearly it is not impossible as Recosoft offers their PDF2ID plugin that does exactly that.

Anyway, as I am keen to enable a DTP export format, unless something prohibitive presents, I will target OpenXPS with the understanding that it is supported by Scribus, a best-of-breed Open Source DTP application. Ecma International approved Open XML Paper Specification (OpenXPS) as an Ecma standard (ECMA-388) back in 2009. I don't hold any childish reservations about MS domination or whatever, if the format exports the limited scope content of LPub3D documents in a good enough manner and is open, I will use it.

Cheers,

**Comment by TrueMylenium** [comment]
Fair enough, though at the end of the day it perhaps resolves nothing, at least not the way I would envision my workflows.
