### ISSUE TITLE
Issue: Font info is not language-independent

### ISSUE THREAD

**Issue by TrueMylenium** [trevorsandy/lpub3d#369]
Let's assume one were to exchange LPub files with others and their system language settings are different. What happens? Any font definition that references a font weight not named generically in English will break down because of course a German "Fett" is different from "Bold". Sure, it's a minor issue, but could it be made so that in the future the internal font name is stored instead of the localized UI name?

**Comment by trevorsandy** [comment]
This is a good question. Thank you. 

I couldn't find source that either describes Qt's "internal" font names or any Qt font setting routine that take said as an input. So as of current, I imagine "find and replace" is your friend.

Cheers,

**Comment by TrueMylenium** [comment]
This perhaps?

https://doc.qt.io/qt-5/qfontdatabase.html

It at least seems to have options to query whether a font actually has bold and italic, assuming it actually has a consistent font family and since it's inside Qt, it should be language- and platform-agnostic. In turn to me this means that if these font styles were expressed with a meta command instead of referencing the actual font weight UI string, it might work across different languages without any special extra steps.
