### ISSUE TITLE
Issue: Some callout pointers do not render correctly if...

### ISSUE THREAD

**Issue by TrueMylenium** [trevorsandy/lpub3d#371]
Some callout pointers do not render correctly when jumping directly to a page from the top menu. Specifically the issue appears to be related to the cache state of the sub-models and oddly enough only affects single-segment pointers. Seems to me the program really insists on linearly progressing forward through steps, which could also indicate an issue with the parse tree. I can fix it by going back to the previous page and then forward again, but it's still confusing and a bit annoying.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

I am not able to reproduce this behaviour but that is not to say it is not valid. Perhaps I do not appreciate some nuances around the number of pages you are jumping over or the configuration of the pointer(s).

Do not hesitate to add any additional detail, including a sample model file, that would make the described behaviour more reproducible.

Cheers,
