### ISSUE TITLE
Issue: Inadequate transparency flattening for PDF output

### ISSUE THREAD

**Issue by TrueMylenium** [trevorsandy/lpub3d#372]
Transparency flattening on pixel images for PDF output is not handled all that well - talking about the dreaded black fringes here, naturally. It seems that LPub is not using the actual page background at all but rather sticks to an abstract default black background/ fill. I'm working with 24 bit PNGs, so there should be no issues whatsoever, given that it has antialiased transparency. Of course I can work around this for the time being by adding just that bit of extra color, but regardless, it seems strange that the program would allow to use transparencies not blended against a specific color and then can't handle this correctly on PDF generation. If this is file format specific, please advise which formats might work. I'll be experimenting a bit myself as well. On that note, is there a way to actually control PDF output like e.g. with the .joboptions files in Acrobat and other professional  PDF tools?

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

Indeed, the Qt PDFWriter module is not the most robust and feature rich. I could spend money to licence a paid PDF writer module, it's actually suggested by Qt, but this approach would likely break my Open Source licence. If you know of any C++ open sourced writer that offers more functionality than the Qt module, I'll be pleased to take a look.

> On that note, is there a way to actually control PDF output like e.g. with the .joboptions files in Acrobat and other professional PDF tools? 

Not to my knowledge. Here are the [public functions of the Qt PDFWriter](https://doc.qt.io/qt-5/qpdfwriter.html).

Cheers,

**Comment by TrueMylenium** [comment]
Ah, okay. I was under the impression that there would be something else at work.
