### ISSUE TITLE
LPub Crashing when substituting a submodell that was threaded as part

### ISSUE THREAD

**Issue by technicbasics** [trevorsandy/lpub3d#377]
### Subject
LPub Crashing when substituting a submodell that was threaded as part in the part list.

### Environment
2.3.13r64
also in all 2.3.12 versions
W10 - 64bit

### Workaround
Enter the Syntax directly in the file

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

Unfortunately, I am no able to reproduce it. See below the steps I have executed. For me the behaviour is as expected. Can you provide any additional details and perhaps an example model file that produces the unexpected behaviour on your installation ? It would also be helpful to have the LPub3D log and, if possible, an archived bundle of the LPub3D working folder.

![Screenshot - 31_10_2019 , 13_15_47](https://user-images.githubusercontent.com/13388970/67946922-b5a23d00-fbe2-11e9-8ee7-3e3f83f2c067.png)

![Screenshot - 31_10_2019 , 13_16_01](https://user-images.githubusercontent.com/13388970/67946923-b5a23d00-fbe2-11e9-8cf1-dbeac9de848a.png)

![Screenshot - 31_10_2019 , 13_16_33](https://user-images.githubusercontent.com/13388970/67946924-b5a23d00-fbe2-11e9-8dcd-115e66fb762e.png)

![Screenshot - 31_10_2019 , 13_16_54](https://user-images.githubusercontent.com/13388970/67946925-b63ad380-fbe2-11e9-8f73-e7f55ef1f897.png)

![Screenshot - 31_10_2019 , 13_20_53](https://user-images.githubusercontent.com/13388970/67946926-b63ad380-fbe2-11e9-9a0c-c3bea0ac1119.png)

Manually add the desired part colour - 15
![Screenshot - 31_10_2019 , 13_26_30](https://user-images.githubusercontent.com/13388970/67946927-b63ad380-fbe2-11e9-9c9b-e9724c7e5187.png)

Cheers,

**Comment by technicbasics** [comment]
Hi Trevor
I only got this error reported from a friend in the ldraw forum. It does not always seem to happen. I've also tried to reproduce the bug with ten different variants and have not been able to it. Thank you for your efforts.
Johann

**Comment by trevorsandy** [comment]
Hi Johann,

With pleasure.

Cheers,

**Comment by trevorsandy** [comment]
Although I could not reproduce the behaviour described. I did discover and correct the exception where when no substitute flags are specified (e.g. colour, scale, etc...), the substitute command is ignored. This behaviour is only present when the substitute command is manually entered.

Cheers,
