### ISSUE TITLE
Picture on front page cover no longer transparent

### ISSUE THREAD

**Issue by technicbasics** [trevorsandy/lpub3d#379]
### Subject
As of version 2.3.13, the image on the front page cover is no longer transparent.
The underlying text is no longer visible.

### Environment
2.3.13 all versions

Version 2.3.12r112 and lower
![2 3 12](https://user-images.githubusercontent.com/49073781/68143333-887ec300-ff31-11e9-8365-8221c0cd2f08.PNG)

2.3.13rxx
![2 3 13](https://user-images.githubusercontent.com/49073781/68143356-97657580-ff31-11e9-9b58-023a9e1e0b12.PNG)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

Actually, it is not the picture item that is transparent but the background of the underlying text item. 

Indeed, "Bring-to-front and send-to-back" behaviour was added in v2.3.13 - see #244 for details. As part of this capability, the "depth" of a page's items have been rearranged. For the cover page both text and image items are at a depth value of 0. This means that the item placed last will be on top. As the picture is placed after the text, either by the user or programmatically, and is opaque, the behaviour is as you have shown in the illustrations. If you would like to place the picture under the text, simply click the "Send-to-Back" menu item and it will be placed behind any overlapping page items.

Cheers,

**Comment by technicbasics** [comment]
Hi Trevor
Thanks for the answer.
I only have the problem, as soon as I click on the icon "Bring to front" or "Bring to back", no matter with which model, the program crashes.
No matter what I want to move. (Pictures, callouts, ...)

**Comment by trevorsandy** [comment]
Hello Johan - I took a look and I have apparently broken something.

This behaviour will be fixed shortly.

Cheers,

**Comment by trevorsandy** [comment]
AbEnd when using the BringToFront/SendToBack menu items on a cover page has been corrected.

I also refactored the overall code base supporting this behaviour. Text items on the front and back cover pages are now, by default, placed at a Z depth above images. 

Cheers,
