### ISSUE TITLE
Faded part not displaying using LDView as renderer

### ISSUE THREAD

**Issue by d-j-m-0** [trevorsandy/lpub3d#38]
### Subject of the issue
Instructions generated by LPub3D version 2.2 using LDView as the renderer are not including the image for the PF Medium motor when it should be displayed as a faded part. This works correctly using LPub3D version 2.0. Refer to the attached zip file, which contains the LDR file and PDF generated by LPub3D version 2.0.

[fade_test.zip](https://github.com/trevorsandy/lpub3d/files/1831841/fade_test.zip)

### Your environment
* Version of LPub3D -2.2
* Operating system - Windows 7, 32 bit

### Configuration
[Note: Provide details and content below as needed with appropriate redactions]
* LPub3D installation path
  - Windows: `D:\Program Files\LPub3D`
* Application data path 
  - Windows: `%USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\`

### Steps to reproduce
**LPub3D version 2.0**
Ran LPub3D 2.2
Opened LDR file.
Cleared all cache.
Navigated to second page of instructions.
Faded PF motor shown correctly
Generate PDF instructions.
Corresponding LPub3D log file: 
[LPub3DLog_2_0_20.txt](https://github.com/trevorsandy/lpub3d/files/1831845/LPub3DLog_2_0_20.txt)

**LPub3D version 2.2**
Uninstalled LPub3D version 2.0
Installed LPub3D version 2.2
Ran LPub3D 2.2
Opened LDR file.
Cleared all cache.
Navigated to second page of instructions.
Faded PF motor not shown:
![no_fade_motor_2_2_780](https://user-images.githubusercontent.com/37604323/37691875-d0fbfaee-2d19-11e8-94d0-475b9218a46e.png)
Corresponding LPub3D log file:
[LPub3DLog_2_2_780_no_fade.txt](https://github.com/trevorsandy/lpub3d/files/1831847/LPub3DLog_2_2_780_no_fade.txt)

### Expected behaviour
PF Mediium motor image should appear as a faded part.

### Actual behaviour
No image generated for PF Medium motor

### Workaround
None known.

### Solution suggestion
No suggestion.

**Comment by trevorsandy** [comment]
This behaviour is reproducible. Taking a look...

**Comment by trevorsandy** [comment]
This behaviour has been corrected. Here is a summary of the cause, work around and resolution:
 
**Cause:** LPub3D writes incorrectly formatted Windows paths to the LDView .ini files.
**Cause:** LDView writes-back incorrectly formatted Windows paths to the LDView ini files.
**Unexpected behaviour:** LDView would not find a 'faded' part submitted by LPub3D. More specifically, LDView will not find parts where it cannot resolve the parts' file path.

The way this is supposed to work is as follows:

- LPub3D uses 2 LDView.ini files ldview.ini and ldviewPOV.ini. ldview.ini is used to generate images rendered by LDView and ldviewPOV.ini is used to generate the .pov files for LPub3D-Trace (POV-Ray).
- Parts from the previous step are faded by copying and appending the step's CSI entries to a 'fade file' folder.
- The CSI entries are updated with the appropriately appended 'fade names' (e.g. 58120.dat -> 58120-fade.dat).
- Colour codes in the fade file are updated to the fade color defined in preferencess
- On application startup, at preferences change and at detection of fade option ON, the ldview.ini file's `[ExtraSearchDirs]` section is updated with paths to the fade folder (the fade folder structure mimics the LDraw folder structure with 'parts', 'p' and so on...)
- LDView consumes the extra search directory paths from the .ini file a resolves the faded parts

_LPub3D writes incorrectly formatted Windows paths to the LDView .ini files:_
Version 2.1.0 and 2.2.0 creates LDView.ini files at application startup if they do not already exist. If they exist, extra search directories defined in LPub3D are written the ini files if no search directories are present. The proper LDView Windows file path written to the `[ExtraSearchDirs]` section of the ini file should be `Dir007=C:\\Users\\Trevor\\AppData\\Local\LPub3D Software Maint\\LPub3D\\fade\\parts`. In the current version LPub3D this path is incorrectly written like this `C:\Users\Trevor\AppData\Local\LPub3D Software Maint\LPub3D\fade\parts`. The missing 'Dir007=' key violates the ini file format and ensures LDView will not be able to find this value. While single-backslash separators for Windows' paths are not incorrect, using them also created unexpected behaviour in LDView as described in the next paragraph.

_LDView writes-back incorrectly formatted Windows paths to the LDView ini files:_
When I write, or if the .ini template contains a Windows directory path using single-backslash separators e.g. `Dir007=C:\Users\Trevor\AppData\Local\LPub3D Software Maint\LPub3D\fade\parts`, LDView reads the path and writes back a bad path with double backslashes where one, or more, occurrences of the separators will have only one backslash. For example, a written-back path would look like this: `Dir007=C:\\Users\\Trevor\\AppData\\Local\\LPub3D Software Maint\\LPub3D\fade\\parts` [Notice the single slash after 'LPub3D].

As you can imagine, LDView fails to resolve the bad path and returns an error message for the related part. As no image is generated, the page display is as presented.

If the .ini template contains or I write the Windows path separator with double backslashes, then a correctly formatted path is written back, LDView happily finds the fade file produces the related image.

**RESOLUTION**
I have updated LPub3D to write well formatted, (always using double slashes for Windows paths) LDView .ini files.

**WORK AROUND**
While the update will be available in v2.1.1 shortly, existing releases (2.1.0, 2.2.0) allows you to edit all configuration files from the GUI as shown below. For Windows installs, you can manually update the paths as described above. Once valid paths are added both LDView and LPub3D will behave as expected.

![screenshot - 24_03_2018 04_20_24](https://user-images.githubusercontent.com/13388970/37859851-bcff55ce-2f1a-11e8-93bf-a9c0c449f5d4.png)

![screenshot - 24_03_2018 04_22_57](https://user-images.githubusercontent.com/13388970/37859862-0f76375a-2f1b-11e8-9e51-8a8e45d3f8ac.png)

Cheers,

**Comment by d-j-m-0** [comment]
Thank you for the heads up. I will retry this once v2.2.1 is released.

Regards,

David

**Comment by ReneFrijhoff** [comment]
Unfortunately the workaround doesn't work.
