### ISSUE TITLE
PNG Export - transparent background exports as black background.

### ISSUE THREAD

**Issue by trdoolan** [trevorsandy/lpub3d#380]
### Subject
After upgrading from v2.3.6 to 2.3.13r72, JPG/PNG export using LDView as the renderer produces images with a solid black background when "none (transparent)" is selected in configuration.

Also, LPub3D loses all it's application menus after such an export, requiring a restart of the application.

### Environment
* Version of LPub3D - see Help->About LPub3D
v2.3.13r
* Operating system - OS Name, Processor Architecture (x86,x86_64)
MacOSX Sierra 10.12.6, Macbook Pro 15" Mid2012, 16Gb RAM, Intel Core i7 2.3GHz, nVidia GeForce GT650M

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  - macOS: `/Applications/LPub3D.app`
* Application data path
  - macOS: `~/Library/Application Support/LPub3D Software/LPub3D/`
 * Registry Extract

  - macOS: ` ~/Library/Preferences/com.lpub3d-software.LPub3D.plist`

* Renderer configuration files
  - `[Application data path]/ldv/ldvExport.ini`
  - `[Application data path]/3rdParty/ldglite-1.3/config/ldglite.ini`
  - `[Application data path]/3rdParty/ldview-4.3/config/ldview.ini`
  - `[Application data path]/3rdParty/ldview-4.3/config/ldviewPOV.ini`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.conf`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.ini`

### Logs
* Application Log: `[Application data path]/logs/LPub3DLog.txt`
* Renderer Log: `[LDraw model path]/stdout-ldglite`
* Renderer Log: `[LDraw model path]/stdout-povray`
* Renderer Log: `[LDraw model path]/stderr-ldglite`
* Renderer Log: `[LDraw model path]/stderr-povray`

### Screenshots
* Configuration->Preferences->General
* Configuration->Preferences->Rendering
* Configuration->Preferences->Publishing
* Configuration->Preferences->Logging
* Configuration->Preferences->Other
Included in ZIP
[Lpub Support Files.zip](https://github.com/trevorsandy/lpub3d/files/3827008/Lpub.Support.Files.zip)

### Steps to reproduce
Tell me how to reproduce this issue.
Provide a sample mpd/ldr file that reproduces the problem.

LDR file included in ZIP file uploaded/attached.
Normal output procedure for PNG image files. Same occurs for JPG export

### Expected behaviour
Files output should have transparent backgrounds

### Actual behaviour
Files are being produced with a black background.

### Workaround
None so far.

### Solution suggestion
The setting within LPub3D normally works, but after upgrading to 2.3.13, it's no longer processing transparent settings. Normal colours set as solid background work as expected.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

Transparent PNG exports are now restored.

Cheers,
