### ISSUE TITLE
LPUB3D crops the assembly image at the edge of the page

### ISSUE THREAD

**Issue by 1963maniac** [trevorsandy/lpub3d#386]
### Subject
On large models that don't fit the page; moving the active part of the image, LPUB3D does not redraw it, it remains cut off.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

Functionality to set the 'lookat' target is being implemented in the next release.

Cheers,

**Comment by trevorsandy** [comment]
Implemented. See #412.

Cheers,

**Comment by 1963maniac** [comment]
Thank you for this emailed information. Thank you!  Thank you!  Thank you!
for LPUB3D!!! Kay Kampf, 1963maniac

**Comment by trevorsandy** [comment]
> Thank you! for LPUB3D!!!

With pleasure. 

Cheers,
