### ISSUE TITLE
Changing assembly scale does not work correctly anymore

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#389]
Using the newest official release LPub3D 2.3.13.

Changing the assembly scale of a step doesn't work correctly anymore. Pressing right-mouse on an assembly image and changing the scale results in the wrong meta command being inserted into the file.

If I change the scale local, it inserts this
`LOCAL 0.9000`
instead of this
`0 !LPUB ASSEM MODEL_SCALE LOCAL  0.9000`

And if I change the scale globally, it inserts this (which also results in a parsing error)
`0.9000`
instead of this
`0 !LPUB ASSEM MODEL_SCALE 0.9000`

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. Unfortunately, I cannot reproduce it. I've tried both the latest release build (see screenshots) and on my maintenance build. Both instances produce the expected behaviour using this model file example:

```
0 FILE main.ldr
0 Untitled Model
0 Name:  Lego_-_Overwatch_-_Wrecking_Ball_grapple_hook
0 Author:  LPub3D
0 !LPUB ASSEM MODEL_SCALE GLOBAL  0.9000
0 !LPUB ROTATE_ICON PLACEMENT LOCAL RIGHT CENTER ASSEM OUTSIDE OFFSET -2.12353 0.02976
0 !LPUB INSERT ROTATE_ICON
0 !LPUB SUBMODEL_DISPLAY SHOW GLOBAL TRUE
0 !LPUB INSERT COVER_PAGE FRONT
0 STEP
0 !LPUB ASSEM MODEL_SCALE LOCAL  0.8000
1 9 0 48 120 1 0 0 0 1 0 0 0 1 11272.dat
0 STEP
1 4 0 48 50 1 0 0 0 1 0 0 0 1 11272.dat
0 STEP
1 4 0 48 0 1 0 0 0 0 -1 0 1 0 submodel-1.ldr
0 STEP
1 5 0 48 160 1 0 0 0 1 0 0 0 1 11272.dat
0 STEP
0 !LPUB INSERT COVER_PAGE BACK
0 NOFILE 
0 FILE submodel-1.ldr
0 Author: Simone Bissi
0 !LPUB SUBMODEL_DISPLAY PART MARGINS LOCAL 1.48000 0.0300
0 !LPUB PLI CONSTRAIN LOCAL HEIGHT 1.12
0 !LPUB MULTI_STEP PLI PER_STEP FALSE
0 !LPUB MULTI_STEP BEGIN
1 0 0 -4 0 0 0 1 0 -1 0 1 0 0 75937.dat
0 STEP
1 72 18.509 -26.5 -21.163 -0.707 0.707 0 0 0 -1 -0.707 -0.707 0 61252.dat
1 72 -19.2749 -26.5 -20.3966 -0.707107 -0.707107 0 0 0 -1.000001 0.707107 -0.707107 0 61252.dat
1 72 -0.11 -26.5 28 1 0 0 0 0 -1 0 1 0 61252.dat
1 179 -0.11 -26.5 28 1 0 0 0 0 -1 0 1 0 54200.dat
0 STEP
1 179 18.509 -26.5 -21.163 -0.707 0.707 0 0 0 -1 -0.707 -0.707 0 54200.dat
1 179 -19.2749 -26.5 -20.3966 -0.707107 -0.707107 0 0 0 -1.000001 0.707107 -0.707107 0 54200.dat
0 STEP
0 !LPUB MULTI_STEP DIVIDER
1 14 0 15.22 0 0 0 -1 -1 0 0 0 1 0 6587.dat
0 STEP
0 !LPUB INSERT ROTATE_ICON
1 322 -0.0002 -22.78 0.0046 0 0 1 0 1 0 -1 0 0 18674.dat
0 STEP
0 !LPUB MULTI_STEP END
0 NOFILE
``` 

![Screenshot - 04_01_2020 , 14_08_16](https://user-images.githubusercontent.com/13388970/71766073-4e637a80-2efc-11ea-81cd-8dfe3111dc55.png)

![Screenshot - 04_01_2020 , 14_09_10](https://user-images.githubusercontent.com/13388970/71766074-4e637a80-2efc-11ea-978e-c5c758c31ed3.png)

Cheers,

**Comment by Landcross** [comment]
Sorry for the late reply. But using your example model, for me it still does not work.

Unmodified file:
![image](https://user-images.githubusercontent.com/12005521/72981532-47ce7180-3ddd-11ea-9ac4-8f223e8622ad.png)

Changing the scale as follows:
![image](https://user-images.githubusercontent.com/12005521/72981558-59b01480-3ddd-11ea-93e8-b310574e4341.png)

Results in this error message:
![image](https://user-images.githubusercontent.com/12005521/72981595-72b8c580-3ddd-11ea-9ba3-56b084f98afd.png)

Which shows up because it produced this meta command:
![image](https://user-images.githubusercontent.com/12005521/72981614-7f3d1e00-3ddd-11ea-8eaa-a58812f74dba.png)

**Comment by trevorsandy** [comment]
Can you post a screenshot of the 'About LPub3D' dialogue window ?

Cheers,

**Comment by Landcross** [comment]
Here you go :)

![image](https://user-images.githubusercontent.com/12005521/73141858-ddd9f480-4088-11ea-91e2-21775374664f.png)

**Comment by trevorsandy** [comment]
Thank you. 

There’s been 113 revisions (updates) since the official v2.3.13 release. 

You can download the latest “continuous” build [here](https://github.com/trevorsandy/lpub3d/releases/tag/continuous).

Cheers,

**Comment by trevorsandy** [comment]
If you continue to experience this behaviour with the latest LPub3D release, do not hesitate to reopen this ticket.

Cheers,
