### ISSUE TITLE
LPub3D inserting extra INSERT MODEL/INSERT PAGE

### ISSUE THREAD

**Issue by d-j-m-0** [trevorsandy/lpub3d#39]
LPub3D version 2.2 is inserting extra LPUB instructions in spite of the instructions already being present in the LDR. This does not happen in LPub3D version 2.0.

### Your environment
* Version of LPub3D - 2.2
* Operating system - Windows 7, 32 but

### Configuration
* LPub3D installation path
  - Windows: `D:\Program Files\LPub3D`
* Application data path 
  - Windows: `%USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\`

### Steps to reproduce
Extract motor_pin.ldr in the attached zip file.
[fade_test.zip](https://github.com/trevorsandy/lpub3d/files/1831856/fade_test.zip)
Open the extracted file motor_pin.ldr with notepad (or equivalent text editor). Note the existence of the LPUB INSERT MODEL and LPUB INSERT PAGE commands.
Run LPub3D version 2.2
Open the extracted file motor_pin.ldr.
Look at the LDR displayed within LPub3D. It has inserted additional LPUB commands.

### Expected behaviour
The extra commands should not be inserted.

### Actual behaviour
They are inserted.
Refer to attached screenshot:
![extra_insert_2_2_780](https://user-images.githubusercontent.com/37604323/37692081-51897032-2d1b-11e8-9da8-03663e5e9728.png)

### Workaround
None.

### Solution suggestion
Unknown.

**Comment by trevorsandy** [comment]
I cannot reproduce this issue.

**PREFERENCES CONFIGURATION**
- Fade Step = ON
- Renderer = LDView | LDGLite
- Use multiple files single call rendering = OFF

I followed the steps you outlined and everytime, I get the same behaviour - only 1 set of INSERT MODEL meta commands are inserted. 

If I delete the meta commands and open the file only 1 set of INSERT MODEL meta commands are inserted.

With the file open, if I change the preferences to set Fade Step = OFF, the INSERT MODEL meta commands are removed as expected. If I reset Fade Step = ON, 1 set of INSERT MODEL meta commands are written as expected.

Cheers,
