### ISSUE TITLE
Broken items layout on dialogs tabs if window size changed

### ISSUE THREAD

**Issue by Symbian9** [trevorsandy/lpub3d#390]
### Environment

- Version of LPub3D: `LPub3D-2.3.13.113.1624_20200104-x86_64.AppImage`
- Operating system - Debian 9.x (x86_64)

### Configuration

* LPub3D installation path
  - AppImage (Linux): `/tmp/.mount_LPub3D<UniqueID>/usr/share/lpub3d`
* Application data path
  - AppImage (Linux): `~/.local/share/LPub3D Software/<AppImage File Name>/`
* Registry Extract
  - AppImage (Linux): `~/.config/LPub3D Software/<AppImage File Name>.conf`

<details>

```
[Defaults]
Author=
BackgroundColor=-1
DisplayAllAttributes=false
DoNotShowPageProcessDlg=false
Email=
GenerateCoverPages=false
IgnoreMixedPageSizesMsg=false
PdfPageImage=false
PrintDocumentTOC=false
PublishDescription=
URL=

[Logging]
AllLogLevels=false
DebugLevel=false
ErrorLevel=false
FatalLevel=false
IncludeAllLogAttributes=false
IncludeFileName=false
IncludeFunction=true
IncludeLineNumber=true
IncludeLogLevel=true
IncludeTimestamp=false
InfoLevel=false
LogLevel=true
LogLevels=false
Logging=true
LoggingLevel=STATUS
NoticeLevel=false
StatusLevel=false
TraceLevel=false

[POVRay]
POVRayPath=/var/tmp/.mount_LPub3DKJnScW/opt/lpub3d/3rdParty/lpub3d_trace_cui-3.8/bin/lpub3d_trace_cui

[Settings]
AASamples=8
AddLSynthSearchDir=false
ApplyCALocally=true
ArchiveLSynthParts=false
CameraDistFactorNative=-260
Centimeters=false
CheckUpdates=0
CustomSceneBackgroundColor=false
CustomSceneGridColor=false
CustomSceneGuideColor=false
CustomSceneRulerTickColor=false
CustomSceneRulerTrackingColor=false
DisplayTheme=Default
DrawAxes=1
EnableFadeSteps=false
EnableHighlightStep=false
EnableImageMatting=false
EnableLDViewSingleCall=false
EnableLDViewSnapshotsList=false
ExcludedPartsFile=/home/mint/.local/share/LPub3D Software/LPub3D-2.3.13.113.1624_20200104-x86_64.AppImage/extras/excludedParts.lst
ExtendedSubfileSearch=false
FadeStepsOpacity=50
FadeStepsUseColour=false
FreeFormAnnotationsFile=/home/mint/.local/share/LPub3D Software/LPub3D-2.3.13.113.1624_20200104-x86_64.AppImage/extras/freeformAnnotations.lst
GridLines=0
GridSizeIndex=1
GridStuds=0
HidePageBackground=false
HighlightFirstStep=false
HighlightStepColor=#FFFF00
HighlightStepLineWidth=1
LDrawColourPartsFile=/home/mint/.local/share/LPub3D Software/LPub3D-2.3.13.113.1624_20200104-x86_64.AppImage/extras/fadeStepColorParts.lst
LDrawLibrary=LEGO
LEGOFadeStepColour=Light_Blue
LEGOLDSearchDirs=/home/mint/Documents/ldraw/models
LEGOLDrawLibPath=/home/mint/Documents/ldraw
LPRecentFileList=/home/mint/Documents/ldraw/models/pyramid.ldr
LdrawFilesLoadMsgs=0
LoadLastOpenedFile=false
NativeProjection=1
POVFileGenerator=Native
POVRayDisplay=false
PageDisplayPause=3
PartsLibrary=/home/mint/.local/share/LPub3D Software/LPub3D-2.3.13.113.1624_20200104-x86_64.AppImage/libraries/complete.zip
PartsListIcons=64
PerspectiveProjection=false
PliControlFile=/home/mint/.local/share/LPub3D Software/LPub3D-2.3.13.113.1624_20200104-x86_64.AppImage/extras/pli.mpd
PliSubstitutePartsFile=/home/mint/.local/share/LPub3D Software/LPub3D-2.3.13.113.1624_20200104-x86_64.AppImage/extras/pliSubstituteParts.lst
PovrayAutoCrop=true
PovrayRenderQuality=0
PreferredRenderer=Native
ProjectsPath=/home/mint/Documents/ldraw/models
RendererTimeout=6
SaveOnRedraw=true
SaveOnUpdate=true
SceneBackgroundColor=#aeadac
SceneGridColor=#1e1b18
SceneGuideColor=#aa0000
SceneGuides=false
SceneGuidesLine=2
SceneGuidesPosition=0
SceneRuler=false
SceneRulerTickColor=#35322f
SceneRulerTracking=2
SceneRulerTrackingColor=#00FF00
ShowAnnotationMessages=true
ShowDownloadRedirects=true
ShowGuidesCoordinates=false
ShowParseErrors=true
ShowSaveOnRedraw=true
ShowSaveOnUpdate=true
ShowTrackingCoordinates=false
SnapToGrid=false
ThemeAutoRestart=false
TitleAnnotationFile=/home/mint/.local/share/LPub3D Software/LPub3D-2.3.13.113.1624_20200104-x86_64.AppImage/extras/titleAnnotations.lst

[Updates]
CheckUpdateFrequency=0
EnableDownloader=true
ShowAllNotifications=true
ShowUpdateNotifications=true
```
</details>

### Logs

- Application Log: `[Application data path]/logs/LPub3DLog.txt`

<details>

INFO void Application::initialize() @ln 655 "Initializing application..." 
INFO void Application::initialize() @ln 658 ----------------------------- 
INFO void Application::initialize() @ln 659 "LPub3D v2.3.13 r113 (Release) for Linux 64bit" 
INFO void Application::initialize() @ln 660 ============================= 
INFO void Application::initialize() @ln 661 "Arguments....................()" 
INFO void Application::initialize() @ln 684 "LPub3D Application Folder....(lpub3d)" 
INFO void Application::initialize() @ln 689 "LPub3D App Data Path.........(/home/mint/.local/share/LPub3D Software/LPub3D-2.3.13.113.1624_20200104-x86_64.AppImage)" 
INFO void Application::initialize() @ln 694 "LPub3D Executable Path.......(/var/tmp/.mount_LPub3DKJnScW/usr/bin)" 
INFO void Application::initialize() @ln 695 "LPub3D Log Path..............(/home/mint/.local/share/LPub3D Software/LPub3D-2.3.13.113.1624_20200104-x86_64.AppImage/logs/LPub3DLog.txt)" 
INFO void Application::initialize() @ln 714 "LPub3D Extras Resource Path..(/var/tmp/.mount_LPub3DKJnScW/usr/share/lpub3d)" 
INFO void Application::initialize() @ln 717 "LPub3D Renderers Exe Path....(/var/tmp/.mount_LPub3DKJnScW/opt/lpub3d/3rdParty)" 
INFO void Application::initialize() @ln 720 "LPub3D Loaded LDraw Library..(LEGO® Parts)" 
INFO void Application::initialize() @ln 721 "Logging Level................(STATUS (0), Levels: [status,info,trace,debug,notice,error,fatal,off])" 
INFO void Application::initialize() @ln 723 "Debug Logging................(Enabled)" 
INFO void Application::initialize() @ln 724 ----------------------------- 
STATUS void Application::splashMsg(QString) @ln 94 "5% - Loading library for LEGO® Parts..." 
STATUS void Application::splashMsg(QString) @ln 94 "5% - Locate LDraw archive libraries..." 
STATUS void Application::splashMsg(QString) @ln 94 "10% - Copying archive libraries..." 
STATUS void Application::splashMsg(QString) @ln 94 "10% - Locate LDraw directory..." 
STATUS void Application::splashMsg(QString) @ln 94 "15% - Preferences loading..." 
STATUS void Application::splashMsg(QString) @ln 94 "15% - Selecting update settings..." 
STATUS void Application::splashMsg(QString) @ln 94 "20% - LPub3D GUI window loading..." 
STATUS void Application::splashMsg(QString) @ln 94 "25% - LPub3D window defaults loading..." 
INFO static void Preferences::lgeoPreferences() @ln 1705 "LGEO library status..." 
INFO static void Preferences::lgeoPreferences() @ln 1725 "LGEO library path  : Not found" 
INFO static void Preferences::rendererPreferences(UpdateFlag) @ln 1736 "Image renderers..." 
INFO static void Preferences::rendererPreferences(UpdateFlag) @ln 1776 "LDGLite : /var/tmp/.mount_LPub3DKJnScW/opt/lpub3d/3rdParty/ldglite-1.3/bin/ldglite" 
INFO static void Preferences::rendererPreferences(UpdateFlag) @ln 1797 "LDView  : /var/tmp/.mount_LPub3DKJnScW/opt/lpub3d/3rdParty/ldview-4.3/bin/ldview" 
INFO static void Preferences::rendererPreferences(UpdateFlag) @ln 1893 "POVRay  : /var/tmp/.mount_LPub3DKJnScW/opt/lpub3d/3rdParty/lpub3d_trace_cui-3.8/bin/lpub3d_trace_cui" 
INFO static void Preferences::rendererPreferences(UpdateFlag) @ln 2143 "Processing renderer configuration files..." 
INFO static void Preferences::setLDGLiteIniParams() @ln 2189 "Initializing /home/mint/.local/share/LPub3D Software/LPub3D-2.3.13.113.1624_20200104-x86_64.AppImage/3rdParty/ldglite-1.3/config/ldglite.ini..." 
INFO static void Preferences::setLDGLiteIniParams() @ln 2243 "LDGLite.ini file   : /home/mint/.local/share/LPub3D Software/LPub3D-2.3.13.113.1624_20200104-x86_64.AppImage/3rdParty/ldglite-1.3/config/ldglite.ini" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2266 "Initializing /home/mint/.local/share/LPub3D Software/LPub3D-2.3.13.113.1624_20200104-x86_64.AppImage/ldv/ldvExport.ini..." 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: [General]" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: Antialias=64" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: AutoCrop=1" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: CurveQuality=4" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: HFOV=0.00999999977648258209228516" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: InstallPath=" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: InstallPath 4.1=" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: ProcessLDConfig=1" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: " 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: [3dsExporter]" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: SeamWidth=0.5" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: " 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: [CustomColors]" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: " 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: [ExtraSearchDirs]" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: " 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: [PovExporter]" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: Ambient=0.4" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: BottomInclude=" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: ChromeBril=5" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: ChromeRefl=0.85" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: ChromeRoughness=0.01" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: ChromeSpecular=0.8" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: ConditionalEdges=0" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: CustomAspectRatio=1.5" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: Diffuse=0.4" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: EdgeRadius=0.15" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: Edges=0" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: FileVersion=3.6" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: FindReplacements=0" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: Floor=0" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: FloorAxis=1" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: HideStuds=0" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: InlinePov=1" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: Phong=0.5" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: PhongSize=40" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: PovLights=1 45.0 0.0 1.0 200 4;2 30.0 120.0 0.0 0 0;3 60.0 -120.0 1.0 80 3" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: PrimitiveSubstitution=1" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: Quality=3" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: Refl=0.08" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: Reflections=1" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: RubberPhong=0.1" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: RubberPhongSize=10" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: RubberRefl=0" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: SeamWidth=0.5" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: SelectedAspectRatio=ffffffff" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: Shadows=1" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: SmoothCurves=1" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: TextureOffsetFactor=5" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: TopInclude=" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: TransFilter=0.8" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: TransIoR=1.25" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: TransRefl=0.2" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: UnmirrorStuds=1" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: XmlMap=1" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: XmlMapPath=" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: " 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: [RecentFiles]" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: " 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: [Sessions]" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: Native 3DS/Antialias=64" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: Native 3DS/AutoCrop=1" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: Native 3DS/CheckPartTracker=0" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: Native 3DS/CurveQuality=10" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: Native 3DS/DrawLightDats=0" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: Native 3DS/EdgeThickness=1" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: Native 3DS/FOV=0.100000001490116119384766" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: Native 3DS/HiResPrimitives=1" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: Native 3DS/IgnorePBuffer=0" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OUT: Native 3DS/InstallPath=" 
INFO static void Preferences::updateLDVExportIniFile(UpdateFlag) @ln 2306 "NativePOV.ini OU

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

Indeed, there are some Qt layout inconsistencies between the various Unix/Linux. This behaviour is particularly evident on macOS and flavours of Linux that I do not explicitly build - e.g. Mint.

Cheers,

**Comment by trevorsandy** [comment]
Is set an acceptable dialog size depending on the platform. Let me know if this update resolves the mal sized and “hidden” dialogues in your environment ?

Cheers,
