### ISSUE TITLE
Making debian package fails with perl time error

### ISSUE THREAD

**Issue by mfeldt** [trevorsandy/lpub3d#391]
[CreateDeb.sh.log](https://github.com/trevorsandy/lpub3d/files/4040605/CreateDeb.sh.log)

see log

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

Set C locale in _builds/utilities/update-config-files.sh_. For example:

```
...

echo "   Start update-config-files.sh execution..."

export LC_ALL=C
```

There are also some other errors in your build log. See GitHub ticket #338 for full details on building LPub3D from source.

Cheers,

**Comment by mfeldt** [comment]
Thanks for dealing with this so swiftly.  Note however I was not attempting to fully build from source, but simply called https://github.com/trevorsandy/lpub3d/blob/master/builds/linux/CreateDeb.sh, which did all the setup by itself...

**Comment by trevorsandy** [comment]
https://github.com/trevorsandy/lpub3d/blob/master/builds/linux/CreateDeb.sh fully builds LPub3D from source so be sure to execute it using the following steps:

To build directly the `LPub3D-ci` source, substitute `lpub3d` with `lpub3d-ci` in the outlined build steps - for example:

- [ ] 1. enter your user directory  
`$ cd ~/`
- [ ] 2. get `CreateDeb.sh` build and packaging script. [if you already have a cloned `LPub3D-ci` GitHub remote repository, substitute  `trevorsandy` with your repository owner ID and be sure to update the script paths to point to your remote versus to the remote at `trevorsandy`].
`$ wget https://raw.githubusercontent.com/trevorsandy/lpub3d-ci/master/builds/linux/CreateDeb.sh`
- [ ] 3. enable execute permissions and execute the build and package script  
`$ chmod +x CreateDeb.sh && ./CreateDeb.sh`

Cheers,
