### ISSUE TITLE
background and placement statements ignored, statements of other page are applied

### ISSUE THREAD

**Issue by swl2019** [trevorsandy/lpub3d#392]
The render engine does not use the (global) multi step placement and background picture instruction of the current page 18 (lines 4978 & 4983), but the one of page 41 (lines 4701 & 4702). However these instructions are not the next ones above (which would be the ones of page 7 (lines 4889 & 4890)). If the placement or background picture is changed via the UI Dialogs for page 18 the correct instruction lines are added to the expected lines for page 18, but they do not show any effect (still the ones of page 41 are used). This is not the only place with this behavior there are more similar pages: 113, 115, 117, 153, 159.
A similar effect is on pages 268 and 276: the placement instructions affecting page 268 are the ones of page 276. But this does not apply to the background picture, which is correct.
Again the background picture and placement instructions of page 297 is applied on page 296, and those of page 293 apply to page 300
I use the “Ignore step” instruction to not show the last step in a multistep page. However this results in a 1 page offset: page 346 follows directly page 344 (page 345 is disappeared). Same applies to pages 368 followed directly 370, 373 resp. 375

I use the latest version, on a Windows 10 Environment, Standard Installation, 
I added in the unoffical path of the library some custom parts (part of the attached files)

As the files are to big to attach them here please follow this link [https://drive.google.com/open?id=11AInOStG5D6vzXURQFTZmYgQ7roD02M8](url)
 
### Steps to reproduce
open the file 
go to the pages (page number on the page)
Change the Position or Background Image and see thath the program applies the changes to the other places/pages.

Do I use the program in a wrong way?

Thank you
Jörg

**Comment by trevorsandy** [comment]
Hi Jörg,

Thank you for reporting this behaviour. Somehow I missed it so my apologies for the delayed response. I will take a look and come back to you soonest. 

Cheers,

**Comment by swl2019** [comment]
Hi Trevor,

 

hopfully you are well.

 

I usually do not push for replys, but I am neary finished with an instruction, just the issue reported in item 404 prevents me to close the job. It would be great if you could have a look into this, just to tell me if I did something wrong causing the issue, as I would correct my mistake and could go on.

 

I found a quick fix for this issue (#392): I just instruct to change the place for the page nummer - this breaks the alternating order, but it does not look to odd. The one reported in #404 rely is an issue as the bill of material is just not correct.

 

Thank you

Best Regards Jörg

 
 

Gesendet: Donnerstag, 06. Februar 2020 um 16:18 Uhr
Von: "Trevor SANDY" <notifications@github.com>
An: "trevorsandy/lpub3d" <lpub3d@noreply.github.com>
Cc: "swl2019" <git@familie-schwarzlaender.de>, "Author" <author@noreply.github.com>
Betreff: Re: [trevorsandy/lpub3d] background and placement statements ignored, statements of other page are applied (#392)


Hi Jörg,

Thank you for reporting this behaviour. Somehow I missed it so my apologies for the delayed response. I will take a look and come back to you soonest.

Cheers,

**Comment by trevorsandy** [comment]
Fixed.

Cheers,
