### ISSUE TITLE
Cannot update 

### ISSUE THREAD

**Issue by DanieleBenedettelli** [trevorsandy/lpub3d#393]
### Subject
If I try to check for updates or refresh libraries, I get a popup:
---------------------------
Software Update
---------------------------
<b>An error occured while checking for LPub3D update.&nbsp;&nbsp;&nbsp;</b>
---------------------------
Error connecting to update server: <br>Error creating SSL context ().
---------------------------
OK   
---------------------------

### Environment
* Version of LPub3D 2.3.13 r0 build 1511
* Operating system - Win 10, 64 bit

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  - Windows: `C:\Program Files\LPub3D` [x86_64]

* Application data path
C:\Users\Danny\AppData\Local\LPub3D Software\LPub3D\libraries

### Logs
- [UPD - Trevor SANDY] Not required for this behaviour

### Screenshots
* Configuration->Preferences->General
* Configuration->Preferences->Rendering
* Configuration->Preferences->Publishing
* Configuration->Preferences->Logging
* Configuration->Preferences->Other

### Steps to reproduce
Help->Check for updates

### Expected behaviour
Should check for updates

### Actual behaviour
Show error message

### Workaround
I downloaded manually latest version
I also checked the firewall, and allowed Lpub3D access to internet

**Comment by trevorsandy** [comment]
Daniele,

At this moment, I'm not sure what is causing this behaviour as I am not able to reproduce it on my system. For me, the library update works as expected. Are you running a Windows installed (.exe) or portable (extracted .zip) instance of LPub3D ?

To progress, I can suggest is the following:

1. Download and extract a portable (.zip) instance of LPub3D - I recommend using [continuous build release](https://github.com/trevorsandy/lpub3d/releases/tag/continuous) which, at this time is 113 revisions ahead of the official release.
2. Manually download the [archive libraries](https://www.ldraw.org/article/14.html) (be sure to rename ldrawunf.zip to lpub3dldrawunf.zip)  and place them in the 'extras' subfolder folder - overwriting the existing libraries. You should only need to download the Unofficial library as the official one will be the same as what you will download.
3. Open LPub3D and proceed as before

You could also try to update the libraries in the portable instance to see if the behaviour is repeatable or isolated to your installed instance of LPub3D.

Cheers,

**Comment by technicbasics** [comment]
Hi Trevor
The same problem here.
Both in the fixed version and in the portable version.
I am sure, there waas a thread on ldraw.org, because other have the same problem, but i can't find it.

**Comment by technicbasics** [comment]
Hi Trevor
I have found the thread,
please look here....
https://forums.ldraw.org/thread-23955.html

**Comment by trevorsandy** [comment]
I cannot reproduce this behaviour. 

Moreover, there are multiple sources that would cause an SSL fail.  If you continue to experience this behaviour with the latest LPub3D release, it may be linked to your local environment firewall settings as I have included the SSL libraries which should address the scenario where they are not present.

Cheers,

**Comment by technicbasics** [comment]
Now it works! Many thanks! Regards Johann --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 13.03.21, 15:45 schrieb Trevor SANDY ***@***.***>:

   
  I cannot reproduce this behaviour. 
  Moreover, there are multiple sources that would cause an SSL fail. If you continue to experience this behaviour with the latest LPub3D release, it may be linked to your local environment firewall settings as I have included the SSL libraries which should address the scenario where they are not present. 
  Cheers,

**Comment by ZPhilo** [comment]
I do have the same problem, even using the latest installable version (2.4.2 R19 release). That may well be something in my Windows configuration, but where to look at?

**Comment by technicbasics** [comment]
Hello Trevor
The problem is back.
But there is a difference.
In the mobile version it works, in the installed version (2.4.3) of the AIOI of ldraw.org it doesn't work.
