### ISSUE TITLE
Callout pointer arrow head 

### ISSUE THREAD

**Issue by DanieleBenedettelli** [trevorsandy/lpub3d#394]
### Subject
The border on the arrow head of the callow pointer should be continuous.

### Environment
* Version of LPub3D - 2.3.13 r0
* Operating system - Win 10 x64

### Configuration
Standard (didn't touch anything after update to latest version)

### Steps to reproduce
Set page background to anything but white.
Generate a callout pointer, add white border.

### Expected behaviour
See image (prev version was working fine): line and arrow should be black, white border all around
![arrow_border_prev_version](https://user-images.githubusercontent.com/47357389/73927925-8fbbc100-48d2-11ea-99f1-f5bfc821d281.jpg)

### Actual behaviour
See image (curr version); arrow head has border that interrupts the black line
![arrow_border_curr_version](https://user-images.githubusercontent.com/47357389/73927926-90545780-48d2-11ea-93c5-98223727467b.jpg)

### Workaround
Manually editing the PDF, bring the pointer line to front (on top of arrowhead).

### Solution suggestion
Generate pointer line and then arrowhead (it was working fine in previous sw versions).

**Comment by trevorsandy** [comment]
Hello Daniele,

I'm quite sure this behaviour has been fixed after the v2.3.13 r0. 

Please download and install the [continuous build release](https://github.com/trevorsandy/lpub3d/releases/tag/continuous) which, at this time is at r113.

You may consider downloading a portable distribution (.zip) which can be extracted and executed out of the box anywhere on your machine where no elevated UAC is required.

Let me know your results.

Cheers,

**Comment by jacovandermolen** [comment]
Interesting to see how the red arrowhead looks like. How?

**Comment by trevorsandy** [comment]
You can modify pointer settings from its context (right-click) menu.

Cheers,

**Comment by jacovandermolen** [comment]
OK, I totally missed that one! Great feature ;-)

**Comment by trevorsandy** [comment]
Fixed.

Cheers,

**Comment by jacovandermolen** [comment]
I still have not figured out how to adjust the look of the arrowhead?
In the examples, the red point is indented whereas the black is straight.

**Comment by trevorsandy** [comment]
> I still have not figured out how to adjust the look of the arrowhead?
In the examples, the red point is indented whereas the black is straight.

Sorry, I completely overlooked this comment.

I’m not sure you can. It looks like I’m using different fonts between the examples you show. I’ll take a look. 

Open a new ticket as this behaviour is unexpected.

Cheers,
