### ISSUE TITLE
Filenames of png exports contain ever more "150_DPI" extensions...

### ISSUE THREAD

**Issue by mfeldt** [trevorsandy/lpub3d#395]
### Subject
When exporting png files, the filenenames get longer with each page

### Environment
* Version of LPub3D - 2.3.14.1
* Operating system - Ubuntu 16.04

### Steps to reproduce
* Produce instructions
* export as png

### Expected behaviour
png files should be produced with filenames according to the pattern "model_lpub3d_%2d.png", numbered accordingly

### Actual behaviour
here's an ls of the export directory:

model_full_bi_lp3d_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_page_25.png
model_full_bi_lp3d_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_page_24.png
model_full_bi_lp3d_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_page_23.png
model_full_bi_lp3d_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_page_22.png
model_full_bi_lp3d_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_page_21.png
model_full_bi_lp3d_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_page_20.png
model_full_bi_lp3d_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_page_19.png
model_full_bi_lp3d_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_page_18.png
model_full_bi_lp3d_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_page_17.png
model_full_bi_lp3d_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_page_16.png
model_full_bi_lp3d_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_page_15.png
model_full_bi_lp3d_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_page_14.png
model_full_bi_lp3d_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_page_13.png
model_full_bi_lp3d_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_page_12.png
model_full_bi_lp3d_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_page_11.png
model_full_bi_lp3d_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_page_10.png
model_full_bi_lp3d_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_page_9.png
model_full_bi_lp3d_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_page_8.png
model_full_bi_lp3d_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_page_7.png
model_full_bi_lp3d_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_page_6.png
model_full_bi_lp3d_150_DPI_150_DPI_150_DPI_150_DPI_150_DPI_page_5.png
model_full_bi_lp3d_150_DPI_150_DPI_150_DPI_150_DPI_page_4.png
model_full_bi_lp3d_150_DPI_150_DPI_150_DPI_page_3.png
model_full_bi_lp3d_150_DPI_150_DPI_page_2.png
model_full_bi_lp3d_150_DPI_page_1.png

### Solution suggestion
I guess there's something that appends the DPI-string (not needed anyway in my opinion) the number of times that the page number is...

**Comment by riazanovskiy** [comment]
Strange, I thought this was fixed a long time ago
https://github.com/trevorsandy/lpub3d/issues/346

**Comment by trevorsandy** [comment]
Fixed.

Cheers
