### ISSUE TITLE
Redesign INCLUDE file meta command behaviour

### ISSUE THREAD

**Issue by DanieleBenedettelli** [trevorsandy/lpub3d#396]
### Subject
The PDF page size is wrong, does not take into account the PAGE SIZE specified in included file.

### Environment
* Version of LPub3D - 2.3.13 rev 113
* Operating system - Win 10 x64

### Steps to reproduce
[page_size_bug.zip](https://github.com/trevorsandy/lpub3d/files/4171774/page_size_bug.zip)
open attached file "page_size_bug.ldr"
export to PDF.

### Expected behaviour
The PDF should have a page size of 11.7 6.58 (16:9 ratio).

### Actual behaviour
The page is huge, the PAGE SIZE specified in the included header is ignored.

### Workaround
I have to add the line 
0 !LPUB PAGE SIZE GLOBAL 11.7 6.58
to the main file, 

### Solution suggestion
Take into account all settings specified in included files.

**Comment by trevorsandy** [comment]
Implemented.

Cheers,
