### ISSUE TITLE
assem with callout does not remain where its dragged to

### ISSUE THREAD

**Issue by DanieleBenedettelli** [trevorsandy/lpub3d#397]
### Subject
When an assem has a callout, and you try dragging to another position on the page, the position is not kept, but changes once you release the mouse button.

### Steps to reproduce
[lpub3d_bug_test_assem_placement_offset.zip](https://github.com/trevorsandy/lpub3d/files/4172878/lpub3d_bug_test_assem_placement_offset.zip)
open the file and try dragging the assem (screenshots included).

### Expected behaviour
The image should remain where I drag it, no matter if and where the callout is.

### Actual behaviour
It seems that lpub3d tries to place the centroid of the assem+callout where I release the mouse.

### Workaround
I have to manually twaek the x y offset values in the meta command

**Comment by mfeldt** [comment]
I've noticed that too. Much better to click on assem (callout) placement, select "relative to page" and select one of the fixed possibilities (top left, top center, top right, center left, ....)

No more hassle!

**Comment by DanieleBenedettelli** [comment]
I tried doing what you suggest, but when placing the callouts relative to the page, the pointers change position when I render the file to PDF.  I had to revert to the assem-relative placement.

**Comment by DanieleBenedettelli** [comment]
CSI does not remain where it is dragged to. It still happens in dev build 2.4.0 r195 build 2415.
screenshots attached.
![1-csi-pre-drag](https://user-images.githubusercontent.com/47357389/100198601-53f2f600-2efc-11eb-8fb8-ae538106cc6c.png)
![2-csi-drag](https://user-images.githubusercontent.com/47357389/100198604-548b8c80-2efc-11eb-9023-56c57af4fb7a.png)
![3-csi-post-drag](https://user-images.githubusercontent.com/47357389/100198605-55242300-2efc-11eb-93fb-733fc65e08c7.png)

**Comment by trevorsandy** [comment]
Thank you for reasserting this behaviour. 

Somehow I completely forgot to treat this ticket in 2.4.0. I'll take a look. Is the stated workaround still applicable ?

Regarding your _LDRAW file messed_ up ticket, can you confirm the _scrambled_ LDraw text behaviour is present in 2.4.0 dev build 2415 r195 ? Leave a comment in that ticket accordingly so I'm aware of any further work to do there.

Cheers,

**Comment by trevorsandy** [comment]
This behaviour is corrected in v2.4.1.

Cheers,
