### ISSUE TITLE
Inserted image in first page of submodel appear in parent model.

### ISSUE THREAD

**Issue by ZPhilo** [trevorsandy/lpub3d#399]
### Subject
If you try to add an image (edit -> add picture) in the first page of a submodel xxx, the image actually appears in the model page that calls xxx. Adding text in the same conditions work fine. Adding image on the second page of the submodel works fine too. Tested only with a submodel page with multiple steps per page.

### Environment
* Version of LPub3D: 2.3.13 R113 B1624
* Operating system - Win10 / x86_64

### Workaround
Replace the "0 !LPUB INSERT  PICTURE" in the right place of the source.

**Comment by trevorsandy** [comment]
Fixed.

Cheers,
