### ISSUE TITLE
No option to uninstalled LPub3D version 2.2

### ISSUE THREAD

**Issue by d-j-m-0** [trevorsandy/lpub3d#40]
### Subject of the issue
LPub3D version 2.2 uninstall does not work. LPub3D version 2.0 unistall does work.

### Your environment
* Version of LPub3D - 2.2
* Operating system - Windows 7, 32 bit

### Configuration
* LPub3D installation path
  - Windows: `D:\Program Files\LPub3D`
* Application data path 
  - Windows: `%USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\`

### Steps to reproduce
With LPub3d version 2.0 installed, open the Windows Control Panel.
Select the action to uninstall a program.
Highlight LPub3D and then click uninstall (refer to screenshot):
![uninstall_lpub3d_2_0_20](https://user-images.githubusercontent.com/37604323/37692235-3bb1c5e2-2d1c-11e8-89fd-5bcfb9d04c4f.jpg)
Software is successfully uninstalled.

Reboot machine and log in.
Install LPub3D version 2.2,
Reboot machine and log in.
Open the Windows Control Panel.
LPub3D is not listed (refer to screenshot)
![no_uninstall_lpub3d_2_2](https://user-images.githubusercontent.com/37604323/37692288-7d483658-2d1c-11e8-92d0-df8e6e426bc4.jpg)

Navigate to the directory where LPub3D has been installed.
Run the uninstall program as an administrative user (see screenshot):
![uninstall_lpub3d_2_2](https://user-images.githubusercontent.com/37604323/37692321-aa5e79ae-2d1c-11e8-854b-0123b734f1fa.jpg)
Dialog window is displayed saying there is no installation (see screenshot)
![no_installation_dialog_2_2](https://user-images.githubusercontent.com/37604323/37692359-ddb0fcc8-2d1c-11e8-9e29-af5a0d23aa69.jpg)
Trying to run the uninstall program with the login id of the user doing the original install results in the same dialog window being displayed.

### Expected behaviour
LPub3D should be listed in the Windows Control Panel/Programs with an option to uninstall.

### Actual behaviour
There is no way to uninstall LPub3D version 2.2

### Workaround
None known.

### Solution suggestion
No idea.

**Comment by trevorsandy** [comment]
This behaviour does not present on Windows 10. I've just finished setting up a Windows 7 SP1 VMWare image to see what behaviour presents there. Taking a look...

**Comment by trevorsandy** [comment]
This behaviour has been corrected. Here is a summary of the cause and work around:

**Cause:** Install script did not take into account 32bit Windows
**Cause:** NSIS `SetRegView` command prevented the install script from accessing (read or write) the registry.

**Unexpected behaviour:** Attempting to run uninstall.exe produces the message 'There is no installation of LPub3D.' Uninstaller entry missing from the Control Panel/Programs and features

The install script did not take into account 32bit Windows when reading from the registry during the installer's initialisation. Consequently, the parameters needed by the uninstall program were not available. This is the reason for the 'There is no installation of LPub3D.' message. when trying to launch the uninstaller from either the application folder.

NSIS `SetRegView` command prevented the install script from accessing (read or write) the registry. You can see the evidence of this when you receive empty prompts for the install and LDraw paths during installation execution. If a previous version of LPub3D is installed, these paths should be automatically filled with the existing value read from the registry. This is also the reason the Uninstall entry for upgraded application in Control Panel/Programs and features is missing.

**WORKAROUND**
- These steps apply to LPub3D 2.1.0 and 2.2.0 installed on Windows 7 32bit
- Backup your registry. 
- `reg export "HKEY_CURRENT_USER\Software\LPub3D Software" %USERPROFILE%\Desktop\LPub3D_DATA_Hive.reg` 
- `reg export "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\CurrentVersion\Uninstall\LPub3D" %USERPROFILE%\Desktop\LPub3D_UNINSTALL_2.0.20_Hive.reg`
- Uninstall previous version of LPub3D
- `reg import %USERPROFILE%\Desktop\LPub3D_DATA_Hive.reg`
- Reboot your computer.
- Install new version of LPub3D

**UNINSTALL v2.1.0 or v2.2.0**
- These step apply to LPub3D 2.1.0 and 2.2.0 instlled on Windows 7 32bit
- Create the registry file `%USERPROFILE%\Desktop\LPub3D_UNINSTALL_2.2.0_Hive.reg` with the following entries. NOTE, replace C:\... with your install path.
```
  Windows Registry Editor Version 5.00

  [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\LPub3D]
  "InstallLocation"="C:\\Program Files\\LPub3D"
  "DisplayName"="LPub3D 2.2.0 Win64"
  "UninstallString"="\"C:\\Program Files\\LPub3D\\uninstall.exe\" /allusers"
  "DisplayVersion"="2.2.0"
  "DisplayIcon"="C:\\Program Files\\LPub3D\\LPub3D22.exe,0"
  "Publisher"="Trevor SANDY"
  "URLInfoAbout"="https://trevorsandy.github.io/lpub3d/"
  "URLUpdateInfo"="https://trevorsandy.github.io/lpub3d/"
  "HelpLink"="https://github.com/trevorsandy/lpub3d/issues"
  "Comments"="LPub3D - An LDraw Building Instruction Editor"
  "VersionMajor"="2"
  "VersionMinor"="2"
  "InstallDate"=dword:0133ed5c
  "NoModify"=dword:00000001
  "NoRepair"=dword:00000001
  "StartMenuFolder"="LPub3D"
  "EstimatedSize"=dword:000312c7
```
- Open a command console with Adminsitrator privilages. 
- Import LPub3D_UNINSTALL_2.0.20_Hive.reg with the command `reg import %USERPROFILE%\Desktop\LPub3D_UNINSTALL_2.2.0_Hive.reg`
- Reboot your computer
- Got to Control Panel/Programs and features; you should now see the missing uninstall entry "LPub3D 2.2.0 Win64" for LPub3D. 
- Proceed with your uninstall steps as required.
