### ISSUE TITLE
Undeclared hard dependency in Debian 10 "Buster" package

### ISSUE THREAD

**Issue by rsbx** [trevorsandy/lpub3d#401]
The Debian 10 "Buster" package (lpub3d 2.3.14.1533 amd64) has the following undeclared hard dependencies:
 - shared-mime-info
 - desktop-file-utils

in the postinst and postrm scripts (builds/linux/obs/debian).

This can be fixed by wrapping (see below) the calls with tests for the executables OR by declaring the dependency in builds/linux/obs/debian/control.

...
if [ -x update-mime-database ]; then
  update-mime-database  /usr/share/mime >/dev/null
fi
if [ -x update-desktop-database ]; then
  update-desktop-database
fi
...

Wrapping the calls has the advantage that those Debian administrators that build lean systems will not have to install those packages in order to install lpub3d.

**Comment by rsbx** [comment]
Just tried installing 2.4 Debian 10 packages and the postinst and postrm scripts are missing the square brackets, '[' and ']'.

The install appeared to succeed but with errors related to the 2 conditionals in the postinst script.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. Please provide a log of the offending behaviour and what you believe is the corrective action for your environment.

My [Debian 10](https://software.opensuse.org//download.html?project=home%3Atrevorsandy&package=lpub3d) [build log](https://build.opensuse.org/package/live_build_log/home:trevorsandy/lpub3d/Debian_10/x86_64) do not show errors similar to the behaviour you are describing.

Cheers,

**Comment by rsbx** [comment]
Only single brackets are necessary; double brackets look odd in this use but bash does not complain.

The errors scrolled by in the console output of dpkg when I installed the package. Since there were issues with  these scripts in 2.3.14, I was watching the install closely.

**Comment by trevorsandy** [comment]
Implemented.

Cheers,
