### ISSUE TITLE
Crash when adding text to an inserted blank page

### ISSUE THREAD

**Issue by ZPhilo** [trevorsandy/lpub3d#402]
### Subject
LPub3D crashes when I try to add text to a newly inserted blank page.

### Environment
    Version of LPub3D: 2.3.13 R113 B1624
    Operating system - Win10 / x86_64

### Workaround
Add text to any model page, and move the text meta to the desired page using source window.

**Comment by ZPhilo** [comment]
[LPub3D.zip](https://github.com/trevorsandy/lpub3d/files/4299636/LPub3D.zip)

**Comment by trevorsandy** [comment]
Fixed.

Cheers,
