### ISSUE TITLE
Cable annotation title not reporting cm

### ISSUE THREAD

**Issue by DanieleBenedettelli** [trevorsandy/lpub3d#403]
### Subject
The cable annotation reports only the number, not "cm".

### Environment
Release 2.3.13 rev 113 build 1624
Win10 x64

### Expected behaviour
The annotation should report 25 cm (or 35 cm, or 50 cm)

### Actual behaviour
The annotation reports just the length number

### Workaround
I can show the correct annotation by adding the part 11145.dat to the  free form part annotations file, but does not work.

### Solution suggestion
Maybe I just have to tweak the regex in the title annotation file. It was working in previous versions.

**Comment by trevorsandy** [comment]
Fixed.

Cheers,
