### ISSUE TITLE
Bill of Material part count differs from total count over all PLIs

### ISSUE THREAD

**Issue by swl2019** [trevorsandy/lpub3d#404]
While the part count in the step's PLI is correct the Bill of Material Shows a wrong total count. This happens not to all parts. 

A common pattern of all parts with this deficit is that they are used in the places with a buffer store, buffer load and Ignore part scenario to model “flying” parts I the instructions. But not all parts in this scenarios are affected.

In the attached PDF two examples are shown, also the configuration screenshots are there.
The model uses quite often user defined parts. None of these parts are affected by this issue. 

[issue.pdf](https://github.com/trevorsandy/lpub3d/files/4446554/issue.pdf)

The custom parts are part of the linked ZIP (filesize is to big to be attached). There the model files as well as the free form annotation config file, the custom PLI.mpd file and the used background pictures are provided as well.
https://drive.google.com/file/d/1-aT5dWkuCw6wl_qDXyhmYCqtn0N_UbEs/view?usp=sharing

Here the resulting instruction manual: https://drive.google.com/file/d/1N-w97lVyBDfjsOHZ4vZG2Wg4M9wutmuu/view?usp=sharing 

p.s. 
you still can find the issue with the ignored background instructions (see issue #392): examples are page 160 or 188

**Comment by trevorsandy** [comment]
Fixed.

Cheers,
