### ISSUE TITLE
Fade Previous Parts also affect transparent parts in current step.

### ISSUE THREAD

**Issue by rsbx** [trevorsandy/lpub3d#405]
When Fade Previous Parts is enabled, transparent parts in the current step loose all non-first surface details. I.e. interior details that are normally visible in a transparent part disappear. A 2 x 2 trans-black brick makes a nice test part.

Environment:
System: Linux, Debian 10 "Buster", all updates applied
Version: lpub3d_2.3.14.1533_amd64.deb
Render-er: Native (the others do not work)

Output of "glxinfo -B":
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) Haswell Mobile  (0x416)
    Version: 18.3.6
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.3.6
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 18.3.6
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 18.3.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10

**Comment by trevorsandy** [comment]
Fixed.

Cheers,
