### ISSUE TITLE
Setting display of page numbers to false, makes times indicator of non-called-out submodels disappear

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#406]
Ok, so this one took a bit of trial-and-error to track down what exactly was causing the issue.

If the page number display is set to false, then the times indicator of non-called-out submodels is also gone.
That might sound a bit vague, so here's an example model:
```
0 FILE main.ldr
0 Author: Firstname Lastname [Username]
0 !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
1 4 0 0 0 1 0 0 0 1 0 0 0 1 3003.dat
1 4 40 0 0 1 0 0 0 1 0 0 0 1 3003.dat
1 4 20 -24 0 1 0 0 0 1 0 0 0 1 3003.dat
0 ROTSTEP END
1 4 80 0 0 1 0 0 0 1 0 0 0 1 3003.dat
1 4 60 -24 0 1 0 0 0 1 0 0 0 1 3003.dat
1 4 40 -48 0 1 0 0 0 1 0 0 0 1 3003.dat
0 STEP
0 !LPUB CALLOUT BEGIN
1 2 -20 -24 0 1 0 0 0 1 0 0 0 1 subModel-1.ldr
1 2 100 -24 0 1 0 0 0 1 0 0 0 1 subModel-1.ldr
0 !LPUB CALLOUT POINTER CENTER 0 0.298883 0.296774 0 0 0 0 0 0 1
0 !LPUB CALLOUT POINTER CENTER 0 0.746512 0.564516 0 0 0 0 0 0 1
0 !LPUB CALLOUT END
0 STEP
1 14 -20 -72 0 1 0 0 0 1 0 0 0 1 subModel-2.ldr
1 14 100 -72 0 1 0 0 0 1 0 0 0 1 subModel-2.ldr
0 STEP
0 NOFILE 
0 FILE submodel-1.ldr
0 Name: subModel-1.ldr
0 Author: Firstname Lastname [Username]
0 !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
1 2 0 0 0 1 0 0 0 1 0 0 0 1 3003.dat
0 ROTSTEP END
1 2 -20 -24 0 1 0 0 0 1 0 0 0 1 3003.dat
0 STEP
1 2 20 -24 0 1 0 0 0 1 0 0 0 1 3003.dat
0 STEP
0 NOFILE 
0 FILE submodel-2.ldr
0 Name: subModel-2.ldr
0 Author: Firstname Lastname [Username]
0 !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
0 !LPUB MULTI_STEP BEGIN
1 14 0 0 0 1 0 0 0 1 0 0 0 1 3003.dat
0 ROTSTEP END
1 14 -20 -24 0 1 0 0 0 1 0 0 0 1 3003.dat
0 STEP
1 14 20 -24 0 1 0 0 0 1 0 0 0 1 3003.dat
0 STEP
0 !LPUB MULTI_STEP END
0 NOFILE 
```

If you open this file in LPub3D, the called-out submodel looks like this:
![image](https://user-images.githubusercontent.com/12005521/90952844-17c87900-e467-11ea-8cfb-341160ada30a.png)

And the non-called-out submodel looks like this:
![image](https://user-images.githubusercontent.com/12005521/90952855-24e56800-e467-11ea-8eef-e8498b400cd6.png)

Now, if you set `Display Page Number` to off/false (Page Globals Setup -> Page Number, or `0 !LPUB PAGE DISPLAY_PAGE_NUMBER GLOBAL FALSE` )

Then not only are the page numbers removed, but also the times indicator for non-called-out submodels:
![image](https://user-images.githubusercontent.com/12005521/90952890-6544e600-e467-11ea-9d04-4f2729a630ae.png)

I'm using LPub3D 2.3.13:
![image](https://user-images.githubusercontent.com/12005521/90952897-7beb3d00-e467-11ea-9d68-13a3d5d121bf.png)

**Comment by trevorsandy** [comment]
Fixed.

Cheers,
