### ISSUE TITLE
The number of sub-models used is not displayed

### ISSUE THREAD

**Issue by technicbasics** [trevorsandy/lpub3d#407]
### Subject
If a sub-model is inserted several times, the number is not displayed in the last step. In my opinion, this problem, like the callout  problem #360 , only occurs when the model has a certain complexity. Feel free to provide you with a file if necessary

### Environment
* Version of LPub3D - 2.3.13r113
* Operating system - Win 10

**Comment by technicbasics** [comment]
I still tested something.
For me the problem only occurs when the submodel ends on a multistep page. If it ends as a single step then the number is displayed.

**Comment by trevorsandy** [comment]
Fixed. See #360.

Cheers,
