### ISSUE TITLE
Application hanging

### ISSUE THREAD

**Issue by Greg1989** [trevorsandy/lpub3d#408]
Subject
After I have opened LPub3D, the application hangs when I start using any drop down menus.  The menu becomes unmanageable, nd all I can do is minimize the application to the task bar.  It was working fine before, and I am not sure why it is doing this now.

Environment
* Version of LPub3D - v2.3.13 r113
* Operating system - win 10

**Comment by Greg1989** [comment]
[LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/5166233/LPub3DLog.txt)

Here is the log file.

**Comment by trevorsandy** [comment]
Closing this ticket. If you continue to experience this behaviour with the latest release, do not hesitate to reopen.

Cheers,
