### ISSUE TITLE
Could not write to native PLI image file (and other warnings) 

### ISSUE THREAD

**Issue by kingjayko** [trevorsandy/lpub3d#409]
### Subject

Updated all mlcad software with AIOI. Everything works fine except for LPub3D, which gives multiple errors. Tried several things, nothing helped. Tried different render methods, all gave errors. Log is attached at the bottom. Perhaps something to do with file locations? 

![Warning](https://user-images.githubusercontent.com/71013195/92591885-fc4ed200-f29e-11ea-861f-f47ae3739ed7.png)

### Environment
* Version of LPub3D - Release 2.3.13 revision 113 build 1624
* Operating system - Windows 10, 64-bit system, 4.6.0 Nvidia 425.91
Quadro K1100M

### Configuration

* LPub3D installation path
  - Windows: C:\Program Files (x86)\LDraw\LPub3D

* Application data path
  - Windows: C:\Users\Rik\AppData\Local\LPub3D Software\LPub3D
  
![PreferencesGeneral](https://user-images.githubusercontent.com/71013195/92591583-76328b80-f29e-11ea-949a-7c8b20aa9253.png)

![PreferencesOther](https://user-images.githubusercontent.com/71013195/92591585-7763b880-f29e-11ea-83a6-f34959904f99.png)

![PreferencesPublishing](https://user-images.githubusercontent.com/71013195/92591586-7763b880-f29e-11ea-9f74-bd7d7b915275.png)

![PreferencesRendering](https://user-images.githubusercontent.com/71013195/92591587-77fc4f00-f29e-11ea-8b05-fe041eff8121.png)

![PreferencesThemeLogging](https://user-images.githubusercontent.com/71013195/92591589-77fc4f00-f29e-11ea-8109-3e7cb6ee2613.png)

### Logs

[LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/5194719/LPub3DLog.txt)

**Comment by trevorsandy** [comment]
Closing this ticket. If you continue to experience this behaviour with the latest LPub3D release, do not hesitate to reopen.

Cheers,
