### ISSUE TITLE
No PLI or assembly images generated when POV-Ray selected as the renderer.

### ISSUE THREAD

**Issue by d-j-m-0** [trevorsandy/lpub3d#41]
When using LPub3D version 2.2, if POV-Ray is selected as the renderer, no images are being generated.

### Your environment
* Version of LPub3D - 2.2
* Operating system - Windows 7, 32 bit

### Configuration
[Note: Provide details and content below as needed with appropriate redactions]
* LPub3D installation path
  - Windows: `D:\Program Files\LPub3D` [x86_64]
* Application data path 
  - Windows: `%USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\`

### Logging
[LPub3DLog_2_2_780_povray_ldview_multiple.txt](https://github.com/trevorsandy/lpub3d/files/1831882/LPub3DLog_2_2_780_povray_ldview_multiple.txt)
[stderr-povray.txt](https://github.com/trevorsandy/lpub3d/files/1831883/stderr-povray.txt)

### Steps to reproduce
Use the file motor_pin.ldr in the attached zip file. Open it using LPub3D version 2.2
[fade_test.zip](https://github.com/trevorsandy/lpub3d/files/1831887/fade_test.zip)
Set renderer to POV-Ray in preferences. Close Preferences dialog.
Resulting page that is displayed in LPub3D:
![no_povray_2_2_780](https://user-images.githubusercontent.com/37604323/37692542-41105498-2d1e-11e8-9062-9ff44a1a8845.png)

### Expected behaviour
Images should be generated.

### Actual behaviour
Images are not generated.

### Workaround
None known.

### Solution suggestion
Suspect there is a hard-coded path related to the POV-Ray ini file. My LPub3D installation is on D: drive, not C: drive. The path to the POV-Ray instance ini file installed as part of the LPub3D bundle should reflect the appropriate installation drive/directory when invoked by LPub3D. I suspect it is not.

**Comment by trevorsandy** [comment]
I can reproduce this behaviour with the AppVeyor-built distribution (the one you download from GitHub). 
Builds from my development environment do not display this behaviour. Taking a look...

**Comment by trevorsandy** [comment]
The problem has been isolated. 

**Cause:** LPub3D-Trace (customised POV-Ray renderer) fails to parse the command line when there are spaces in the executable file path.
**Unexpected behaviour:** Image is not rendered. LPub3D-Trace exist with the following message in stderr-povray: 
```
Problem with option setting
C:\Users\Trevor\Projects\Working\Zig Edsrogram Biles\LPub3D_x86_64\3rdParty\lpub3d_trace_cui-3.8\bin\lpub3d_trace_cui64.exe -d +I"C:\Users\Trevor\FailTest\LPub3D\tmp\CSILDR~1.POV" +O"C:\Users\Trevor\FailTest\LPub3D\assem\motor_pin_1_0_0_0_1_0_0_0_1_1_1240_150_DPCM_1.png" +W1240 +H1753 +UA +A +L"C:\Users\Trevor\Projects\Working\ZIGEDS~1\LPUB3D~1\3rdParty\LPUB3D~1.8\RESOUR~1\include" +L"C:\Users\Trevor\Projects\Working\ZIGEDS~1\LPUB3D~1\3rdParty\LPUB3D~1.8\RESOUR~1\ini" +L"C:\Users\Trevor\LDraw\lgeo\lg" +L"C:\Users\Trevor\LDraw\lgeo\ar" +L"C:\Users\Trevor\LDraw\lgeo\stl"
Failed to parse command-line option
``` 
Note that spaces in the model file name, the model file path, and library paths **do not** cause this behaviour. For example the following command executes successfully.
```
C:\LPub3D_Maint\LPub3D\3rdParty\lpub3d_trace_cui-3.8\bin\lpub3d_trace_cui64.exe -d
+I"C:\Users\Trevor\Projects\Working\spaces in the file path test\LPub3D\tmp\CSILDR~1.POV"
+O"C:\Users\Trevor\Projects\Working\spaces in the file path test\LPub3D\assem\motor_pin_1_0_0_0_1_0_0_0_1_2_1240_150_DPCM_1.png"
+W1240
+H1753
+UA
+A
```
Here is an excerpt from the above command:
```
Dynamic optimizations:
  CPU detected: Intel,SSE2,AVX,AVX2,FMA3
  Noise generator: avx2fma3-intel (hand-optimized by Intel)

Parser Options
  Input file: C:\Users\Trevor\Projects\Working\SPACES~1\LPub3D\tmp\CSILDR~1.POV
  Remove bounds........On 
  Split unions.........Off
  Library paths:
    C:\Program Files\LPub3D\3rdParty\lpub3d_trace_cui-3.8\resources
    C:\Program Files\LPub3D\3rdParty\lpub3d_trace_cui-3.8\resources\ini
    C:\Program Files\LPub3D\3rdParty\lpub3d_trace_cui-3.8\resources\include
    C:\Users\Trevor\Projects\Working\LPUB3D~2\3rdParty\LPUB3D~1.8\RESOUR~1\include
    C:\Users\Trevor\Projects\Working\LPUB3D~2\3rdParty\LPUB3D~1.8\RESOUR~1\ini
    C:\Users\Trevor\LDraw\lgeo\lg
    C:\Users\Trevor\LDraw\lgeo\ar
    C:\Users\Trevor\LDraw\lgeo\stl
  Clock value:    0.000  (Animation off)
Image Output Options
  Image resolution.....1240 by 1753 (rows 1 to 1753, columns 1 to 1240).
  Output file..........C:\Users\Trevor\Projects\Working\spaces in the file path test\LPub3D\assem\motor_pin_1_0_0_0_1_0_0_0_1_1_1240_150_DPCM_1.png, 32 bpp
 with alpha PNG
  Dithering............Off
  Graphic display......Off
  Mosaic preview.......Off
  Continued trace......Off
```
Note the spaces in the Library paths.

**WORK AROUND**

If you wish to use the LPub3D-Trace (POV-Ray) renderer on Windows, you may do so successfully using a portable (.zip) version of [LPub3D](https://github.com/trevorsandy/lpub3d/releases/download/v2.2.0/LPub3D_x86_64-2.2.0.0.795_20180316.zip). Portable version are available for both [32bit](https://github.com/trevorsandy/lpub3d/releases/download/v2.2.0/LPub3D_x86-2.2.0.0.795_20180316.zip) and [64bit](https://github.com/trevorsandy/lpub3d/releases/download/v2.2.0/LPub3D_x86_64-2.2.0.0.795_20180316.zip) Windows.

Be sure to extract the package into a folder without spaces and, if using v2.1.0 or v2.2.0, you must also manually set the extra search directories where applicable as described in issue #38.

**Comment by trevorsandy** [comment]
Fixed.
