### ISSUE TITLE
Cannot generate multiple images in single call with renderer set to LDView

### ISSUE THREAD

**Issue by d-j-m-0** [trevorsandy/lpub3d#42]
LDView is not running properly to generate multiple images in a single call.

### Your environment
* Version of LPub3D - 2.2
* Operating system - Windows 7, 32 bit.

### Configuration
* LPub3D installation path
  - Windows: `D:\Program Files\LPub3D
* Application data path 
  - Windows: `%USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\`

### Logging
* Application Log: (refer to the tail end of this log file:
[LPub3DLog_2_2_780_povray_ldview_multiple.txt](https://github.com/trevorsandy/lpub3d/files/1831902/LPub3DLog_2_2_780_povray_ldview_multiple.txt)

### Steps to reproduce
Extract the LDR from the attached zip file:
[fade_test.zip](https://github.com/trevorsandy/lpub3d/files/1831904/fade_test.zip)
Open the ldr file using LPub3D version 2.2.
Ensure in the Preferences dialog that LDView is selected as the renderer and the checkbox related to generating multiple images in a single call is ticked.
When the preferences dialog is closed, LPub3D attempts to render the PLI and assembly. It runs LDView (the one bundled with LPub3D version 2.2) but LDView then prompts for a file. Refer to screenshot:
![ldview_multiple_2_2_780](https://user-images.githubusercontent.com/37604323/37692760-9ecd8e38-2d1f-11e8-808a-2b1f3f3982ee.png)
When the "Cancel" button is clicked and then the menu item File/Item selected in LDView, the following dialog window is displayed:
![single_call_dialog_2_2_780](https://user-images.githubusercontent.com/37604323/37692786-d3fe31fc-2d1f-11e8-9fec-3740f62691b5.png)

### Expected behaviour
The instructions page content in LPub3D should be generated correctly. It works correctly using LPub3D version 2.0.

### Actual behaviour
Instead of generating the images, it prompts to open a file within LDView.

### Workaround
Untick the multiple images checkbox in Preferences when using LDView as the renderer.

### Solution suggestion
No idea.

**Comment by trevorsandy** [comment]
This behaviour is most likely linked with #38. I believe the underlying root cause is the same.

**Comment by trevorsandy** [comment]
Fixed.
