### ISSUE TITLE
Feature: modernized buffer exchange

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#43]
I would like to submit a feature request I have had for _years_: buffer exchange working through multiple steps.

**The problem**
The current implementation of buffer exchange only has a start command and everything after the start command is placed in the buffer. That means that if I want to buffer a part in e.g. step 20 and only want to retrieve it in step 25, I need to store and retrieve the same parts in step 20, 21, 22, 23 and 24, because otherwise it would also buffer everything else in the in-between steps.

**The solution**
The solution would be quite simple (in theory at least): being able to mark where the buffer should end. That way LPub3D knows where to stop storing the parts in the buffer. One could extend the current buffer exchange meta command like so:

```
0 BUFEXCHG A STORE BEGIN
// parts
0 BUFEXCHG A STORE END
0 STEP
// parts
0 STEP
0 BUFEXCHG A RETRIEVE
```

And in that case, only the parts between BEGIN and END are stored and when retrieved in the third step, the parts from step 2 remain untouched.

Aside from that, you could also edit the retrieve command like so:

```
0 BUFEXCHG A RETRIEVE BEGIN
// parts
0 BUFEXCHG A RETRIEVE END
```
To remove the need for the PLI BEGIN IGN commands that are usually found together with a buffer exchange retrieve.

You could also create a completely new meta command to keep buffer exchange completely backwards-compatible (instead of partly); either way is fine with me as long as the functionality is there.

In an ideal world, there would also be support for cross-submodel retrieving (e.g. I store a buffer in submodel X and retrieve it later on in its parent model), but that's something for another time.

**Comment by trevorsandy** [comment]
Thanks for submitting this request. I'll add this to LPub3DNext's feature requests.
