### ISSUE TITLE
Page number cannot be placed below PLI

### ISSUE THREAD

**Issue by laurensvalk** [trevorsandy/lpub3d#454]
In an effort to simplify various step numbers in a complicated model, I'm starting to think it may be easier to just use the page number, since it does not reset under any circumstance.

This works nicely, but there seems to be a placement error when trying to put the page number beneath the PLI:

![image](https://user-images.githubusercontent.com/12326241/94367253-d10d1500-00dd-11eb-8436-100d2b932364.png)

This is the default pyramid with 4 settings inserted:

```
0 Example Pyramid for Demonstration of LDRAW Library
0 Name: pyramid.ldr
0 Author: James Jessiman
0 !LPUB PLI PLACEMENT GLOBAL TOP_LEFT PAGE INSIDE
0 !LPUB PAGE NUMBER PLACEMENT BOTTOM LEFT PLI OUTSIDE
0 !LPUB PAGE NUMBER FONT "Sans Serif,48,-1,5,50,0,0,0,0,0"
0 !LPUB ASSEM SHOW_STEP_NUMBER GLOBAL FALSE
1 1 -40 -24 60 1 0 0 0 1 0 0 0 1 3001.dat
1 1 40 -24 60 1 0 0 0 1 0 0 0 1 3001.dat
1 1 60 -24 0 0 0 1 0 1 0 -1 0 0 3001.dat
1 1 40 -24 -60 1 0 0 0 1 0 0 0 1 3001.dat
1 1 -40 -24 -60 1 0 0 0 1 0 0 0 1 3001.dat
1 1 -60 -24 0 0 0 1 0 1 0 -1 0 0 3001.dat
0 STEP
1 4 -20 -48 40 1 0 0 0 1 0 0 0 1 3001.dat
1 4 40 -48 20 0 0 1 0 1 0 -1 0 0 3001.dat
1 4 20 -48 -40 1 0 0 0 1 0 0 0 1 3001.dat
1 4 -40 -48 -20 0 0 1 0 1 0 -1 0 0 3001.dat
0 STEP
1 14 0 -72 20 1 0 0 0 1 0 0 0 1 3001.dat
1 14 0 -72 -20 1 0 0 0 1 0 0 0 1 3001.dat
0 STEP
1 0 0 -96 0 1 0 0 0 1 0 0 0 1 3003.dat
0 STEP
```

**Comment by trevorsandy** [comment]
Placing the page number relative to the PLI or CSI for that matter, is not a currently available placement option. 

As this scenario is limited to pages formatted as single-step or pli-per-page, which rarely form an entire instruction document and; therefore, rarely a reasonable approach, I never looked at implementing it.

However as I’ve added the ability to suppress the step number on a pli-per-page layout, it is now somewhat more reasonable to have this capability.

**Comment by laurensvalk** [comment]
> Placing the page number relative to the PLI or CSI for that matter, is not a currently available placement option.

But there is a dialog for it?

![image](https://user-images.githubusercontent.com/12326241/94376857-83180180-011d-11eb-93bf-21929241189d.png)

And this then produces the number below the page as in the screenshot.

> As this scenario is limited to pages formatted as single-step or pli-per-page, which rarely form an entire instruction document and; therefore, rarely a reasonable approach, I never looked at implementing it.

It is the format of some newer official sets that have digital-only instructions. Usually a very long document with one step per page, to be mobile-friendly.

I'm currently working around the placement by just placing the page==step number to the left-middle of the page, since the PLI is usually small anyway.

Also, I realized now that in this approach

```
ASSEM SHOW_STEP_NUMBER GLOBAL FALSE
```

has an unfortunate side effect, which is that step numbers for callouts also go away, which is probably to be expected.

**Comment by trevorsandy** [comment]
Indeed - Relative to PLI is in the combo list but there is no coded routine to accomodate selecting this option.

> It is the format of some newer official sets that have digital-only instructions. Usually a very long document with one step per page, to be mobile-friendly.

Lol - yep, like writing your thesis on your mobile device. It's entirely possible but one who chooses to do this probably shouldn't be writing a thesis anyway.

```
ASSEM SHOW_STEP_NUMBER GLOBAL FALSE
```

That's right; hence, the reason I did a split for the pli-per-page group step number. It's not intuitive to have to turn off step numbering globally to satisfy a desired page format albeit, turning off and on the step number on a page by page basis is possible. In the future, I may further split turning off step numbering for callouts independently of the global command also.

Cheers,

**Comment by laurensvalk** [comment]
> turning off and on the step number on a page by page basis is possible

Cool, and per step as well. That's awesome. I tried it, and indeed it lets me re-enable the steps in the limited number of callouts that I am currently using.

Thanks again for the hard work on this!
