### ISSUE TITLE
Custom parts not loading and rendering

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#456]
### Subject
My custom parts are not loading and do not render in CSI and PLI

### Environment
* Version 2.4
* Windows 10

### Steps to reproduce
In the previous version I used (2.3.12) my custom parts were archived to lpub3dldrawunf.zip and thus rendered correct.

### Expected behavior
New custom parts should be available. My search paths are cofigured correct.

### Actual behavior
On the loading screen at 70% it says:  Skip parts archive per user preference...

### Workaround
I start and close LPub3D 2.3.12 and copy the lpub3dldrawunf.zip from 2.3.12 to the 2.4 folder

### Solution suggestion
Archive new custom parts. Where do I set the user preference to do so? I cannot find it.

**Comment by trevorsandy** [comment]
Hi Jaco. Thanks for reporting this behaviour. Please see #437. Let me know if 437 solves the unexpected behaviour so I can treat this ticket accordingly.

I'm a bit behind in updating the tickets for v3.4.0 so not all of them will have useful details at this time.

Cheers,

**Comment by jacovandermolen** [comment]
I totally overlooked the menu option and to be honest I didn't expect it
there, but somewhere as a checkbox in the preferences.

Op ma 5 okt. 2020 om 19:55 schreef Trevor SANDY <notifications@github.com>:

**Comment by jacovandermolen** [comment]
Solved.

**Comment by trevorsandy** [comment]
Understood. It is where it is to be more accessible to the user as the expectation is the user will dynamically interact with this option. For example, the user will turn on parts archive for the first load of a new model with custom parts,  and turn it off right after to improve startup performance. The thinking is if there are no new custom parts to archive, there is no need to spend time and cycles going through the archive checks every time the application is started.

Cheers,

**Comment by jacovandermolen** [comment]
OK, thanks. I like it.

Op ma 5 okt. 2020 om 21:58 schreef Trevor SANDY <notifications@github.com>:

**Comment by trevorsandy** [comment]
Excellent. 

There are many new features and enhancements in v2.4. Build Modifications for example is particularly extensive. This new feature is a replacement for Buffer Exchange.

Please do not hesitate to share any unexpected behaviour, or your thoughts, as I’m quite certain they’ll be some with such a large amount of new content.

Cheers,

**Comment by jacovandermolen** [comment]
Do you have any documentation on Build Modifications? I'd like to test that.

Op di 6 okt. 2020 om 14:00 schreef Trevor SANDY <notifications@github.com>:

**Comment by trevorsandy** [comment]
Yes, a concise description and example model file is documented in #411 

Cheers,
