### ISSUE TITLE
Crash when adding multiple next step on allready multistep page

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#459]
### Subject
Crash when adding multiple next steps on already multistep page

### Environment
* Version 2.4
* Windows

### Configuration
* LPub3D installation path
  - Windows: C:\MJ\LEGO\LPub3D_x86_64

### Logs
Cannot attach dump file to this issue

### Screenshots
![afbeelding](https://user-images.githubusercontent.com/32261647/95435423-da567700-0952-11eb-84c1-fbf025f6c1c6.png)
![afbeelding](https://user-images.githubusercontent.com/32261647/95435442-e04c5800-0952-11eb-9656-4d4add09e7eb.png)
![afbeelding](https://user-images.githubusercontent.com/32261647/95435465-e6423900-0952-11eb-881d-4c517c07815d.png)

### Steps to reproduce
Open any model, I test with the pyramid model.
Choose Add Next step
Choose Add Next steps

### Expected behavior
Next steps should be added.

### Actual behavior
I get two errors (see screenshots) and a dump file and LPub closes.

### Workaround
Do not add multiple next steps on an already multistep page.

### Solution suggestion
Metacommands should go in the right place and order. Detect if a page is already multistep if a user adds more next steps.

**Comment by trevorsandy** [comment]
Thanks for reporting this behaviour. 

I took a look and this behaviour only occurs when the step group command `0 !LPUB MULTI_STEP BEGIN` is not  preceded by a `0 STEP` meta command. 

So from the pyramid.ldr example, this block will generate the unexptected behaviour: 

```
0 Example Pyramid for Demonstration of LDRAW Library
0 Name: pyramid.ldr
0 Author: James Jessiman

0 // This file demonstrates how you can assemble a model from part files.
0 // Each line starting with "1" adds one part. It states its color, position and orientation.
0 // Each line reading "0 STEP" begins another step in building the model.
0 // To watch these steps and look at the model, open this file in program LDView.
0 // There, you can go forward and backward through the build steps of this file.
0 // This file intentionally is kept as simple as possible.
0 // LDRAW offers many more things. For more information, visit http://www.ldraw.org

1 1 -40 -24 60 1 0 0 0 1 0 0 0 1 3001.dat
1 1 40 -24 60 1 0 0 0 1 0 0 0 1 3001.dat
1 1 60 -24 0 0 0 1 0 1 0 -1 0 0 3001.dat
1 1 40 -24 -60 1 0 0 0 1 0 0 0 1 3001.dat
1 1 -40 -24 -60 1 0 0 0 1 0 0 0 1 3001.dat
1 1 -60 -24 0 0 0 1 0 1 0 -1 0 0 3001.dat

0 STEP
...
```
 
But if `0 STEP` is added after the header commands and before the first type 1-5 part line, the _Add Next Steps_ command executes as expected. For example, if you change the above example to the sample below the behaviour is as expected.

```
0 Example Pyramid for Demonstration of LDRAW Library
0 Name: pyramid.ldr
0 Author: James Jessiman

0 STEP

0 // This file demonstrates how you can assemble a model from part files.
0 // Each line starting with "1" adds one part. It states its color, position and orientation.
0 // Each line reading "0 STEP" begins another step in building the model.
0 // To watch these steps and look at the model, open this file in program LDView.
0 // There, you can go forward and backward through the build steps of this file.
0 // This file intentionally is kept as simple as possible.
0 // LDRAW offers many more things. For more information, visit http://www.ldraw.org

1 1 -40 -24 60 1 0 0 0 1 0 0 0 1 3001.dat
1 1 40 -24 60 1 0 0 0 1 0 0 0 1 3001.dat
1 1 60 -24 0 0 0 1 0 1 0 -1 0 0 3001.dat
1 1 40 -24 -60 1 0 0 0 1 0 0 0 1 3001.dat
1 1 -40 -24 -60 1 0 0 0 1 0 0 0 1 3001.dat
1 1 -60 -24 0 0 0 1 0 1 0 -1 0 0 3001.dat

0 STEP
...
```

I will update the behavour to handle the first scenario.

Cheers,

**Comment by jacovandermolen** [comment]
OK, I see. I have a legacy concerning Buffer Exchange ;-)
But it seems more logical and workable to give good descriptions.
