### ISSUE TITLE
CSI is cut off by the page size and dpi (zoom to location)

### ISSUE THREAD

**Issue by cameronmiller1988** [trevorsandy/lpub3d#463]
Hey Trevor, 

Long time fan. I have a suggestion/enhancement. I have seen requests for a "zoom to location" function for very large models. 

I looked into the LDView command line for some other stuff and noticed that there is a call for autocrop. Would it be possible to have LPub3D calculate the image size based on the model and not the page? I tried a couple tutorials in QT to read and interpret the code surrounding this but it is beyond what I could comprehend. 

The reason for asking for an image that is large than the page is that a user could simply move the images around to "zoom" to the desired location on the model. I know that LPub3D has not problem with images off the page because of the way multi step pages are handled. 

Forgive me if this isnt the correct venue to request such a thing. 

I also realize this may not be possible for all the renders but I know that the auto crop can be done in LDView. 

### Environment
Inherent program behavior change.

**Comment by trevorsandy** [comment]
Hello Cameron. Thank you for your suggestion and your continued support. 

The capability you are describing is already implemented in v2.4.0. I just haven't had the time to document its ticket - #412. 

As you are comfortable looking at code - here is the commit [4e688159](https://github.com/trevorsandy/lpub3d/commit/4e688159cd0ff8df688b37958b9d39ed12164690)

Cheers,
