### ISSUE TITLE
Change Assembly Camera Angles removes highlighting

### ISSUE THREAD

**Issue by AdvancedStyle** [trevorsandy/lpub3d#468]
### Subject
When right clicking on assembly image and choose "Change Assembly Camera Angles", when the assembly image is regenerated the whole thing is faded (current step is not highlighted)

### Steps to reproduce
1) Right click on assembly image and choose "Change Assembly Camera Angles" and change one of the settings to some other number
2) Choose "This step only: Yes"
3) Image regenerates with all faded steps

### Workaround
In order to make it work you have to clear the model cache (Alt + M), however this also brings up another issue of if you do Alt+M without saving them it resets all your changes.
So current full work around is:
1) Change Camera Angles
2) Ctrl + s (to save)
3) Alt + M (to regenerate cache)

### Environment
* LPub3D-2.4.0.0.1990_20201003-x86_64.AppImage
* Ubuntu 18.04.5 LTS
* 64GB RAM / 36core CPU

### Screenshots
![lpub3d_general](https://user-images.githubusercontent.com/2044211/97020186-286d9c00-1549-11eb-98ac-80365fef0532.png)
![lpub3d_logging](https://user-images.githubusercontent.com/2044211/97020189-29063280-1549-11eb-9755-9a5a0f6147f0.png)
![lpub3d_other](https://user-images.githubusercontent.com/2044211/97020190-299ec900-1549-11eb-9960-d51b39e61004.png)
![lpub3d_publishing](https://user-images.githubusercontent.com/2044211/97020193-299ec900-1549-11eb-9daa-7523bf216fc8.png)
![lpub3d_render](https://user-images.githubusercontent.com/2044211/97020195-299ec900-1549-11eb-938f-fdb49323cfbb.png)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

Camera Angles Before:
![Screenshot - 15_11_2020 , 04_39_50](https://user-images.githubusercontent.com/13388970/99162337-035dea80-26fd-11eb-9213-cd9ee84c72d5.png)

Camera Angles After:
![Screenshot - 15_11_2020 , 04_41_15](https://user-images.githubusercontent.com/13388970/99162340-107ad980-26fd-11eb-99c1-fd17e0e0f518.png)

Cheers,
