### ISSUE TITLE
Crash on export PDF

### ISSUE THREAD

**Issue by AdvancedStyle** [trevorsandy/lpub3d#469]
### Subject
When I try to export my instructions to PDF the program crashes

### Steps to reproduce
1) Open attached model: 
[police_station_2_done.ldr.zip](https://github.com/trevorsandy/lpub3d/files/5430455/police_station_2_done.ldr.zip)
2) Click Export to PDF button (see screenshot):
![Screenshot from 2020-10-23 16-38-26](https://user-images.githubusercontent.com/2044211/97024054-3ffb5380-154e-11eb-85df-9e98413c1dc1.png)
3) Click "Ok"...application loads from 1 to 18 then crashes.
4) PDF file is generated by cannot open as it is Damaged (see attached)
[police_station_2_150_DPI.pdf](https://github.com/trevorsandy/lpub3d/files/5430447/police_station_2_150_DPI.pdf)

### Log
Attached 
[LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/5430453/LPub3DLog.txt)

### Environment
* LPub3D-2.4.0.0.1990_20201003-x86_64.AppImage
* Ubuntu 18.04.5 LTS
* 64GB RAM / 36core CPU

### Screenshots
![lpub3d_general](https://user-images.githubusercontent.com/2044211/97020186-286d9c00-1549-11eb-98ac-80365fef0532.png)
![lpub3d_logging](https://user-images.githubusercontent.com/2044211/97020189-29063280-1549-11eb-9755-9a5a0f6147f0.png)
![lpub3d_other](https://user-images.githubusercontent.com/2044211/97020190-299ec900-1549-11eb-9960-d51b39e61004.png)
![lpub3d_publishing](https://user-images.githubusercontent.com/2044211/97020193-299ec900-1549-11eb-9daa-7523bf216fc8.png)
![lpub3d_render](https://user-images.githubusercontent.com/2044211/97020195-299ec900-1549-11eb-938f-fdb49323cfbb.png)

**Comment by trevorsandy** [comment]
Thank you for report this behaviour and providing an example. I'll take a look.

Cheers,

**Comment by AdvancedStyle** [comment]
I've found that this issue occurs if you are missing the final "0 STEP" in the code (i think I must have deleted this at some point thinking this indicated a final empty step)
