### ISSUE TITLE
Feature Request: Offset Step Counter

### ISSUE THREAD

**Issue by AdvancedStyle** [trevorsandy/lpub3d#472]
It would be very useful to be able to set what number the steps start on (instead of "1").

For example if you have a multi-floor build I find it easier to break down each floor into a separate instruction file; the problem is each floor will start with "Step 1" so you can't really join the instruction PDFs together later.

So add a couple of new settings:
- In "Page Setup" add a "Starting Page Number:" (default to "1")
- In "Assembly Setup" add a "Starting Step Number:" (default to "1")

It might also be useful to be able to manual change the number of a specific step by right clicking on the number and overwriting the number with arbitrary text

**Comment by trevorsandy** [comment]
Thank you for your suggestion.

I have added this capabiity to the next release. See #477.

Cheers,
