### ISSUE TITLE
Some weird stuff going on with step group margins and step-number placement

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#474]
So, I'm not exactly sure if something's going wrong here or if I'm just misunderstanding stuff, but the situation is as follows:

I have this step group:
![image](https://user-images.githubusercontent.com/12005521/97572421-7d496080-19e8-11eb-975a-cf588cc70c83.png)

The placement of the step-numbers is as follows:
![image](https://user-images.githubusercontent.com/12005521/97572466-8fc39a00-19e8-11eb-94a0-396b0bf392a3.png)

I want to increase the (vertical) space between the two steps. So I go into the step-group settings. And I change one of these (I'm not exactly sure what the difference is, but it doesn't matter for this issue):
![image](https://user-images.githubusercontent.com/12005521/97572903-43c52500-19e9-11eb-94df-c331d29a3b72.png)

So, if I change either of them, I expect the space between the different steps to increase. And it does. But what I don't expect is that the step number moves, but it does. Take a look at this and compare to the first image:
![image](https://user-images.githubusercontent.com/12005521/97573022-69522e80-19e9-11eb-8646-22a7f97bf886.png)

The space between the PLI and step number has increased too, but I don't know why and I don't want it either. How can I keep the step number from moving down when I increase the margin between the steps in a step group?

**Comment by Landcross** [comment]
I just realized the following: even though my step-number is configured to allign with the bottom of the PLI (see configuration in the above post), it seems to align with the bottom of the 'step-group-item' or something (for lack of a better term). See this:
![image](https://user-images.githubusercontent.com/12005521/97593408-f73a1380-1a01-11eb-9674-d3e80d0e258b.png)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

It looks like this might be a 'side-effect' of the last behaviour update to Step Groups:

![Screenshot - 30_10_2020 , 14_10_16](https://user-images.githubusercontent.com/13388970/97708995-ecdb5080-1ab9-11eb-854c-a29959ba7477.png)

I'll take a look.

Cheers,

**Comment by Landcross** [comment]
Oh, so that _is_ a new feature. I was already wondering whether I just never noticed that step justification setting before, or whether it was new. I don't really understand what it's doing either. There seems to be very little difference (at least on my test page).

Nevertheless, changing that setting didn't seem to have any real effect on this issue. Yes, things seemed to move a bit here and there, but the step number was never aligned with the bottom of the PLI, no matter the justification setting.

**Comment by trevorsandy** [comment]
Indeed, the behaviour you are describing is not expected. 

Anyway, see #333 for details on how the step-group step justification behaves.

Cheers,

**Comment by Landcross** [comment]
Just a little heads-up, just in case. The behavior described in the issue above is not limited to LPub3D 2.4, LPub3D 2.3 also behaves the same.

**Comment by trevorsandy** [comment]
Indeed, #333 was introduced in v2.3.13 so I expect this behaviour to be present from that version.

Cheers,

**Comment by trevorsandy** [comment]
If you are still having difficulty with this item, the following two steps, using the default step justification (Left), will yield the layout you expect.

1. Set the divider length to _Page_ - see the divider context menu item to launch the divider dialogue. The `LOCAL` meta command is:

`0 !LPUB MULTI_STEP SEPARATOR LOCAL PAGE_LENGTH THICKNESS 0.03 "black" MARGINS 0.5 0.05`

2. Set only the L[eft]/R[ight] assembly margin to extend the width of each step.

`0 !LPUB MULTI_STEP ASSEM MARGINS GLOBAL 0.8000 0.0100`

Result:

![Screenshot - 07_12_2020 , 08_55_24](https://user-images.githubusercontent.com/13388970/101324100-fea6d500-3869-11eb-80b8-10a172de466c.png)

Note: To have the divider span closer to the edge of the page top/bottom, adjust the header/footer height in _Page Globals Setup_. 

Cheers,

**Comment by trevorsandy** [comment]
Fixed.

Cheers,
