### ISSUE TITLE
Feature request: being able to move the camera of the assembly image

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#481]
I have another feature request. I'm not 100% sure if it's already in LPub3D, but I think it's not.

I'd love to be able to move the camera of the assembly image; move the center point of the model. When working on larger models, they usually don't fit on a single page without using a very small scale. Usually parts in a step are only added on a specific location, and it would be nice to be able to look at that specific location. Currently LPub3D only centers the camera on the center of the model.

And for completeness sakes: I personally would like to have this feature using LDVew as renderer.

Similar software such as Bricklink's stud.io does support this feature. For example, when I move this assembly image down:
![image](https://user-images.githubusercontent.com/12005521/98783570-15d4dd00-23fa-11eb-88ef-69281c1fdba5.png)

It looks like this:
![image](https://user-images.githubusercontent.com/12005521/98783591-1e2d1800-23fa-11eb-8927-39793bfaacca.png)

**Comment by trevorsandy** [comment]
This behaviour is currently available in v2.4 - see #412. 

There are still some display alignment tweaks between the 3DViewer and the model document outstanding. It's a bit tricky considering each renderer is using different default camera settings. Anyway, if you are mainly interested in the model document image, you are free to play with the generated camera settings meta commands until you achieve your desired display. Once set, the renderer will always produce the same display based on the defined settings.

This ticket also references the same behaviour requested in #463 

Cheers,

**Comment by Landcross** [comment]
Hmm, I was already playing with that 3DViewer before this feature request, because I was already kinda expected something like this was in there. But I couldn't get it to work and thought it was just not there, so I made this request.

But apparently it is there, and I just can't get it to work properly. No matter what I do in the 3D viewer, the rendered assembly image does not match what I'm viewing. Furthermore, after I press Save Camera Settings, the 3DViewer jumps to another view anyway.

Maybe I'm just doing stuff completely wrong, but I doubt it. I could make a screencapture and email it to you, if you don't mind? That would show what I'm doing and what I'm seeing better and easier than any text.

**Comment by trevorsandy** [comment]
There could be some unexpected behaviour triggered by other new features in v2.4 - notably the new Build Modification and Viewer-Editor integration. The next maintenance build will have better performance and stability.

I’m working on the last outstanding tickets before releasing the next maintenance build hopefully before the weekend is over.

> No matter what I do in the 3D viewer, the rendered assembly image does not match what I'm viewing. 

The behaviour you are describing is what I have acknowledged in the following statement:

> There are still some display alignment tweaks between the 3DViewer and the model document outstanding. It's a bit tricky considering each renderer is using different default camera settings. Anyway, if you are mainly interested in the model document image, you are free to play with the generated camera settings meta commands until you achieve your desired display. Once set, the renderer will always produce the same display based on the defined settings.

Are you unable to reposition and/or zoom your images - i.e using the 3DViewer initially and manual meta command tuning for precision ?

Cheers,

**Comment by Landcross** [comment]
> Are you unable to reposition and/or zoom your images - i.e using the 3DViewer initially and manual meta command tuning for precision ?

No matter how I manually change the camera parameters, I can't seem to be able to move the camera. Only zoom in and out :/

**Comment by trevorsandy** [comment]
Are you following the steps outlined [here ](https://github.com/trevorsandy/lpub3d/issues/412#issue-703981088)?

Are the following meta commands present `ASSEM CAMERA_ANGLES, ASSEM CAMERA_TARGET` in your model for the ASSEM you are attempting to minipulate ?

Do you have any abnormal (ERROR) messages in your log ?

Cheers,

**Comment by trevorsandy** [comment]
Closing this ticket. If you continue to experience this behaviour, do not hesitate to reopen.

Cheers,
