### ISSUE TITLE
Double Assembly Margins in callout/step-group settings

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#482]
In LPub 2.4 the Callout and Step Group settings have double assembly margin settings. See also this image:
![image](https://user-images.githubusercontent.com/12005521/98965373-4310b080-250a-11eb-8695-aa556f1e6574.png)

If you change either of them, save the settings and then reopen the popup, you'll see both have changed, so they change the same setting.

They do seem, however, to create two separate !LPUB commands in the file:
![image](https://user-images.githubusercontent.com/12005521/98965678-9c78df80-250a-11eb-838f-35bca549921a.png)

To be complete, I could find double assembly margin settings in:

- Callout Setup -> Contents -> Assembly
- Step Group Setup -> Assembly

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected. 

![Screenshot - 15_11_2020 , 07_07_47](https://user-images.githubusercontent.com/13388970/99178238-50e45280-2711-11eb-9e0f-d42a05f4445e.png)

The _Assembly Image_ Margins are applied to the range background item in a multi-step page. The correct syntax is:

`0 !LPUB CALLOUT ASSEM MARGINS GLOBAL 0.3000 0.0000`

The _Assembly Margins_ is applied at CSI placement calculation using the following syntax:

`0 !LPUB CALLOUT MARGINS GLOBAL 0.5000 0.5000`

They should not share the same meta attribute. 

I suspect this behaviour may be the source of the unexpected behavioiur described in #474.

This behavioiur has been corrected in v2.4.1.

cheers,
