### ISSUE TITLE
Changing colors and text size to LDRAW editor (especially numbers)

### ISSUE THREAD

**Issue by DanieleBenedettelli** [trevorsandy/lpub3d#484]
### Subject
When using the light theme, numbers are orange and almost unreadable in the LDRAW text editor.

### Workaround
I tried the dark theme to no avail.

### Solution suggestion
Is it possible to manually change the colors of the various parts (numbers, metas, etc)?
Is there any manually editable file for this?

**Comment by trevorsandy** [comment]
Hello Daniele, 

Thank you for your request. Not yet, but the first phase of this enhancement is in the queue and will be soon available. I will move all colour settings to the LPub3D platform-specific settings location. This will be the LPub3D.ini file on Windows portable distros for example.

Cheers,

**Comment by trevorsandy** [comment]
All Theme colours can be edited from the Preferences dialogue in v2.4.1- see #490:

![Screenshot - 07_12_2020 , 07_37_57](https://user-images.githubusercontent.com/13388970/101317752-64da2a80-385f-11eb-8871-0190c0fd1873.png)

Cheers,

**Comment by trevorsandy** [comment]
Implemented.

Cheers,
