### ISSUE TITLE
crash while draggin callouts and pointers

### ISSUE THREAD

**Issue by DanieleBenedettelli** [trevorsandy/lpub3d#486]
### Subject
When I create a pointer and soon after than I drag to move it, LPUB crashes.
It seems I need to wait for the META command to be committed to the file.
Same happens when I change the placement of an item and then I move it.

### Environment
2.4.0 revision 0 build 1990
Win 10 x64

Dump attached
[LPub3D.zip](https://github.com/trevorsandy/lpub3d/files/5589941/LPub3D.zip)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

It is corrected in v2.4.1 - see #466

Cheers,

**Comment by DanieleBenedettelli** [comment]
I tried a LPUB3D-CI
and this is new...

*0 !LPUB CALL CALLOUUOLLAC BUPL! 0*

N ROTATEDT POINTER BOTTOM 0.472 0.545 0.037 0.500 0.500 0.500 0.500 0.500
0.500 0.000 1

1 4 -240 -100 -220 0.809 0 0.588 0 1 0 -0.588 0 0.809 horn_right.ldr

0 !LPUB CALLOUT PLACEMENT TOP RIGHT ASSEM OUTSIDE OFFSET -0.4723 -0.2274

0 !LPUB CALLOUT END



Il giorno mar 24 nov 2020 alle ore 14:13 Trevor SANDY <
notifications@github.com> ha scritto:

**Comment by trevorsandy** [comment]
I don't understand. What's new ? 

The sample commands looks corrupted. 

Was this the result of dragging a callout and pointer in the DevOps (lpub3d-ci) build ?

Cheers,

**Comment by DanieleBenedettelli** [comment]
Actually, the same behavior is in release 2.4.0.
I submitted an issue, and reverting back to old versions, as this is
preventing me to finish the work.

D

Il giorno mar 24 nov 2020 alle ore 15:06 Trevor SANDY <
notifications@github.com> ha scritto:

**Comment by DanieleBenedettelli** [comment]
After a CALLOUt POINTER DRAG it replaces the good lines with the file
initial lines in the LPUB text editor, while on the external editor the
file is changed correctly.


Il giorno mar 24 nov 2020 alle ore 15:10 Daniele Benedettelli <
danielebenedettelli@gmail.com> ha scritto:

**Comment by trevorsandy** [comment]
Implemented, see #466.

Cheers,
