### ISSUE TITLE
LDRAW file messed up 

### ISSUE THREAD

**Issue by DanieleBenedettelli** [trevorsandy/lpub3d#487]
### Subject
File is messed up when moving CSI or other mouse or manual text editing.

### Environment
2.4.0 build 1990
WIn10 x64

Sometimes the file gets messed up (but checking the file in external text editor is fine)
![weird_bug_mess_up_file](https://user-images.githubusercontent.com/47357389/100104508-94079980-2e66-11eb-88fe-45526107f962.png)
Then, going back one page and forward to the same page, the file is fine.
![weird_bug_mess_after_page_change](https://user-images.githubusercontent.com/47357389/100104512-94a03000-2e66-11eb-8e8b-537b448ee1a9.png)
If you manually edit the messed up version, the file gets effectively corrupted.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

Indeed, this behaviour was first reported in #476. I'm currently working on it.

Cheers,

**Comment by DanieleBenedettelli** [comment]
FYI, to keep working reliably, I reinstalled v.2.3.13 r0 which does not
have that issue.

Thanks for all your work on this.
D

Il giorno mar 24 nov 2020 alle ore 17:16 Trevor SANDY <
notifications@github.com> ha scritto:

**Comment by DanieleBenedettelli** [comment]
Good morning.
Sorry to bother. Which is the latest release or beta without that issue?
I really need it to continue working on my book. In order to speed up the
release of version 2.4.1, I am willing to contribute with a donation if
appreciated.

Regards,
D


Il mar 24 nov 2020, 18:02 Daniele Benedettelli <
danielebenedettelli@gmail.com> ha scritto:

**Comment by trevorsandy** [comment]
Hello Daniele,

To be sure I'm clear. You have tried the last development build and can confirm the _scrambled_ LDraw text is present in that relesase ?

This behaviour started with the new _buffered pageing_ capability introduced in 2.4.0 r0. I expect to correct it for 2.4.1 and have already taken steps to do so in the latest development build; nevertheless, I am still finding scenarios where unexpected behaviour persists so I'm working through those at the moment.

Some steps you can take now to mitigate this behaviour:

You can download and extract a portable distribution of the latest DevOps build [(b2415 r195)](https://github.com/trevorsandy/lpub3d-ci/releases) and perform the following steps as needed. This way, there is not need to install or uninstall the application. Just extract and start working. If the build is unsatisfactory, just delete the downloaded archive and extract folder.

You can turn off _buffered paging_ from the new Editor _Preferences_ menu item.

![Screenshot - 25_11_2020 , 07_24_58](https://user-images.githubusercontent.com/13388970/100191487-7e3eb680-2ef0-11eb-8dd9-8575f6982bff.png)

You can complete your editing in Notepad++ (there is an LDraw syntax definition file the LPub3D extras subfolder that you can import to prettify the text decoration) and LPub3D will automatically detect changes and prompt you to refresh the content accordingly.

Cheers,

**Comment by DanieleBenedettelli** [comment]
Thank you.
Editing is smoother, and without buffering, that bug is gone.
I tried to export a page, but it gives these errors, although the page
parameters are set to custom ones.
Here's the log:
2020-11-25T09:13:32.475 ERROR "Could not load page 1 layout parameters."
2020-11-25T09:13:34.296 ERROR "Could not load page 1 size parameters."
2020-11-25T09:13:34.829 ERROR "Could not load page 1 orientation
parameter."
2020-11-25T09:13:35.356 NOTICE void __cdecl Gui::exportAsPdf(void) @ln 898
"                  Exporting page 1 of 1, size(pixels) W 0 x H 0,
orientation Portrait, DPI 300, pixel ratio 1..."

Unless I solve this problem, it's unusable.
Thanks,
D

Il giorno mer 25 nov 2020 alle ore 07:40 Trevor SANDY <
notifications@github.com> ha scritto:

**Comment by trevorsandy** [comment]
Very well. 

> I tried to export a page, but it gives these errors, although the page
parameters are set to custom ones.

I'll take a look.

To progress faster, can you share the complete LPub3D log and a sample model file that produces this behavour ?

You can share the file via my email address if you do not care to attache it here.

Cheers,

**Comment by DanieleBenedettelli** [comment]
This is enough to reproduce the bug.

D

Il giorno mer 25 nov 2020 alle ore 09:26 Trevor SANDY <
notifications@github.com> ha scritto:

**Comment by trevorsandy** [comment]
Very well - Thanks.

Cheers,

**Comment by trevorsandy** [comment]
FYI - Printing has been restored in the dev build.

Cheers,

**Comment by DanieleBenedettelli** [comment]
Thank you so much!
Do I find it under the same page, same build number and revision?
https://github.com/trevorsandy/lpub3d-ci/releases

Il giorno mer 25 nov 2020 alle ore 16:36 Trevor SANDY <
notifications@github.com> ha scritto:

**Comment by trevorsandy** [comment]
> Do I find it under the same page, same build number and revision?

Yes, you will find the new build at the same URL, and no, the date, build number, and revision will be updated. 

A build takes about 40 minutes once started.

Cheers,

**Comment by DanieleBenedettelli** [comment]
Ah, the upload is automatic after the build. Cool, thanks!

D

Il mer 25 nov 2020, 17:19 Trevor SANDY <notifications@github.com> ha
scritto:

**Comment by trevorsandy** [comment]
Fixed.

Cheers,
