### ISSUE TITLE
CALLOUT ROTATED shows all the steps instead of last step only

### ISSUE THREAD

**Issue by DanieleBenedettelli** [trevorsandy/lpub3d#489]
### Subject
as subject says

### Environment
LPUB3D dev release 2.4.0 r 204 build 2424
Win 10 x64

### Expected behaviour
In v. 2.3.13 when creating a callout and right clicking to add Assembled Image to Parent Image, only the last step of a submodel should be shown in the callout, but all the steps are now shown.
[test_callout_assembled_bug.zip](https://github.com/trevorsandy/lpub3d/files/5604190/test_callout_assembled_bug.zip)

### Workaround
none

### Solution suggestion
Revert some changes occurred in latest versions

**Comment by trevorsandy** [comment]
This behaviour has been corrected in v2.4.1

![Screenshot - 07_12_2020 , 07_33_58](https://user-images.githubusercontent.com/13388970/101317364-a918fb00-385e-11eb-9708-f81e607743da.png)

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

Cheers,
