### ISSUE TITLE
PLI and PAGE NUMBER PLACEMENT broken

### ISSUE THREAD

**Issue by DanieleBenedettelli** [trevorsandy/lpub3d#495]
### Subject
PLI PLACEMENT meta does not work as it did in LPub3D BETA 2.4.0.204.2424
PAGE NUMBER PLACEMENT is broken too.

### Environment
Win 10 x64
LPub3D BETA 2.4.0.271.2491

### Screenshots
How it shows up in 2424 dev build
![2424](https://user-images.githubusercontent.com/47357389/103341161-670e5e00-4a86-11eb-93d0-b11cf5f8ff1a.png)

How it shows up in 2491 dev build
![2491](https://user-images.githubusercontent.com/47357389/103341166-68d82180-4a86-11eb-9f7b-2576720287de.png)

### Steps to reproduce
0 !LPUB PLI PLACEMENT TOP_LEFT PAGE INSIDE 0.1 0.07
Offset numbers have no effect.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

> How it shows up in 2424 dev build

If the command `0 !LPUB PLI PLACEMENT TOP_LEFT PAGE INSIDE 0.1 0.07` produced the display shown for DevOps build 2424, then it was wrong. However, I am not able to produce this behaviour in the latest development build so this is no longer an issue.


> How it shows up in 2491 dev build

This behaviour is as expected for for the command 0 !LPUB PLI PLACEMENT TOP_LEFT PAGE INSIDE 0.1 0.07. Were you expecting something different ?

I am not able to determine what is currently broken from the current information in this ticket. If you can provide any additional details do not hesitate.

Cheers,

**Comment by DanieleBenedettelli** [comment]
> > How it shows up in 2491 dev build
> 
> This behaviour is as expected for for the command 0 !LPUB PLI PLACEMENT TOP_LEFT PAGE INSIDE 0.1 0.07. Were you expecting something different ?
> 
I was expecting the offsets to be applied, moving the PLI to the right and down a bit.
Why is this not working anymore? 

Thanks,
D

**Comment by DanieleBenedettelli** [comment]
This works:
0 !LPUB PLI PLACEMENT TOP_LEFT PAGE INSIDE OFFSET 0.1 0.06

**Comment by trevorsandy** [comment]
Excellent,

Cheers,
