### ISSUE TITLE
CALLOUT PLACEMENT X PLI OUTSIDE does not work

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#498]
### Subject
CALLOUT PLACEMENT X PLI OUTSIDE does not work
Where X is anywhere (top right, bottom left, etc.)

### Environment
* Version Dev-release 2.4.0 Revision 310 Build 2530 Hash 4181e10c
* Windows 10

### Configuration
Portable distro

### Steps to reproduce
Convert submodel to Callout and set placement to PLI X OUTSIDE

### Expected behaviour
The callout should be placed relative at the PLI where I set I want it to be.

### Actual behaviour
The callout is placed in the left upper corner of the page, what ever position to the PLI is set.

### Workaround
Move Callout by hand

![afbeelding](https://user-images.githubusercontent.com/32261647/105357750-8caa0580-5bf5-11eb-98ae-f51a825dfa99.png)

[pliplacementtest.mpd.txt](https://github.com/trevorsandy/lpub3d/files/5849635/pliplacementtest.mpd.txt)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

If I well understand, you are adding the above meta command manually after converting the Callout using a menu action. I will check, but I curious to know if you also got this behaviour when using the placement dialogue ?

Cheers,

**Comment by jacovandermolen** [comment]
> If I well understand, you are adding the above meta command manually after converting the Callout using a menu action. I will check, but I am curious to know if you also got this behaviour when using the placement dialogue ?

Alas, no. I did not add it by hand, I only used the dialog, which then places the meta-command.

**Comment by trevorsandy** [comment]
Very well. Thanks for the update. I'm working on this now.

Cheers,

**Comment by jacovandermolen** [comment]
OK, I see this is solved in the DevOps Build 2538 (r318).

**Comment by trevorsandy** [comment]
Fixed.

Cheers,
