### ISSUE TITLE
Lpub3D 2.4 - multiple errors

### ISSUE THREAD

**Issue by forelockmocs** [trevorsandy/lpub3d#500]
I've just installed version 2.4. Unfortunately I have a lot of errors. I will reinstall the previous version for now.

Error 1:
It keeps giving me this message at startup:
"Could not open the LEGO LDraw color parts file [], Error: No file name specified. Would you like to generate it now?" Of course I always click on "Yes" (generate one) but the issue keeps popping up. 

![01](https://user-images.githubusercontent.com/62996120/105576502-6b6f2380-5d73-11eb-80e2-63ffd7244261.JPG)
](url)

Error 2:
I also have a LOT of errors when opening a file that worked fine in version 2.3 regarding an invalid substitute meta command.

![02](https://user-images.githubusercontent.com/62996120/105576514-7b870300-5d73-11eb-905e-a8fc5aa83dfa.JPG)

Error 3: 
The file gets messed up (that issue was already reported)

Error 4:
When giving the command to go to the next page (from page 2 to 3) it goes to page 1 instead and start recounting the number of pages.

### Environment
* Version of LPub3D - 2.4.0 build 0
* Operating system - Windows 10 Home - Intel Core i7-8700

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

Please take a look at the latest [LPub3D release](https://github.com/trevorsandy/lpub3d/releases) v2.4.1.

I will close this ticket. If you continue to experience this behaviour, do not hesitate to reopen.

Cheers,
