### ISSUE TITLE
Make generate arrows optional when converting to callout

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#501]
### Subject
Make generate arrows optional when converting to callout

Currently, I am working on a model that uses many small submodels that need to be called out. Some steps have over 30 or more instances of one certain submodel. When converting to a call out, an arrow is generated for each use of the same submodel. This takes rather long and is, in my case, not necessary. 

So my question is: can it be made optional to automatically generate arrows from callouts?
One can always add one or more arrows later.

I believe I asked this before, but cannot find the issue.

**Comment by trevorsandy** [comment]
Yes, this is a useful use case and is somewhat trivial to implement.

I don’t recall seeing this request before. I’ll add it to the queue.

Cheers,

**Comment by jacovandermolen** [comment]
Great! Tnx.

**Comment by trevorsandy** [comment]
Implemented.
![Screenshot - 10_02_2021 , 14_23_29](https://user-images.githubusercontent.com/13388970/107515770-c0040280-6bab-11eb-8c9e-5587954db802.png)

![Screenshot - 10_02_2021 , 14_23_50](https://user-images.githubusercontent.com/13388970/107515784-c72b1080-6bab-11eb-994b-e26523bb43d7.png)

Cheers,

**Comment by jacovandermolen** [comment]
Great! Looks good ;-)

**Comment by trevorsandy** [comment]
Implemented.

Cheers,
