### ISSUE TITLE
LPub3d crashes on startup (Mac)

### ISSUE THREAD

**Issue by welsmore** [trevorsandy/lpub3d#503]
### Subject
Pretty much as above, crashes on startup using 99% of CPU.

### Environment
* 4.2 - just downloaded
* Operating system - MacOS 11.2 and 11.2.1 (Big Sur)

### Configuration

* LPub3D installation path
  - macOS: `/Applications/LEGO CAD Software/LPub3D.app`
* Application data path

  - macOS: `~/Library/Application Support/LPub3D Software/LPub3D/` (same effect if I copy it just into 'Applications'

* Registry Extract

  - macOS: I tried deleting the old .plist file to see if that would cure it, it didn't. So brand new one:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Logging.AllLogLevels</key>
	<false/>
	<key>Logging.DebugLevel</key>
	<false/>
	<key>Logging.ErrorLevel</key>
	<false/>
	<key>Logging.FatalLevel</key>
	<false/>
	<key>Logging.IncludeAllLogAttributes</key>
	<false/>
	<key>Logging.IncludeFileName</key>
	<false/>
	<key>Logging.IncludeFunction</key>
	<true/>
	<key>Logging.IncludeLineNumber</key>
	<true/>
	<key>Logging.IncludeLogLevel</key>
	<true/>
	<key>Logging.IncludeTimestamp</key>
	<false/>
	<key>Logging.InfoLevel</key>
	<false/>
	<key>Logging.LogLevel</key>
	<true/>
	<key>Logging.LogLevels</key>
	<false/>
	<key>Logging.Logging</key>
	<true/>
	<key>Logging.LoggingLevel</key>
	<string>STATUS</string>
	<key>Logging.NoticeLevel</key>
	<false/>
	<key>Logging.StatusLevel</key>
	<false/>
	<key>Logging.TraceLevel</key>
	<false/>
	<key>Settings.LDrawLibrary</key>
	<string>LEGO</string>
</dict>
</plist>

* Renderer configuration files
All as per a standard (new) installation

### Logs
I have an application log I can send you - it's about 2Mb. It ends like this every time;
ERROR static void Annotations::annotationMessage(QString &, Where &) @ln 2706 Regular expression pattern was not found in titleAnnotations.lst. Be sure the following lines exist in the file header: # File: titleAnnotations.lst # The Regular Expression used is: ^(\b.*[^\s]\b:)\s+([\(|\^].*)$ (file: titleAnnotations.lst) 
ERROR static void Annotations::annotationMessage(QString &, Where &) @ln 2706 Regular expression pattern was not found in freeformAnnotations.lst. Be sure the following lines exist in the file header: # File: freeformAnnotations.lst # The Regular Expression used is: ^(\b.*[^\s]\b)(?:\s)\s+(.*)$ (file: freeformAnnotations.lst) 
INFO void Application::initialize() @ln 750 "Initializing application..." 
INFO void Application::initialize() @ln 753 ----------------------------- 
INFO void Application::initialize() @ln 754 "LPub3D v2.4.0 for macOS 64bit" 
INFO void Application::initialize() @ln 755 ============================= 
INFO void Application::initialize() @ln 756 "Arguments....................()" 
INFO void Application::initialize() @ln 759 "macOS Binary Directory.......(MacOS)" 
INFO void Application::initialize() @ln 765 "macOS Base Directory.........(LEGO CAD Tools)" 
INFO void Application::initialize() @ln 784 "LPub3D App Data Path.........(/Users/warrenelsmore/Library/Application Support/LPub3D Software/LPub3D)" 
INFO void Application::initialize() @ln 786 "LPub3D Bundle App Path.......(/Applications/LEGO CAD Tools)" 
INFO void Application::initialize() @ln 809 "LPub3D Extras Resource Path..(/Applications/LEGO CAD Tools/LPub3D.app/Contents/Resources)" 
INFO void Application::initialize() @ln 815 "LPub3D Loaded LDraw Library..(LEGO® Parts)" 
INFO void Application::initialize() @ln 816 "Logging Level................(STATUS (0), Levels: [status,info,trace,debug,notice,error,fatal,off])" 
INFO void Application::initialize() @ln 818 "Debug Logging................(Enabled)" 
INFO void Application::initialize() @ln 819 ----------------------------- 
INFO void Application::initialize() @ln 750 "Initializing application..." 
INFO void Application::initialize() @ln 753 ----------------------------- 
INFO void Application::initialize() @ln 754 "LPub3D v2.4.0 for macOS 64bit" 
INFO void Application::initialize() @ln 755 ============================= 
INFO void Application::initialize() @ln 756 "Arguments....................()" 
INFO void Application::initialize() @ln 759 "macOS Binary Directory.......(MacOS)" 
INFO void Application::initialize() @ln 765 "macOS Base Directory.........(Applications)" 
INFO void Application::initialize() @ln 784 "LPub3D App Data Path.........(/Users/warrenelsmore/Library/Application Support/LPub3D Software/LPub3D)" 
INFO void Application::initialize() @ln 786 "LPub3D Bundle App Path.......(/Applications)" 
INFO void Application::initialize() @ln 809 "LPub3D Extras Resource Path..(/Applications/LPub3D.app/Contents/Resources)" 
INFO void Application::initialize() @ln 815 "LPub3D Loaded LDraw Library..(LEGO® Parts)" 
INFO void Application::initialize() @ln 816 "Logging Level................(STATUS (0), Levels: [status,info,trace,debug,notice,error,fatal,off])" 
INFO void Application::initialize() @ln 818 "Debug Logging................(Enabled)" 
INFO void Application::initialize() @ln 819 ----------------------------- 

### Screenshots
N/A

### Steps to reproduce
Start app

### Expected behaviour
Should start

### Actual behaviour
Doesn't start

### Workaround
None

### Solution suggestion
None!

**Comment by welsmore** [comment]
I've just tried the CI build - and that does work. Similar RegEx errors as above, but it will at least start :-)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

> ERROR static void Annotations::annotationMessage(QString &, Where &) @ln 2706 Regular expression pattern was not found in titleAnnotations.lst. Be sure the following lines exist in the file header: # File: titleAnnotations.lst # The Regular Expression used is: ^(\b.[^\s]\b:)\s+([(|^].)$ (file: titleAnnotations.lst)
ERROR static void Annotations::annotationMessage(QString &, Where &) @ln 2706 Regular expression pattern was not found in freeformAnnotations.lst. Be sure the following lines exist in the file header: # File: freeformAnnotations.lst # The Regular Expression used is: ^(\b.[^\s]\b)(?:\s)\s+(.)$ (file: freeformAnnotations.lst)

The annotation files are not compatible with the CI version of LPub3D - they are the old ones from 2.3.13. Remove these file(s) and up-to-date versions will be written on subsequent LPub3D startup. It goes without saying you should take steps to preserve any custom entries you have made in the old annotation files. The working instance of these files should be under `~/Library/Application Support/LPub3D Software/LPub3D/extras`

> The following LDView libraries were not found:%2%2-/opt/X11/lib/libOSMesa.dylib - invalid version.

> and similar for POVray as well, but I think these are issues you're already aware of? It will at least start and seems to be stable :-)

Looks like the macOS required library check is failing again. The log entry is benign if LPub3D starts. It likely means the library is available and of a compatible version but was not found or the search string to return the library version was somehow not well formed. Note, if your librarys are compatible, you can disable the library check in the plist. See #57 and #146 for details on this behaviour. Anyhow, I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Closing this ticket. If this behaviour is present in the latest LPub3D release, do not hesitate to reopen.

Cheers,
