### ISSUE TITLE
CALLOUT BACKGROUND COLOR not applied when meta is included

### ISSUE THREAD

**Issue by DanieleBenedettelli** [trevorsandy/lpub3d#504]
### Subject
When the metacommand
0 !LPUB CALLOUT BACKGROUND COLOR "#ffffff"
is in an included header instead of in the file itself, it's ignored.

### Environment
LPUB 3D 2.4.0 rev 303 build 2523
Win 10 x64

### Steps to reproduce
create a header file 
add meta 0 !LPUB CALLOUT BACKGROUND COLOR "#ffffff"
include header in main file
create callout

### Expected behaviour
callout should have white background

### Actual behaviour
callout has submodel color background

### Workaround
I need to add the meta
0 !LPUB CALLOUT BACKGROUND COLOR "#ffffff"
in the main file again,

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I’ll take a look.

Cheers,

**Comment by trevorsandy** [comment]
I'm not able to reproduce this behaviour on the latest DevOps build. 

![Screenshot - 14_02_2021 , 03_32_03](https://user-images.githubusercontent.com/13388970/107866836-469f3500-6e75-11eb-89dc-65dc01e0543d.png)

Let me know if the latest build resolves this behaviour for you.

Cheers,

**Comment by trevorsandy** [comment]
Cannot reproduce. 

If you continue to experience this behaviour with the latest LPub3D release, please do not hesitate to reopen this ticket.

Cheers,
