### ISSUE TITLE
Execute fade, highlight, and preferred renderer from meta command

### ISSUE THREAD

**Issue by trevorsandy** [trevorsandy/lpub3d#505]
###  Subject
Execute fade, highlight, and preferred renderer lcoally.

### Environment
Version of LPub3D - 2.4.1
Operating system - All

### Solution
Enable fade previous steps, highlight current step and select preferred renderer locally - i.e. at individual steps. 
Fade and highlight setup must be enabled globally. For example, `0 !LPUB HIGHLIGHT_STEP SETUP GLOBAL TRUE` enables highlight current step to be executed locally. Use the context menu to add local command. For example, 
`0 !LPUB ASSEM HIGHLIGHT_STEP ENABLED LOCAL TRUE` set highlight current step for the `STEP` in which it is specified. ~~The `RESET` flag, returns the settings to the default preferences at the end of the step.~~

Note: Called out steps in a step-group have not yet been implemented.

![Screenshot - 27_02_2021 , 08_37_28.png](https://app.gitkraken.com/api/glo/boards/5b248f78dd21bf100044c350/attachments/6039f99a177177001183c3ba)

Cheers,

**Comment by jacovandermolen** [comment]
Great. I'll take a look!

**Comment by trevorsandy** [comment]
Very well. Note that the RESET command flag is redundant with LOCAL and will be dropped in the next update.

Cheers,

**Comment by jacovandermolen** [comment]
OK, I tested in 2.4.0.368.2588 with no succes so far.

Do I need to add `0 !LPUB HIGHLIGHT_STEP SETUP GLOBAL TRUE` manually?

Doing so with highlight enabled in prefs, choosing Highlight Current Assembly Step in any step and choosing either combination of checkboxes does not render the step or next ones with or without hightlight on or off.
Highlight stays on no matter what option.



P.S. 0 !LPUB BUILD_MOD REMOVE crashes in this version.

**Comment by trevorsandy** [comment]
You can add `0 !LPUB HIGHLIGHT_STEP SETUP GLOBAL TRUE` manually but it is also configurable from the Global Highlight Current Step settings.

![Screenshot - 01_03_2021 , 11_10_09](https://user-images.githubusercontent.com/13388970/109482800-bf5dde00-7a7e-11eb-8978-c96d8dd23b7d.png)

You cannot enable Highlight Current Steps in preferences. This setting will enable highlight current steps globally and the local highlight commands will be ignored accordingly. You will notice in the Global Highlight Current Step dialog that you are not allowed to select both 'Setup' and 'Enable'. If you check the 'Setup' box, the SETUP meta command above should be written. This tells LPub3D to 'setup' highlight current parts but do not enable against any steps. Instead the user is expected to enable his/her specific steps using the context menu action which should only display when the global 'SETUP' command is present. So the steps to execute this feature should be:

- Toggle the `HIGHLIGHT_STEP SETUP GLOBAL TRUE` command to TRUE and make sure it is in the first step of the base model file.
- At the desired step, select the highlight current step action to place a LOCAL highlight current step command

Keep in mind that steps with callouts are not implemented in the  last DevOps build.

> !LPUB BUILD_MOD REMOVE crashes in this version.

I tested with BUILD MODIFICATION enabled and (as the posted shot shows) did not see any unexpected behaviour. Can you provide an example and steps to reproduce ?

Cheers,

**Comment by jacovandermolen** [comment]
I will post a clip on the build mod crash in the build mod issue.
https://github.com/trevorsandy/lpub3d/issues/411

**Comment by jacovandermolen** [comment]
Regarding the local highlight feature:

Maybe I misunderstand, but what I'd expect is this:
I setup Highlight on (Configuration > Preferences)
LPub adds 

0 // The following 3 command lines were auto-generated for fade or highlight step.
0 // Use 0 !LPUB INSERT DISPLAY_MODEL to override automatic insertion and deletion.
0 STEP
0 !LPUB INSERT MODEL
0 !LPUB INSERT PAGE

I disable highlight for the entire model modifying the 0 !LPUB HIGHLIGHT_STEP SETUP GLOBAL FALSE command (set to FALSE)
I then expect no step to be rendered with highlight
In the step I want to be highlighted I set 0 !LPUB ASSEM HIGHLIGHT_STEP ENABLED LOCAL TRUE
This works from that step and beyond until I add 0 !LPUB ASSEM HIGHLIGHT_STEP ENABLED LOCAL FALSE to a step
That step and following steps are rendered without highlight

**Comment by trevorsandy** [comment]
Indeed, you misunderstand the behaviour as it is currently implemented. 

> I disable highlight for the entire model modifying the 0 !LPUB HIGHLIGHT_STEP SETUP GLOBAL FALSE command (set to FALSE)

`0 !LPUB HIGHLIGHT_STEP SETUP GLOBAL FALSE` does not disable highlight current step. In fact, when set to FASLE, this command has no effectl. When set to TRUE, as stated above, it "tells LPub3D to 'setup' highlight current [STEP] parts but do not enable [current step highlighting] against any steps".

> I setup Highlight on (Configuration > Preferences)

If you do this, then you are enabling highlight current step for the entire model file - i.e. all steps. As stated above, doing this will make LPub3D completely ignore the local command `0 !LPUB HIGHLIGHT_STEP SETUP GLOBAL [TRUE|FALSE]`.

Per my instructions above, if you want to apply individual current step highlighting, you must only set  `0 !LPUB HIGHLIGHT_STEP SETUP GLOBAL TRUE` at the first step of the base model followed by `0 !LPUB ASSEM HIGHLIGHT_STEP ENABLED LOCAL TRUE RESET` at the specified step you wish to highlight.

If you would like to persist the highlight current step beyond a single step then omit the LOCAL and RESET keyowrds - e.g. `0 !LPUB ASSEM HIGHLIGHT_STEP ENABLED TRUE` in the initial command and place `0 !LPUB ASSEM HIGHLIGHT_STEP ENABLED FALSE RESET` at the last step you wish to highlight. This should 'RESET' the highlight behaviour to disabled. 

Cheers,

**Comment by jacovandermolen** [comment]
Right. I think this makes things more clear.
I'll take a look again ;-)

**Comment by trevorsandy** [comment]
I've updated the behaviour in the latest DevOps build. 

You can check the behaviour for called out submodels in a step-group with the following model file. At this point, the Native renderer is executing as expected; however, there still seems to be some kinks with LDView and LDGLite. I'm working on those at the moment.

```
0 FILE main.ldr
0 Name: main.ldr
0 Author: Jaco van der Molen [Jaco]
0 !LICENSE Not redistributable : see NonCAreadme.txt
0 !LPUB HIGHLIGHT_STEP SETUP GLOBAL TRUE
0 // Enable the following line to change the renderer using a meta command
0 //!LPUB PREFERRED_RENDERER GLOBAL LDVIEW
0 !LPUB PAGE ORIENTATION GLOBAL LANDSCAPE
0 !LPUB INCLUDE "headers/header.ldr"
0 !LPUB BUILD_MOD_ENABLED GLOBAL TRUE
0 !LPUB MULTI_STEP BEGIN
1 0 0 0 0 -1 0 0 0 1 0 0 0 -1 3032.dat
0 STEP
1 0 40 -8 -30 0 0 -1 0 1 0 1 0 0 3021.dat
1 0 0 -8 -30 0 0 -1 0 1 0 1 0 0 3021.dat
1 0 -40 -8 -30 0 0 -1 0 1 0 1 0 0 3021.dat
0 STEP
0 !LPUB BUILD_MOD BEGIN "FrontBumper"
0 !LPUB CALLOUT PLI PER_STEP FALSE
0 !LPUB CALLOUT BEGIN
1 0 0 96 -50 1 0 0 0 1 0 0 0 1 subModel-1.ldr
0 !LPUB CALLOUT POINTER CENTER 0 0.427326 0.71746 0 0 0 0 0 0 1
0 !LPUB CALLOUT END
1 4 -50 8 -50 0 0 -1 0 -1 0 -1 0 0 HasvL3.dat
1 4 50 8 -50 0 0 -1 0 -1 0 -1 0 0 HasvL3.dat
0 !LPUB BUILD_MOD END_MOD
1 0 0 24 -50 1 0 0 0 1 0 0 0 1 subModel-1.ldr
0 !LPUB BUILD_MOD END
0 // Note: For steps with called out submodel(s), the highlight meta command must be placed at the bottom of the step
0 !LPUB ASSEM HIGHLIGHT_STEP ENABLED LOCAL TRUE
0 STEP
0 !LPUB BUILD_MOD REMOVE "FrontBumper"
1 0 0 -8 40 -1 0 0 0 1 0 0 0 -1 3032.dat
1 0 0 -16 0 -1 0 0 0 1 0 0 0 -1 3020.dat
0 STEP
0 !LPUB MULTI_STEP END
0 NOFILE 
0 FILE submodel-1.ldr
0 Name: subModel-1.ldr
0 Author: Jaco van der Molen [Jaco]
0 !LICENSE Not redistributable : see NonCAreadme.txt
1 0 0 -8 0 1 0 0 0 1 0 0 0 1 4477.dat
0 STEP
1 71 -70 -16 0 1 0 0 0 1 0 0 0 1 36841.dat
1 0 -40 -16 0 1 0 0 0 1 0 0 0 1 99781.dat
1 0 0 -16 0 1 0 0 0 1 0 0 0 1 99781.dat
1 0 40 -16 0 1 0 0 0 1 0 0 0 1 99781.dat
1 71 70 -16 0 1 0 0 0 1 0 0 0 1 36841.dat
0 STEP
1 71 -60 -24 0 1 0 0 0 1 0 0 0 1 99780.dat
1 0 0 -24 0 1 0 0 0 1 0 0 0 1 3710.dat
1 71 60 -24 0 1 0 0 0 1 0 0 0 1 99780.dat
0 NOFILE
```

Cheers,

**Comment by jacovandermolen** [comment]
Sorry for my late reaction, but I will take a look again and try with DevOps Build 2601 (r381)

**Comment by jacovandermolen** [comment]
I got successful with DevOps Build 2608 (r388). Looks good!
I must admit, I only use the native renderer ;-) making instructions with build mods, stud style and texmaps! Great!!!

**Comment by trevorsandy** [comment]
Excellent.

Also note that I've added behaviour to support your original expectations whereby:

1. Set Highlight at Configuration > Preferences
2. Set `0 !LPUB ASSEM HIGHLIGHT_STEP ENABLED GLOBAL FALSE`  at the first step (header) of the top model.
3. Set `0 !LPUB ASSEM HIGHLIGHT_STEP ENABLED LOCAL TRUE`  at the specified single-step page.

Additionally, the syntax for Multistep and Called out steps require the respective additional keywords. So a Multistep command would be `0 !LPUB MULTI_STEP ASSEM HIGHLIGHT_STEP ENABLED LOCAL TRUE` 

Cheers,

**Comment by jacovandermolen** [comment]
Great! Really happy with this.

**Comment by trevorsandy** [comment]
Implemented.

Cheers,
