### ISSUE TITLE
lpub3d 2.4.0 hangs on startup on macOS Big Sur 11.2.2 - 100% CPU

### ISSUE THREAD

**Issue by 802044875** [trevorsandy/lpub3d#507]
### Subject
lpub3d 2.4.0 hangs on startup on macOS Big Sur 11.2.2 - 100% CPU - never shows a dialogue box, never crashes.  Fresh install of 2.4.0 after deleting contents of ~/Library/Application Support/LPub3D Software/LPub3D/ and deleting ~/Library/Preferences/com.lpub3d-software.LPub3D.plist

Fresh install does not create a new instance of ~/Library/Preferences/com.lpub3d-software.LPub3D.plist

### Environment
* Version of LPub3D - 2.4.0
* Operating system - macOS, Apple M1

### Configuration
* LPub3D installation path
  - macOS: `/Applications/LPub3D.app`
* Application data path
  - macOS: `~/Library/Application Support/LPub3D Software/LPub3D/`
* Registry Extract
  - macOS: ` ~/Library/Preferences/com.lpub3d-software.LPub3D.plist` - missing

* Renderer configuration files
  - `[Application data path]/ldv/ldvExport.ini` - missing
  - `[Application data path]/3rdParty/ldglite-1.3/config/ldglite.ini` - config directory missing
  - `[Application data path]/3rdParty/ldview-4.4/config/ldview.ini` - config directory missing
  - `[Application data path]/3rdParty/ldview-4.4/config/ldviewPOV.ini` - config directory missing
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.conf` - config directory missing
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.ini` - config directory missing

### Logs
* Application Log: `[Application data path]/logs/LPub3DLog.txt`:

INFO void Application::initialize() @ln 750 "Initializing application..." 
INFO void Application::initialize() @ln 753 ----------------------------- 
INFO void Application::initialize() @ln 754 "LPub3D v2.4.0 for macOS 64bit" 
INFO void Application::initialize() @ln 755 ============================= 
INFO void Application::initialize() @ln 756 "Arguments....................()" 
INFO void Application::initialize() @ln 759 "macOS Binary Directory.......(MacOS)" 
INFO void Application::initialize() @ln 765 "macOS Base Directory.........(Applications)" 
INFO void Application::initialize() @ln 784 "LPub3D App Data Path.........(/Users/martinwebb/Library/Application Support/LPub3D Software/LPub3D)" 
INFO void Application::initialize() @ln 786 "LPub3D Bundle App Path.......(/Applications)" 
INFO void Application::initialize() @ln 809 "LPub3D Extras Resource Path..(/Applications/LPub3D.app/Contents/Resources)" 
INFO void Application::initialize() @ln 815 "LPub3D Loaded LDraw Library..(LEGO® Parts)" 
INFO void Application::initialize() @ln 816 "Logging Level................(STATUS (0), Levels: [status,info,trace,debug,notice,error,fatal,off])" 
INFO void Application::initialize() @ln 818 "Debug Logging................(Enabled)" 
INFO void Application::initialize() @ln 819 ----------------------------- 

Brew has been installed, with required libraries updated/installed prior to LPub3D being installed. LibPNG is updated/reinstalled as per instructions:

Mac-mini:~ martinwebb$ otool -L $(brew list libpng | grep dylib$)
/opt/homebrew/Cellar/libpng/1.6.37/lib/libpng16.16.dylib:
	/opt/homebrew/opt/libpng/lib/libpng16.16.dylib (compatibility version 54.0.0, current version 54.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
/opt/homebrew/Cellar/libpng/1.6.37/lib/libpng.dylib:
	/opt/homebrew/opt/libpng/lib/libpng16.16.dylib (compatibility version 54.0.0, current version 54.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
/opt/homebrew/Cellar/libpng/1.6.37/lib/libpng16.dylib:
	/opt/homebrew/opt/libpng/lib/libpng16.16.dylib (compatibility version 54.0.0, current version 54.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)

### Steps to reproduce
Fresh install of lpub3d - start application - never shows a dialogue, 100% CPU

### Expected behaviour
Application should show a dialogue and allow a model to be loaded/created

### Actual behaviour
Application hangs

**Comment by lzandman** [comment]
Same for me!

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

Please take a look at the new released version v2.4.1 of LPub3D and let me know if the startup freeze Is also present with it.

Cheers,

**Comment by 802044875** [comment]
Just installed v2.4.1 - works for me.

Many, many thanks!

**Comment by trevorsandy** [comment]
Excellent. 

Cheers,
