### ISSUE TITLE
Part 32532 shown in wrong orientation

### ISSUE THREAD

**Issue by mfeldt** [trevorsandy/lpub3d#508]
### Subject
The part 32532 (Technic Brick 6 x 8 with Open Center 4 x 6) is shown by lpub3d in the wrong orientation...

### Environment
* dev release 2.4.0 revision 344 build 2564 (actually affects all versions I've tried...)
* Ubuntu 20.04, x86_64
### Configuration
any

### Steps to reproduce
1. Open the attached test file 
2. View in LDCad (see below)
![Screenshot from 2021-03-08 16-17-15](https://user-images.githubusercontent.com/1193964/110340514-a5497000-8029-11eb-8575-65df9deb3ff0.png)
3.) View in Lpub3d
![Screenshot from 2021-03-08 16-19-16](https://user-images.githubusercontent.com/1193964/110340760-e477c100-8029-11eb-8f92-be056a0b1181.png)

### Expected behaviour
The two orientations shown should be identical. Since all other viewing tools follow LDCad, and the orientation shown in Lpub3D is actually impossible (no holes for the pins) I presume that LPub3d is off..

### Actual behaviour
See screenshots

### Workaround
None found yet

### Solution suggestion
Update your model file to use 32532a.dat.

Here's the source of the .ldr:

```
0 Untitled Model
0 Name:  UntitledModel
0 Author:  
0 CustomBrick
1 15 0.000000 -24.000000 0.000000 1.000000 0.000000 0.000000 0.000000 1.000000 0.000000 0.000000 0.000000 1.000000 32532.dat
1 4 -40.000000 -14.000000 -60.000000 0.000000 0.000000 1.000000 0.000000 1.000000 0.000000 -1.000000 0.000000 0.000000 3673.dat
1 4 40.000010 -14.000000 -60.000000 0.000000 0.000000 1.000000 0.000000 1.000000 0.000000 -1.000000 0.000000 0.000000 3673.dat
1 4 -0.000010 -14.000000 60.000000 0.000000 0.000000 1.000000 0.000000 1.000000 0.000000 -1.000000 0.000000 0.000000 3673.dat

```

### Update
32532.dat has been moved to 32532a.dat. You are likely seeing this behaviour because your parts library includes the old part.

Cheers,

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I believe there is a bug in the Native renderer that's causing this anomaly. I'll take a look.

### Workaround
Switch your preferred renderer to LDGLite or LDView.

Cheers,

**Comment by trevorsandy** [comment]
After some additional investigating, it looks like 32532.dat has been moved to 32532a.dat. I imagine the old part (32532) was incorrectly oriented. 

The new part (32532a) correctly renders with the Native renderer - and also LDGLite and LDView.
![Screenshot - 10_03_2021 , 08_37_57](https://user-images.githubusercontent.com/13388970/110594797-8a881000-817d-11eb-8d77-e18d0c11b6c1.png)

If you display the Preview tab and click on the part, its description will show it 32532 was moved:
![Screenshot - 10_03_2021 , 08_37_01](https://user-images.githubusercontent.com/13388970/110594682-6b897e00-817d-11eb-9770-76e69974538c.png)

Cheers,

**Comment by rsbx** [comment]
You're looking at UNOFFICIAL parts. I just checked 
https://www.ldraw.org/library/official/parts/32532.dat and it has not 
been moved.

Looking at the LDraw.org parts tracker for UNOFFICIAL parts: it does 
appear that the current OFFICIAL 32532.dat has moved to UNOFFICIAL 
32532a.dat and a new UNOFFICIAL 32532.dat references that rotated.

I'm disappointed that they seem to be changing an in-use existing 
OFFICIAL parts in a way that invalidates existing designs. I was under 
the impression that this type of change would use a new variant name for 
the modified (improved?) part and leave the existing uses intact.

**Comment by trevorsandy** [comment]
> You're looking at UNOFFICIAL parts. I just checked

Good catch! Nominally, the Native renderer should lookup/load OFFICIAL parts before UNOFFICIAL ones. It could be that my unofficial parts archive library reload call, or some other routine, is disturbing this order; hence, why unofficial part is being returned when an official instance exist.

I’ll take a look. If the reload calls are the source of this behaviour, I’ll update them to preserve the default search order, and perhaps even look at offering a flag to allow the user to specify the official/unofficial search order.

Cheers,

**Comment by trevorsandy** [comment]
I took a look at the Native renderer parts library load calls. 

When the UNOFFICIAL archive library is present (this is always the case for LPub3D), loaded parts will ultimately point to this archive. Thus, the Native renderer will lookup/return UNOFFICIAL parts before OFFICIAL ones in LPub3D. 

The reason for this is the archive load calls will load the official library first, followed by the unofficial library if it exists. However, if the part info is already loaded (e.g. an official part with the same name as an unofficial part), its archive file attribute will be set to the currently loading library; hence why, the unofficial library is specified for 32532.dat in LPub3D.

Although this scenario (official and unofficial files with the same name and different behaviour) is a rare exception and should actually not be permitted by the LDraw administrators, it is a valid use case, as we can see here, so I’ll add a flag to allow the user to specify the official/unofficial search order.

Cheers,
