### ISSUE TITLE
Meta command for divider/separator is incorrect

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#511]
### Subject
Meta command for divider/separator is incorrect

### Environment
* Version of LPub3D 2.4.0 r396
* Windows 10 64 bit

### Configuration
Local distribution

### Steps to reproduce
Adding a divider on a multistep page and adjusting the margins of the divider does nothing

### Expected behavior
The margins should be set, processed, and rendered

### Actual behavior
Setting margins of a divider has no effect.
The meta-command for example that is written is this:
`0 !LPUB MULTI_STEP DIVIDER THICKNESS 0.03125 "black" MARGINS 0.5 0.25`

### Workaround
Change meta command manually to
`0 !LPUB MULTI_STEP SEPARATOR THICKNESS 0.03125 "black" MARGINS 0.5 0.25`

So change DIVIDER to SEPARATOR 

### Solution suggestion
Write the correct meta command

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I’ll take a look.

For consistency, I recently updated the parse engine so that both `SEPARATOR` and `DIVIDER` commands are supported. I must have overlooked something.

Cheers.
