### ISSUE TITLE
Submodel image does not show at first step of Step Group

### ISSUE THREAD

**Issue by forelockmocs** [trevorsandy/lpub3d#512]
### Subject
I have installed version 2.4.1. I tried to recreate every setup that I use in the previous version I had (2.3.13.133). Everything worked out great, except one thing: Getting a submodel image to show at the first step of a Step Group when using continuous numbering.

When choosing continuous step numbers,
![image](https://user-images.githubusercontent.com/62996120/111338891-98ef9380-8677-11eb-805e-16668390c443.png)

the submodel image at step one of a step group vanishes:
![image](https://user-images.githubusercontent.com/62996120/111339063-bfadca00-8677-11eb-974b-08117cc6a872.png)

When turning continuous step numbers off, the image re-appears:
![image](https://user-images.githubusercontent.com/62996120/111339222-e0761f80-8677-11eb-819f-119d9b897024.png)

### Environment
* LPub3D 2.4.1
* Win10

### Solution suggestion
It now only shows the submodel image at the **first** step group step, when the step number is also 1. It should look at the lowest step number in the same step group.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I’ll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

Cheers,
