### ISSUE TITLE
Error when marking a line in the LDraw editor

### ISSUE THREAD

**Issue by technicbasics** [trevorsandy/lpub3d#515]
### Subject
If a line is marked in the LDraw Editor and the mouse pointer is dragged outside the window and released there, the program does not recognize it.
If the mouse is then moved back into the window, the marking is continued at this point.

### Environment
* Version of LPub3D - 2.4.0 and later
* Operating system - Win10 x86

### Steps to reproduce
seee subject

https://user-images.githubusercontent.com/49073781/112277324-ef655f00-8c81-11eb-9c89-07504b5c599b.mp4

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

Cheers,
