### ISSUE TITLE
weird rendering - primitive substitution problem?

### ISSUE THREAD

**Issue by DanieleBenedettelli** [trevorsandy/lpub3d#516]
### Subject
A gear using a torus primitive is rendered in a weird way when primitive substitution is enabled using LDVIEW as a renderer.

### Environment
2.4.1 r41 build 2660
Win 10 x64

### Expected behaviour
![without_primitive_sub](https://user-images.githubusercontent.com/47357389/112823024-0395cb80-9089-11eb-8c83-791f9ab44dfd.png)

### Actual behaviour
![error_primitive_substitution](https://user-images.githubusercontent.com/47357389/112822772-a69a1580-9088-11eb-9db1-53d9bb182dea.png)

### Workaround
I am disabling primitive substitution

### Solution suggestion
It worked fine in older releases prior to 2.4.1, so something might have changed.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

Indeed, there has been some LDView updates for 2.4.1 to incorporate stud style and improved POV file generation. To save time, can you prepare an example model file that produces this behaviour or share the part numbers? I’ll take a look.

Cheers,

**Comment by DanieleBenedettelli** [comment]
Sorry I forgot to specify that part number is 6589.dat
Thanks!

**Comment by trevorsandy** [comment]
This behaviour might be linked to the LDView [Support more n-16 primitives, and update curve quality to round up to 16 except for the lowest setting.](https://github.com/tcobbs/ldview/commit/de9f7e6aa6a1c001dee452c404932d523f4066bb) update. Take a look at the commit to see how you can tune your settings to take into account this change.

Is 6589.dat the only part that is displaying this behaviour ?

Cheers,

**Comment by DanieleBenedettelli** [comment]
For now , I could find only part 6589.dat.
The only setting I can change is the curve quality slider.
No matter which settings I choose, the behavior is the same. The primitive is larger that it should be.
![curve_quality](https://user-images.githubusercontent.com/47357389/112842586-fe914600-90a1-11eb-8591-35ca5f778a64.png)

**Comment by trevorsandy** [comment]
I can't seem to reproduce this behaviour. My renders are as expected.

LPub3D latest DevOps:

![Screenshot - 30_03_2021 , 05_21_30](https://user-images.githubusercontent.com/13388970/112929818-73539700-9119-11eb-929a-0da42b8b2254.png)

Test file: 6589-and-3707.ldr

```
0 Gear and Axle
0 Name: Gear and Axle.ldr
0 Author: LPub3D
0 6589, 3707
1 19 -142 150 -320 0 0 1 0 -1 0 1 0 0 6589.dat
1 0 -209 150 -320 1 0 0 0 0 1 0 -1 0 3707.dat

```

I created a fresh LDView (LPub3D edition) Windows 10 build from commit [2c5a2f743](https://github.com/trevorsandy/ldview/tree/qmake-build) and, using the default LPub3D LDView settings (see ini file below), also could not produce the behaviour.

![6589-and-3707 TestResult Win32](https://user-images.githubusercontent.com/13388970/112930307-523f7600-911a-11eb-9ad6-c2f2f0cc3188.png)

Command: 
`<full path>\LDView.exe  "6589-and-3707.ldr" -LDrawDir="<full path>\LDraw" -SaveSnapshot="6589-and-3707.TestResult.Win32.png" -IniFile="<full path>\ldview.ini" -SaveWidth=1024 -SaveHeight=1024 -SaveActualSize=0 -HaveStdOut=1 -v`

LDView.ini:
```
[General]
AllowPrimitiveSubstitution=1
Antialias=4
AutoCrop=1
BackgroundColor3=00a9b4d8
ConditionalHighlights=1
CurveQuality=4
DrawLightDats=0
EdgeThickness=1
EdgesOnly=0
HiResPrimitives=1
InstallPath=C:\\Users\\Trevor\\Projects\\build-LPub3D-Desktop_Qt_5_11_3_MSVC2015_32bit-Debug\\mainApp\\32bit_debug\\3rdParty\\LDView-4.4\\bin
InstallPath 4.1=C:\\Users\\Trevor\\Projects\\build-LPub3D-Desktop_Qt_5_11_3_MSVC2015_32bit-Debug\\mainApp\\32bit_debug\\3rdParty\\LDView-4.4\\bin
LightVector=-0.163398,-0.235473,0.958047
Lighting=1
LineSmoothing=1
MemoryUsage=1
PerformSmoothing=1
PolygonOffset=1
ProcessLDConfig=1
SaveActualSize=0
SaveAlpha=1
SaveZoomToFit=0
Seams=1
ShowHighlightLines=1
SnapshotSuffix=.png
SubduedLighting=1
Texmaps=1
TextureOffsetFactor=5
TextureStuds=1
TransDefaultColor=1
UseQualityLighting=0
UseQualityStuds=1
UseSpecular=0
Wireframe=0

[CustomColors]

[ExtraSearchDirs]

[RecentFiles]

```

Cheers,

**Comment by DanieleBenedettelli** [comment]
Actually, you reproduced a different version of the problem.
The gear has a hole in correspondence of the high resolution ring. In my
case, the ring is too big.
I might have that high res primitive installed in the 48 folder, but its
scale is wrong. In your case, it's missing altogether.

D

Il giorno mar 30 mar 2021 alle ore 05:57 Trevor SANDY <
***@***.***> ha scritto:

**Comment by trevorsandy** [comment]
Indeed. I saw the hole but thought it was a new version of the gear. So this behaviour is most certainly linked to the recent LDView primitive substitution updates as my older build of LDView renders 6589.dat as expected.

![6589-and-3707 TestResult Win32](https://user-images.githubusercontent.com/13388970/112941554-11059100-912f-11eb-87c2-0ea14fc819a5.png)

I'll open a ticket in LDView.

Cheers,

**Comment by trevorsandy** [comment]
Ok - I feel like a dog chasing its tail here. Both my LDView build and the official build are correctly rendering 6589.dat. 

It looks like the latest DevOps build used the cached build which, as originally premised, was impacted by the recent updates to the primitive substitution behaviour. There were some patches to correct some unexptected behaviour with primitive substitution after the recent updates. I did apply those patches but the last DevOps build did not rebuild LDView. 

![Screenshot - 30_03_2021 , 09_20_47](https://user-images.githubusercontent.com/13388970/112949227-457e4a80-9139-11eb-9910-157a10cc7e6a.png)

Similiarly, my local DevOps environment was using the older, unpatched, instance of LDView. This shot shows 6589.dat with the latest LDView.

![Screenshot - 30_03_2021 , 09_18_37](https://user-images.githubusercontent.com/13388970/112948967-fb956480-9138-11eb-93ed-665398ae35aa.png)

I expect to push my final v2.4.2 updates today. I'll set LDView to rebuild so the next DevOps build should be ok.

Cheers,

**Comment by DanieleBenedettelli** [comment]
Thanks for chasing this out!

Il giorno mar 30 mar 2021 alle ore 09:24 Trevor SANDY <
***@***.***> ha scritto:
