### ISSUE TITLE
Disable automatic insertion of page/model

### ISSUE THREAD

**Issue by d-j-m-0** [trevorsandy/lpub3d#517]
### Subject
When creating building instructions that are small in length (e.g. trying to fit on to two sides of a single sheet of paper) with "Highlight Current Step" enabled, every time the model is opened, LPub3D automatically adds the commands "INSERT MODEL" and "INSERT PAGE". This results in an extra page being added to the building instructions, circumventing the desire to keep the length small.

If would be helpful to have a user configurable option to disable the automatic insertion of these commands. At present, every time the model is being opened, the automatically inserted commands have to be manually deleted.

### Environment
* Version of LPub3D - Release 2.4.1 Revision 0 Build 2389
* Operating system - Windows 10, x86_64

### Solution suggestion
Add a checkbox within the preferences dialog (as shown below) to identify whether or not the automatic insertion of the commands should occur,

![image](https://user-images.githubusercontent.com/37604323/113056556-6d88af00-9208-11eb-9a57-e85738818b93.png)

**Comment by trevorsandy** [comment]
Thank you for your suggestion. This behaviour currently exists as a meta command.

You can disable the final model step from the fade previous steps or highlight current step globals setup dialogue.

The following shot shows the highlight current step dialogue.

![Screenshot - 01_03_2021 , 11_10_09](https://user-images.githubusercontent.com/13388970/109482800-bf5dde00-7a7e-11eb-8978-c96d8dd23b7d.png)

Cheers,

**Comment by d-j-m-0** [comment]
While the dialog adds the command

`0 !LPUB FINAL_MODEL_ENABLED GLOBAL FALSE`

to the model, the following is still being automatically added to the LDraw file

```
0 STEP
0 // The following 3 command lines were auto-generated for fade or highlight step.
0 // Use 0 !LPUB INSERT DISPLAY_MODEL to override automatic insertion and deletion.
0 !LPUB INSERT MODEL
0 !LPUB INSERT PAGE
0 STEP
```

which still results in the undesired extra page being added to the building instructions.

For an example, please refer to the attached zipped containing two mpd files (the file to open is advent_2021.mpd).

Regards,

David

[advent_2021.zip](https://github.com/trevorsandy/lpub3d/files/6253607/advent_2021.zip)

**Comment by trevorsandy** [comment]
Thank you for this update. I’ll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected. I forgot to add the disable flag.

Cheers,
