### ISSUE TITLE
XYZ icon in 3D viewer arrow colors wrong?

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#519]
### Subject
The XYZ icon in 3D viewer arrow colors for Y and Z are switched
Z arrow is green, Y arrow is blue
![afbeelding](https://user-images.githubusercontent.com/32261647/113396806-68f4ff80-939c-11eb-8b48-bc7a6d69ee3a.png)
Z arrow is blue, Y arrow is green
![afbeelding](https://user-images.githubusercontent.com/32261647/113396872-7a3e0c00-939c-11eb-9572-e9c05fbb88f9.png)

### Solution suggestion
Make the arrows the same color in both icon and 3D view of the model

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I’ll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

![Screenshot - 02_04_2021 , 23_05_26](https://user-images.githubusercontent.com/13388970/113456128-b4df8d00-940c-11eb-971f-f3efc27f4de5.png)

![Screenshot - 02_04_2021 , 23_06_25](https://user-images.githubusercontent.com/13388970/113456136-bc9f3180-940c-11eb-82c0-e7581b8f2d63.png)

Cheers,

**Comment by jacovandermolen** [comment]
Great!
