### ISSUE TITLE
Add image of sub-model before the first step

### ISSUE THREAD

**Issue by lattam** [trevorsandy/lpub3d#52]
Hi, 
thank you for this amazing project! I have one proposal for another feature which is common in many LEGO instructions. The big models often consist of several sub-models and when you start to build any of those sub-models, it is nice to have an overall picture of that sub-model at the beginning of assembly (just before the first step). 
I didn't manage to achieve this using the current tools.

Thank you for considering!

**Comment by trevorsandy** [comment]
This is a nice feature. I'll add it to the list for LPub3DNext.

You can achieve this functionality by generating the steps that make up the model; then saving the final model image (perhaps with a different name); then consuming the image as a picture (insert picture) in a subsequent generation pass. You can move pictures around, or place the image on its own page, this approach is flexible.

Cheers,

**Comment by lattam** [comment]
Thank you, I didn't know about this workaround. Will definitely try it.

**Comment by Landcross** [comment]
I didn't see this feature request earlier, but I would also love this feature. While the work-around mentioned by Trevor would work in theory, it's not the look I'm after. It's difficult to explain, so let's show an example: https://www.lego.com/biassets/bi/6187733.pdf

See for example page 10 or page 25. The submodel image is positioned relative to the PLI, which would, in the case of the work-around, already be positioned where you want the image to be. If that makes sense...

**Comment by jacovandermolen** [comment]
Hi Trevor,
Thanks for this update! I start following LPub3D again.
I am curious: is this feature done or in the next version.
How does this work?

**Comment by trevorsandy** [comment]
Hi Jaco - With pleasure. This feature is not animated in LPub3D at this moment. While I have the framework in place to implement it, there are other features that I plan to bundle at the same time.

Cheers,

**Comment by jacovandermolen** [comment]
OK great, I'll wait for it then.

**Comment by trevorsandy** [comment]
Implemented.

Submodel display globals setup menu
![screenshot - 05_11_2018 07_56_13](https://user-images.githubusercontent.com/13388970/47984145-f6519e00-e0d5-11e8-88e7-4bba9d2ebfd7.png)

Extensive options, including options to show main (top) model at first step
![screenshot - 05_11_2018 07_56_49](https://user-images.githubusercontent.com/13388970/47984146-f6519e00-e0d5-11e8-9b6f-cc5593f3bf29.png)

Options to change scale, camera angle and rotation
![screenshot - 05_11_2018 08_03_31](https://user-images.githubusercontent.com/13388970/47984147-f6519e00-e0d5-11e8-8cf5-58ba4703ddc2.png)

Default placement is top right of step number (if displayed) or bottom left of page header
![screenshot - 05_11_2018 08_11_12](https://user-images.githubusercontent.com/13388970/47984148-f6ea3480-e0d5-11e8-93ad-423b5cb7fa83.png)

Context menu
![screenshot - 05_11_2018 08_12_34](https://user-images.githubusercontent.com/13388970/47984149-f6ea3480-e0d5-11e8-9c4b-cec6db4acdde.png)

Available for called out submodels including number of instances in callout
![screenshot - 05_11_2018 08_15_32](https://user-images.githubusercontent.com/13388970/47984150-f6ea3480-e0d5-11e8-9124-9b98e825144e.png)

Multi-step page
![screenshot - 05_11_2018 08_45_52](https://user-images.githubusercontent.com/13388970/47984600-585ed300-e0d7-11e8-9aac-e4f46d8f7c6c.png)

Callout context menu
![screenshot - 05_11_2018 08_16_26](https://user-images.githubusercontent.com/13388970/47984151-f6ea3480-e0d5-11e8-9711-6b39f8952cbb.png)

Show top model option
![screenshot - 05_11_2018 08_18_22](https://user-images.githubusercontent.com/13388970/47984153-f782cb00-e0d5-11e8-9ab9-4bc39bd75966.png)

Show top model option.
![screenshot - 05_11_2018 08_34_24](https://user-images.githubusercontent.com/13388970/47984155-f782cb00-e0d5-11e8-9535-eeaf6ea9794a.png)

Cheers,

**Comment by Landcross** [comment]
Nice! :)
Is it also possible to only place them at normal submodels and not at callouts?

**Comment by jacovandermolen** [comment]
Great feature! Can't wait to try it ;-)
Thanks, Tevor.

**Comment by jacovandermolen** [comment]
The instance count is not right when using a submodel in a buffer exchange, though the buffered instance is ignored.
Placement and relative to seem not entirely correct either.
I will PM a model file to illustrate.

**Comment by trevorsandy** [comment]
Hi Jaco, thanks for reporting this behaviour.

Question, is this behaviour linked to displaying a submodel at its first step ?

If not, kindly open a new ticket.

Cheers,

**Comment by jacovandermolen** [comment]
Sorry: solution for correcting instance count is to inline the submodel after the buffer exchange. So that is "solved".

Another problem: Submodel rotation does not seem to have any effect.

**Comment by trevorsandy** [comment]
Very well, thanks.

Cheers,

**Comment by jacovandermolen** [comment]
> Question, is this behaviour linked to displaying a submodel at its first step ?

Yes, it is.
Rotation only redraws when an entire reset is done or by changing the scale to force a re-render.
Or delete the generated image in ..\LPub3D\submodels manually.
