### ISSUE TITLE
Add archive parts on demand action

### ISSUE THREAD

**Issue by trevorsandy** [trevorsandy/lpub3d#521]
###  Subject
On initial startup that it is necessary to set 'Archive Parts On Launch' and restart to load custom parts (i.e. helper parts). I don't like this flow so I'll add an action to execute parts archive on demand.

### Environment
Version of LPub3D - 2.4.3
Operating system - All

### Solution
Add archive parts on demand action

![Screenshot - 05_04_2021 , 04_40_33](https://user-images.githubusercontent.com/13388970/113532021-a9d25b80-95ca-11eb-9ca7-87e57b508bab.png)

Search directory parts archive progress dialogue

![Screenshot - 05_04_2021 , 04_43_08](https://user-images.githubusercontent.com/13388970/113532649-2fa2d680-95cc-11eb-963a-6cfb2aa52513.png)

Cheers,

**Comment by trevorsandy** [comment]
Implemented.

Cheers,

**Comment by cjhendrix** [comment]
That is a really helpful change. Thanks.
