### ISSUE TITLE
POV-Ray render issue when directory name contains a space

### ISSUE THREAD

**Issue by d-j-m-0** [trevorsandy/lpub3d#525]
### Subject
When POV-Ray is selected to render the images and the directory path to the LDraw file contains a space, images fail to render and an error dialog window is displayed instead.

### Environment
* Version of LPub3D - 2.4.2 r19
* Operating system - Windows 10, x86_64

### Screenshots
Example of the error dialog:
![image](https://user-images.githubusercontent.com/37604323/113789384-1730e880-9793-11eb-9ace-98f2126d8997.png)

### Steps to reproduce
Create a directory path which has one of the folder names somewhere in the path containing a space.
You could use the sample I attached to issue #517.

### Expected behaviour
POV-Ray renders the images.

### Actual behaviour
Error dialog windows are displayed.

### Workaround
Rename the directory e.g. replace a space with an underscore.

### Solution suggestion
Quote the full file name path in the generated commands. Use:
`-ExportFile="some arbitrarily named file path for CSI POV file"`
and
`"some arbitrarily named file path for temp csi.ldr file"`

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

Indeed, I corrected this behaviour for POV-Ray some years ago - see #41. I imagine something has changed or a new source for this behaviour has emerged. I’ll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

Cheers,

**Comment by trevorsandy** [comment]
This update breaks the Windows build. Fixing update...

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

Cheers,
