### ISSUE TITLE
Using "Remove LPub formatting" causes a crash

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#526]
### Subject
Using Remove LPub3D formatting causes a crash

### Environment
* Version of LPub3D 2.4.x
* Windows 10, 64 bit

### Configuration
Portable distro

### Steps to reproduce
In a file with LPub meta's choose Edit >Remove LPub formatting

### Expected behaviour
All LPub meta's should be removed

### Actual behaviour
Many popups like this
![afbeelding](https://user-images.githubusercontent.com/32261647/113911609-7403c180-97da-11eb-9aef-110c30497c4a.png)
Closing them all, LPub3D crashes

### Solution suggestion
Please fix.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

Are you using an include file ? This prompt should only be generated when the `INCLUDE` meta command is used and either no file is specified or the file path/name cannot be resolved.

Can you provide an example model file that reproduces this behaviour. I am not able to reproduce it with the latest DevOps build. I used the following model file with _header/header.ldr_ at the model file root. I did not see any unexpected behaviour.

```
0 FILE main.ldr
0 Name: main.ldr
0 Author: Jaco van der Molen [Jaco]
0 !LICENSE Not redistributable : see NonCAreadme.txt
0 !LPUB PAGE ORIENTATION GLOBAL LANDSCAPE
0 !LPUB BUILD_MOD_ENABLED GLOBAL TRUE
0 !LPUB INCLUDE "headers/header.ldr"
0 !LPUB MULTI_STEP BEGIN
1 0 0 0 0 -1 0 0 0 1 0 0 0 -1 3032.dat
0 STEP
1 0 40 -8 -30 0 0 -1 0 1 0 1 0 0 3021.dat
1 0 0 -8 -30 0 0 -1 0 1 0 1 0 0 3021.dat
1 0 -40 -8 -30 0 0 -1 0 1 0 1 0 0 3021.dat
0 STEP
0 !LPUB MULTI_STEP END
0 !LPUB BUILD_MOD BEGIN "FrontBumper"
1 0 0 96 -50 1 0 0 0 1 0 0 0 1 subModel-1.ldr
1 4 -50 8 -50 0 0 -1 0 -1 0 -1 0 0 HasvL3.dat
1 4 50 8 -50 0 0 -1 0 -1 0 -1 0 0 HasvL3.dat
0 !LPUB BUILD_MOD END_MOD
1 0 0 24 -50 1 0 0 0 1 0 0 0 1 subModel-1.ldr
0 !LPUB BUILD_MOD END
0 STEP
0 !LPUB BUILD_MOD REMOVE "FrontBumper"
1 0 0 -8 40 -1 0 0 0 1 0 0 0 -1 3032.dat
1 0 0 -16 0 -1 0 0 0 1 0 0 0 -1 3020.dat Name: main.ldr
0 Author: Jaco van der Molen [Jaco]
0 !LICENSE Not redistributable : see NonCAreadme.txt
0 !LPUB PAGE ORIENTATION GLOBAL LANDSCAPE
0 !LPUB BUILD_MOD_ENABLED GLOBAL TRUE
0 !LPUB INCLUDE "headers/header.ldr"
0 !LPUB MULTI_STEP BEGIN
1 0 0 0 0 -1 0 0 0 1 0 0 0 -1 3032.dat
0 STEP
1 0 40 -8 -30 0 0 -1 0 1 0 1 0 0 3021.dat
1 0 0 -8 -30 0 0 -1 0 1 0 1 0 0 3021.dat
1 0 -40 -8 -30 0 0 -1 0 1 0 1 0 0 3021.dat
0 STEP
0 !LPUB MULTI_STEP END
0 !LPUB BUILD_MOD BEGIN "FrontBumper"
1 0 0 96 -50 1 0 0 0 1 0 0 0 1 subModel-1.ldr
1 4 -50 8 -50 0 0 -1 0 -1 0 -1 0 0 HasvL3.dat
1 4 50 8 -50 0 0 -1 0 -1 0 -1 0 0 HasvL3.dat
0 !LPUB BUILD_MOD END_MOD
1 0 0 24 -50 1 0 0 0 1 0 0 0 1 subModel-1.ldr
0 !LPUB BUILD_MOD END
0 STEP
0 !LPUB BUILD_MOD REMOVE "FrontBumper"
1 0 0 -8 40 -1 0 0 0 1 0 0 0 -1 3032.dat
1 0 0 -16 0 -1 0 0 0 1 0 0 0 -1 3020.dat
0 NOFILE 
0 FILE submodel-1.ldr
0 Name: subModel-1.ldr
0 Author: Jaco van der Molen [Jaco]
0 !LICENSE Not redistributable : see NonCAreadme.txt
1 0 0 -8 0 1 0 0 0 1 0 0 0 1 4477.dat
0 STEP
1 71 -70 -16 0 1 0 0 0 1 0 0 0 1 36841.dat
1 0 -40 -16 0 1 0 0 0 1 0 0 0 1 99781.dat
1 0 0 -16 0 1 0 0 0 1 0 0 0 1 99781.dat
1 0 40 -16 0 1 0 0 0 1 0 0 0 1 99781.dat
1 71 70 -16 0 1 0 0 0 1 0 0 0 1 36841.dat
0 STEP
1 71 -60 -24 0 1 0 0 0 1 0 0 0 1 99780.dat
1 0 0 -24 0 1 0 0 0 1 0 0 0 1 3710.dat
1 71 60 -24 0 1 0 0 0 1 0 0 0 1 99780.dat
0 NOFILE 
```

Cheers,

**Comment by jacovandermolen** [comment]
That is the strange thing: I have not used an INCLUDE meta. I must double check

**Comment by jacovandermolen** [comment]
My current test model is this one
[40252.mpd.txt](https://github.com/trevorsandy/lpub3d/files/6276520/40252.mpd.txt)
that has no INCLUDE in it.
Remove LPub formatting results in removing the LPub metas, but then LPub3D 2.4.2.22.2684 stops responding until I stop the program manually. A dmp file is made. Here it is.
[LPub3D.dmp.zip](https://github.com/trevorsandy/lpub3d/files/6276609/LPub3D.dmp.zip)

**Comment by trevorsandy** [comment]
Ok. I know what's happening but I haven't figured out why it's happening on your system. It's not happening on mine. Basically, the include file variable's default setting (includeFileNotFound) is lost when passed to the countPage threaded call. I've put stricter conditions and type conversion in place to see if this makes a difference.

Cheers,

**Comment by jacovandermolen** [comment]
Is this LPub3D_x86_64-2.4.2.40.2702_20210411 the latest where I can test?

**Comment by trevorsandy** [comment]
Yes. 

I haven’t gotten around to evaluating the BuildMod behaviour with your example file. I believe the abnormal end you are experiencing is rooted in the unexpected BuildMod behaviour shown in your last clip. If you attempt to clear the LPUB formatting without having received a BuildMod parse message, I believe you will not receive an abend. Also, while it is possible that my latest updates may prevent the formatting removal abend, they were not implemented to correct the BuildMod problem - this action is outstanding. I believe a BuildMod update to address your scenario will be necessary.

Cheers,

**Comment by jacovandermolen** [comment]
Ok 2.4.2.40.2702_20210411 fixes Remove LPub formatting. That works again with a few files I tested, including the one with the build mods.

Please let me know if you need anything regarding getting build mods corrected, like testing or sample files. “We” are getting there!

**Comment by jacovandermolen** [comment]
I am sorry to report, but I have found another file that crashes again while using Remove LPub formatting :-(

**Comment by jacovandermolen** [comment]
Still, any version of LPub so far tested crashes when using "Remove LPub formatting"

**Comment by trevorsandy** [comment]
Quite strange. I spent some time redesigning this for v2.4.5. My tests using the VW were successful - there must have been a regression.

As you can see there are new options to clear the different components of a model file now.

Are you seeing an outright failure on all of the menu options ?

Are you seeing a failure with all the files you've tried ?

Cheers,

**Comment by trevorsandy** [comment]
I still cannot reproduce an AbnormalEnd but I did find a conflict with the build modification setting which caused the unformat routine to ignore all formatting - versus only ignoring build modification formatting. The resulting behaviour when build modifications is enabled was the application did nothing when triggering the _Remove LPub Formatting_ menu actions. This behaviour has been corrected in a new ticket #638.

Cheers,

**Comment by jacovandermolen** [comment]
Version 2.4.5.49.3257 fixed this. Unformatting works good now.

**Comment by trevorsandy** [comment]
Excellent.

Cheers,

**Comment by trevorsandy** [comment]
Indeed. 

As you may already know, placing a _BUILD_MOD_ action command before the _MULTI_STEP END_ command will try to perform the _(REMOVE)_ action on the last step of the multi-step page but since the last STEP in multi-step page has already been processed (the line before), undefined behaviour may occur - hence, a possible abnormal end. 

With regards to page processing, for all intents and purposes, you should see _MULTI_STEP END_ the same as STEP and ROTSTEP. 

So thanks for reporting this behaviour. As I encounter these exceptions, I will update the code to more gracefully handle them.

Cheers,

**Comment by trevorsandy** [comment]
There is a good example of why it is a good practice to place the _MULTI_STEP END_ command before the _BUILD_MOD_ action (_REMOVE/APPLY_) command in your _XB-15002.ldr_ model file: 

Lines 39 - 41:

```
0 STEP
0 !LPUB BUILD_MOD REMOVE "main.ldr Mod 1"
0 !LPUB MULTI_STEP END
```

Lines 39 - 41 Corrected:

```
0 STEP
0 !LPUB MULTI_STEP END
0 !LPUB BUILD_MOD REMOVE "main.ldr Mod 1"
```

If you process page 1 - 3 of this model file using the original configuration, you will notice your build modification for step 3 is not rendered because _BUILD_MOD REMOVE_ removes the modification before the page can be rendered. This is not what you want. But putting the _REMOVE_ command before ending the _MULTI_STEP_ page will produce this result.

Placing the commands in the corrected order will produce the expected rendering.

> As I encounter these exceptions, I will update the code to more gracefully handle them.

I've added this message when this scenario is encountered.
![Screenshot - 06_12_2022 , 22_26_39](https://user-images.githubusercontent.com/13388970/206028247-021b0273-457b-45b4-8503-7b4b19166164.png)

Cheers,

**Comment by jacovandermolen** [comment]
Indeed. In some cases I had to manually move some lines, but in the end I got all my BM's to work.
So thank you so much for that.

_I think LPub3D has come a long way and can easily compete with Stud.io.
Though the learning curve for LPub3D (and LDraw for that matter) is still high.
IMHO the LDraw tools are aimed at high end and experienced users._

**Comment by jacovandermolen** [comment]
Version 2.4.5.49.3257 fixed the remove formatting, but seems broken again in LPub3D_x86_64-2.4.7.75.3551_20230905?

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

Are you experiencing both an abnormal end and no response (#638) when attempting to unformat the document ?

I am not able to reproduce either behaviour with v2.4.7r75.

![RemoveFormatting_01](https://github.com/trevorsandy/lpub3d/assets/13388970/5d1f04a5-1614-45f1-817f-e8eafc5d4c52)

![RemoveFormatting_02](https://github.com/trevorsandy/lpub3d/assets/13388970/a26834e0-aa48-40c3-b229-ee081d6512cf)

As you can see, there are several unformat options available. Is the unexpected behaviour present on one of the granular options ?

Cheers,
