### ISSUE TITLE
Unable to generate ldraw color parts file

### ISSUE THREAD

**Issue by cjhendrix** [trevorsandy/lpub3d#527]
### Subject
I've been struggling with the highlight step feature since installing 2.42 (upgrading from the last 2.3 version). The behavior has been inconsistent, but I did a fresh install and will document here the current behavior I am seeing. The main issue has been that activating the highlight current step (via Configuration>Preferences) often does not stick (reopening the dialog shows "enable highlight current step" to be unchecked). Similarly, if the "enable highlight current step" remains checked, changing the highlight color doesn't stick. After a fresh install, when activating highlighting, I get a message about generating the LDraw Color Parts file, but the application closes a few seconds after saying "yes" to that dialog (details and screenshots below).

### Environment
* Version of LPub3D - 2.4.2 r19 build 2451
* Operating system - Win 10, x86_64

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  - Windows: `C:\Program Files\LPub3D` (confirmed)
* Application data path
  - Windows: `%USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\` (confirmed)
* Registry Extract
https://www.dropbox.com/s/xpmx7tjyyekq6ju/LPub3D_Hive.reg?dl=1

### Logs
* Application Log: https://www.dropbox.com/s/m7ezf4qapylcgvs/LPub3DLog.txt?dl=1
* Renderer Log: no render logs generated

### Steps to reproduce
Uninstall (including user data) LPub3D
Reinstall
Open the application
Open the test.ldr file (link below)
Configuration>Preferences
![image](https://user-images.githubusercontent.com/1654485/114130109-2bdebf00-9900-11eb-89f0-0daf96297f6f.png)
Enable "Enable Highlight Current Step" and change color to red (the problem occurs regardless of changing the color or not)
![image](https://user-images.githubusercontent.com/1654485/114130188-50d33200-9900-11eb-8981-55933ca4972c.png)
Click "ok"
Get message about "unable to open" the ldraw color parts file.
![image](https://user-images.githubusercontent.com/1654485/114130215-5cbef400-9900-11eb-8874-ba050f212a47.png)
Click "yes"
Lpub3d Closes a few seconds later. Dump file: https://www.dropbox.com/s/t5j7k7qznwfuscf/LPub3D.dmp?dl=1

Test file (although it's happening with every file I have tried) https://www.dropbox.com/s/rzxu91oi0x4eqb0/test.ldr?dl=1

By changing the default search directory from .../ldraw/MODELS to .../ldraw, I was able to get the generate procedure to finish. However, I still get the "unable to open ldraw color parts file" message. When saying "yes" to generate the file, I get some overlapping text in status bar at for a second before the application closes. I managed to capture a screenshot of it:
![image](https://user-images.githubusercontent.com/1654485/114131690-5aaa6480-9903-11eb-9f14-152e372bb67e.png)

### Expected behaviour
I'm not sure if I should be seeing the "Could not open ldraw color parts file" message or not. I don't remember it before. 

### Actual behaviour
LPUb3D closes a few seconds after starting to generate the ldraw color parts file

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. It looks like the colour parts list file complete path is not being passed to the regen call. I see the following message in your log file:

`2021-04-09T06:18:51.843 NOTICE "Could not open the LEGO LDraw color parts file [], Error: No file name specified"`

I’ll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected. 

I found a discrepancy whereby the color parts file path was not set. This update should correct this behavioiur.

Cheers,

**Comment by cjhendrix** [comment]
Thanks very much for the quick response! The workaround solved my problem easily.
