### ISSUE TITLE
ROTSTEP interpreted slightly differently than in earlier versions of LPub3d

### ISSUE THREAD

**Issue by cjhendrix** [trevorsandy/lpub3d#529]
### Subject
I generally use ROTSTEP to set the camera angles, and when I need to flip an assemble over, I just change the 3rd ROTSTEP angle to `180`. With the latest version, I notice a slight difference in how ROTSTEP is displayed when rotating Z by 180. For example:
```
1 15 0 -40 0 1 0 0 0 1 0 0 0 1 3006.dat
0 ROTSTEP 30 45 0 ABS
1 15 100 -16 0 1 0 0 0 1 0 0 0 1 3006.dat
0 ROTSTEP 30 45 180 ABS
```
When I composite those two steps together, you can see that the parts don't align:
![image](https://user-images.githubusercontent.com/1654485/114263989-a2ef8280-99e8-11eb-8efc-64b253fe3cf6.png)

### Environment
* Version of LPub3D - 2.4.2 r19 build 2451
Operating system - Win 10, x86_64

### Configuration
LPub3D installation path
Windows: C:\Program Files\LPub3D (confirmed)
Application data path
Windows: %USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\ (confirmed)
Registry Extract - https://www.dropbox.com/s/xpmx7tjyyekq6ju/LPub3D_Hive.reg?dl=1

* Renderer configuration files
https://www.dropbox.com/s/c9k6wxvxk34a3qf/configs.zip?dl=1

### Logs
* Application Log: https://www.dropbox.com/s/m7ezf4qapylcgvs/LPub3DLog.txt?dl=1
* Renderer Log: none generated

### Screenshots
* Configuration->Preferences->General
![image](https://user-images.githubusercontent.com/1654485/114263225-95d09480-99e4-11eb-9d3e-8efcdcf0fca2.png)

* Configuration->Preferences->Rendering
![image](https://user-images.githubusercontent.com/1654485/114263242-af71dc00-99e4-11eb-9634-142bbf0025fb.png)

### Steps to reproduce
Open test file: https://www.dropbox.com/s/rzxu91oi0x4eqb0/test.ldr?dl=1
Notice slightly different angle between the assemblies in step 1 and 2:
![image](https://user-images.githubusercontent.com/1654485/114263329-18f1ea80-99e5-11eb-8ab1-cafda91a1238.png)

### Expected behaviour
In the past, I believe these parts would be aligned when the rotation is changed only in the Z by 180.

### Actual behaviour
The assemblies in the two steps are slightly misaligned

### Workaround
I imagine some trial and error with the ROTSTEP angles would allow one to compensate for the misalignment

**Comment by cjhendrix** [comment]
After playing with it a bit more, I don't think the inversion of the ROTSTEP (adding 180 to the third element) has anything to do with it. I'm seeing slight changes in angle even without additional ROTSTEP commands:
```
0 Author: CJ Hendrix
0 Name: test.ldr
0 !LPUB INSERT DISPLAY_MODEL GLOBAL FALSE
0 !LPUB FINAL_MODEL_ENABLED GLOBAL FALSE
0 !LPUB PLI MODEL_SCALE GLOBAL  0.2500
0 !LPUB MULTI_STEP BEGIN
1 15 0 -40 0 1 0 0 0 1 0 0 0 1 3006.dat
0 ROTSTEP 30 45 0 ABS
1 15 100 -16 0 1 0 0 0 1 0 0 0 1 3006.dat
0 STEP
1 15 100 8 0 1 0 0 0 1 0 0 0 1 3004.dat
0 // The following 3 command lines were auto-generated for fade or highlight step.
0 // Use 0 !LPUB INSERT DISPLAY_MODEL to override automatic insertion and deletion.
0 STEP
0 !LPUB MULTI_STEP END
0 !LPUB INSERT MODEL
0 !LPUB INSERT PAGE
```
yields 
![image](https://user-images.githubusercontent.com/1654485/114270448-b7de0d00-9a0c-11eb-8410-b060a0788572.png)


and when superimposed you can see the angles are slightly different
![image](https://user-images.githubusercontent.com/1654485/114270431-9da42f00-9a0c-11eb-8734-def751bd0cfe.png)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

Indeed, when using the Native renderer, the image alignment may change between renderings (as pieces are added) because of changes in the camera position which uses latitude, longitude and calculated camera distance. 

Try changing the projection to Orthographic. Test using the LDGLite or LDView renderer.

Cheers,

**Comment by cjhendrix** [comment]
The more I played with it, the more I began to think that's what was happening. Thanks for clarifying. And as always thanks for your work on LPub3d. I really get a lot of enjoyment from it.

**Comment by trevorsandy** [comment]
With pleasure! 

Cheers,
