### ISSUE TITLE
Bug: Inserting text on a submodel insertion page gets placed in the submodel instead of the parent model

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#53]
### Subject of the issue
The insert text feature misplaces the text when the text is inserted on a page where a submodel is added to the parent model.

So, for example: page 5-10 show the construction of a submodel. Then, on page 11 the submodel is added to the parent model. If I go to Edit -> Add Text to add text to page 11, it is instead added on page 10, at the very end of the submodel.

Furthermore, because it is placed at the absolute end of the submodel, after the last STEP command the text is invisible too.

### Your environment
* Version of LPub3D: 2.2.2 Rev. 0 Build 848 (but this bug has been in LPub3D for a long time now)
* Operating system: Windows 10 Pro x64

### Steps to reproduce
Here is a sample mpd file: https://drive.google.com/open?id=1L-M3iVRYBA4PtRFQduNd9opI_7NqQeTo
Open it in LPub3D, go the last page (page 7) and add some text. You'll see that it doesn't get added to the page. Go back to page 6 and take a look in the File Editor: it's added at the end of the submodel.

### Workaround
Manually cut and paste the generated meta to the appropriate step location using the LDraw Text Editor pane.

**Comment by trevorsandy** [comment]
Thanks for reporting this behaviour. I’ll take a look.

**Comment by trevorsandy** [comment]
Corrected.
