### ISSUE TITLE
Adding rotate icon inside a callout adds the command to the main model, not the submodel in the callout

### ISSUE THREAD

**Issue by cjhendrix** [trevorsandy/lpub3d#532]
### Steps to reproduce

1. In a callout, right click on a step and add rotate icon.
2. `INSERT ROTATE_ICON` is (correctly I think) added to the submodel ldr
3. Right click the rotate icon and 'change rotate icon placement', selecting 'center' (my default is assem outside right center)
4. `0 !LPUB CALLOUT ROTATE_ICON PLACEMENT LOCAL CENTER ASSEM INSIDE` is added to the containing model, but I think the correct behavior would be to add it to the submodel. 

### Environment
* Version of LPub3D - 2.4.2 r0 build 2432
* Operating system - Win10, x86_64

### Workaround
Manually cut/paste the line from the main model into the submodel. This seems to work fine. Subsequent click & drag positioning of the rotate icon works as expected.

I'm happy to provide any of the other configuration/log/test files that you think are needed to troubleshoot.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. It has been corrected.

Cheers,
