### ISSUE TITLE
Selecting "substitute part" in PLI for a custom part causes LPub3D to crash

### ISSUE THREAD

**Issue by cjhendrix** [trevorsandy/lpub3d#538]
Selecting "substitute part" in PLI for a custom part causes LPub3D to crash

### Subject
I have a custom part which is an official part combined with a "sticker" part (another .dat file using the TEXMAP command to apply a png). I need to rotate the part so that the stickered side displays in the PLI. 

Right clicking and selecting "substitute part" causes the application to crash (with dialog advising to send the dmp file). Right clicking on non-custom parts opens the dialog as expected.

Perhaps relevant is the structure of my libraries: (using the example of a custom sticker part "applied" to an official part, tile 2x2):
ldraw/parts/3068b.dat (official part)
ldraw/custom/parts/sticker.dat (sticker part using texmap)
ldraw/custom/parts/3068b_with_sticker.dat (custom part with 3068b and sticker part)
ldraw/custom/parts/textures/sticker.png

Search Directories are (default, I think):
C:\Users\Public\Documents\LDraw
C:\Users\hendr\AppData\Local\LPub3D Software\LPub3D\LEGOcustom\parts
C:\Users\hendr\AppData\Local\LPub3D Software\LPub3D\LEGOcustom\p 

### Environment
* Version of LPub3D - 2.4.2. r0 2432
* Operating system - Win10, x86_64

### Configuration
* LPub3D installation path
  - Windows: `C:\Program Files\LPub3D` [x86_64]

* Application data path
  - Windows: `%USERPROFILE%\AppData\Local\LPub3D Software\LPub3D\`

* Registry Extract: https://www.dropbox.com/s/xpmx7tjyyekq6ju/LPub3D_Hive.reg?dl=1
* Renderer configuration files: https://www.dropbox.com/s/5m3id3m141xslmv/config2021-04-21.zip?dl=1

### Logs (dmp and log)
https://www.dropbox.com/s/gdc6s2egdq9gysy/crash.zip?dl=1

### Screenshots
* Configuration->Preferences->Rendering

### Steps to reproduce
If helpful, I can provide the custom parts and mpd

### Expected behaviour
PLI Substitue part dialog should open

### Actual behaviour
LPub3D crashes, displaying the crash dialog

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

The abend was triggered by the use of reserved character `_` in the part name. The character `_` is used to delimit attributes in the part name key - e.g. `3068b-0_4_1240_150_DPI_1_30_23_-45`. The abend was triggered when an incorrect number of attributes were parsed as `_` are used in `3068b_with_sticker` I've added a check to ensure that substitute parts with `_` in the name are supported.

### Workaround
To progress before the correction is deloyed, remove `_` from part name - e.g. `3068b-with-sticker`.

Cheers,
