### ISSUE TITLE
Bug?: LDView Multiple files single call rendering slow

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#54]
### Subject of the issue
Using the 'Multiple files singe call rendering' option makes rendering really slow. I was under the impression it should speed things up instead of slowing things down.

### Your environment
* Version of LPub3D - 2.2.2 Rev. 0 Build 848
* Operating system - Windows 10 Pro 64bit

### Configuration
I can provide any necessary logs or configurations, just didn't feel like adding ALL of time now as most will probably be useless.

### Steps to reproduce
Just rendering something with and without Multiple files single call rendering on.

### Expected behavior
I was always under the impression that this setting would speed things up. If I remember correctly it also did in earlier versions of LPub3D.

### Actual behaviour
Having this option turned on makes rendering incredible slow. I was rendering a 600 page pdf and when I came back it had only rendered about 30 pages in 30 minutes. I cancelled the rendering, turned 'Multiple files single call rendering' off and rendered the pdf again. This time it did about 100 pages in 10 minutes.

David on the LDraw forums reported a similar behaviour: https://forums.ldraw.org/thread-22765-post-28600.html#pid28600

**Comment by trevorsandy** [comment]
Starting with version 2.2.2, I'm using the new LDView feature (which I requested) `-SaveSnapshotsList=<List Filename>`. This command places the list of generated CSI/PLI LDraw files in a single 'ListFile' reducing size of the command string and allowing LDView to read only one file entry from the command line versus the list of LDraw file entries. See LDView Help [Command Line -> Requesting One or More Snapshots](https://trevorsandy.github.io/lpub3d/assets/docs/ldview/Help.html#SaveSnapshots) for more details. Somehow, this new command seems to be taking a longer time to process the command string than just listing the CSI/PLI LDraw files on the command line when using the `-SaveSnapShots` call. Perhaps there's something amiss with the way LPub3D is executing the command.

I'll take a look.

**Comment by trevorsandy** [comment]
What does the [ExtraSearchDirs] section of

  - `[Application data path]/3rdParty\ldview-4.3\config\ldview.ini`
  - `[Application data path]/3rdParty\ldview-4.3\config\ldviewPOV.ini`

look like ?

**Comment by trevorsandy** [comment]
My renderer benchmark show there is a remarkable reduction in performance (as compared to using `SaveSnapshots=1` or even if not using the single call optimization) when using `-SaveSnapshotList=<list file>` so for 'Single Call' rendering,  I've reverted the LDView renderer call to use `-SaveSnapshots=1` 

You can see the benchmarks in this graphic - which includes the new LPub3D Native renderer based on the LPub3D 3DViewer :

![screenshot - 07_08_2018 20_12_58](https://user-images.githubusercontent.com/13388970/43794364-5716a454-9a7e-11e8-95f1-27f7a074b3ff.png)

The full data set for the benchmark is here:

[renderer_bench.pdf](https://github.com/trevorsandy/lpub3d/files/2267518/renderer_bench.pdf)
