### ISSUE TITLE
Global callout pointer tip size settings don't have an effect (local is working)

### ISSUE THREAD

**Issue by cjhendrix** [trevorsandy/lpub3d#543]
### Subject
Thanks for making the callout pointer tip resizable. I've always wanted to adjust that a bit. 

When I set the pointer size locally, it works as expected, however setting it globally does not. 

Global command (not working):
![image](https://user-images.githubusercontent.com/1654485/116183142-aa6b9700-a71d-11eb-83f4-5f4d13a59ded.png)

Local command (working):
![image](https://user-images.githubusercontent.com/1654485/116183092-93c54000-a71d-11eb-9bba-9a44d7073ea8.png)

### Environment
* Version of LPub3D
![image](https://user-images.githubusercontent.com/1654485/116183197-c1aa8480-a71d-11eb-83da-1a249862e5df.png)
* Operating system - Win10, x86_64

I'm happy to provide additional configuration/logs info if needed.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. Corrected.

Cheers,
