### ISSUE TITLE
Using the redraw button iterates through every page

### ISSUE THREAD

**Issue by cjhendrix** [trevorsandy/lpub3d#546]
### Subject
I have **not** enabled the new "Cycle each page" [function](https://github.com/trevorsandy/lpub3d/issues/545), but when I click the redraw button, the application iterates through the file (starting from page 2), drawing each page until it reaches the page where I clicked the redraw button. This occurs regardless of whether or not an edit has been made.

Skipping forward multiple pages with the page dropdown in the menu bar behaves normally (i.e. intermediate pages are not drawn).

### Environment
* Version of LPub3D
![image](https://user-images.githubusercontent.com/1654485/116806775-82ba6b80-ab2f-11eb-9aa4-75e3d0417dd3.png)
* Operating system - Win10 ,x86_64

### Logs
* Application Log: https://www.dropbox.com/s/m7ezf4qapylcgvs/LPub3DLog.txt?dl=1
* I added a note in the log where the redraw button was clicked.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. It is as designed.

There are 2 menu actions on the Command Editor toolbar: 

1. **Redraw** - Deletes the current cache (PLI, CLI, SMI, and temp) and redraws the document up to the page where Redraw was triggered. It is unintuitive to clear the entire document cache but only regenerate the current page; therefore, cycle pages is automatic. It is on my TODO list to allow the user to select whether to clear only the page, the current submodel, or the entire document cache when selecting the Redraw action but I think the default will remain the entire document.

2. **Update** - Redisplay the current page without disturbing the cache. However, if the current submodel/model has been modified (e.g. a meta command was added/removed etc...), the current page’s CSI(s) will be regenerated. Page, PLIs, CSIs and the SMI can also be Reset from their respective context menu. Cycle pages is not called for Update and should never occur as the action is triggered from the current page against the current page.

Cheers,

**Comment by cjhendrix** [comment]
Thanks for that. Just to confirm, this as designed behavior is new, right? In previous versions, the Redraw button definitely didn't trigger this behavior. Just want to be sure we're understanding each other well.

With regards to your TODO, it would be really useful to be able right click on an assembly image and cause it (and only it) to be refreshed.

**Comment by trevorsandy** [comment]
> this as designed behavior is new, right?

Yes, it is.

> With regards to your TODO, it would be really useful to be able right click on an assembly image and cause it (and only it) to be refreshed.

This behaviour already exists. Look for the `Reset...` context menu action. There is one on each CSI, PLI, SMI and Page background.

Cheers,

**Comment by cjhendrix** [comment]
Thanks Trevor. For me, when I use the CSI reset in the context menu:
![image](https://user-images.githubusercontent.com/1654485/116821654-06e61080-ab7b-11eb-810c-7fb9286394ec.png)

I get the new behavior, i.e. each page from page 2 up to the current page is redrawn sequentially. It would be great if that would only redraw the CSI on the current page.

**Comment by trevorsandy** [comment]
> With regards to your TODO, it would be really useful to be able right click on an assembly image and cause it (and only it) to be refreshed.

Indeed, I took a look and can confirm that FILE_RELOAD is passed to the page cycle call which triggers the new behaviour. This is the case for page and step Reset. 

I don’t think this behaviour is intuitive so I’ll remove it for both Page an Step in the next update - doing so is trivial. 

Cheers,

**Comment by trevorsandy** [comment]
Changed.

Removed automatic cycling of pages when refreshing a page's PLI, CLI or SMI. 

Also added a prompt to cycle each page when clearing all caches or reloading the model file after custom parts cache clear or search directory change. This prompt is triggered if the current display page is greater than 1 and Edit->Cycle Each Page is not enabled.

Cheers,
