### ISSUE TITLE
BUFEXCHG seems to interfere with MULTI_STEP SUBMODEL_DISPLAY PLACEMENT

### ISSUE THREAD

**Issue by cjhendrix** [trevorsandy/lpub3d#547]
### Subject
I ran into this behavior in a complex model that I'm working on. I've replicated it in a simpler test file to better understand the circumstances under which it occurs. 

The test mpd has a submodel (call it "A") with a nested submodel (call it "B") inside it. Both A and B use `MULTI_STEP SUBMODEL_DISPLAY PLACEMENT` to display the completed submodel on the first page of the submodel steps. 

Here is what A looks like:
![image](https://user-images.githubusercontent.com/1654485/116823617-bfb14d00-ab85-11eb-97cc-704ae9ee22e5.png)
The submodel display is correctly offset to `-1 -3`

If B is added to A in a step with `BUFEXCHG`, the `OFFSET` portion of the `MULTI_STEP SUBMODEL_DISPLAY PLACEMENT` command has no effect. The placement will reflect the offsets of A instead of B. 
![image](https://user-images.githubusercontent.com/1654485/116823727-5847cd00-ab86-11eb-861a-79d3e11bc79b.png)
The submodel display should be at `+2 +2` ,but instead is at the same position and the submodel display for A.

If there is no `BUFEXCHG`, the offsets for B will apply as expected:
![image](https://user-images.githubusercontent.com/1654485/116838967-ab467200-abd0-11eb-8cff-242839401677.png)
Submodel correction displayed at `+2 +2`

MPDs:
with BUFEXCHG:  https://www.dropbox.com/s/igj8r0cxdtu3fro/test6%20-%20nested%20submodels%20-%20with%20bufexchg.ldr?dl=1

without BUFEXCHG: https://www.dropbox.com/s/ls9m4ov9wtun5mz/test6%20-%20nested%20submodels%20-%20without%20bufexchg.ldr?dl=1

### Environment
* Version of LPub3D 
![image](https://user-images.githubusercontent.com/1654485/116839081-2d369b00-abd1-11eb-894d-13841f858122.png)
* Operating system - Win10, x86_64

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by cjhendrix** [comment]
Glad to provide you with a challenge.  :)  Thanks for the fix.
