### ISSUE TITLE
Crash when dragging items

### ISSUE THREAD

**Issue by welsmore** [trevorsandy/lpub3d#549]
### Subject
Whenever I try to drag an item (subassembly, arrow etc), lpub3D crashes. This is (very) repeatable.

### Environment
* Version of LPub3D - 2.4.2 revision 101 Build 2533
* Operating system - Mac x86 64 bit, OS X Big Sur

### Configuration

* LPub3D installation path

  - macOS: `/Applications/LEGO CAD Applications/LPub3D.app`

* Application data path

  - macOS: `~/Library/Application Support/LPub3D Software/LPub3D/`
  - macOS: ` ~/Library/Preferences/com.lpub3d-software.LPub3D.plist`

All config files and screenshots available here: https://www.dropbox.com/sh/5hteaek37e7iq2n/AAC0WVb6XnldbkjIM3F2fGd6a?dl=0

### Steps to reproduce
Try dragging something (anything). This happens even with the basic ldraw car

### Expected behaviour
Not crash :-)

### Actual behaviour
Crash

### Workaround
None

### Solution suggestion
Rebooting sometimes fixes it - or allows a few drags before it crashes. I wonder if it's a memory leak or similar?

**Comment by welsmore** [comment]
An update - I can also cause this to happen on Windows 10 too.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

> An update - I can also cause this to happen on Windows 10 too.

Excellent, can you produce it with Win10 and forward the dump file ? This would be a big help.

Cheers,

**Comment by welsmore** [comment]
I presume you mean this? (it's been a while since I've used Windows!) https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

Interesting, I just set that up and at least got an error message of "Run:Exception Access Violation - no RTTI data! has been thrown. It's not written a dump file yet

**Comment by trevorsandy** [comment]
> I presume you mean this? (it's been a while since I've used Windows!) https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

You should not have to do anything to generate a .dmp file. LPub3D for Windows has the built-in configuration to generate this file and inform the user of it's location. The message prompt will read:

`LPub3D crashed. Crash information was saved to the file C:\Users\<your user name>\AppData\Local\Temp\LPub3D.dmp, please send it to the developer for debugging.`

Here is a shot showing a .dmp file message prompt 

![dmp file ](https://user-images.githubusercontent.com/47357389/112028137-262f5e00-8b38-11eb-8067-07397fcc0c49.png)

If you are some how experiencing an abnormal end without the .dmp file message prompt, can you capture this in a short video and post it ?

Cheers,

**Comment by welsmore** [comment]
Don't get your hopes up! I get no crash message at all - the video is here: https://www.dropbox.com/s/nt7ahzqwac6e0ha/bandicam%202021-05-05%2017-30-46-089.mp4?dl=0 and you can see it just disappearing.

Crash dump is here: https://www.dropbox.com/s/yqvpe16d61wwsl6/LPub3DLog.txt?dl=0

Thankyou for all this!

**Comment by cjhendrix** [comment]
I get this as well sometimes, though not often (win10 64bit). If it happens again I'll see if there is a dmp and share it.

**Comment by trevorsandy** [comment]
I'm cannot reproduce this behaviour with the latest release r121. Moreover, the log you provided is unremarkable. So I'm left with not much to go on in terms of where to look. 

The video clip shows the described behaviour on v2.42 r0. Today's release is r121. There has been alot of updates and fixes. Several abend-causing item have been corrected. You can see the README for details.

Let me know if you continue to experience the abend on r121.

Cheers,

**Comment by trevorsandy** [comment]
As you have access to a windows environment. Download a portable distro. Unzip and open the car model then try to trigger the abend by dragging it around. If not, try with your model. Also try to trigger the abend by re-sizing the callout quantity if you can. Let me know if you are successful to reproduce the behaviour. The aim is to test if this behaviour may be linked to your settings.

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

If you continue to experience this behaviour on the latest release of LPub3D, do not hesitate to reopen this ticket.

Cheers,
