### ISSUE TITLE
Crash when adding pointers to callouts

### ISSUE THREAD

**Issue by cjhendrix** [trevorsandy/lpub3d#550]
### Subject
I was trying to add a callout pointer **segment**, which caused a crash. In trying to work around that, I deleted the pointer and tried to add it back (via context menu). Consistently, the pointer is drawn and the application crashes: 
![image](https://user-images.githubusercontent.com/1654485/117323407-263cb080-ae8f-11eb-9422-e59b8a01bd85.png)
The highlighted command is the one that has just been added before the crash. 

I've had this happen in other models from time to time, but this is the first time I see it consistently. 

If it is relevant, I use the following global lines at the beginning of most of my models:

```
0 !LPUB CALLOUT POINTER_ATTRIBUTE GLOBAL BORDER SOLID COLOR #ffffff WIDTH 0.016
0 !LPUB CALLOUT POINTER_ATTRIBUTE GLOBAL TIP WIDTH 0.200 HEIGHT 0.15
```

(thanks for making the the GLOBAL parameter work on that; it's very helpful)

Here is the dmp: https://www.dropbox.com/s/t5j7k7qznwfuscf/LPub3D.dmp?dl=1

### Environment
* Version of LPub3D
![image](https://user-images.githubusercontent.com/1654485/117324153-d4485a80-ae8f-11eb-84b0-36074241bab8.png)

* Operating system - Win10 ,x86_64

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

> Here is the dmp: https://www.dropbox.com/s/m7ezf4qapylcgvs/LPub3DLog.txt?dl=1

This is not the LPub3D.dmp file; rather, it is the LPub3D Log. The dump file is located at the path indicaed in the prompt received when the application abnormal ends. For example, you can see the .dmp file path in the shot you provided above.

Cheers,

**Comment by cjhendrix** [comment]
Sorry about that. I grabbed the wrong dropbox link. Here is the dmp file: https://www.dropbox.com/s/t5j7k7qznwfuscf/LPub3D.dmp?dl=0  and I have corrected in the ticket as well.

**Comment by trevorsandy** [comment]
Excellent. Many thanks.

Cheers,
