### ISSUE TITLE
Crash when loading mpd

### ISSUE THREAD

**Issue by cjhendrix** [trevorsandy/lpub3d#553]
### Subject
I'm getting a crash when LPub3D is in the "counting document page" step of loading an MPD. This is happening with multiple files that were opening fine before today. I upgraded to 2.4.3 r0 on the 14th when you released it, and the these files were working.

Simple test files (with only a few parts/steps) still open ok. 

DMP: https://www.dropbox.com/s/t5j7k7qznwfuscf/LPub3D.dmp?dl=1
Log: https://www.dropbox.com/s/m7ezf4qapylcgvs/LPub3DLog.txt?dl=1

Note that the last line of the log says the document has 60 pages (and that is what is shown in the interface dropdown at the time of the crash message), however this mpd should have more than 150 pages. For several versions now, I've been noticing strange things happening in the page drop down (showing few pages than really exist until getting to the "last" page, then more pages are added to the drop down).  It hasn't caused any problems so far, so I hadn't reported it, but maybe it's related?

### Environment
* Version of LPub3D
![image](https://user-images.githubusercontent.com/1654485/118710216-491b7d00-b81e-11eb-87d7-057ca782e2fd.png)
* Operating system - Win10, x86_64

### Configuration
Happy to share any additional configs or files that would be helpful.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

Can you share an example model file that is reproducing this behaviour ? If you prefer, you can PM it via my email.

Cheers,

**Comment by trevorsandy** [comment]
I'm not able to reproduce this behaviour at the moment but I'll keep this ticket open a bit longer in case something changes.

Cheers,
