### ISSUE TITLE
No Prompt Using the Command Line Option

### ISSUE THREAD

**Issue by Relento** [trevorsandy/lpub3d#554]
### Subject
I can generate instructions using the command line option. But there is no prompt no matter what command I use to run `LPub3D.exe`. For example, `LPub3D.exe --help` will have no outputs in the console and the program exits immediately. There is no output in the `LPub3DLog.txt` as well if I run this command. 
![image](https://user-images.githubusercontent.com/23029424/119280905-53f05c00-bbe8-11eb-9104-91cae01722c3.png)

### Environment
* Version of LPub3D - 2.4.3 Revision 0 Build 2557
* Operating system - Win 10, x64

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by Relento** [comment]
Redirection to output works. Yeah, it is a weird issue.... Anyway, thanks for your prompt reply!
