### ISSUE TITLE
Command Line  Option Cannot Change Export Directory when Exporting PNG Files

### ISSUE THREAD

**Issue by Relento** [trevorsandy/lpub3d#555]
First, thanks for your great work on this project!

### Subject
It seems that I cannot change the export directory using the `-d` option when exporting instructions as png files. LPub3D will treat the directory where ldr file is in as the export directory. `-of` option works perfectly when exporting instructions as pdf files. 

### Environment
* Version of LPub3D - 2.4.3 Revision 0 Build 2557
* Operating system - Win 10, x64

### Solution suggestion
It seems that here
https://github.com/trevorsandy/lpub3d/blob/14d22e32da2cd621ede7275bd1cd28b2a0c45aa0/mainApp/commandline.cpp#L340-L341 the code will parse the arguments as `saveFileName` rather than `saveDirectoryName`, I think changing it to `saveDirectoryName` may fix the problem? But I don't read through related code thoroughly.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

Cheers,
