### ISSUE TITLE
Unexpected gap between step number and PLI

### ISSUE THREAD

**Issue by cjhendrix** [trevorsandy/lpub3d#556]
### Subject
In multi step, with a specific combination of step number and PLI placement commands, there is an unexpected gap between the step number and PLI:
![image](https://user-images.githubusercontent.com/1654485/119764439-ac0db380-beb1-11eb-86dd-74aff328f9a0.png)

This only seems to occur in these conditions:

1. the step number is on top or bottom of the parts list (not left or right) AND
2. the pli is to the left or right of the assembly (not top or bottom)

In this example (with PLI at `TOP LEFT`), the gap is as expected
![image](https://user-images.githubusercontent.com/1654485/119764792-5a195d80-beb2-11eb-919e-33138a4f22eb.png)

All my margins are set the same (top/bottom = left/right), but just in case, the only multi step margin commands in the file are:
```
0 !LPUB MULTI_STEP ASSEM MARGINS 0.6 0.6
0 !LPUB MULTI_STEP PLI MARGINS 0.1000 0.1000
```

### Environment
* Version of LPub3D - 
![image](https://user-images.githubusercontent.com/1654485/119765133-e62b8500-beb2-11eb-9673-1811c268fd77.png)

* Operating system - Win10, x86_64

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by jacovandermolen** [comment]
Follow up on this one.
Here is what happens too with the PLI and stepnumber using the settings in my standard header.ldr

![car_150_DPI_page_1](https://user-images.githubusercontent.com/32261647/228507687-93d6d0de-33b7-41c5-8197-3e2032999398.png)

[car - kopie.ldr.txt](https://github.com/trevorsandy/lpub3d/files/11099611/car.-.kopie.ldr.txt)
[header.ldr.txt](https://github.com/trevorsandy/lpub3d/files/11099612/header.ldr.txt)

I expect this:
![car_150_DPI_page_1](https://user-images.githubusercontent.com/32261647/228508252-af3b0d72-48d8-48e7-9ac0-5575f959028b.png)

**Comment by DanieleBenedettelli** [comment]
Same problem here. In build 2.4.4 it worked fine, with latest build 2.4.6 the pli overlap.

**Comment by trevorsandy** [comment]
Hello Jaco and Daniele

Thank you for reporting this behaviour.

Indeed, this behaviour is unfortunately a regression I have caused by my attempt to correct an age-old LPub bug whereby placing an item at certain positions outside of its relativeTo item was broken - see #690.

Consequently, I will move your remarks to a new ticket #694

Cheers,

**Comment by trevorsandy** [comment]
Unfortunately, I am unable to reproduce this behaviour with the latest release build.

For me, the multi-step page does not render with an unexpected gap for the following condition:

1. the STEP number is on TOP or BOTTOM of the PLI ( not LEFT or RIGHT ) and
2. the PLI is to the LEFT or RIGHT of the CSI ( not TOP or BOTTOM )

Portrait
![UnexpectedGap](https://user-images.githubusercontent.com/13388970/228994413-68c29aaf-df85-4959-9ba3-af4174b0dce0.png)

Landscape
![UnexpectedGapLandscape](https://user-images.githubusercontent.com/13388970/228995463-25ccc5e1-f89e-4e76-abc3-4db4e7600536.png)

If you continue to experience this behaviour on the latest release of LPub3D, do not hesitate to reopen this ticket.

Cheers,
