### ISSUE TITLE
Generating PDF crashes LPub on a certain page

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#557]
### Subject
Generating PDF crashes LPub on a certain page

### Environment
* Version of LPub3D 2.4.3.6.2793
* Windows 10 64 bit

### Configuration
Local distribution

### Steps to reproduce
Generating a PDF from this file crashes upon reaching page 19.
[40252LPub243x.mpd.txt](https://github.com/trevorsandy/lpub3d/files/6553426/40252LPub243x.mpd.txt)

### Expected behavior
LPub should not crash and produce the PDF ;-)

### Actual behavior
Crash

**Comment by trevorsandy** [comment]
Hi Jaco,

This behaviour has been corrected. You can take a look with the latest [DevOps build](https://github.com/trevorsandy/lpub3d-ci/releases/tag/continuous).

Let me know if your checks continue to produce unexpected behaviour. 

Cheers,
