### ISSUE TITLE
Submodel preview image is empty for some submodels

### ISSUE THREAD

**Issue by cjhendrix** [trevorsandy/lpub3d#558]
### Subject
The command `SUBMODEL_DISPLAY SHOW GLOBAL TRUE` is set at the beginning of the file and non-callout submodels are being displayed with their first step as expected with one exception. On this page, the "image is empty", and LPub3D produces two errors:

![image](https://user-images.githubusercontent.com/1654485/119928664-50f4c300-bf7c-11eb-842d-4c7cc0cf3a91.png)

![image](https://user-images.githubusercontent.com/1654485/119928817-9fa25d00-bf7c-11eb-8f97-0514db31be47.png)

Sometimes, (but not always), two additional error messages are generated, then abend.

I've tried deleting the LPUB folder for the project and reopening the file. I also get the same result in multistep or single step. 

Two possible clues:
1) You can see in the screencaps above that the submodel display (empty image icon) is at top left to the step number. This is the correct position. However, after the error messages are accepted, the submodel display moves to the right.
![image](https://user-images.githubusercontent.com/1654485/119929345-9d8cce00-bf7d-11eb-80c5-21dc034dc064.png)

2) This submodel is nested one level further down that the others, which are displaying correctly. The hierarchy looks like this:

- MPD (`SHOW GLOBAL TRUE`)
-- submodel (not displayed, `SHOW LOCAL FALSE`)
--- submodel (displays correctly)
---- submodel (does not display)
--- submodel (displays correctly)

I'm happy to provide the MPD if that's helpful.

### Environment
* Version of LPub3D 
![image](https://user-images.githubusercontent.com/1654485/119929705-4cc9a500-bf7e-11eb-960e-a7d3c9470961.png)
* Operating system - Win10 ,x86_64

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

> I'm happy to provide the MPD if that's helpful.

Indeed. A simple example MPD would be quite helpful. 

Cheers,

**Comment by trevorsandy** [comment]
I'm taking a look at this item for the next release (2.4.5). It would be quite helpful to have a example model file that produces this behaviour. Ideally also specifying the step/page where the behaviour resides if there are multiple occurrences of the troubled item.

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

Cheers,
