### ISSUE TITLE
CALLOUT ROTATE_ICON SIZE shifts icon but doesn't change size

### ISSUE THREAD

**Issue by cjhendrix** [trevorsandy/lpub3d#560]
### Subject
The command shifts the position of the rotate icon around within the callout, but doesn't change the size. This is a different behavior than the non-callout version of the command.

To replicate:
On a rotate icon within a callout, right-click and use "change rotate icon size" to set new values
Icon will shift location, but size remains the same

### Environment
* Version of LPub3D
![image](https://user-images.githubusercontent.com/1654485/120141724-4be27e80-c1dd-11eb-9ad5-c619946f85c6.png)

* Operating system - Win10 ,x86_64

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. Indeed, this does not appear to be the expected behaviour. I’ll take a look.

Cheers,

**Comment by adaneslavo** [comment]
I did some global defines for Rotation Icon. It works fine, but one icon is stubborn and do not want to change at all:
![obraz](https://user-images.githubusercontent.com/33016300/147632894-b897481a-d412-4447-8d42-9726228573aa.png)
![obraz](https://user-images.githubusercontent.com/33016300/147632954-b272dce7-07bd-4dc7-8df9-3263c83107b3.png)
![obraz](https://user-images.githubusercontent.com/33016300/147632988-d0e6e960-f159-4695-bd08-354be7fd800e.png)
[Pobrane.zip](https://github.com/trevorsandy/lpub3d/files/7787575/Pobrane.zip)

**Comment by trevorsandy** [comment]
I'm taking a look at this item for the next release (2.4.5). It would be quite helpful to have a example model file that produces this behaviour. Ideally also specifying the step/page where the behaviour resides if there are multiple occurrences of the troubled item.

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

Cheers,
