### ISSUE TITLE
Could not write to Native PLI image file...

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#562]
### Subject
Error
Could not write to Native PLI image file: [path]...rel.png]
Reason: Image is empty. 

### Environment
LPub3D_x86_64-2.4.3.49.2836_20210609

### Screenshots
![afbeelding](https://user-images.githubusercontent.com/32261647/121315407-9adc9200-c908-11eb-86e8-b9c210b27242.png)

### Steps to reproduce
Reaching a multistep page where a submodel starts I get this error

### Expected behaviour
The submodel preview should be rendered

### Actual behaviour
![afbeelding](https://user-images.githubusercontent.com/32261647/121315123-551fc980-c908-11eb-9982-d88d38edeb2e.png)

### Workaround
None found

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. Indeed the DevOps build is currently unstable. Could you share the log file generated when this error is produced ?

Cheers,

**Comment by jacovandermolen** [comment]
[LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/6622298/LPub3DLog.txt)

**Comment by trevorsandy** [comment]
Thank you. I don't see any anomalies in the log trace. Is this behaviour reproducible on a generic multi-step page ? If not then I'll need an example model file that reproduces the behaviour.

I also noted you are using an include file. Is this where the image meta command behaviour reported in #561 is located ?

Cheers,

**Comment by jacovandermolen** [comment]
I am not sure what you mean by a "generic multi-step page".

I can PM (mail) you the model, since I do not want it to be public here.

My standard settings (header) file is also located on my Google Drive folder, which I sync on my computers and laptops where I work from. I have a LEGO folder on my synced drive where the header file is, my LDConfig and pli.ldr

Then I work from a Models subfolder with subfolders for my models on the local machine where I work from.
Each model has its own folder like this

C:\MJ\LEGO\Models\SomeModel\SomeModel.ldr
C:\MJ\LEGO\Models\SomeOtherModel\SomeOtherModel.ldr
etc...

**Comment by trevorsandy** [comment]
Ok. Thanks. 

> I am not sure what you mean by a "generic multi-step page".

A simple page with more than 1 step whithout advanced configuration like BUFEXCHG, CALLOUTS etc...

Cheets,

**Comment by jacovandermolen** [comment]
Ah, OK. It is page 1 step 1 with a buildmod.
This page has 3 steps, where step 3 is a rotation step.
I will remove that and see what happens.

**Comment by adaneslavo** [comment]
I encountered the same problem in my build:
![obraz](https://user-images.githubusercontent.com/33016300/147632315-cdc6d295-0818-4604-abab-cdf15c04266b.png)
![obraz](https://user-images.githubusercontent.com/33016300/147632334-0bd26aee-5671-4cf1-8a01-cfbf56b7b094.png)
![obraz](https://user-images.githubusercontent.com/33016300/147632359-dbefde4c-dbd6-4a20-ae6b-bd18289465a0.png)
[LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/7787546/LPub3DLog.txt)
The funny thing is the Callout is done correctly.

Initial setup:
```
0 !LPUB PAGE SIZE GLOBAL 5.8268 8.2677 A5
0 !LPUB PAGE ORIENTATION GLOBAL LANDSCAPE
0 !LPUB PAGE SUBMODEL_BACKGROUND_COLOR "#e3e3e3" "#ffffcc" "#ffcccc" "#ccccff"
0 //Stepy
0 !LPUB STEP_NUMBER PLACEMENT GLOBAL BOTTOM LEFT PLI OUTSIDE
0 //Assembly
0 !LPUB ASSEM MARGINS GLOBAL 0.5 5
0 !LPUB ASSEM MODEL_SCALE  GLOBAL 2.000
0 //Multistepy
0 !LPUB MULTI_STEP STEP_SIZE GLOBAL 3.7000 2.400
0 !LPUB MULTI_STEP ASSEM MARGINS GLOBAL 0.3000 0.0000
0 !LPUB MULTI_STEP MARGINS GLOBAL 0.5000 0.5000
0 !LPUB MULTI_STEP SEPARATOR GLOBAL 0.0123031 black 0.19685 0.19685
0 !LPUB MULTI_STEP PLACEMENT GLOBAL TOP PAGE INSIDE
0 !LPUB MULTI_STEP PLI PLACEMENT GLOBAL TOP_LEFT ASSEM OUTSIDE
0 !LPUB MULTI_STEP STEP_NUMBER GLOBAL PLACEMENT BOTTOM LEFT PLI OUTSIDE
0 //Callouty
0 !LPUB CALLOUT SEPARATOR GLOBAL 0.0312499 Black 0.19685 0.19685
0 !LPUB CALLOUT BORDER GLOBAL ROUND Black 0.0312499 15 MARGINS 0.0499999 0.0499999
0 !LPUB CALLOUT PLI PER_STEP GLOBAL FALSE
0 //Ramki z czesciami
0 !LPUB PLI BORDER GLOBAL ROUND 0 Black 0.031 15.000 MARGINS 0.050 0.050
0 !LPUB PLI MARGINS GLOBAL 0.3000 0.3000
0 !LPUB PLI PART MARGINS GLOBAL 0.2000 0.2000
0 !LPUB PLI INSTANCE_COUNT MARGINS 0.2000 0.2000
0 !LPUB PLI PLACEMENT TOP_LEFT PAGE INSIDE
0 !LPUB PLI SORT_ORDER PRIMARY GLOBAL "Part Category"
0 !LPUB PLI SORT_ORDER SECONDARY GLOBAL "Part Color"
0 !LPUB PLI SORT_ORDER TERTIARY GLOBAL "Part Size"
0 !LPUB PLI SORT_ORDER PRIMARY_DIRECTION GLOBAL "Ascending"
0 !LPUB PLI SORT_ORDER SECONDARY_DIRECTION GLOBAL "Ascending"
0 !LPUB PLI SORT_ORDER TERTIARY_DIRECTION GLOBAL "Descending"
0 !LPUB PLI INSTANCE_COUNT FONT GLOBAL "Arial,20,-1,5,75,0,0,0,0,0,Pogrubiony"
0 !LPUB PLI MODEL_SCALE GLOBAL 1.8000
0 !LPUB PLI BACKGROUND COLOR "#ffffff"
```
![obraz](https://user-images.githubusercontent.com/33016300/147632520-465eb096-ea95-408c-a29e-41195c32f532.png)

**Comment by aefferenpriv** [comment]
I am experiencing this behavior in the latest version as well. Version 2.4.4 revision 4 build 2675 
<img width="386" alt="image" src="https://user-images.githubusercontent.com/93044629/173834824-d9acf86a-1b31-4cde-bd1d-19b930668fa1.png">

**Comment by trevorsandy** [comment]
If you continue to experience this behaviour on the latest release of LPub3D, do not hesitate to reopen this ticket.

Cheers,
