### ISSUE TITLE
Messed up render of part

### ISSUE THREAD

**Issue by CreativeMind12** [trevorsandy/lpub3d#563]
I am trying to make instructions for my upcoming moc in Lpub3d, but on the very first page there is a messed up render of the "Technic Beam 11 x 5 with Open Center 5 x 3". Could you please help me fix this? Thanks. (And Yes I have installed the latest version)
![Screenshot 2021-06-17 145645](https://user-images.githubusercontent.com/86082645/122477245-46768980-cf7c-11eb-9d38-8dfa5682ef7f.png)

**Comment by DouglasVH01** [comment]
I found that altering the scale of the parts list fixes this.  If you right click on the parts list, inside the box, but not on any part, and choose "Change Parts List Scale", then change it to, say, 1.01, or 0.99, that often fixes this problem.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

Unfortunately, I am unable to reproduce this behaviour with the latest build.

If you continue to experience this behaviour on the latest release of LPub3D, do not hesitate to reopen this ticket.

Cheers,
