### ISSUE TITLE
I lost half of my project when I imported it into Lpub3d

### ISSUE THREAD

**Issue by CreativeMind12** [trevorsandy/lpub3d#564]
Hi everyone, I just want to state that Lpub3d has been malfunctioning for me since day one. Recently, I imported my creating into Lpub3d, and it had 106 steps to start with and a few submodels. After importing it into Lpub3d, it totally messed up my creation and turned it into 282 pages, but when I look into the instructions it just repeats the same few steps over and over again. When I imported my project back into LDCad, it only showed those few steps that lPub3d was rendering over and over again. Highly disappointed. I will be uninstalling Lpub3d unless the creator fixes this for me.

**Comment by adaneslavo** [comment]
Yeah, this is is annoying issue. Backups guys. For now, only this can save your life :)

**Comment by adaneslavo** [comment]
In my file I noticed, that when I reach and pass 300 lines, then the code above that number is copied to the top of the code. This issue can be done by editor few times making the code multiply to over 1000 lines. You can do nothing to stop this, especially in bigger projects.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

This behaviour has been corrected.

If you continue to experience this behaviour on the latest release of LPub3D, do not hesitate to reopen this ticket.

Cheers,
