### ISSUE TITLE
Error when marking a line in the LDraw editor

### ISSUE THREAD

**Issue by technicbasics** [trevorsandy/lpub3d#565]
### Subject
Same problem, as I already submit #515 
Sometimes, after this problem, it is no longer possible to mark text because the cursor can no longer be set.
And it also happens that the model code is copied from this marking to the end of the (sub) model, and is inserted at the end of the code. This was already reported in #564.

### Environment
* Version of LPub3D - 2.4.3r0
* Operating system - Win10
Prozessor	Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz   2.60 GHz
Installierter RAM	12,0 GB (11,9 GB verwendbar)
Systemtyp	64-Bit-Betriebssystem, x64-basierter Prozessor

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

Cheers,
