### ISSUE TITLE
Command Editor Issues - multiple issues

### ISSUE THREAD

**Issue by trdoolan** [trevorsandy/lpub3d#566]
### Subject
Multiple errors and corruptions of code when using command editor

### Environment
* Version of LPub3D - see Help->About LPub3D
v2.4.3 r0 (Portable)
* Operating system - OS Name, Processor Architecture (x86,x86_64)
Win10-64bit, AMD Ryzen5 2600 (x86_64), 48Gb RAM

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
 - Portable version
  - Windows: `%USERPROFILE%\Desktop\LPub3D_x86_64\

* Application data path
  - Windows: `%USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\`

* Registry Extract
  - Windows (portable): `<application path>\config\LPub3D Software\LPub3D.ini`

* Renderer configuration files
  - `[Application data path]/ldv/ldvExport.ini`
  - `[Application data path]/3rdParty/ldglite-1.3/config/ldglite.ini`
  - `[Application data path]/3rdParty/ldview-4.4/config/ldview.ini`
  - `[Application data path]/3rdParty/ldview-4.4/config/ldviewPOV.ini`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.conf`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.ini`

### Logs
* Application Log: `[Application data path]/logs/LPub3DLog.txt`
* Renderer Log: `[LDraw model path]/stdout-ldglite`
* Renderer Log: `[LDraw model path]/stdout-povray`
* Renderer Log: `[LDraw model path]/stderr-ldglite`
* Renderer Log: `[LDraw model path]/stderr-povray`

### Screenshots
* Configuration->Preferences->General
* Configuration->Preferences->Rendering
* Configuration->Preferences->Publishing
[Issue Files.zip](https://github.com/trevorsandy/lpub3d/files/6912059/Issue.Files.zip)
[Issue Files.zip](https://github.com/trevorsandy/lpub3d/files/6912060/Issue.Files.zip)

* Configuration->Preferences->Logging
* Configuration->Preferences->Other

### Steps to reproduce
Tell me how to reproduce this issue.
Provide a sample mpd/ldr file that reproduces the problem.
Happens with all LDR files at present. Current design is approx 7800pcs, but also happening with models as low as 800pcs

### Expected behaviour
To work as any text editor interface would, as it did previously. 

### Actual behaviour
Issue 1: editor does not accept click and type editing about 50% of the time. 
Issue 2: editor malforms typed input. Best example is that it copies-in-reverse what is entered, such as applying "0 ROTSTEP 0 0 0 RELLER 0 0 0 PETSTOR 0" when "0 ROTSTEP 0 0 0 REL" is typed in the editor.
Issue 3: editor is randomly copying and adding entire sections of code to the end of the section.
Issue 4: I think this has been reported previously, but when using the mouse to click-select a block of text, after releasing the mouse button, the editor acts as if it still clicked and continued moving-selecting text. 

### Workaround
None. Having to manually edit errors out using external editor. 

### Solution suggestion
Unknown. I've no idea as to what has caused this in the first place to offer a valid opinion on a solution, i'm sorry.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

This behaviour has been corrected.

Cheers,
