### ISSUE TITLE
Parts list doesn't appear in steps after callout

### ISSUE THREAD

**Issue by trdoolan** [trevorsandy/lpub3d#567]
### Subject
Steps subsequent to callout used do not have a parts window

### Environment
* Version of LPub3D - see Help->About LPub3D
 v2.4.3 r0 (Portable)
* Operating system - OS Name, Processor Architecture (x86,x86_64)
 Win10-64bit, AMD Ryzen 5 2600 (x86_64)

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  - Windows: `%USERPROFILE\Desktop\LPub3D_x86_64\

* Application data path
  - Windows: `%USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\`

* Registry Extract
  - Windows (portable): `<application path>\config\LPub3D Software\LPub3D.ini`
* Renderer configuration files
  - `[Application data path]/ldv/ldvExport.ini`
  - `[Application data path]/3rdParty/ldglite-1.3/config/ldglite.ini`
  - `[Application data path]/3rdParty/ldview-4.4/config/ldview.ini`
  - `[Application data path]/3rdParty/ldview-4.4/config/ldviewPOV.ini`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.conf`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.ini`

### Logs
* Application Log: `[Application data path]/logs/LPub3DLog.txt`
* Renderer Log: `[LDraw model path]/stdout-ldglite`
* Renderer Log: `[LDraw model path]/stdout-povray`
* Renderer Log: `[LDraw model path]/stderr-ldglite`
* Renderer Log: `[LDraw model path]/stderr-povray`

### Screenshots
* Configuration->Preferences->General
* Configuration->Preferences->Rendering
* Configuration->Preferences->Publishing
* Configuration->Preferences->Logging
* Configuration->Preferences->Other

### Steps to reproduce
Happening with multiple files

### Expected behaviour
PLI window should still be present as for previous steps

### Actual behaviour
No PLI window on steps subsequent to callout step

### Workaround
None at present. Likely have to use a separate assembly page and manually edit output images to create desired result

### Solution suggestion
None at this time.
![Screenshot 2021-08-01 124310](https://user-images.githubusercontent.com/44559092/127757396-29e98906-9485-4976-8e6d-0af3e3330eeb.png)
[Issue Files.zip](https://github.com/trevorsandy/lpub3d/files/6912068/Issue.Files.zip)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. Unfortunately, I cannot reproduce it on the latest development build with the model files I have. 

For me, the behaviour is as expected. PLIs are rendered after a callout step.

![Screenshot - 11_09_2022 , 03_38_05](https://user-images.githubusercontent.com/13388970/189508047-ae76a6e2-f4c7-4147-b0e1-d9213ccc5c50.png)

![Screenshot - 11_09_2022 , 03_38_38](https://user-images.githubusercontent.com/13388970/189508049-dcc358f9-c5a7-4266-8d2b-2fc3db2731ce.png)

If you could provide an example model file that produces this behaviour it would be quite helpful.

Cheers,

**Comment by trevorsandy** [comment]
If you continue to experience this behaviour on the latest release of LPub3D, do not hesitate to reopen this ticket.

Cheers,
