### ISSUE TITLE
Remove Group meta doesn't work

### ISSUE THREAD

**Issue by technicbasics** [trevorsandy/lpub3d#569]
### Subject
Useing the the "0 !LPUB REMOVE GROUP "xxx" " doesn´t work.

### Environment
* Version of LPub3D - 2.4.3r0
* Operating system - Win10 64 bit

The meta work's in 2.3.13r133 fine!
See attached file and pictures.

V2.3.13r133:

![RG_2_3 13_r133](https://user-images.githubusercontent.com/49073781/130594411-6cd20e71-b9ca-4592-9de5-fab6b860000f.PNG)

V 2.4.3r0:
![RG_2_4_3_r0](https://user-images.githubusercontent.com/49073781/130594468-d29f6ff1-790f-4aba-88f2-6a6c7623ca94.PNG)

File:
0 Name: Removegroup.ldr
0 Author: Johann Eisner [technicbasics]
0 !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
0 !LPUB MULTI_STEP BEGIN
1 2 0 0 0 0 -1 0 -1 0 0 0 0 -1 32526.dat
1 0 10 -40 -80 -1 0 0 0 1 0 0 0 -1 2780.dat
0 STEP
0 MLCAD BTG A
1 4 20 -40 -80 0 -1 0 -1 0 0 0 0 -1 32526.dat
0 GROUP 1 A
0 STEP
0 !LPUB REMOVE GROUP "A"
0 !LPUB PLI BEGIN IGN
1 4 20 -40 -80 0 -1 0 1 0 0 0 0 1 32526.dat
0 !LPUB PLI END
1 71 20 0 0 -1 0 0 0 0 1 0 1 0 32054.dat
0 STEP
0 !LPUB MULTI_STEP END

**Comment by trevorsandy** [comment]
Corrected.

![Screenshot - 11_09_2022 , 07_27_13](https://user-images.githubusercontent.com/13388970/189513827-34dd032c-9383-4863-9aad-47d0532ecb66.png)

Cheers,
