### ISSUE TITLE
Bill of materials showing twice in PDF file

### ISSUE THREAD

**Issue by snakebyte73** [trevorsandy/lpub3d#571]
### Subject
I am having trouble when generating the pdf file.
The last page of the Bill of materials is shown twice in the PDF.
![Pic01](http://www.snakebyte.dk/lego/lpub3d_forum/BillOfMaterialsPic01.png)

How do i avoid this ?

### Environment
* Version of LPub3D - Release2.4.3 Revision 0 Build 2557
* Operating system - Windows 10 X64
![Pic01](http://www.snakebyte.dk/lego/lpub3d_forum/BillOfMaterialsVersion.png)

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  - Windows: C:\Program Files\LPub3D\
* Application data path
  - Windows: `%USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\`
* Registry Extract
  - Windows (installed): `reg export "HKEY_CURRENT_USER\Software\LPub3D Software" %USERPROFILE%\Desktop\LPub3D_Hive.reg`
* Renderer configuration files
  - `[Application data path]/ldv/ldvExport.ini`
  - `[Application data path]/3rdParty/ldglite-1.3/config/ldglite.ini`
  - `[Application data path]/3rdParty/ldview-4.4/config/ldview.ini`
  - `[Application data path]/3rdParty/ldview-4.4/config/ldviewPOV.ini`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.conf`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.ini`

### Logs
* Application Log: `[Application data path]/logs/LPub3DLog.txt`
* Renderer Log: `[LDraw model path]/stdout-ldglite`
* Renderer Log: `[LDraw model path]/stdout-povray`
* Renderer Log: `[LDraw model path]/stderr-ldglite`
* Renderer Log: `[LDraw model path]/stderr-povray`

### Screenshots
![Pic01](http://www.snakebyte.dk/lego/lpub3d_forum/BillOfMaterialsPrefsGeneral.png)
![Pic01](http://www.snakebyte.dk/lego/lpub3d_forum/BillOfMaterialsPrefsRenderes.png)
![Pic01](http://www.snakebyte.dk/lego/lpub3d_forum/BillOfMaterialsPrefsPublishing.png)
![Pic01](http://www.snakebyte.dk/lego/lpub3d_forum/BillOfMaterialsPrefsThemeLogging.png)
![Pic01](http://www.snakebyte.dk/lego/lpub3d_forum/BillOfMaterialsPrefsOther01.png)
![Pic01](http://www.snakebyte.dk/lego/lpub3d_forum/BillOfMaterialsPrefsOther02.png)

### Steps to reproduce
This is what the steps look like:
0 STEP
0 // The following 3 command lines were auto-generated for fade or highlight step.
0 // Use 0 !LPUB INSERT DISPLAY_MODEL to override automatic insertion and deletion.
0 !LPUB NOSTEP
0 !LPUB INSERT MODEL
0 !LPUB INSERT PAGE
0 STEP
0 !LPUB BOM CONSTRAIN LOCAL HEIGHT 5.1800
0 !LPUB INSERT COVER_PAGE BACK
0 !LPUB INSERT BOM
0 NOFILE 

### Expected behaviour
Tell me what should happen

### Actual behaviour
Tell me what happens instead

### Workaround
Share your work around if available

### Solution suggestion
Share your opinion on how to achieve the expected behaviour

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

Unfortunately, I am unable to reproduce this behaviour with the latest build. For me the BOM is displayed as expected.

If you continue to experience this behaviour on the latest release of LPub3D, do not hesitate to reopen this ticket.

Cheers,
