### ISSUE TITLE
Part not showing correctly in LPub3D

### ISSUE THREAD

**Issue by snakebyte73** [trevorsandy/lpub3d#572]
### Subject
part 2958c01.dat not showing correctly in LPub3D
The is what it looks like in LDCad
![Pic01](http://www.snakebyte.dk/lego/lpub3d_forum/DishPic01.png)

This is what it looks like in LPub3D
![Pic01](http://www.snakebyte.dk/lego/lpub3d_forum/DishPic02.png)

I have checked the complete.zip in "C::\Users\<MyUser>\AppData\Local\LPub3D Software\LPub3D\libraries\
and all the dat files used for this part is precent.

### Environment
* Version of LPub3D - Release2.4.3 Revision 0 Build 2557
* Operating system - Windows 10 X64
![Pic01](http://www.snakebyte.dk/lego/lpub3d_forum/BillOfMaterialsVersion.png)

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  - Windows: Windows: C:\Program Files\LPub3D\
* Application data path
  - Windows: %USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\
* Registry Extract
  - Windows (installed): `reg export "HKEY_CURRENT_USER\Software\LPub3D Software" %USERPROFILE%\Desktop\LPub3D_Hive.reg`
* Renderer configuration files

### Logs
* Application Log: `[Application data path]/logs/LPub3DLog.txt`
* Renderer Log: `[LDraw model path]/stdout-ldglite`
* Renderer Log: `[LDraw model path]/stdout-povray`
* Renderer Log: `[LDraw model path]/stderr-ldglite`
* Renderer Log: `[LDraw model path]/stderr-povray`

### Screenshots
![Pic01](http://www.snakebyte.dk/lego/lpub3d_forum/BillOfMaterialsPrefsGeneral.png)
![Pic01](http://www.snakebyte.dk/lego/lpub3d_forum/BillOfMaterialsPrefsRenderes.png)
![Pic01](http://www.snakebyte.dk/lego/lpub3d_forum/BillOfMaterialsPrefsPublishing.png)
![Pic01](http://www.snakebyte.dk/lego/lpub3d_forum/BillOfMaterialsPrefsThemeLogging.png)
![Pic01](http://www.snakebyte.dk/lego/lpub3d_forum/BillOfMaterialsPrefsOther01.png)
![Pic01](http://www.snakebyte.dk/lego/lpub3d_forum/BillOfMaterialsPrefsOther02.png)

### Steps to reproduce
Just add the part and check it out in LPub3D
1 0 0 -33 220 -1 0 0 0 1 0 0 0 -1 2958c01.dat

### Expected behaviour
The stickers should be visible on the part

### Actual behaviour
Tell me what happens instead

### Workaround
Share your work around if available

### Solution suggestion
Share your opinion on how to achieve the expected behaviour

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

Unfortunately, I am unable to reproduce this behaviour with the latest build. For me the behaviour is as expected.

If you continue to experience this behaviour on the latest release of LPub3D, do not hesitate to reopen this ticket.

Cheers,
