### ISSUE TITLE
Add next steps button is gone in latest version

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#573]
I just noticed that the latest version of LPub (2.4.3) is missing the button to add multiple steps at once that used to appear when clicking with the right-mouse button on the page. The one which was added here: https://github.com/trevorsandy/lpub3d/issues/136

**Comment by Landcross** [comment]
Well I'll be damned. This morning the button has appeared again. Maybe it's somehow related to whatever submodel is in focus, no idea. I'll try to investigate. In the meantime I guess this issue is 'on hold' 😅

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

Launching the context menu from hovering over the assembly will yield different menu items than hovering over the page or even within the assembly item border.

Be sure you are placing the mouse cursor to engage the desired context menu actions.

Cheers,
