### ISSUE TITLE
Submodel usage/times indicator appears 1 step too early

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#574]
Imagine a submodel with 5 steps that is used 4x. If I put the first 4 steps on page 1 and the last step on page 2, then both pages now show 4x, but only the last page should show 4x. The configuration of the steps doesn't matter. As long as the second-to-last step is in a step-group and the last step is separate, then both last pages of the submodel show the 4x.

I'm using latest official release LPub 2.4.3

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

Unfortunately, I am unable to reproduce this behaviour with the latest build.

If you continue to experience this behaviour on the latest release of LPub3D, do not hesitate to reopen this ticket.

Cheers,
