### ISSUE TITLE
[v2.4] Submodel preview crashes the LPub3d

### ISSUE THREAD

**Issue by adaneslavo** [trevorsandy/lpub3d#575]
[LPub3D 2.4.0.0.1990 + Win 7 x64]
When I enable "Submodel preview" in "Configuration/Build Instructions Setup/Submodel Preview Setup" LPub keeps crashing when I enter the page with submodel. No matter I use Global or Local commands, basic or enhanced commads or simple project with default setting - even base thing makes crash.

![obraz](https://user-images.githubusercontent.com/33016300/147629792-89cef354-5515-4da6-9054-007d8535f430.png)

I upload logs, earliest and latest save I made of project, pdf file for you to know what to expect in the project:
[LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/7787425/LPub3DLog.txt)
[Submodel_preview.zip](https://github.com/trevorsandy/lpub3d/files/7787431/Submodel_preview.zip)
[(alt) 8236 - Motocykl_150_DPI.pdf](https://github.com/trevorsandy/lpub3d/files/7787446/alt.8236.-.Motocykl_150_DPI.pdf)
[LPub3D.zip](https://github.com/trevorsandy/lpub3d/files/7787514/LPub3D.zip)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

Unfortunately, I am unable to reproduce this behaviour.

If you continue to experience this behaviour on the latest release of LPub3D, do not hesitate to reopen this ticket.

Cheers,
