### ISSUE TITLE
[v2.4] BoM components alignment

### ISSUE THREAD

**Issue by adaneslavo** [trevorsandy/lpub3d#576]
In official LEGO instructions all parts listed in BoM are aligned in columns, and thos columns are aligned to top left corner of the BoM area. Is there any ays to copy that behaviour? By default it is aligned to bottom left corner and I cannot change that.
![obraz](https://user-images.githubusercontent.com/33016300/147630197-0cc7cfad-e82e-4a14-b434-bd2bec21dd2c.png)
![obraz](https://user-images.githubusercontent.com/33016300/147630320-4fe804b8-4896-492e-9e09-2b9cc518f985.png)

Moreover some sorting is not correct (current Color ==> Category ==> Size):
![obraz](https://user-images.githubusercontent.com/33016300/147708539-5e92190b-c697-4b80-ac9d-4e04b7e846b2.png)
![obraz](https://user-images.githubusercontent.com/33016300/147708690-6084166f-3df3-466b-b069-d8448e62d275.png)
As you can see, some parts switched their places.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

Please see #257 and #225 for additional BOM sorting details.

Cheers,
