### ISSUE TITLE
[v2.4] PLI Alignment and Assem margin

### ISSUE THREAD

**Issue by adaneslavo** [trevorsandy/lpub3d#577]
When I use command:
```
0 !LPUB MULTI_STEP PLI PLACEMENT GLOBAL TOP_LEFT ASSEM OUTSIDE
```
but instead of TOP_LEFT I use either TOP LEFT, TOP CENTER, etc. then using:
```
0 !LPUB MULTI_STEP ASSEM MARGINS
```
allows me to move Assem only in vertical axis. The horizontal axis is blocked whatever value is entered in first parameter. I put an example in multistep, but in standard page the problem persists.

Also, setting 
```
0 !LPUB PLI PLACEMENT GLOBAL TOP_LEFT STEP_NUMBER OUTSIDE
```
with whatever alignment throws an error:
![obraz](https://user-images.githubusercontent.com/33016300/147630755-8e0800bd-06a4-4868-bf5b-29ac89068d72.png)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

This behaviour is as designed.

Please see the #602 for how to review the available LPub3D meta commands.

Cheers,
