### ISSUE TITLE
[v2.4] CTDs and "computer thoughts"

### ISSUE THREAD

**Issue by adaneslavo** [trevorsandy/lpub3d#578]
[Win 7 x64 + LPub3d 2.4.0.0.1990]
Two things:
- LPub keeps crashing whenever I move an object: Arrow, Frame, Callout, Image and quickly try to click another object or even the same. It looks like it thinks too long and cannot be stopped. These crashes are really frequent, so I make backups every important change is made.
![obraz](https://user-images.githubusercontent.com/33016300/147631382-7de4fccb-40e8-4378-8753-d3b162745b0c.png)
[LPub3D.zip](https://github.com/trevorsandy/lpub3d/files/7787500/LPub3D.zip)

- Cursor very often disappears when I f.e. change PLI window dimensions, move an Arrow and few other procedures. Insted of cursos shows up Windows' circle of "thinking" and keeps circling until I restart LPub. It makes very hard to point something precisely, especially in the code.
![obraz](https://user-images.githubusercontent.com/33016300/147631488-662c038f-b76d-45d2-8c2f-10750916df83.png)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

There have been many improvements to the latest release of LPub3D.

If you continue to experience this behaviour on the latest release of LPub3D, do not hesitate to reopen this ticket.

Cheers,
