### ISSUE TITLE
[v2.4] Axle size number frame size

### ISSUE THREAD

**Issue by adaneslavo** [trevorsandy/lpub3d#579]
When I change font of either round or square:
![obraz](https://user-images.githubusercontent.com/33016300/147631734-0d7c3378-c8ca-44db-970c-fdcb9e70e9aa.png)
then the number is misaligned. I cannot align it, so I tried to change circle/square size, but it's impossible too. Maybe I'm missing something?
![obraz](https://user-images.githubusercontent.com/33016300/147631848-a9a7d3a0-8ae7-4aaf-8601-b58c563509cf.png)
![obraz](https://user-images.githubusercontent.com/33016300/147708777-d29d538c-0d4c-4f7d-8afd-d35fc549a4ec.png)
![obraz](https://user-images.githubusercontent.com/33016300/147631870-ae861f68-738a-4ab2-b75c-3fba67c586f2.png)
![obraz](https://user-images.githubusercontent.com/33016300/147631892-14bea741-c26c-49f0-9dc1-7fa5be9312ac.png)

Also, unckecking the field below in BoM is impossible, because it rechecks again. What does it do?
![obraz](https://user-images.githubusercontent.com/33016300/147632037-1fff8107-0908-4264-a816-1c7e5c4d287f.png)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

This behaviour has been corrected.

Cheers,
