### ISSUE TITLE
[v2.4] Part annotations on page impossible to enter

### ISSUE THREAD

**Issue by adaneslavo** [trevorsandy/lpub3d#580]
When I choose part annotation option:
![obraz](https://user-images.githubusercontent.com/33016300/147701512-d85e87e5-ab5d-4c3d-8e48-9ebf577fd6fe.png)
and click on the option:
![obraz](https://user-images.githubusercontent.com/33016300/147701553-87337b43-d31f-4658-8b25-26cfe7d947de.png)
then series of errors come out:
![obraz](https://user-images.githubusercontent.com/33016300/147701576-a6b67b77-09c8-41c4-b93d-df320a21d892.png)
![obraz](https://user-images.githubusercontent.com/33016300/147701588-0c19695a-1576-46fb-9352-d409cab0e831.png)
![obraz](https://user-images.githubusercontent.com/33016300/147701695-704dd634-9ca5-42b0-b260-0fc23e0ec517.png)
and nothing happens. Strange, because PLI and BoM have correct annotations.
[LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/7790534/LPub3DLog.txt)

What's more, page is blocked, which means I cannot change page until restart of LPub.

What's even stranger, this worked:
![obraz](https://user-images.githubusercontent.com/33016300/147701953-2c1ac545-51c3-4fa1-b9d4-8bfe78407eba.png)
so I copied the command line all over the project and changed the part number. Even though sometimes it didn't show up.
![obraz](https://user-images.githubusercontent.com/33016300/147708085-f0eab821-ab7c-48dd-83f0-529b9d2ebe88.png)

Callouts have option to click:
![obraz](https://user-images.githubusercontent.com/33016300/147702143-fa6628a7-d522-4299-a73d-df94a8074477.png)
but it does nothing.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

This behaviour has been corrected.

Cheers,
