### ISSUE TITLE
[v2.4] Assembled image is not showing copies

### ISSUE THREAD

**Issue by adaneslavo** [trevorsandy/lpub3d#581]
My assembled image should show "x2" in the corner but it doesn't and it cannot be enabled:
![obraz](https://user-images.githubusercontent.com/33016300/147709672-930fb56f-3f75-45ae-a231-e216cc6def0a.png)
![obraz](https://user-images.githubusercontent.com/33016300/147709711-89425dbf-0c07-4904-b48b-b1adde1d0a73.png)
![obraz](https://user-images.githubusercontent.com/33016300/147709732-9869170b-299d-4b2f-8072-3a1038f446ef.png)
![obraz](https://user-images.githubusercontent.com/33016300/147709741-ff5c5fa2-86d2-4716-aca8-e5b05252eb23.png)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

Unfortunately, I am unable to reproduce this behaviour. 

If you continue to experience this behaviour on the latest release of LPub3D, do not hesitate to reopen this ticket.

Cheers,
