### ISSUE TITLE
Provide build guide/requirements to build latest git version

### ISSUE THREAD

**Issue by nathaneltitane** [trevorsandy/lpub3d#585]
### Subject
Cannot seem to find any mention of build requirements to build git source code: installed an old version (Ubuntu 20.10 package, on a 21.10 install that keeps crashing when preferences are changed or when instruction pass a certain amount of pages...)

Would like to build my own before posting bugs.

Thanks

**Comment by barthel** [comment]
Take a look on: https://github.com/trevorsandy/lpub3d/blob/master/builds/utilities/README.md
For DEB package building in: https://github.com/trevorsandy/lpub3d/blob/master/builds/linux/CreateDeb.sh

I haven't tried to build my own yet, but maybe this information will take you a step further.
