### ISSUE TITLE
Lpub3D segfault (no trace) on model file build configuration

### ISSUE THREAD

**Issue by nathaneltitane** [trevorsandy/lpub3d#586]
### Subject
I have been attempting to generate a build instruction configuration on a model file and it has proven impossible due to recurent crashes due to segmentation faults being generated by any attempt at modyfing the default setup and or adding/changing element placement.

### Environment
* Version of LPub3D - see Help->About LPub3D
![Screenshot_20220425_225112](https://user-images.githubusercontent.com/5674757/165210249-7ec2d906-168b-4bd1-ae7e-d4d6740d0228.png)

* Operating system - (K)Ubuntu 21.10 x64

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  - Linux:  `/usr/share/lpub3d`
* Application data path
  - Linux: `~/.local/share/LPub3D Software/LPub3D/`
* Registry Extract
  - Linux: `~/.config/LPub3D Software/LPub3D.conf`
* Renderer configuration files

### Logs
* Application Log: `[Application data path]/logs/LPub3DLog.txt`
[LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/8559466/LPub3DLog.txt)
[LPub3DLog.1.txt](https://github.com/trevorsandy/lpub3d/files/8559467/LPub3DLog.1.txt)

### Screenshots
* Configuration->Preferences->General
* Configuration->Preferences->Rendering
* Configuration->Preferences->Publishing
* Configuration->Preferences->Logging
* Configuration->Preferences->Other

### Steps to reproduce
Tell me how to reproduce this issue.
Provide a sample mpd/ldr file that reproduces the problem.

### Expected behaviour
Tell me what should happen

### Actual behaviour
Tell me what happens instead

### Workaround
Share your work around if available

### Solution suggestion
Share your opinion on how to achieve the expected behaviour

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

I have treated the quantifiable instability items in v2.4.5. Please take a look at that release and let me know if you continue to experience any carryover items from v2.4.4.

For the very latest updates, you can also take a look at the [DevOps build](https://github.com/trevorsandy/lpub3d-ci/releases/tag/continuous) which include the latest reported issues as you can see in the commit and issue trackers. Here is the latest [DevOps build action](https://github.com/trevorsandy/lpub3d-ci/actions/runs/3553111194).

Cheers,
