### ISSUE TITLE
Invalid appstream file

### ISSUE THREAD

**Issue by hfiguiere** [trevorsandy/lpub3d#589]
### Subject
The current appdata file at `mainApp/lpub3d.appdata.xml` is invalid because it is a "collection" appstream, not an appdata.

This was introduced by commit 560b15424ec186501faef7d31eb8c389a2c724a7

### Expected behaviour

The appdata should validate.

### Actual behaviour

When the flatpak updated to the currently missing 2.4.4 tag, I get
```
Error: no <component> node
repo/files/share/appdata/io.github.trevorsandy.LPub3D.appdata.xml: failed to parse repo/files/share/appdata/io.github.trevorsandy.LPub3D.appdata.xml: no <component> node
```

### Solution suggestion

If you have more than one component, you should have one appdata file per component, ideally named after the `id`.

**Comment by trevorsandy** [comment]
This behaviour has been corrected and will be available in release v2.4.5.

You can take an advanced look by pointing the build to the DevOps repository `trevorsandy/lpub3d-ci`.

Let me know if your checks continue to produce unexpected behaviour. 

Cheers,
