### ISSUE TITLE
BUILD_MOD in Multipart model not working as expected

### ISSUE THREAD

**Issue by aefferenpriv** [trevorsandy/lpub3d#591]
### Subject
For modeling I use MLcad, so I will use terms related to MLcad (version 3.51)
I have several nested models where I apply the new BUILD_MOD. However it totally messes up the instruction regarding applying the behavior from BUILD_MOD and order of steps and when you go pages back and forth the visual results in LPub3D differs per iteration. I use LPub3D version 2.4.4 revision 0 build 2671.

Not to share my original building instruction I recreated the behavior in a different model. I have read all I could find about BUILD_MOD but could not find the issue causing this behavior.
I have several nested models and in the main model I apply the Remove statements. In the attachment the details. I am not an expert in software development on this level. What I expect is that some caching issues are at play and maybe some global or local variables which are not set to zero at certain places in the sequences or iterations. In the attachment:

-  LPub3D.issue_2022061201_10.pptx: the actual behavior and expected behavior in last slide.
- Build-MOD_case.mpd.txt: the actual LPub3D file.

Environment
Version of LPub3D - 2.4.4 revision 0 build 2671 SHA oba24afe3
Operating system - Windows 10, 64
Configuration
LPub3D installation path

Windows: C:\Program Files (x86)\LDraw\LPub3D
Application data path

Windows: %USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\
Registry Extract

Windows (installed): reg export "HKEY_CURRENT_USER\Software\LPub3D Software" %USERPROFILE%\Desktop\LPub3D_Hive.reg - not found
Renderer configuration files

[Application data path]/ldv/ldvExport.ini
[Application data path]/3rdParty/ldglite-1.3/config/ldglite.ini
[Application data path]/3rdParty/ldview-4.4/config/ldview.ini
[Application data path]/3rdParty/ldview-4.4/config/ldviewPOV.ini
[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.conf
[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.ini
Steps to reproduce
open LPub3D
open a 'project'
on first page change the scale via the on screen right mouse click menu.
confirm changed scale
now hover over the LPub3D icon in menu bar,
hover over the thumbnail
now the menu screens appear again.

Expected behavior in the PPTx-file in last slide attached.
[LPub3D issue_2022061201_10.pptx](https://github.com/trevorsandy/lpub3d/files/8885618/LPub3D.issue_2022061201_10.pptx)
[Build-MOD_case.mpd.txt](https://github.com/trevorsandy/lpub3d/files/8885623/Build-MOD_case.mpd.txt)

**Comment by trevorsandy** [comment]
This behaviour has been corrected and will be available in release v2.4.5.

You can take an advanced look with the latest [DevOps build](https://github.com/trevorsandy/lpub3d-ci/releases/tag/continuous).

Let me know if your checks continue to produce unexpected behaviour. 

Cheers,

**Comment by trevorsandy** [comment]
I'm added the enhancement to treat submodels in build modifications. Consequently, the model file you provided is now processed as you expected. Here are the processed images for the entire model file:

Step 1
![mainmodel_2_submodel-05_2_submodel-02_2_submodel-01-0_1_0_0_0_1_0_0_0_1_1_1240_150_DPI_1_30_23_45](https://user-images.githubusercontent.com/13388970/204079986-64761170-3e88-4922-814f-0b946f3d1fa1.png)

Step 2
![mainmodel_2_submodel-05_2_submodel-02_3_submodel-03-0_1_0_0_0_1_0_0_0_1_1_1240_150_DPI_1_30_23_45](https://user-images.githubusercontent.com/13388970/204080000-bc59da22-2a7e-4807-83d9-a964ad2a8b85.png)

Step 3
![mainmodel_2_submodel-05_2_submodel-02-0_1_0_0_0_1_0_0_0_1_1_1240_150_DPI_1_30_23_45](https://user-images.githubusercontent.com/13388970/204080008-07be2b72-942b-4e86-afbe-930a8e264857.png)

Step 4
![mainmodel_2_submodel-05_2_submodel-02-0_1_0_0_0_1_0_0_0_1_2_1240_150_DPI_1_30_23_45](https://user-images.githubusercontent.com/13388970/204080016-b2054991-1171-4316-b474-c6621e4aff18.png)

Step 5
![mainmodel_2_submodel-05_2_submodel-02-0_1_0_0_0_1_0_0_0_1_3_1240_150_DPI_1_30_23_45](https://user-images.githubusercontent.com/13388970/204080027-d63a1454-37a0-4019-961f-320a8ef3d224.png)
 
Step 6
![mainmodel_2_submodel-05_3_submodel-04-0_1_0_0_0_1_0_0_0_1_1_1240_150_DPI_1_30_23_45](https://user-images.githubusercontent.com/13388970/204080041-ef9926e6-9a98-439d-9846-4666b198f91f.png)

Step 7
![mainmodel_2_submodel-05-0_1_0_0_0_1_0_0_0_1_1_1240_150_DPI_1_30_23_45](https://user-images.githubusercontent.com/13388970/204080045-b8b0fe09-1f66-442d-bc47-0c69c95f7cf9.png)

Step 8
![mainmodel_2_submodel-05-0_1_0_0_0_1_0_0_0_1_2_1240_150_DPI_1_30_23_45](https://user-images.githubusercontent.com/13388970/204080080-6041c2b4-b04a-47de-a880-367feb80a2fd.png)

Step 9
![mainmodel_2_submodel-05-0_1_0_0_0_1_0_0_0_1_3_1240_150_DPI_1_30_23_45](https://user-images.githubusercontent.com/13388970/204080100-68325171-d6f2-473c-b940-64ddee7e7ede.png)

Step 10
![mainmodel-0_1_0_0_0_1_0_0_0_1_1_1240_150_DPI_1_30_23_45](https://user-images.githubusercontent.com/13388970/204080107-fddb59d1-9050-4ebf-8c6d-37d42b2b8a18.png)

Step 11
![mainmodel-0_1_0_0_0_1_0_0_0_1_2_1240_150_DPI_1_30_23_45](https://user-images.githubusercontent.com/13388970/204080112-dd2711b3-fea7-484f-9eac-ea87522e2005.png)

Step 12
![mainmodel-0_1_0_0_0_1_0_0_0_1_3_1240_150_DPI_1_30_23_45](https://user-images.githubusercontent.com/13388970/204080117-a8ccd18e-f734-409b-97a0-1e40e0f884e1.png)

Step 13
![mainmodel-0_1_0_0_0_1_0_0_0_1_4_1240_150_DPI_1_30_23_45](https://user-images.githubusercontent.com/13388970/204080119-3ccdafcd-dd96-4ab9-a97c-58c0ff921ec1.png)

Step 14
![mainmodel-0_1_0_0_0_1_0_0_0_1_5_1240_150_DPI_1_30_23_45](https://user-images.githubusercontent.com/13388970/204080127-2a2818a7-9c6f-4ab6-a67a-b8d405ee3064.png)

Step 15
![mainmodel-0_1_0_0_0_1_0_0_0_1_6_1240_150_DPI_1_30_23_45](https://user-images.githubusercontent.com/13388970/204080133-b6ab4a3b-95fb-4e7f-aede-373e5edd6770.png)

Cheers,
