### ISSUE TITLE
Not all pages are displayed in the dropdown menu

### ISSUE THREAD

**Issue by technicbasics** [trevorsandy/lpub3d#592]
### Subject
If you are in a building instruction, only some of the following pages of the current page are displayed in the page dropdown menu.

### Environment
* Version of LPub3D - 2.4.3 + 2.4.4 all versions
* Operating system - Win11 64bit

![Lpub3D Seitendropdown](https://user-images.githubusercontent.com/49073781/173234180-e7b01d3c-6c02-4a9e-a42e-4d6fbd47caf3.png)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

This behaviour has been corrected.

Cheers,
