### ISSUE TITLE
LPub3D renders very slow on Windows

### ISSUE THREAD

**Issue by billward** [trevorsandy/lpub3d#60]
### Subject of the issue
It takes several minutes just to render a single page. It's much faster on Mac. I suspect there's some kind of Windows security feature that is interfering with invoking the rendering subprocess?

### Your environment
* Version of LPub3D - LPub3D-2.2.2.0.848_20180412.exe
* Operating system - Windows 10 Pro v1709 build 16299.547 (x86,x86_64)

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  - Windows: `D:\LDraw\LPub3D` [x86_64]
* Application data path
  - Windows: C:\Users\wward.ORADEV\AppData\Local\LPub3D Software\LPub3D
* Registry Extract
  - (https://github.com/trevorsandy/lpub3d/files/2255307/LPub3D_Hive.reg.txt)
* Renderer configuration files
  - (https://github.com/trevorsandy/lpub3d/files/2255322/3rdParty.zip)

### Logs
* Application Log: 
   - (https://github.com/trevorsandy/lpub3d/files/2255315/LPub3DLog.txt)
   - stderr-ldview and stdout-ldview are empty files

### Screenshots
* (https://user-images.githubusercontent.com/341092/43669954-f8b08a6e-973b-11e8-93fc-8bb54d46f02e.PNG)
* (https://user-images.githubusercontent.com/341092/43669962-04544504-973c-11e8-9abf-9e7ebe9bafb2.PNG)
* (https://user-images.githubusercontent.com/341092/43669968-0f157792-973c-11e8-8935-64becab9e730.PNG)
* (https://user-images.githubusercontent.com/341092/43669972-1783f8e0-973c-11e8-9f37-3671c92ab4d0.PNG)
* (https://user-images.githubusercontent.com/341092/43669973-1f223ecc-973c-11e8-8781-48b26827a56e.PNG)

### Steps to reproduce
Any file takes a long time to render. App goes into (Not responding) state for several minutes even for the simplest page.

### Expected behaviour
It should be quick, like on the Mac version.

### Actual behaviour
Render takes several minutes.

### Workaround
Get a cup of tea and wait.

### Solution suggestion
My hope would be that it's something in settings (either in the program or in Windows) that can be changed to make it work better. Perhaps the program can monitor how long it takes to render a page and pop up a dialog to suggest such a change, if one is found.

**Comment by trevorsandy** [comment]
I've seen a few reports on this behaviour. The problem seems to be isolated to the LDView renderer after I upgraded the command line call to use the `-SaveSnapshotsList=<List Filename>` flag. 

I'm just about to release v2.3.0 which has several renderer integration enhancements - including a new 'Native' renderer based on LeoCAD source for 2D images and LDView source for POV-file generation. However, I've not done anything specifically to speed up 3rdParty LDView rendering. 

If the slow LDView rendering persists in v2.3.0 I'll take a look at reverting the LDView command line back to  `-SaveSnapshots=1` and check if performance improves.

**Comment by trevorsandy** [comment]
Yes, I agree. with 2.3.1 my instance (commit 8bd2b66) of LDView render duration seems longer than previous instances. I believe the source of this behaviour is LDView. As time permits, I'll have to setup profiling to see when/where the slowdown was introduced so I'm going to reopen this ticket.

Cheers,

**Comment by jacovandermolen** [comment]
I find 2.3.1 rendering again a lot faster now than 2.3 with LDView.
