### ISSUE TITLE
Extremely unstable application: regularly segfaults

### ISSUE THREAD

**Issue by zoqaeski** [trevorsandy/lpub3d#600]
### Subject
The application regularly crashes with a segmentation fault when doing just about anything. Usually the crash occurs when going to the next step or page.

### Environment
* Version of LPub3D - 2.4.4 Revision 7 Build 2678 SHA 67df33a36
* Operating system - Arch Linux, x86_64, GNOME on Wayland

### Configuration
* LPub3D installation path
  - Linux:  `/usr/share/lpub3d`
* Application data path
  - Linux: `~/.local/share/LPub3D Software/LPub3D/`
%USERPROFILE%\Desktop\LPub3D_Hive.reg`
  - Linux: `~/.config/LPub3D Software/LPub3D.conf`
* Renderer configuration files
  - `[Application data path]/ldv/ldvExport.ini`
  - `[Application data path]/3rdParty/ldglite-1.3/config/ldglite.ini`
  - `[Application data path]/3rdParty/ldview-4.4/config/ldview.ini`
  - `[Application data path]/3rdParty/ldview-4.4/config/ldviewPOV.ini`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.conf`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.ini`

### Logs
* Application Log: `[Application data path]/logs/LPub3DLog.txt`
* Renderer Log: `[LDraw model path]/stdout-ldglite`
* Renderer Log: `[LDraw model path]/stdout-povray`
* Renderer Log: `[LDraw model path]/stderr-ldglite`
* Renderer Log: `[LDraw model path]/stderr-povray`

### Screenshots
* Help->About ![Version information](https://user-images.githubusercontent.com/172912/184063172-4348cbdb-44fb-4d30-a955-c80c80c22fff.png)
* Configuration->Preferences->General 
![General Preferences](https://user-images.githubusercontent.com/172912/184063298-38828767-5fd6-46a5-b4d8-c7dea3452526.png)
* Configuration->Preferences->Rendering 
![Rendering Preferences](https://user-images.githubusercontent.com/172912/184063399-9bae3e21-0a6e-4065-aeb5-d83411096841.png)
* Configuration->Preferences->Publishing 
![Publishing preferences](https://user-images.githubusercontent.com/172912/184063420-8aea2bb1-c8d9-4cfd-93da-e593b44a6c44.png)
* Configuration->Preferences->Logging 
![Logging preferences](https://user-images.githubusercontent.com/172912/184063443-d58b13db-6f26-4e16-bbfb-b4b3112c8c7a.png)
* Configuration->Preferences->Other 
![Other preferences](https://user-images.githubusercontent.com/172912/184063470-9da6f952-a512-494f-a991-8c862117ff57.png)

### Steps to reproduce
Open an LDraw file with the application that has many steps, particularly one with lots of rotation steps or multi-steps. Skip forwards a few steps. The program usually crashes with a segmentation fault. I can generate a crash dump from GDB if that would be helpful?

The original model was created with LeoCAD rather than the built-in Visual Editor.

### Expected behaviour
The application should not crash.

### Actual behaviour
It crashes. 

### Workaround
I'm yet to find one. I've tried recompiling it in an attempt to rule out version mismatches between shared libraries, but that doesn't help.

**Comment by zoqaeski** [comment]
Here's a stack trace from a crash. I rebuilt LPub3D with debug symbols and GDB fetched the symbols for every dependency.

[lpub3d24_trace_20220811T1636.log](https://github.com/trevorsandy/lpub3d/files/9306727/lpub3d24_trace_20220811T1636.log)

That trace came from opening my current project and going to the next page two or three times.

Running `lpub3d24 --help` also segfaults. Here's another stack trace: 
[lpub3d_trace_no_file.log](https://github.com/trevorsandy/lpub3d/files/9306786/lpub3d_trace_no_file.log)

It prints out the options and then crashes immediately when run from a terminal.

**Comment by nathaneltitane** [comment]
I second this @trevorsandy I am using lpub3d almost daily and find it very frustrating to be doing very common setting changes and model instruction editing and just have the application close and crash without warning!

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

Indeed, 2.4.4 was quite unstable. It was the COVID release :-).

Anyway, take a look at the latest release v2.4.5 and let me know if you are still having the same experience.

Cheers,

**Comment by nathaneltitane** [comment]
> Thank you for reporting this behaviour.
> 
> Indeed, 2.4.4 was quite unstable. It was the COVID release :-).
> 
> I don't have a local instance of Arch Linux installed ATM but running the --help command from my IDE returns 0.
> 
> For the abend during model file processing it would be quite helpful to receive the LPub3D runtime and model processing logs and, if possible, an example model file that can reproduce the unexpected behaviour.
> 
> Anyway, take a look at the latest release [LPub3D 24.11.2022 v2.4.5](https://github.com/trevorsandy/lpub3d/releases/tag/v2.4.5) and let me know if you are still having the same experience.
> 
> You can also take a look at the latest [DevOps build](https://github.com/trevorsandy/lpub3d-ci/releases/tag/continuous) which include the latest reported issues as you can see in the commit and issue trackers. Here is the latest [DevOps build action](https://github.com/trevorsandy/lpub3d-ci/actions/runs/3553111194).
> 
> Cheers,

You're building agaist the last LTS version for ubuntu builds. could you upgrade your build spec to use 22.04?

**Comment by trevorsandy** [comment]
Thank you for your request.

The (OBS Ubuntu build)[https://software.opensuse.org/download.html?project=home:trevorsandy&package=lpub3d] is 22.04.

The Ubuntu GitHub build uses Bionic (18.04) by design to enable users on older platforms to run the application.

Cheers,

**Comment by trevorsandy** [comment]
> Running lpub3d24 --help also segfaults. Here's another stack trace:

Coming back to this ticket to report I have reproduced and corrected the segfault after running --version or --help in console mode - see #668.

Cheers,
