### ISSUE TITLE
Projection in visual editor keeps resetting to perspective.

### ISSUE THREAD

**Issue by laurensvalk** [trevorsandy/lpub3d#607]
### Subject

The projection in visual editor keeps resetting to perspective when I go to the next page:

[orthographic.webm](https://user-images.githubusercontent.com/12326241/193535072-89a86b87-41cb-4e8c-b619-98eae1ca1cf7.webm)

This happens *only* if I set the viewpoint to "front":

![image](https://user-images.githubusercontent.com/12326241/193535312-18e0efbb-83bb-4a1a-8352-10482d6f8ca6.png)

When set to "default", the visual editor looks OK.

I don't know if I should be selecting "front" here in the first place, but if I don't do that the rendered image is not orthographic (separate issue?).

### Environment
I am running the `LPub3D-2.4.4.0.2671_20220531-x86_64.AppImage` on Ubuntu 22.04 without any changes.
```
0 New Model
0 Name: pupdevice-color.ldr
0 Author: MLCad
0 Unofficial Model
0 ROTATION CENTER 0 0 0 1 "Custom"
0 ROTATION CONFIG 0 0
1 15 0 0 0 -1 0 0 0 -1 0 0 0 1 37308c01.dat
0 ROTSTEP 35 -35 0 ABS
0
```

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

For each step, a new 3D viewer render and display instance is created and the newly created instance was not reading the preference setting you created.
This behaviour has been corrected. 



> I don't know if I should be selecting "front" here in the first place, but if I don't do that the rendered image is not orthographic (separate issue?).

Indeed, you should not be selecting a viewpoint setting when you intend to use a projection setting. The appropriate behaviour has been corrected in #608.
