### ISSUE TITLE
How to avoid cropping

### ISSUE THREAD

**Issue by laurensvalk** [trevorsandy/lpub3d#609]
### Question
Is there a setting to avoid cropping of images that are too large?

I tried setting all margins to zero but that did not seem to help.

Thanks!

![image](https://user-images.githubusercontent.com/12326241/193540660-4577ccc7-aa86-475b-b33a-4ba1830f8132.png)

**Comment by trevorsandy** [comment]
Thank you for your inquiry. 

Take a look at #412 and perhaps also #274.

Cheers,
