### ISSUE TITLE
canceling continuous next page does not work

### ISSUE THREAD

**Issue by nathaneltitane** [trevorsandy/lpub3d#615]
### Subject
running a continuous next page refresh on large documents and then cancelling it does not function - LPub3D continues parsing and refreshing.

### Environment
* Version of LPub3D - 2.44 OBS ubuntu 22.04
* Operating system - ubuntu 22.04 AMD64

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

It is best to use the shortcut key Ctrl+Shift+N when cancelling continuous page processing.

I've updated the continuous page processing behaviour to better signal the author when a request to cancel is detected.

Cheers,
