### ISSUE TITLE
configuration preferences dialog cutoff/min window size

### ISSUE THREAD

**Issue by nathaneltitane** [trevorsandy/lpub3d#616]
### Subject
the configuration preferences window size is too small and cuts off, restricts visibility of certain settings.
This issue may also be relevant for all other preference windows.

see attached.

![2022-10-25_16-51](https://user-images.githubusercontent.com/5674757/197880253-f151f5f1-e15d-485a-a595-3d94eaf134de.png)

min window size should be adjuste for content to show as follows:

![2022-10-25_16-53](https://user-images.githubusercontent.com/5674757/197880266-62c2403c-54a1-4a5b-959c-8dee0f270362.png)

### Environment
* Version of LPub3D - 2.44 OBS ubuntu 22.04 AMD64
* Operating system - Ubuntu 22.04 amd64

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

I've set the preferences form width and height dimensions based those indicated by the Qt Designer editor. 

Certainly it looks like those values do not universally adjust the preferences form sufficiently. 

I'll take another look.

Cheers,

**Comment by trevorsandy** [comment]
I've added an update that uses a better approach to calculate the minimum size hint.

This update should correct the reported behaviour.

Cheers,
