### ISSUE TITLE
Give Lpub3D a version agnostic binary name

### ISSUE THREAD

**Issue by nathaneltitane** [trevorsandy/lpub3d#617]
### Subject
'lpub3d24' is not version agnostic (it seems) and would cause breakage on scripts depending on the program/binary.

'lpub3d' would be better suited to ensure that dependencies are met with dependant programs and scripts.

### Environment
* Version of LPub3D -ALL
* Operating system - ALL

**Comment by trevorsandy** [comment]
Thank you for your request.

The LPub3D binary is named as I intended.

Configuration scripts under my maintenance are updated automatically at build time. I am not aware of any broken scripts.

Cheers,
