### ISSUE TITLE
Immediate crash

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#619]
### Subject
LPub crashes while starting

### Environment
LPub3D_x86_64-2.4.4.299.2970_20221121
Windows 10

### Configuration
* LPub3D installation path
C:\MJ\LEGO Related\LPub3D_x86_64-2.4.4.299.2970_20221121\LPub3D_x86_64

![image](https://user-images.githubusercontent.com/32261647/203049422-9bfd003f-4a07-49a2-9b09-71891ce5cb8b.png)
[LPub3D.dmp.txt](https://github.com/trevorsandy/lpub3d/files/10056309/LPub3D.dmp.txt)
[LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/10056315/LPub3DLog.txt)

**Comment by technicbasics** [comment]
Same problem here.
Both x86 and x86_64

Windows 11

[LPub3D.dmp.txt](https://github.com/trevorsandy/lpub3d/files/10060252/LPub3D.dmp.txt)
[LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/10060258/LPub3DLog.txt)

**Comment by trevorsandy** [comment]
Hi Jaco and Johann,

Thank you for reporting this behaviour and providing the dump. 

It looks like there is a problem with the LDView renderer library (specifically the components integrated into LPub3D that is used to present the LDView preferences and POV file generation settings). 

The  r299 build was meant to be a dry-run in the production environment but I did not expect this anomaly - so thanks again. 

Anyway, I'm taking a look right now.

Cheers,

**Comment by jacovandermolen** [comment]
OK.
What would be the most current and stable version ATM?
I use 2.4.2.125.2557_20210514 most and sometimes 2.4.3.138.2925_20220703
Both are stable enough for me to work with.

Can we pick up debugging the buildmod feature again?

**Comment by trevorsandy** [comment]
> What would be the most current and stable version ATM?

2.4.2 series are probably best until the next release.

The 2.4.4 r299 build is quite stable (it's actually the 2.4.5 release candidate) - aside from the reported abend. This abend is a bit surprising and mysterious because it is indeed in the GitHub Windows release builds but I'm so far unable to reproduce it locally (still working on it).

> Can we pick up debugging the buildmod feature again?

Yes. I've used the file you supplied some time ago extensively in dev testing and, for me, there were no outstanding parse issues. Along the way, I've also completed the ability to use/nest submodels in the build modifications (versus only parts). This update will more-or-less enable the ability to automate your model. The following model file demonstrates the added cabability - thanks to Allard van Efferen for providing it:


```
0 FILE mainmodel.ldr
0 Mainmodel
0 Name: Mainmodel.mpd
0 Author: Allard van Efferen (Rabbitdesign)
0 !LDRAW_ORG Unofficial Model
0 !LPUB BUILD_MOD_ENABLED GLOBAL TRUE
0 ROTATION CENTER 0 0 0 1 "Custom"
0 ROTATION CONFIG 0 0
1 15 0 0 0 1 0 0 0 1 0 0 0 1 64782.dat
0 STEP
0 !LPUB BUILD_MOD BEGIN "gate"
1 15 0 -200 -80 1 0 0 0 1 0 0 0 1 submodel-05.ldr
0 !LPUB BUILD_MOD END_MOD
1 15 0 -200 -40 1 0 0 0 1 0 0 0 1 submodel-05.ldr
0 !LPUB BUILD_MOD END
0 STEP
0 !LPUB BUILD_MOD REMOVE "leg"
0 !LPUB BUILD_MOD REMOVE "fence"
1 15 100 -160 -40 0 0 1 0 -1 0 1 0 0 32013.dat
1 15 -100 -160 -40 0 0 -1 0 -1 0 -1 0 0 32013.dat
0 STEP
0 !LPUB BUILD_MOD REMOVE "bridge"
1 2 100 -140 -40 0 0 1 0 -1 0 1 0 0 32013.dat
1 2 -100 -140 -40 0 0 -1 0 -1 0 -1 0 0 32013.dat
0 STEP
0 !LPUB BUILD_MOD REMOVE "lid"
1 13 100 -120 -40 0 0 1 0 -1 0 1 0 0 32013.dat
1 13 -100 -120 -40 0 0 -1 0 -1 0 -1 0 0 32013.dat
0 STEP
0 !LPUB BUILD_MOD REMOVE "gate"
1 72 100 -100 -40 0 0 1 0 -1 0 1 0 0 32013.dat
1 72 -100 -100 -40 0 0 -1 0 -1 0 -1 0 0 32013.dat
0 NOFILE
0
0 FILE submodel-01.ldr
0 submodel-01
0 Name: submodel-01.ldr
0 Author: Allard van Efferen (Rabbitdesign)
0 !LDRAW_ORG Unofficial Model
0 ROTATION CENTER 0 0 0 1 "Custom"
0 ROTATION CONFIG 0 0
1 0 -40 0 0 1 0 0 0 0 1 0 -1 0 32034.dat
1 0 40 0 0 1 0 0 0 0 1 0 -1 0 32034.dat
1 0 -40 -40 0 0 -1 0 1 0 0 0 0 1 22961.dat
1 0 40 -40 0 0 -1 0 1 0 0 0 0 1 22961.dat
1 0 -40 50 0 1 0 0 0 0 -1 0 1 0 59443.dat
1 0 40 50 0 1 0 0 0 0 -1 0 1 0 59443.dat
1 0 0 0 0 0 0 -1 0 1 0 1 0 0 18948.dat
0 NOFILE
0
0 FILE submodel-02.ldr
0 submodel-02
0 Name: submodel-02.ldr
0 Author: Allard van Efferen (Rabbitdesign)
0 !LDRAW_ORG Unofficial Model
0 ROTATION CENTER 0 0 0 1 "Custom"
0 ROTATION CONFIG 0 0
1 4 10 -10 -20 0 -1 0 -1 0 0 0 0 -1 60484.dat
1 4 50 -10 -20 0 -1 0 -1 0 0 0 0 -1 60484.dat
1 4 30 -10 0 0 -1 0 1 0 0 0 0 1 32524.dat
1 4 -10 -10 0 0 -1 0 1 0 0 0 0 1 32524.dat
1 4 -30 -10 0 0 -1 0 1 0 0 0 0 1 32524.dat
1 4 70 -10 0 0 -1 0 1 0 0 0 0 1 32524.dat
1 4 90 -10 0 0 -1 0 1 0 0 0 0 1 32524.dat
1 4 10 -10 40 0 -1 0 1 0 0 0 0 1 32316.dat
1 4 50 -10 40 0 -1 0 1 0 0 0 0 1 32316.dat
0 STEP
0 !LPUB BUILD_MOD BEGIN "leg"
1 4 30 50 -60 1 0 0 0 1 0 0 0 1 submodel-01.ldr
0 !LPUB BUILD_MOD END_MOD
1 4 30 10 -20 1 0 0 0 0 -1 0 1 0 submodel-01.ldr
0 !LPUB BUILD_MOD END
0 STEP
0 !LPUB BUILD_MOD BEGIN "fence"
1 4 30 -70 -60 1 0 0 0 1 0 0 0 1 submodel-03.ldr
0 !LPUB BUILD_MOD END_MOD
1 4 30 -30 -20 1 0 0 0 0 1 0 -1 0 submodel-03.ldr
0 !LPUB BUILD_MOD END
0 NOFILE
0
0 FILE submodel-03.ldr
0 submodel-03
0 Name: submodel-03.ldr
0 Author: Allard van Efferen (Rabbitdesign)
0 !LDRAW_ORG Unofficial Model
0 ROTATION CENTER 0 0 0 1 "Custom"
0 ROTATION CONFIG 0 0
1 14 -15 -10 0 0 1 0 0 0 1 1 0 0 32449.dat
1 14 -25 -10 0 0 1 0 0 0 1 1 0 0 32449.dat
1 14 15 -10 0 0 1 0 0 0 1 1 0 0 32449.dat
1 14 25 -10 0 0 1 0 0 0 1 1 0 0 32449.dat
1 14 0 0 0 0 -1 0 0 0 1 -1 0 0 32316.dat
1 14 40 0 0 0 -1 0 0 0 1 -1 0 0 32316.dat
1 14 -40 0 0 0 -1 0 0 0 1 -1 0 0 32316.dat
0 NOFILE
0
0 FILE submodel-04.ldr
0 submodel-04
0 Name: submodel-04.ldr
0 Author: Allard van Efferen (Rabbitdesign)
0 !LDRAW_ORG Unofficial Model
0 ROTATION CENTER 0 0 0 1 "Custom"
0 ROTATION CONFIG 0 0
1 1 0 0 0 0 1 0 0 0 1 1 0 0 40490.dat
1 1 20 0 0 0 1 0 0 0 1 1 0 0 40490.dat
1 1 40 0 0 0 1 0 0 0 1 1 0 0 40490.dat
1 1 60 0 0 0 1 0 0 0 1 1 0 0 40490.dat
1 1 -20 0 0 0 1 0 0 0 1 1 0 0 40490.dat
1 1 -40 0 0 0 1 0 0 0 1 1 0 0 40490.dat
1 1 -60 0 0 0 1 0 0 0 1 1 0 0 40490.dat
1 1 80 40 0 0 1 0 0 0 1 1 0 0 32316.dat
1 1 80 -60 0 0 1 0 0 0 1 1 0 0 32316.dat
1 1 -80 -60 0 0 1 0 0 0 1 1 0 0 32316.dat
1 1 -80 40 0 0 1 0 0 0 1 1 0 0 32316.dat
0 NOFILE
0
0 FILE submodel-05.ldr
0 submodel-05
0 Name: submodel-05.ldr
0 Author: Allard van Efferen (Rabbitdesign)
0 !LDRAW_ORG Unofficial Model
0 ROTATION CENTER 0 0 0 1 "Custom"
0 ROTATION CONFIG 0 0
1 0 0 -20 0 1 0 0 0 1 0 0 0 1 71709.dat
1 0 80 -20 -20 0 -1 0 1 0 0 0 0 1 32140.dat
1 0 -80 -20 -20 0 -1 0 1 0 0 0 0 1 32140.dat
1 0 100 -20 0 0 1 0 -1 0 0 0 0 1 32316.dat
1 0 -100 -20 0 0 1 0 -1 0 0 0 0 1 32316.dat
1 0 60 80 40 0 1 0 0 0 1 1 0 0 32525.dat
1 0 -60 80 40 0 1 0 0 0 1 1 0 0 32525.dat
1 0 -45 180 40 0 -1 0 -1 0 0 0 0 -1 32056.dat
1 0 -35 180 40 0 -1 0 -1 0 0 0 0 -1 32056.dat
1 0 45 180 40 0 -1 0 -1 0 0 0 0 -1 32056.dat
1 0 35 180 40 0 -1 0 -1 0 0 0 0 -1 32056.dat
0 STEP
0 !LPUB BUILD_MOD BEGIN "bridge"
1 0 -30 190 -80 1 0 0 0 1 0 0 0 1 submodel-02.ldr
0 !LPUB BUILD_MOD END_MOD
1 0 -30 100 -10 1 0 0 0 0 1 0 -1 0 submodel-02.ldr
0 !LPUB BUILD_MOD END
0 STEP
0 !LPUB BUILD_MOD BEGIN "lid"
1 0 0 -20 -140 1 0 0 0 0 1 0 -1 0 submodel-04.ldr
0 !LPUB BUILD_MOD END_MOD
1 0 0 80 -40 1 0 0 0 1 0 0 0 1 submodel-04.ldr
0 !LPUB BUILD_MOD END
0 NOFILE
0
```

Cheers,

**Comment by jacovandermolen** [comment]
Ok, that is good news!
What version do you recommend to test Allard 's model?

**Comment by trevorsandy** [comment]
> What version do you recommend to test Allard 's model?

That would be anything after v2.4.4 r299 - since r299 is not playing nice on Windows.

cheers,

**Comment by trevorsandy** [comment]
This behaviour is corrected.

The source of the problem was a missing header reference which, strangely, did not manifest any abnormal behaviour in debug mode - only in release mode.

Cheers,

**Comment by technicbasics** [comment]
Thanks for corrrecting, will test 2.4.5 asap.
Regards Johann

**Comment by jacovandermolen** [comment]
I did some tests with 2.4.5. This is looking good!
Besides the Front- and Backcoverpage bug [#620](https://github.com/trevorsandy/lpub3d/issues/620) , which is already solved ;-)

**Comment by trevorsandy** [comment]
Excellent.

The latest [DevOps build](https://github.com/trevorsandy/lpub3d-ci/releases/tag/continuous) which includes #620 is available.

Cheers,

**Comment by trevorsandy** [comment]
Reported issues before 10:00 PM tonight will be integrated into v2.4.6 which I'd like to release by tomorrow evening.

Cheers,
