### ISSUE TITLE
Settings for Coverpage and Backcover do not work

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#620]
### Subject
Settings on Coverpage and Backcover do not work

### Environment
* Version of LPub3D - 2.4.5.0.2977
* Windows 10

0 !LPUB PAGE DOCUMENT_COVER_IMAGE DISPLAY GLOBAL TRUE
0 !LPUB PAGE DOCUMENT_COVER_IMAGE FILE GLOBAL "someimage.png"

Does not show image on Frontcoverpage

Title/Title description do not show.

In fact, nothing I set up to show up on the frontcover page is rendered.

Setting something (like 0 !LPUB PAGE LEGO_DISCLAIMER DISPLAY GLOBAL TRUE) on Back Cover puts it on the Frontcover page.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
I must have been sleeping on this one! 

Anyway, the reported behaviour has been corrected.

Cheers,

**Comment by jacovandermolen** [comment]
OK, this is fixed. Tnx

**Comment by jacovandermolen** [comment]
Seems to work again :-)
Only the LPub3D plug logo is not rendered.

**Comment by jacovandermolen** [comment]
Hi Trevor,
Currently I am using 2.4.5 r62 and the LPub3D logo image is not showing.
This is also the case with many versions I have tried and tested. Also 2.4.7.72.
