### ISSUE TITLE
Error loading file with unofficial parts

### ISSUE THREAD

**Issue by billward** [trevorsandy/lpub3d#626]
![image](https://user-images.githubusercontent.com/341092/204377321-7f7fe43f-3d78-470d-9f81-bd0e93968b1a.png)
![image](https://user-images.githubusercontent.com/341092/204377353-f730f2be-40e6-4e4d-8acf-a1387475dd3e.png)
[hull.mpd.txt](https://github.com/trevorsandy/lpub3d/files/10107355/hull.mpd.txt)

Not sure how to represent unofficial parts ... the attached hull.mpd file (.txt added for github to allow) works fine in MLCAD but does not load properly in LPub3D - see screenshots attached.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour and providing an example.

LPub3D loads both the official (complete.zip) and unofficial (ldrawunf.zip) archive libraries at startup so it is sufficient to only reference the unofficial top-level part in your model file. For example paring down _hull.mpd_ to this

```
0 FILE Adagio-72.ldr
0 Adagio-72
0 Name: Adagio-72.ldr
0 Author: LDraw
0 Unofficial Model
0 ROTATION CENTER 0 0 0 1 "Custom" 
0 ROTATION CONFIG 0 0
0 !LPUB ASSEM MODEL_SCALE LOCAL 0.500
0 !LPUB PLI MODEL_SCALE LOCAL 0.100
1 1 0 0 0 1 0 0 0 1 0 0 0 1 59278c01.dat
0
```

... will render this view (i've added scaling commands for better visuals) in LPub3D:

![Screenshot - 30_11_2022 , 04_19_23](https://user-images.githubusercontent.com/13388970/204699828-c20aa5c7-acf7-4e6c-88f0-e79b67ec5e98.png)

It is not necessary to include subfiles and primitives in your model file. In fact, doing this without following the MPD/LDR file conventions will likely lead to problems as these items may be treated as top-level parts when they are not.

If you intend to create custom parts, simply add them into a subfolder under your LDraw unofficial library (e.g. LDraw\Unofficial\customParts) and run the Archive Unofficial Parts... menu action to add your custom part to the unofficial archive library.

![Screenshot - 30_11_2022 , 04_49_19](https://user-images.githubusercontent.com/13388970/204703375-609f16c7-76f8-430d-b82e-b9c6876e691b.png)

 Additionally, you can enable load messages in the `Preferences` dialog to see parse errors during file load.

![Screenshot - 30_11_2022 , 04_51_37](https://user-images.githubusercontent.com/13388970/204703695-905dca99-34d1-46af-995d-ccc0c64855c4.png)

In this error example, you can see several primitives were treated as parts and were not found.
![Screenshot - 30_11_2022 , 04_32_24](https://user-images.githubusercontent.com/13388970/204703716-7340bfcd-fc37-4c32-b0b1-6e0c30666f65.png)


Cheers,

**Comment by billward** [comment]
Thanks for the explanation. In this particular project I'm only concerned
about doing the unofficial part. It sounds like the way that mlcad is
importing the unofficial parts is to blame... I'm not sure how to configure
that software to load the unofficial parts automatically without importing
them this way however but that's not your problem!

Sent from my phone (sorry if my reply is brief, ask me again when I'm at a
real keyboard)

**Comment by trevorsandy** [comment]
> I'm not sure how to configure that software to load the unofficial parts automatically without importing them this way...

It looks like you do not have MLCad configured to read your unofficial parts. Follow the guidance in the attached document to enable this capability. Once completed, you should be able to simply add just the part reference (versus all the part's sub components) just as you would with official parts.

[Adding_unofficial_LDraw_parts_to_MLCad.pdf](https://github.com/trevorsandy/lpub3d/files/10119879/Adding_unofficial_LDraw_parts_to_MLCad.pdf)

Cheers,

**Comment by billward** [comment]
Thank you! That is definitely going above and beyond the expected level of
service for your software

Sent from my phone (sorry if my reply is brief, ask me again when I'm at a
real keyboard)
