### ISSUE TITLE
Remove LPub Formatting menu action does nothing

### ISSUE THREAD

**Issue by trevorsandy** [trevorsandy/lpub3d#638]
###  Subject
Triggering the _Remove LPub Formatting_ menu action does nothing.

### Environment
Version of LPub3D - 2.4.5
Operating system - All

### Expected behaviour
Formatting should be removed.

### Actual behaviour
The application flashes but no formatting is removed. This behaviour is present for _Unformat Document_ and _Unformat Current Submodel_ menu actions.

### Solution
Fix it.

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

![Screenshot - 04_12_2022 , 15_13_10](https://user-images.githubusercontent.com/13388970/205495608-8221a55c-07ac-4285-ad9e-1488c54f1d1a.png)

![Screenshot - 04_12_2022 , 15_13_33](https://user-images.githubusercontent.com/13388970/205495613-c95427ee-1ade-46f7-a7ba-a960672f7b94.png)

Note that the following menu action toggles only apply to unformatting _Current Page_, _Single Step_, or _Current Submodel_. 

- _Remove Build Mod Format_
- _Remove Child Submodel Format_

The _Unformat Document_ menu action removes _ALL_ LPub document formatting.

Cheers,

**Comment by jacovandermolen** [comment]
Hasn't this been fixed?
Remove format with version x86_64-2.4.7.75.3551_20230905 does nothing.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. Unfortunately, I am not able to reproduce it with v2.4.7r75.

![RemoveFormatting_01](https://github.com/trevorsandy/lpub3d/assets/13388970/5d1f04a5-1614-45f1-817f-e8eafc5d4c52)

![RemoveFormatting_02](https://github.com/trevorsandy/lpub3d/assets/13388970/a26834e0-aa48-40c3-b229-ee081d6512cf)

As you can see, there are several unformat options available. Is the unexpected behaviour present on one of the granular options ?

Cheers,
