### ISSUE TITLE
Parts reported not found

### ISSUE THREAD

**Issue by ReneFrijhoff** [trevorsandy/lpub3d#64]
### Subject of the issue
LPub3d reports part files 3039pce.dat and 3068bp72.dat are not in the unofficial library (ldrawunf.zip). That in itself is correct, but they do exist in the official library (complete.zip). Steps taken:

1: Deleted the archive files from C:\Users\Rene\AppData\Local\LPub3D Software\LPub3D\libraries
This didn't help.

2: Refreshed the archive libraries within LPub3D
This didn't help either

3: Added search directories f:\ldraw\parts and f:\ldraw\parts\s
Still not working

4: Refreshed the directories f:\ldraw\p and f:\ldraw\parts
Nope

### Your environment
Version 2.2.0 Revision 0 Build 780 later with Version 2.2.2 Revision 0 Build 848
Windows 7 x64 latest update

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  - Windows: F:\Program Files\LPub3D

* Application data path
  - Windows: %USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\

* Registry Extract
  - Windows: `reg export "HKEY_CURRENT_USER\Software\LPub3D Software" %USERPROFILE%\Desktop\LPub3D_Hive.reg`
[LPub3D_Hive.txt](https://github.com/trevorsandy/lpub3d/files/2299189/LPub3D_Hive.txt)

* Renderer configuration files
  - `[Application data path]/3rdParty\ldglite-1.3\config\ldglite.ini`
[ldglite.ini.txt](https://github.com/trevorsandy/lpub3d/files/2299193/ldglite.ini.txt)
  - `[Application data path]/3rdParty\ldview-4.3\config\ldview.ini`
[ldview.ini.txt](https://github.com/trevorsandy/lpub3d/files/2299195/ldview.ini.txt)
  - `[Application data path]/3rdParty\ldview-4.3\config\ldviewPOV.ini`
[ldviewPOV.ini.txt](https://github.com/trevorsandy/lpub3d/files/2299196/ldviewPOV.ini.txt)
  - `[Application data path]/3rdParty\lpub3d_trace_cui-3.8\config\povray.conf`
[povray.conf.txt](https://github.com/trevorsandy/lpub3d/files/2299197/povray.conf.txt)
  - `[Application data path]/3rdParty\lpub3d_trace_cui-3.8\config\povray.ini`
[povray.ini.txt](https://github.com/trevorsandy/lpub3d/files/2299198/povray.ini.txt)

### Logs
* Application Log: `[Application data path]/logs/LPub3DLog.txt`
[LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/2299201/LPub3DLog.txt)
No render logs are made.

### Screenshots
* Configuration->Preferences->General
![afbeelding](https://user-images.githubusercontent.com/37920537/44296568-cad2ca80-a2c1-11e8-864b-cf0eecd82fff.png)
* Configuration->Preferences->Rendering
![afbeelding](https://user-images.githubusercontent.com/37920537/44296576-e2aa4e80-a2c1-11e8-817c-1310008491b7.png)
* Configuration->Preferences->Publishing
![afbeelding](https://user-images.githubusercontent.com/37920537/44296581-eccc4d00-a2c1-11e8-849a-314f60ee1fd1.png)
* Configuration->Preferences->Logging
![afbeelding](https://user-images.githubusercontent.com/37920537/44296584-fb1a6900-a2c1-11e8-9c88-c733982b68b0.png)
* Configuration->Preferences->Other
![afbeelding](https://user-images.githubusercontent.com/37920537/44296586-040b3a80-a2c2-11e8-937b-eaf4a84af1ce.png)

### Steps to reproduce
Just load the mpd file
[Eagle.mpd.txt](https://github.com/trevorsandy/lpub3d/files/2299203/Eagle.mpd.txt)

### Expected behaviour
It should find the parts just fine.

### Actual behaviour
It doesn´t find the parts as it seems it's looking in the wrong archive (unofficial i.s.o. official)

### Workaround
None so far. Commenting out the concerning lines does work, but that would be the same as deleting them (but at least I can load the file without having LPub3D crashing)

### Solution suggestion
Lpub3D should at least not crash, other then that I really don't have any idea.

**Comment by trevorsandy** [comment]
Hi Rene, I didn’t see the updated LDraw file ?

Cheers,

**Comment by ReneFrijhoff** [comment]
It's definately attached, but I will try again.

I will try to uninstall and reinstall LPub3d. I will let you know the
result.

Cheers,

Op ma 27 aug. 2018 om 07:59 schreef Trevor SANDY <notifications@github.com>:

**Comment by qwertychouskie** [comment]
@ReneFrijhoff You have to attach the files via Github's web interface.  Email attachments won't show up in Github.

**Comment by ReneFrijhoff** [comment]
Ah, sorry. Will do.

Cheers,

Op ma 27 aug. 2018 om 19:47 schreef QwertyChouskie <notifications@github.com

**Comment by ReneFrijhoff** [comment]
Updated version.

[Eagle - Error.mpd.txt](https://github.com/trevorsandy/lpub3d/files/2325056/Eagle.-.Error.mpd.txt)

**Comment by ReneFrijhoff** [comment]
Sorry, clicked wrong button.

**Comment by trevorsandy** [comment]
Rene,

I cannot reproduce the behaviour you describe.

For me all the parts in question load as expected. Here are some shots of the Steps you indicated:

![screenshot - 31_08_2018 03_20_14](https://user-images.githubusercontent.com/13388970/44887634-8dad0600-accd-11e8-8bee-1169398c757c.png)

![screenshot - 31_08_2018 03_18_58](https://user-images.githubusercontent.com/13388970/44887637-900f6000-accd-11e8-8f8a-5e4987de4f59.png)

![screenshot - 31_08_2018 03_17_32](https://user-images.githubusercontent.com/13388970/44887640-9271ba00-accd-11e8-8de4-3f1720cb2c7b.png)

And here is the model file load log indicating - as I described before - all parts in question loading as expected.

[Eagle.Error.mpd_LPub3D.log](https://github.com/trevorsandy/lpub3d/files/2338461/Eagle.Error.mpd_LPub3D.log)

Cheers,

**Comment by ReneFrijhoff** [comment]
I uninstalled and reinstalled LPub3D Version 2.2.2 Revision 0 Build 848 and
these are the results:
Uninstall program, but not user data and user registry settings: Program
still can't find files and crashes.
Uninstall program and user data, but not registry settings: Program still
can't find files, but doesn't crash anymore.
Uninstall program and registry settings, but not user data: Now it does
find the files, which means that something in the registry settings was
screwed up.

Cheers,

**Comment by trevorsandy** [comment]
Some more details being reported on this behaviour...

It only occurs when you enable fade previous steps, if you disable it, the problem does not occur. This happens btw also with the latest version.

**Comment by trevorsandy** [comment]
Ok, after a few rounds of looking, I believe I've found the source and you'll be happy to know it's not so bad. 

You should generate an updated Static Colour Parts List to be sure parts are identified in their current archive. You can generate this list from the UI menubar:

![screenshot - 09_09_2018 21_24_33](https://user-images.githubusercontent.com/13388970/45268026-33ebcf00-b477-11e8-9c11-7ae5d1b6a918.png)

Be mindful it takes about 20 to 30 minutes as the program is checking all parts across the official and unofficial libraries that include static colour parts, including their children.

Alternatively, you can simply open the Static Colour Pats List from the UI and edit your missing entries. 

![screenshot - 09_09_2018 21_31_32](https://user-images.githubusercontent.com/13388970/45268104-14a17180-b478-11e8-9e05-dd51b3ea3050.png)

You can see that Official parts have an 'o' designating such and Unofficial parts a 'u'. 

![screenshot - 09_09_2018 21_40_36](https://user-images.githubusercontent.com/13388970/45268219-0738b700-b479-11e8-85fc-27d5ddc14d14.png)

As expected, the missing parts are both listed as being in the unofficial library; hence, the error message. Simply changing the 'u' to 'o' should correct your behaviour.

![screenshot - 09_09_2018 21_44_33](https://user-images.githubusercontent.com/13388970/45268266-ac538f80-b479-11e8-9511-eada75a6a003.png)

I've update the error message to be more descriptive so, I imagine, going forward it would be easier to pinpoint the source of this behaviour. I've also generated an up to date list which I'll include in v2.3.1.

Cheers,

**Comment by ReneFrijhoff** [comment]
Hi Trevor, thanks for your reply. I will check it out.

Cheers,

Op zo 9 sep. 2018 om 21:47 schreef Trevor SANDY <notifications@github.com>:
