### ISSUE TITLE
Select and move a submodel in 3D viewer causes crash

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#645]
### Subject
Select and move a submodel in 3D viewer causes crash

### Environment
* Version of LPub3D - 2.4.5.62.3270 (and some other previous 2.4.x versions)

### Steps to reproduce
With Build Mods activated, selecting a submodel in the 3D viewer/editor and then move it using the arrows

### Expected behaviour
The submodel should be able to move this way, just like parts

### Actual behaviour
LPub3D crash

### Workaround
Manually add a BM

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Hi Jaco,

I am not able to reproduce this behaviour. Can you confirm that this behaviour is still present in the latest DevOps build containing #646 and #651? 

Also, when you say _selecting a submodel in the 3D viewer/editor..._, are you speaking about selecting an LDraw submodel or selecting all the parts in the current step ? Can you provide a screenshot of what you are selecting ?

Cheers,

**Comment by jacovandermolen** [comment]
OK, I will check. Last DevOps is 2.4.5.110.3318 from yesterday, right?

**Comment by trevorsandy** [comment]
> 2.4.5.110.3318 from yesterday, right?

I submitted a build today (2.4.5.110.3319) which treats #646. I think it is still building as of the writing of this post. It would be good if you could use this one.

Cheers,

**Comment by jacovandermolen** [comment]
OK, got it. Going to test now.

**Comment by jacovandermolen** [comment]
OK, so far so good!
Buildmods work as they should*, selecting and moving either a single part, multiple parts or submodel and moving them in the visual editor work. Applying Buildmods now puts the "hovering" part(s) / submodel at the correct positon.
And I see a litte surprise: choosing to remove a BM now pops up a menu from where you can choose what BM to remove! This is very nice! Exactly what this feature needs, since you can now remove BMs in later steps then only the next.
I have conducted tests now with one part, multiple parts and submodel. All with succes and expected behaviour and result. Selecting and moving in the VE works. I am very excited about this (I was, but now even more ;-)

I need to run some tests in other models.

(* BM did not go well in 2.4.5.110.3318)

One new problem however:
When navigating to the last page and going back one page LPub crashes.
I will reproduce this and describe in depth in new issue.

**Comment by jacovandermolen** [comment]
Alas, I am getting some errors in other models.
Shall I report my findings in new issues, or as a reaction in this thread too?

**Comment by trevorsandy** [comment]
> Shall I report my findings in new issues...
It would be better to use new a issue if the behaviour is new.

Cheers,

**Comment by trevorsandy** [comment]
This behaviour no longer presents as of DevOps build 3319
