### ISSUE TITLE
Moving a part in the 3D viewer/editor misplaces it in other directions too

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#646]
### Subject
Moving a part in the 3D viewer/editor displaces the part in other directions too

### Environment
* Version of LPub3D - 2.4.5.62.3270 (and all other versions)

### Steps to reproduce
1. With Build Mods activated, select a part in the 3D viewer/editor and then for example move it up in the negative Y direction to make it hover above the model
2. Part shows up moved in correct and wanted direction in preview 
3. Create a Build Modification
4. Movement is also affected in the Z direction

### Expected behaviour
The part should only be moved in the choosen direction (?)

### Actual behaviour
Other values of XYZ are also affected.
With a rotation step, the part is rotated back too.

### Workaround
Manually correct the hovering position of the part in the BM (by hand or in LDraw editor)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

![Screenshot - 03_01_2023 , 09_46_50](https://user-images.githubusercontent.com/13388970/210325092-80a47db9-4218-4670-b73b-97e81484d78a.png)

There is still less-than-ideal positioning behaviour regarding new parts added  in the visual editor but the current behaviour is not onerous.

Cheers,

**Comment by jacovandermolen** [comment]
The movement and placement is indeed fixed!
