### ISSUE TITLE
Option Add pointer missing in Call Out

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#647]
### Subject
Option Add pointer missing in right-click menu in Call Out

### Environment
* Version of LPub3D - 2.4.5.62.3270 (and some previous 2.4.x versions)

### Steps to reproduce
Convert a submodel to Callout (either with pointer or pointerless)
Option 1: remove the pointer and later add it again
Option 2: choice was pointerless callout, but want to add pointer either way
Option 3: add a second or more pointer(s) to existing callout with pointer

### Expected behaviour
One should be able to add a pointer in any Callout. Either a pointerless callout where you later do want a pointer, as for a callout that had a pointer which was removed and later want to add again.

### Actual behaviour
On right-click in a Callout the option Add pointer is missing.

### Workaround
Manually add the Metacommand for a pointer.
Or unpack the Callout and add it again, with pointer.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

![Screenshot - 09_12_2022 , 02_57_05](https://user-images.githubusercontent.com/13388970/206606004-140366bb-14fe-4322-946d-de6b1a24d478.png)

Cheers,
