### ISSUE TITLE
Set Attributes to Page Pointer globally

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#648]
### Subject (wish/enhancement)
Set Attributes to Page Pointer globally

### Environment
* Version of LPub3D - 2.4.5.62.3270 (and all other versions)

### Steps to reproduce
Add Page Pointer and set Attributes

### Wanted behaviour
Just like you can setup the Attributes for Callout pointers globally, please make this possible for Page Pointer too
Something like

`0 !LPUB PAGE_POINTER_ATTRIBUTE GLOBAL BORDER SOLID COLOR #ffffff WIDTH 0.016`

### Workaround
Adjust Page Pointer Attributes for each Page Pointer

**Comment by trevorsandy** [comment]
Thank you for your request.

I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

Cheers,

**Comment by jacovandermolen** [comment]
Hi Trevor,
When will you release a DevOps or next version?
