### ISSUE TITLE
Add assembled image to parent page doesn't work properly

### ISSUE THREAD

**Issue by ReneFrijhoff** [trevorsandy/lpub3d#65]
### Subject of the issue
When using 'Add assembled image to parent page' It inserts an assembled image only for the first occurrence. In this case it doesn't add the assembled image for 3 more occurrences. 

### Your environment
* Version of LPub3D - see Help->About LPub3D
Version 2.2.2. Revision 0 Build 848
* Operating system - OS Name, Processor Architecture (x86,x86_64)
Windows 7 x64 latest update

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]

    LPub3D installation path
        Windows: F:\Program Files\LPub3D

    Application data path
        Windows: %USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\

    Registry Extract
        Windows: reg export "HKEY_CURRENT_USER\Software\LPub3D Software" %USERPROFILE%\Desktop\LPub3D_Hive.reg
        [LPub3D_Hive.txt](https://github.com/trevorsandy/lpub3d/files/2300243/LPub3D_Hive.txt)

    Renderer configuration files
        [Application data path]/3rdParty\ldglite-1.3\config\ldglite.ini
[ldglite.ini.txt](https://github.com/trevorsandy/lpub3d/files/2300244/ldglite.ini.txt)
        [Application data path]/3rdParty\ldview-4.3\config\ldview.ini
[ldview.ini.txt](https://github.com/trevorsandy/lpub3d/files/2300245/ldview.ini.txt)
        [Application data path]/3rdParty\ldview-4.3\config\ldviewPOV.ini
[ldviewPOV.ini.txt](https://github.com/trevorsandy/lpub3d/files/2300246/ldviewPOV.ini.txt)
        [Application data path]/3rdParty\lpub3d_trace_cui-3.8\config\povray.conf
[povray.conf.txt](https://github.com/trevorsandy/lpub3d/files/2300247/povray.conf.txt)
        [Application data path]/3rdParty\lpub3d_trace_cui-3.8\config\povray.ini
[povray.ini.txt](https://github.com/trevorsandy/lpub3d/files/2300248/povray.ini.txt)

### Logs
* Application Log: `[Application data path]/logs/LPub3DLog.txt`
[LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/2300254/LPub3DLog.txt)
Renderlogs LDview are empty, others are not created.

### Screenshots

    Configuration->Preferences->General
![afbeelding](https://user-images.githubusercontent.com/37920537/44308055-ae608c00-a3ae-11e8-93a8-c5c36f324603.png)
    Configuration->Preferences->Rendering
![afbeelding](https://user-images.githubusercontent.com/37920537/44308058-b9b3b780-a3ae-11e8-98f4-7bf790c3b865.png)
    Configuration->Preferences->Publishing
![afbeelding](https://user-images.githubusercontent.com/37920537/44308059-c20bf280-a3ae-11e8-962a-b31cb507c75d.png)
    Configuration->Preferences->Logging
![afbeelding](https://user-images.githubusercontent.com/37920537/44308061-ccc68780-a3ae-11e8-8839-0616fece6f1e.png)
    Configuration->Preferences->Other
![afbeelding](https://user-images.githubusercontent.com/37920537/44308066-d7811c80-a3ae-11e8-9394-ec80393fabad.png)

### Steps to reproduce
Right-click to add an asssembled image of the landing gear to the parent page.
[External fuel tanks.mpd.txt](https://github.com/trevorsandy/lpub3d/files/2300258/External.fuel.tanks.mpd.txt)

### Expected behaviour
Assembled image should be inserted at all occurrences

### Actual behaviour
Assembled image is inserted only at first occurrence

### Workaround
Copy lines used in first occurrence to other occurrences.

### Solution suggestion
Program should check for all occurrences

**Comment by ReneFrijhoff** [comment]
I don't quite understand what you mean with 'images are all over the place
and outside the scene boundary' as everything is ok. Are you sure you're
using the correct default unit (cm), resolution (150) and renderer (ldview)?

Also page 7 is the submodel, not the parent page that's why you're not
seeing anything happening on that one. The parent pages are 8, 11, 14 and
17. When adding an assembled image on the parent page on page 7, it only
adds an assembled image on the 1st occurrence which is page 8, but it
doesn't add an assembled image on pages 11, 14 and 17.

Submodel:
[image: afbeelding.png]
1st parent page:
[image: afbeelding.png]
On this one an assembled model is placed, but not at the other occurrences
(pages 11, 14 and 17).

And this model complex? Just normal multi_steps and callouts. Most of my
model files are this way.

Cheers,

Op zo 26 aug. 2018 om 21:18 schreef Trevor SANDY <notifications@github.com>:

**Comment by trevorsandy** [comment]
Very well. Thank you for the good context and precise locations. I'll take a look.

Regarding the display. With these settings...

![screenshot - 26_08_2018 22_34_50](https://user-images.githubusercontent.com/13388970/44632790-37fcf480-a981-11e8-97de-9d1bcb6aad9b.png)

![screenshot - 26_08_2018 22_35_46](https://user-images.githubusercontent.com/13388970/44632791-3af7e500-a981-11e8-9be1-83447f8a94d1.png)

I get these page displays. Of course I haven't gone into the details of why the display is this way because I don't usually spend time looking at items that are outside the scope of the behaviour I'm addressing.

![screenshot - 26_08_2018 22_36_35](https://user-images.githubusercontent.com/13388970/44632817-b194e280-a981-11e8-8120-96d9031c061d.png)

![screenshot - 26_08_2018 22_37_49](https://user-images.githubusercontent.com/13388970/44632818-b3f73c80-a981-11e8-96ea-ebf69cbf6596.png)

Don't mind the different LPub3D user interface from your instance. I'm working with version 2.3.0 which I'm just about to release.

Cheers,

**Comment by ReneFrijhoff** [comment]
This is weird, because this is how it looks on my screen:

[image: afbeelding.png]
[image: afbeelding.png]
After taking another look, I saw that your renderer is ldglite and not
ldview. I would advise you to change the renderer and try again.

Cheers,

Op zo 26 aug. 2018 om 22:48 schreef Trevor SANDY <notifications@github.com>:

**Comment by trevorsandy** [comment]
### Solution

It looks like you'll have to seperate the Submodel Instance Count by unchecking the box in the graphic below. This will allow you to apply the assembled image to each occurrence of the parent. You can then revert the configuration to consolidate the submodel count and your assembled meta commands will be preserved. 

![screenshot - 26_08_2018 23_37_22](https://user-images.githubusercontent.com/13388970/44633286-772f4380-a989-11e8-8304-038041c9071e.png)

This approach will present the landing gear submodel before each parent page occurrence, allowing you to individually add the assembled image at each parent. 

You can see in the following images that with 'Consolidate Submodel Instance Count' unchecked. The page count has increased by 3 (these are the 3 additional instances of the landing gear) to 23 pages. So adding the assembled image to the parent at each occurrence of the landing gear submodel will properly write the meta commands to add/display the assembled image at each occurrence of the parent.

![screenshot - 26_08_2018 23_48_26](https://user-images.githubusercontent.com/13388970/44633367-a8f4da00-a98a-11e8-88aa-d185f20928a5.png)

And here's the second submodel parent occurrence (as an example) - pp12 - properly showing the assembled image...

![screenshot - 26_08_2018 23_50_40](https://user-images.githubusercontent.com/13388970/44633381-dc376900-a98a-11e8-8172-9daffa36c7b7.png)

After you have applied the assembled images, you can now check the consolidate submodel instance flag. Notice in the image below, we are back to 20 pages and the parent also shows the assembled image - again I'm showing the second occurrence as an example.

![screenshot - 27_08_2018 00_00_52](https://user-images.githubusercontent.com/13388970/44633625-2b32cd80-a98e-11e8-8c71-a74a07fcc5aa.png)

Unless there is another compelling reason, I don't see the justification the modify this behaviour by itself. However, if I'm adding a new feature in the future that would implicate this behaviour, I'll take a look at adding the automation to update each occurrence of the submodel parent without having to uncheck the consolidate submodel instance count flag. 

Let me know if this update allows you to move forward with your instructions ? 

Cheers,

**Comment by trevorsandy** [comment]
Just a quick follow up on your previous post. This is what it look like in my browser:

![screenshot - 27_08_2018 00_23_20](https://user-images.githubusercontent.com/13388970/44633763-81544080-a98f-11e8-98ee-ac526a4d8d73.png)

I use LDGLite for speed. The coordinate and camera globe processing is the same as that of LDView - L3P. Anyway, no worries, you should be good to go now.

Cheers,
