### ISSUE TITLE
add callout pointer context menu item missing

### ISSUE THREAD

**Issue by DanieleBenedettelli** [trevorsandy/lpub3d#661]
### Subject
When right-clicking on the callout, the Add Pointer Callout context menu item is missing.

### Environment
dev release 2.4.5 rev 62 build 3270
Win 10 x64

### Configuration
Default out of the distribution zip file 

### Screenshots

![callout add pointer context menu item missing](https://user-images.githubusercontent.com/47357389/210130044-f636f131-9cd7-4bb6-a173-f2aa8b9d3210.png)

### Steps to reproduce
Right click on a callout, the add pointer item is missing.
[callout_pointer_bug.zip](https://github.com/trevorsandy/lpub3d/files/10327039/callout_pointer_bug.zip)

### Expected behaviour
I should be able to manually add a callout pointer

### Actual behaviour
The menu item is missing, and I can't add the pointer.

### Workaround
I copy and paste the meta commands from existing projects where I added callout pointers

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

I am not able to reproduce this behaviour on the latest DevOps build - so I imagine this has been corrected after build 3270.

The sample model file you provided did not have any callout commands:

```
0 FILE main.ldr
0 Author: Danny's LAB
1 321 0 -10 0 1 0 0 0 1 0 0 0 1 3004.dat
1 16 0 -34 0 1 0 0 0 1 0 0 0 1 subModel-1.ldr
0 FILE subModel-1.ldr
0 Author: Danny's LAB
1 321 0 0 0 1 0 0 0 1 0 0 0 1 3004.dat
1 321 0 -24 0 1 0 0 0 1 0 0 0 1 3004.dat
```

With the following callout commands...

```
0 FILE main.ldr
0 Author: Danny's LAB
1 321 0 -10 0 1 0 0 0 1 0 0 0 1 3004.dat
0 !LPUB CALLOUT BEGIN
1 16 0 -34 0 1 0 0 0 1 0 0 0 1 subModel-1.ldr
0 !LPUB CALLOUT END
0 FILE subModel-1.ldr
0 Author: Danny's LAB
1 321 0 0 0 1 0 0 0 1 0 0 0 1 3004.dat
1 321 0 -24 0 1 0 0 0 1 0 0 0 1 3004.dat
```

I get this result:
![Screenshot - 01_01_2023 , 23_56_53](https://user-images.githubusercontent.com/13388970/210186892-2a27ee48-d10c-47e5-9676-2236381da29d.png)

...and with this update:

```
0 FILE main.ldr
0 Author: Danny's LAB
1 321 0 -10 0 1 0 0 0 1 0 0 0 1 3004.dat
0 !LPUB CALLOUT BEGIN
0 !LPUB CALLOUT PLI PER_STEP FALSE
1 16 0 -34 0 1 0 0 0 1 0 0 0 1 subModel-1.ldr
0 !LPUB CALLOUT END
0 FILE subModel-1.ldr
0 Author: Danny's LAB
1 321 0 0 0 1 0 0 0 1 0 0 0 1 3004.dat
1 321 0 -24 0 1 0 0 0 1 0 0 0 1 3004.dat
```
![Screenshot - 01_01_2023 , 23_58_37](https://user-images.githubusercontent.com/13388970/210186908-f7645ba0-24d5-44f4-9821-859bd33efcce.png)

Cheers,
