### ISSUE TITLE
MULTI_STEP meta is placed incorrectly

### ISSUE THREAD

**Issue by technicbasics** [trevorsandy/lpub3d#662]
### Subject
When Multi Step commands are inserted, they are inserted incorrectly in the code window,
and so the steps are showed wrong and so the steps are displayed incorrectly or not at all.

### Environment
* Version of LPub3D - 2.4.5 64-bit
* Operating system - Win11-64bit

![LP3D_1](https://user-images.githubusercontent.com/49073781/210168703-41976a61-468f-4fce-b080-e2a47d006f57.png)
![LP3D_2](https://user-images.githubusercontent.com/49073781/210168712-df3d4940-67b7-4133-bb2e-c6e7cb08b732.png)
![LP3D_3](https://user-images.githubusercontent.com/49073781/210168715-0ee597ec-2f7b-4c78-b209-5c9741b7f90b.png)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

I am not able to reproduce this behaviour on the latest DevOps build - so I imagine this has been corrected in the update for #632.

For me the behaviour is as expected.
![Screenshot - 02_01_2023 , 02_20_31](https://user-images.githubusercontent.com/13388970/210189673-779f44e6-aa93-4328-84cb-a482e446b066.png)

![Screenshot - 02_01_2023 , 02_21_15](https://user-images.githubusercontent.com/13388970/210189675-a87acb33-c827-42b2-817c-fc42d94cf843.png)

Cheers,

**Comment by technicbasics** [comment]
Sorry, I had searched for "Multi_Step" and not "next step". If I had found #632  I wouldn't have created this ticket at all.
Regards Johann
