### ISSUE TITLE
Moving a submodel in the Visual editor after moving a previous submodel gives error

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#665]
### Subject
Moving a submodel in the Visual editor after moving a previous submodel gives errors

### Environment
* Version of LPub3D - 2.4.5.111.3319
* Windows 10

### Steps to reproduce
Select and move a submodel in the Visual editor works fine after the fix (https://github.com/trevorsandy/lpub3d/issues/645)
But then, on another page select another submodel after the previous submodel gives error

![image](https://user-images.githubusercontent.com/32261647/210441520-1024e52a-5003-4a03-9f16-16ee6159ae3f.png)

This dialog keeps comming. Some how, the selection is permanent. 

I will try to make a screenrecording to illustrate.

### Expected behaviour
Where ever I am in the model and at any point selecting a submodel in the Visual editor should work.

### Actual behaviour
Selecting another submodel gives error.

### Workaround
Save the file, close LPub, restart and open the file again, navigate to the page where the other submodel is and then selecting and moving works.

**Comment by jacovandermolen** [comment]
Recording of the problem:
https://drive.google.com/file/d/1RhyzNYyTIg2EAaFGe7PMPfAWYPRS6KOc/view?usp=sharing

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour and providing a demonstration video.

I'll take a look.

I have seen this _persistent_ messaging behaviour before. There is some sort of runaway event processing going on but I have not yet found the source.

 Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

Cheers,
