### ISSUE TITLE
LPub3D - Crash

### ISSUE THREAD

**Issue by Holly-Wood68** [trevorsandy/lpub3d#670]
### Subject
Tried to add a BOM at the end of the attached model. Got error in screenshot. Soon afterwards the prog crashed.

### Environment
* Version of LPub3D: LPub3D 2.4.6.0.3111 
* Operating system: Windows 11 Home, 10.0.22621

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  - Windows: `C:\Program Files\LDraw (64 Bit)\LPub3D` [x86_64]

* Application data path
  - Windows: `%USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\`

* Registry Extract
  - Windows (installed): reg in zip

* Renderer configuration files
  - `[Application data path]/ldv/ldvExport.ini`
  - `[Application data path]/3rdParty/ldglite-1.3/config/ldglite.ini`
  - `[Application data path]/3rdParty/ldview-4.4/config/ldview.ini`
  - `[Application data path]/3rdParty/ldview-4.4/config/ldviewPOV.ini`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.conf`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.ini`

### Logs
* Application Log: `[Application data path]/logs/LPub3DLog.txt`

### Steps to reproduce
Add BOM to attached model

### Expected behaviour
Generate BOM

### Actual behaviour
Error message, then crash message 

[LPub-Crash.zip](https://github.com/trevorsandy/lpub3d/files/10458159/LPub-Crash.zip)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

Cheers,
