### ISSUE TITLE
LPub3d crashed when generating BOM (treat as part issue)

### ISSUE THREAD

**Issue by BerthWan** [trevorsandy/lpub3d#671]
### Subject
I used a universal joint in a model in three subparts in a single callout. I used the "treat as part function" to manage it. There's no problem with the step and its PLI. But, when generating the BOM, the software crashed. There's a error message : "failed to retrieve BOM render options using viewer step key 'ujoint';16;0' for image 'ujoint-0_16_1753_150_DPI_0.9_30_23_-45.png." where ujoint is my submodel's name.
I bypass the issue by copy/paste the PLI png from "LPub3d\parts\" to "LPub3d\bom\" before generating the BOM pages.

### Environment
* Version of LPub3D - LPub3D 2.4.6.0.3111
* Operating system - Windows 10, x86_64

### Configuration
* LPub3D installation path
  - Windows: `D:\Installations\LDRAW\LPub3D_x86_64`

* Registry Extract
  - Windows (portable): `D:\Installations\LDRAW\LPub3D_x86_64\config\LPub3D Software`
  - 
* Renderer configuration files
  - `[Application data path]/ldv/ldvExport.ini`
  - `[Application data path]/3rdParty/ldglite-1.3/config/ldglite.ini`
  - `[Application data path]/3rdParty/ldview-4.4/config/ldview.ini`
  - `[Application data path]/3rdParty/ldview-4.4/config/ldviewPOV.ini`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.conf`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.ini`

### Logs
* Application Log: `[Application data path]/logs/LPub3DLog.txt`
* Renderer Log: `[LDraw model path]/stdout-ldglite`
* Renderer Log: `[LDraw model path]/stdout-povray`
* Renderer Log: `[LDraw model path]/stderr-ldglite`
* Renderer Log: `[LDraw model path]/stderr-povray`

### Screenshots
* Configuration->Preferences->General
* Configuration->Preferences->Rendering
* Configuration->Preferences->Publishing
* Configuration->Preferences->Logging
* Configuration->Preferences->Other

### Steps to reproduce
generate a BOM using the treat as part functionnality (I encountered it on an other model but it was for a minifig, so I ignored it and it solved the issue)

### Expected behaviour
the complete universal joint appears in the BOM

### Actual behaviour
the software crashed after displaying the error message

### Workaround
I tried to generate the BOM without the complete universal joint and it worked fine (but with three subparts in the BOM)

### Solution suggestion
I copy/paste the PLI generated image file in the bom directory.
[lpub3d_big_bom.zip](https://github.com/trevorsandy/lpub3d/files/10459906/lpub3d_big_bom.zip)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

![Screenshot - 24_01_2023 , 11_11_25](https://user-images.githubusercontent.com/13388970/214265938-708decfe-5237-4a45-a990-257891995814.png)

Cheers,

**Comment by BerthWan** [comment]
Thank you.

**Comment by trevorsandy** [comment]
Hello Berth,

Just a quick note to say

`0 STEP` and `0 ROTSTEP` are the same in terms of declaring a new STEP. The only difference is ROTSTEP also presents rotation coordinates.

So this...

```
0 STEP
0 ROTSTEP 0 90 0 REL
```

can be replaced with

```
0 ROTSTEP 0 90 0 REL
```

Cheers,

**Comment by BerthWan** [comment]
Yes I know, but I had issues in the past with some software (I can't remember which one) that was solved with this trick, I kept the habit.
