### ISSUE TITLE
Crash when "Treat as Part" is activated

### ISSUE THREAD

**Issue by ErfinderDesRades** [trevorsandy/lpub3d#672]
LPub3D crashes when activating the "Treat as Part" option on the last page of a submodel.
After activating the option you go through the  document page by page, but when reaching the page with the submodel treated as part LPub3D crashes.

### Environment
* Version of LPub3D - 2.4.6.0.3111_20230111
* Windows 11, Processor 12th Gen Intel(R) Core(TM) i7-12700H   2.70 GHz
* Architecture 64-Bit, 32 GB Ram

### Configuration
* LPub3D installation path
  - Windows: C:\Program Files\LPub3D_246
* Application data path

Until now I couldn't find any workaround

Best regards and thanks a lot in advance.

[230119_LPub3D_crash.zip](https://github.com/trevorsandy/lpub3d/files/10460305/230119_LPub3D_crash.zip)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

Cheers,

**Comment by ErfinderDesRades** [comment]
Many thanks for your response.

Sorry for insisting, but what does it mean, "this behaviour has been corrected"? Will there be a fix in the next update, or how did you correct this behaviour?

Regards

**Comment by trevorsandy** [comment]
> ...what does it mean, "this behaviour has been corrected"? Will there be a fix in the next update

Indeed. 

The aim of this comment is to inform on the state of the unexpected behaviour so someone else wanting to report it can be made aware that 1. the behaviour has been acknowledged and 2. a correction has already been implemented.

Completed corrections are available in the next published release.

Cheers,
