### ISSUE TITLE
Part IDs missing in BOM 

### ISSUE THREAD

**Issue by ErfinderDesRades** [trevorsandy/lpub3d#680]
I'm not really sure ether this is an ssue or not, but when setting up a BOM part IDs don't show up.

I followed your instructions in thread #186 and also in #513. But nothing changed. The BOMalways looks like this:

![image](https://user-images.githubusercontent.com/77791504/214886185-fa9386cd-d984-4c64-91d3-768d9bcd96b9.png)

When checking the local checkbox in the configuration menu I get this message:

![image](https://user-images.githubusercontent.com/77791504/214886641-155f0837-d8f3-45f8-827c-e1a2dcc46626.png)

Is it necessary to download an additional part file, or did I miss anything else?

Regards from Bremen

Environment
Version of LPub3D - 2.4.6.0.3111_20230111
Windows 11, Processor 12th Gen Intel(R) Core(TM) i7-12700H 2.70 GHz
Architecture 64-Bit, 32 GB Ram
Configuration
LPub3D installation path
Windows: C:\Program Files\LPub3D_246

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

Cheers,

**Comment by ErfinderDesRades** [comment]
Great. Again thanks a lot

**Comment by trevorsandy** [comment]
With pleasure.

I've also updated the context help to better explain the part element behaviour. 

![Screenshot - 27_01_2023 , 07_15_08](https://user-images.githubusercontent.com/13388970/215032892-b61d9d89-5f61-4b09-b6f0-365c13381409.png)

Cheers,

**Comment by ErfinderDesRades** [comment]
Hi again,

just a little update: BOM is working fine, exactly as I wanted to.

I would really like to support this project. Is there a possibility to make a donation or something like that?

Regards from sunny Bremen
Andreas


Von: Trevor SANDY ***@***.***>
Gesendet: Freitag, 27. Januar 2023 08:37
An: trevorsandy/lpub3d ***@***.***>
Cc: Andreas Hinz ***@***.***>; Author ***@***.***>
Betreff: Re: [trevorsandy/lpub3d] Part IDs missing in BOM (Issue #680)


With pleasure.

I've also updated the context help to better explain the part element behaviour.

[Das Bild wurde vom Absender entfernt. Screenshot - 27_01_2023 , 07_15_08]<https://user-images.githubusercontent.com/13388970/215032892-b61d9d89-5f61-4b09-b6f0-365c13381409.png>

Cheers,
