### ISSUE TITLE
Sub models are deleted

### ISSUE THREAD

**Issue by technicbasics** [trevorsandy/lpub3d#684]
Just tested something, it looks like it works.
But I currently only have the problem, when LPub crashes with the native renderer, that some submodels are deleted. Mostly those that contain Buffer Exchange commands, but also others.
It seems that the problem is also with the LDView renderer.

_Originally posted by @technicbasics in https://github.com/trevorsandy/lpub3d/issues/664#issuecomment-1407391982_

Tested a little more.
Not the buffer exchange is the problem.
Sub models that contains flex parts (hoses, electric cable, ..) generated with LDCad are deleted after editing and saving the instruction.

**Comment by forelockmocs** [comment]
I have the same problem with flexible parts!

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

Can you provide an example model file that produces this behaviour ?

Cheers,

**Comment by technicbasics** [comment]
Hi Trevor
Can you send me a Mail to "info (at) j-e.at", so that I can send you the file in private.
Regards

**Comment by technicbasics** [comment]
I wanted to upload a test file here now, however .mpd is not supported. Therefore I have sent the file to the mail address that is stored in the credits of Lpup3D. I hope the file arrived, because there are always problems with the delivery to .gmail addresses from my email program.

**Comment by trevorsandy** [comment]
Hi Johann,

> I wanted to upload a test file here now

Simply archive (zip) the file and attach it.

Cheers,

**Comment by technicbasics** [comment]
[Seilwinde.zip](https://github.com/trevorsandy/lpub3d/files/10717268/Seilwinde.zip)
 Hi Trevor
I could have come up with this solution too...I just say ...DAU

**Comment by forelockmocs** [comment]
Hello Trevor,

I will, but I have to finish the current instructions first. For that I went back to the last version that was stable enough for me:
[cid:7bb38450-0482-4f85-8a1c-79d059441247]

When I have finished I will clean up the folder and make a zip-file. Will the files I sent be available for everyone? Or is my reply to this email just for you?

Greetz,
Ron Hebben
________________________________
Van: Trevor SANDY ***@***.***>
Verzonden: zondag 12 februari 2023 14:04
Aan: trevorsandy/lpub3d ***@***.***>
CC: forelockmocs ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [trevorsandy/lpub3d] Sub models are deleted (Issue #684)


Thank you for reporting this behaviour.

Can you provide an example model file that produces this behaviour ?

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

Cheers,
