### ISSUE TITLE
Wrong message in dialog box

### ISSUE THREAD

**Issue by technicbasics** [trevorsandy/lpub3d#701]
### Subject
After editing the code in the Command Editor and click the "Update" button, the message in the question dialog is wrong.
However, this has nothing to do with the functionality of the program, it is just a cosmetic thing.
Dialog box in r106:
![2023-04-10 09_24_50-Pistenbully 600 Polar mpd - LPub3D v2 4 6 r106 (Dev-release)](https://user-images.githubusercontent.com/49073781/230850897-497ce6b9-cb66-453a-906f-bbeb29557464.png)

Dialog box in r131:
![2023-04-09 17_38_38-Pistenbully 600 Polar mpd - LPub3D v2 4 6 r131 (Release)](https://user-images.githubusercontent.com/49073781/230850975-b9b7f7e7-155e-4cc0-ac2c-00b9211b09d1.png)

The new code generated here, which should display the number of pages, is always set to "0".

### Environment
* Version of LPub3D - 2.4.6r131
* Operating system - Windows 11, Home Edition 64bit
* Processor 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz 2.50 GHz
* RAM 16,0 GB
* Grafik NVIDIA RTX 3600, 6GB

### Steps to reproduce
Edit the file code in the command editor and click the "Update" button

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

Indeed, I did not account for page updates in the last 'prompt to cycle pages on jump ahead' commit,

This behaviour has been corrected and will be available in the next build release.

Cheers,
