### ISSUE TITLE
PLI windows are misaligned in Multi Step pages

### ISSUE THREAD

**Issue by technicbasics** [trevorsandy/lpub3d#703]
### Subject
Up to version 2.4.6.r57 the alignment still works correctly for Multi Step pages.
As of version 2.4.6r94, the part windows are always aligned to the associated step and no longer from the widest step.
Between versions from r57 to r94 I could not test, because I did not download them.

### Screenshots
2.4.6r57
![2023-04-18 19_58_33-Pistenbully 600 Polar V1 mpd - LPub3D v2 4 6 r57 (Dev-release)](https://user-images.githubusercontent.com/49073781/232866054-260b9038-3a85-432e-9bc4-438002fec317.png)

2.4.6r94
![2023-04-18 19_56_56-Pistenbully 600 Polar V1 mpd - LPub3D v2 4 6 r94 (Dev-release)](https://user-images.githubusercontent.com/49073781/232866149-2d86e8e2-604d-428a-85f6-6e547ddd2933.png)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

I've completed the correction which will be available in the next DevOps release.

![PLI_Misaligned](https://user-images.githubusercontent.com/13388970/233203027-dc64a2d9-f5b0-4100-9244-7c81448371cb.png)

Cheers,

**Comment by technicbasics** [comment]
Thanks!
