### ISSUE TITLE
Wrong step number in Callouts

### ISSUE THREAD

**Issue by technicbasics** [trevorsandy/lpub3d#705]
### Subject
After adding a "0 !LPUB NOSTEP" command in a callout of a submodel,  the step number show "-1".
Here is a picture with a callout with "NOSTEP" (left), and one without. (right)
![2023-04-20 21_55_55-](https://user-images.githubusercontent.com/49073781/233476676-3ab45342-1239-4086-b3b4-7bc44c54539b.png)

Another problem is, if a "0 !LPUB NOSTEP" command is in a submodel, an you want to convert it in a callout,
LPub3D crash. 
This may be associated with this error message if you use the command in combination with a buffer exchange as I like to do.
See Command window in the picture above.

![2023-04-20 22_05_18-LPub3D LPub Meta Command](https://user-images.githubusercontent.com/49073781/233476622-8d6fc762-3c3f-4515-9c05-f99e1e5174cb.png)

### Environment
* Version of LPub3D - 2.4.6r166

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

FYI, there are several significant updates (some in progress) in the latest DevOps build. 

Was this behaviour present before the DevOps r166 release ?

Cheers,

**Comment by technicbasics** [comment]
Hi TrevorNo, just since r166Am 21.04.23, 04:15 schrieb Trevor SANDY ***@***.***>:

   
  Thank you for reporting this behaviour. 
  FYI, there are several significant updates (some in progress) in the latest DevOps build. 
  Was this behaviour present before the DevOps r166 release ? 
  Cheers,

**Comment by technicbasics** [comment]
Addendum: Only the step number problem has been present since r166. The NOSTEP problem was also present earlier.

**Comment by trevorsandy** [comment]
> After adding a "0 !LPUB NOSTEP" command in a callout of a submodel, the step number show "-1".

This behaviour has been corrected.

![CalloutPageNumber](https://user-images.githubusercontent.com/13388970/233649045-457c8d61-8353-4baf-9559-6d59724fb91b.png)

> Another problem is, if a "0 !LPUB NOSTEP" command is in a submodel, and you want to convert it in a callout, LPub3D crash.

If this is a bug, it will have its own ticket.

Cheers,
