### ISSUE TITLE
Load last opened file on startup not working

### ISSUE THREAD

**Issue by Dark-Noir** [trevorsandy/lpub3d#713]
### Subject
Load last opened file on startup feature no longer working.
Last working version [2.4.4](https://github.com/trevorsandy/lpub3d/releases/tag/v2.4.4).

### Environment
* Version of LPub3D: 3255 (2.4.6-r144) (fresh *.zip version)
* Operating system: Windows 10 22H2 x64

### Configuration
* Installation path
  - Windows: C:\Users\Darkestnoir\Desktop\Programme\LPub3D
* Configuration
  - Windows (portable): [LPub3D.txt](https://github.com/trevorsandy/lpub3d/files/11525807/LPub3D.txt) (renamed to *.txt)

### Logs
- [LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/11525806/LPub3DLog.txt)

### Screenshots
![grafik](https://github.com/trevorsandy/lpub3d/assets/8070059/561b4a1a-80b0-4a84-b0f1-45c806b52f3b)

### Preconditions
1. Fresh *.zip extracted

### Steps to reproduce
1. Start LPub3D.exe
2. Select your LDraw lib
3. Open a *.ldr file
4. Go to "Configuration -> Preferences"
5. Check "Load Last Opened File On Startup"
6. Close the menu with "OK"
7. Exit the LPub3D
8. Start LPub3D.exe again

### Expected behavior
- The last used *.ldr file is loaded

### Actual behavior
- A error message appears
- The last used *.ldr file is not loaded

### Workaround
Use a older version, last working one [2.4.4](https://github.com/trevorsandy/lpub3d/releases/tag/v2.4.4).

### Solution suggestion
Fix it ^^

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

This behaviour has been corrected.

Cheers,
