### ISSUE TITLE
Crash during globally rescaling the assembly image

### ISSUE THREAD

**Issue by Dark-Noir** [trevorsandy/lpub3d#714]
### Subject
Crash during globally rescaling the assembly image, only happens once, but to be honest, LPub3D crashes at many cases, this is just one of them. 
Please improve the stability of LPub3D 🙏 
When you want more crash dumps for other crashes, like when trying to add another step to the same page, just ask (but i hate to created dozens of tickets when no interest is there ^^).

### Environment
* Version of LPub3D: 3255 (2.4.6-r144) (fresh *.zip version)
* Operating system: Windows 10 22H2 x64

### Configuration
* Installation path
  - Windows: C:\Users\Darkestnoir\Desktop\Programme\LPub3D
* Configuration
  - Windows (portable): [LPub3D.txt](https://github.com/trevorsandy/lpub3d/files/11525866/LPub3D.txt) (renamed to *.txt)

### Logs
- [LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/11525868/LPub3DLog.txt)

### Dump
- [LPub3D.exe.5992.zip](https://github.com/trevorsandy/lpub3d/files/11525880/LPub3D.exe.5992.zip)

### Steps to reproduce
1. Start LPub3D.exe
2. Select your LDraw lib
3. Open a *.ldr file
4. Go to "Configuration -> Building instructions Setup... -> Assembly Setup..."
5. Set the "Scale" to "0,60"
6. Close the menu with "OK"

### Expected behavior
- The assembly get globally rescaled

### Actual behavior
- LPub3D crashes

### Workaround
Restart and try again...

### Solution suggestion
Fix it ^^

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

I was not able to reproduce this behaviour on v2.4.6-r144 or the latest [DevOps](https://github.com/trevorsandy/lpub3d-ci/releases/tag/continuous) build.

Using your configuration settings:

![Crash714_A](https://github.com/trevorsandy/lpub3d/assets/13388970/c5b617e7-0449-4438-b4dc-7bb52a485604)

My behaviour from a clean portable distribution install were as expected.

![Crash714](https://github.com/trevorsandy/lpub3d/assets/13388970/2e03635e-1c2c-46ef-a82a-a6db37031dfd)

Cheers,

**Comment by Dark-Noir** [comment]
I get many crashes here and there, not really good to reproduce at the same step.
So i can just send dump files for you to check and fix it.
I working on a ~1500 pages large instruction, maybe its just too much for the program.

**Comment by trevorsandy** [comment]
> I get many crashes here and there... I can just send dump files for you to check and fix it.

The dump file seems to suggest you are exceeding your memory capacity.

Some helpful tips:
- In LPub3D Preferences, set _Show Load Status_ to _Always_ to see any anomalies on model file load
- Turn off high-overhead features like fade and highlight while formatting your model
- Break your model into multiple _books_

Cheers,

**Comment by Dark-Noir** [comment]
> The dump file seems to suggest you are exceeding your memory capacity.
I got 64GB of RAM, if LPub3D can fill it, then there is probably a memory leak 😅 

> Some helpful tips:
> 
>     * In LPub3D Preferences, set _Show Load Status_ to _Always_ to see any anomalies on model file load
> 
>     * Turn off high-overhead features like fade and highlight while formatting your model
>  
>     * Break your model into multiple _books_
Good ideas ty ^^
