### ISSUE TITLE
Part list annotation style gets resetted

### ISSUE THREAD

**Issue by Dark-Noir** [trevorsandy/lpub3d#716]
### Subject
Parts list annotations style can be changed, but it is not applied and is resetted, after re-opening the preferences.

### Environment
* Version of LPub3D: 3255 (2.4.6-r144) (fresh *.zip version)
* Operating system: Windows 10 22H2 x64

### Configuration
* Installation path
  - Windows: C:\Users\Darkestnoir\Desktop\Programme\LPub3D
* Configuration
  - Windows (portable): [LPub3D.txt](https://github.com/trevorsandy/lpub3d/files/11525938/LPub3D.txt) (renamed to *.txt)

### Logs
- [LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/11525939/LPub3DLog.txt)

### Screenshots
- ![grafik](https://github.com/trevorsandy/lpub3d/assets/8070059/97a6e384-0b75-42f2-aa2c-b0a3665628c1)
- ![grafik](https://github.com/trevorsandy/lpub3d/assets/8070059/e489b230-5bb1-457c-988a-d481ab4fdfe2)

### Preconditions
1. Fresh *.zip extracted

### Steps to reproduce
1. Start LPub3D.exe
2. Select your LDraw lib
3. Open a *.ldr file
4. Go to "Configuration -> Building instructions Setup... -> Parts List Setup... -> Annotations"
5. Check "Display Part List (PLI) Annotation From Source"
6. Go to "Styles" sub menu
7. Change the "Style" to anything else than "None"
8. Close the menu with "OK"

### Expected behavior
- The settings is applied
- The PLI annotation style is changed

### Actual behavior
- The setting gets resetted to "None"
- The PLI annotation style is not changed

### Additional info
It is also not possible to change the part annotation border directly by selecting it, the drop down element resets every time (see screenshot 2).

### Workaround
None found

### Solution suggestion
Fix ^^

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

The functionality is not designed to behave as you have described.

> 7.  Change the "Style" to anything else than "None"

Performing this action will not _Change_ the selected style. As stated in the label - _Select Style to Edit_, your selection will simply _enable_ the specified style so you can perform your changes to that style. If no changes are made  (step 8. above), nothing will be applied. You can click the _WhatsThis Help_ - the _?_ at the top right of the dialogue window - and then click the respective dialogue item to display details as shown in the first screenshot below.

> It is also not possible to change the part annotation border directly by selecting it, the drop down element resets every time (see screenshot 2).

If your above remark pertains to using the annotation context (right-click) menu, it is should be noted that modifying a meta command from the context menu will not create a `GLOBAL` command. Having said that. I was not able to reproduce the behaviour you described on v2.4.6-r144 or the latest [DevOps](https://github.com/trevorsandy/lpub3d-ci/releases/tag/continuous) build.

For me the behaviour is as expected:

Using _WhatsThis_ Help
![Annotation716_A](https://github.com/trevorsandy/lpub3d/assets/13388970/5c2d3bac-725e-496b-9842-af4ff153dd4c)

Enable _Square_ style and change the border colour
![Annotation716_B](https://github.com/trevorsandy/lpub3d/assets/13388970/0cef2738-0148-4b6b-a5d1-1b19eb93e621)
![Annotation716_C](https://github.com/trevorsandy/lpub3d/assets/13388970/3b52e324-b951-4c59-81d0-d238211f6e45)

The changed colour is applied to the PLI and also persists as you can see when the setup dialogue is reopened.
![Annotation716_D](https://github.com/trevorsandy/lpub3d/assets/13388970/9d873120-a75a-43e4-885f-093c796fcea4)

Change the `LOCAL` border colour using the annotation context menu
![Annotation716_E](https://github.com/trevorsandy/lpub3d/assets/13388970/d0ec8f5d-dbc3-4562-b2db-4733273a7daf)
![Annotation716_F](https://github.com/trevorsandy/lpub3d/assets/13388970/6608f6aa-c0cc-49e9-850e-51a740515133)
![Annotation716_G](https://github.com/trevorsandy/lpub3d/assets/13388970/eb64718e-073b-46f3-b251-c8e4cc69c4cc)

The new `LOCAL` border colour is persisted as you can see when you reopen the annotation context menu.
![Annotation716_H](https://github.com/trevorsandy/lpub3d/assets/13388970/856adf79-0c96-4783-bb86-32b0c73f34a9)

However, the `GLOBAL` border colour is not changed as you can see when you reopen the Parts List Setup dialogue.
![Annotation716_I](https://github.com/trevorsandy/lpub3d/assets/13388970/9205cdda-e233-4e9c-8c6f-6672e838a714)

Cheers,

**Comment by trevorsandy** [comment]
Addendum: _Build Instruction Setup_ menu item meta command data is sensitive to the currently loaded step. For example, if your currently loaded page is a multi-step page, meta command changes will be applied to the `MULTI_STEP` instance of the meta command - if the command has a unique instance for `MULTI_STEP`, `CALLOUT` etc... Meta commands that only have a single `!LPUB` instance are not affected.

To illustrate, if you are currently on a multi-step page and you change the assembly model scale to 0.9, the affected meta command is `0 !LPUB MULTI_STEP ASSEM MODEL_SCALE GLOBAL  0.9000`. However if you are on a single-step page, the affected meta command will be `0 !LPUB ASSEM MODEL_SCALE GLOBAL  0.9000`. 

Cheers,
