### ISSUE TITLE
Native Render - different viewing angle being used between sub-model and main model

### ISSUE THREAD

**Issue by d-j-m-0** [trevorsandy/lpub3d#718]
### Subject
When using the Native renderer, the images generated for the sub-model appear to be being created using a different viewing angle than when the sub-model image is then displayed in the main image. The same issue does not occur when using LDView to render the images.

### Environment
* Version of LPub3D - Release 2.4.6 revision 294 build 3405
* Operating system - Windows 10, x86_64

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  - Windows: "D:\Program Files\LPub3D"
* Application data path
  - Windows: `%USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\`
* Registry Extract
  - Windows (installed): (attached, with file suffix renamed to "log")
* Renderer configuration files
Available within attached zip file.

### Logs
* Application Log: Available within attached zip file.
* Renderer Log: Available within attached zip file.
* Renderer Log: Available within attached zip file.
* Renderer Log: Available within attached zip file.
* Renderer Log: Available within attached zip file.

### Screenshots; Available within attached zip file.
* Configuration->Preferences->General
* Configuration->Preferences->Rendering
* Configuration->Preferences->Publishing
* Configuration->Preferences->Logging
* Configuration->Preferences->Other

### Steps to reproduce
Open the mpd contained in the attached zip file.
Navigate through the instructions page by page.
Compare the image on the second last page with that on the last page.

### Expected behaviour
When using the Native renderer, the same viewing angle should be used for the final step of the sub-model as when the sub-model appears in the instructions.

### Actual behaviour
The viewing angle differs. The attached images illustrate the angle is different.

![lpub3d_viewing_angle_150_DPI_page_7](https://github.com/trevorsandy/lpub3d/assets/37604323/1d688650-ed2b-49a7-8300-e3f4f33c8703)

![lpub3d_viewing_angle_150_DPI_page_8](https://github.com/trevorsandy/lpub3d/assets/37604323/d889bb5f-2514-47a7-823c-5577b28a78ed)

### Workaround
None known.

### Solution suggestion
N/A

Zip file:
[lpub3d_20230603.zip](https://github.com/trevorsandy/lpub3d/files/11640223/lpub3d_20230603.zip)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

![RotateParts_01](https://github.com/trevorsandy/lpub3d/assets/13388970/620a6638-d7d5-482c-8932-7f331d82e389)

![RotateParts_02](https://github.com/trevorsandy/lpub3d/assets/13388970/e47a19ed-d27b-4289-a1e5-f758c41724ec)

![RotateParts_03](https://github.com/trevorsandy/lpub3d/assets/13388970/7ad88c4c-040a-429d-80a3-a62dc38e34b6)

Cheers,
