### ISSUE TITLE
Callout placement for multi-step is not placed inside assem. Works correctly for non-multi-step.

### ISSUE THREAD

**Issue by d-j-m-0** [trevorsandy/lpub3d#720]
### Subject
When a callout is used on a multi-step, the image for the callout cannot be placed inside the assembly's "area" despite the option being available.

### Environment
* Version of LPub3D -  Release 2.4.6 Revision 294 Build 3405
* Operating system - Windows 10, x86_64

### Steps to reproduce
Open the model within the attached zip file. The first page is defined as a multi-step. Right mouse click on the callout, select "Change callout placement" context menu item, pick (a) Relative to Assem and (b) Bottom/Right. Click Ok. Callout is placed outside of the assembly's image area despite being instructed to place in within the assembly image area..

On page 2 (non-multi-step), repeat the same process. Callout is placed within the assembly's image area (as expected).

![multi_step_callout_placement](https://github.com/trevorsandy/lpub3d/assets/37604323/ea61882e-bd50-4be8-97ac-7423f2e1da90)

![multi_step_not_inside](https://github.com/trevorsandy/lpub3d/assets/37604323/6a9a653d-0395-45b2-ac22-9f06e6a3618f)

![not_multi_step_is_inside](https://github.com/trevorsandy/lpub3d/assets/37604323/ba65fb7a-6850-4e15-847c-c5d13f7535bd)

### Expected behaviour
Callout should appear within the assembly's image area for the step when using a multi-step.

### Actual behaviour
Callout appears outside of the assembly's image area.

### Workaround
None known. Dragging the callout to within the area still has LPub3D thinking the image extends to the right (or below) the assembly's image area, making the step wider or taller than it actually is.

### Solution suggestion
Allow the callout to be placed within the assembly's image area. The width/height of the step should then exclude the callout area except where it extends beyond the boundary of the assembly image area.

[callout_multi_step.zip](https://github.com/trevorsandy/lpub3d/files/11687152/callout_multi_step.zip)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour - another good catch! 

This behaviour has been corrected. Like #719, this was present since legacy LPub.

![CalloutPlacement_00_720](https://github.com/trevorsandy/lpub3d/assets/13388970/bc51fd06-2744-4057-aea2-463bdd8dc954)

![CalloutPlacement_01_720](https://github.com/trevorsandy/lpub3d/assets/13388970/efae3af7-4339-4046-881d-64080ba1be39)

![CalloutPlacement_02_720](https://github.com/trevorsandy/lpub3d/assets/13388970/992c8cd7-3d5a-45e7-a484-2e49125f16ff)

Cheers,
