### ISSUE TITLE
Multi-level inherited colour seems to have lost assembly count in v2.4.6 r322

### ISSUE THREAD

**Issue by d-j-m-0** [trevorsandy/lpub3d#723]
### Subject
The addition of inherited colour consideration to add multiple instances to the instructions seems to have impacted the counting of the sub-assemblies.

In version 2.3.4 r294 the sub-assembly count was correct. In version 2.4.6 r322, the assembly sub-count when there are multiple levels of passing the inherited colour appears to result in a loss of the correct count.

Release r294:
<img width="742" alt="r294" src="https://github.com/trevorsandy/lpub3d/assets/37604323/b98a0243-90b5-48df-83db-635c202968d8">

Release r322:
<img width="741" alt="r322" src="https://github.com/trevorsandy/lpub3d/assets/37604323/da563db4-17f1-42aa-a062-0c1f374ce3ac">

### Environment
* Version of LPub3D -2.4.6 r322
* Operating system - Windows 10, x86_64

### Steps to reproduce
The attached zip file contains a sample mpd. There are also two PDFs in the zip file generated from the mpd. One PDF is generated with v2.4.6 r294 and the other with v2.4.6 r322.

Try generating the PDF for the mpd and see the results.

### Expected behaviour
The sub-assembly count in using  v2.4.6 r322 should be the same as that when using v2.4.6 r294.

### Actual behaviour
The count sometimes seems to be 1 and sometimes 0!

### Workaround
None known.

### Solution suggestion
I wonder if this has something to do with multiple levels of colour inheritance. When there is a single level of inheritance, the sub-assembly counts seem to be correct.

[inherited_multi_level.zip](https://github.com/trevorsandy/lpub3d/files/11742500/inherited_multi_level.zip)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

Indeed. I noticed this item after pushing r324. As I'm treating some discovered regressions, I've yet to push the correction.

The following lines should be:

```cpp
if (!countByColour || argv[1] == LDRAW_MAIN_MATERIAL_COLOUR)
```

https://github.com/trevorsandy/lpub3d/blob/f161acba78c4a1045cfddb9183c244aaa1feff52/mainApp/metaitem.cpp#L350

https://github.com/trevorsandy/lpub3d/blob/f161acba78c4a1045cfddb9183c244aaa1feff52/mainApp/metaitem.cpp#L443

Behaviour with correction.
![inherited_multi-level](https://github.com/trevorsandy/lpub3d/assets/13388970/12555059-331a-49d6-8118-12cb8d7d2410)

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

Cheers,
