### ISSUE TITLE
Assembly image viewing angle incorrect when LDView is used to render

### ISSUE THREAD

**Issue by d-j-m-0** [trevorsandy/lpub3d#725]
### Subject
When the Native renderer is used and a ROTSTEP applied, the rendered assembly images align with the ROTSTEP command.
Page 1:
![r246_r354_p1_native](https://github.com/trevorsandy/lpub3d/assets/37604323/017406a3-3024-450f-bfb8-76a5fe491a36)

Page 2:
![r246_r354_p2_native](https://github.com/trevorsandy/lpub3d/assets/37604323/9a5044e8-fcd5-46c2-9b17-b0074d6f91fe)

When the renderer is set to LDView, although the standard STEP command is rendered as expected.
Page 1:
![r246_r354_p1_ldview](https://github.com/trevorsandy/lpub3d/assets/37604323/94b72b9d-2dbf-4713-8bdb-a6c81b6bb158)

The image generated for the ROTSTEP is incorrect:.
Page 2:
![r246_r354_p2_ldview](https://github.com/trevorsandy/lpub3d/assets/37604323/3df7416f-4d16-4a66-8c3c-9cc722b13b61)

### Environment
* Version of LPub3D - r246 v354
* Operating system - Windows 10, x86_64

### Configuration
* Renderer configuration files
  - `[Application data path]/ldv/ldvExport.ini`
  - `[Application data path]/3rdParty/ldview-4.5/config/ldview.ini`
  - `[Application data path]/3rdParty/ldview-4.5/config/ldviewPOV.ini`
Contained in the attached zip file.

### Screenshots
* Configuration->Preferences->General
![preferences_general](https://github.com/trevorsandy/lpub3d/assets/37604323/159d23c2-649f-40e2-8eb6-8c44a3763595)

* Configuration->Preferences->Rendering
![preferences_renderers](https://github.com/trevorsandy/lpub3d/assets/37604323/4224a32f-5408-433e-bde5-388f388af8b6)

### Steps to reproduce
In LPub3D, set the renderer to Native.
Open the mpd found within the attached zip.
Navigate to page 2.
Close the mpd file.
Set the render to LDView,
Open the mpd file.
Navigate to page 2.

### Expected behaviour
The image generated when using LDView would be taken from a similar viewpoint as that when using the native renderer.

### Actual behaviour
The LDView assembly image is generated from side on rather than the elevated position.

### Workaround
USe the Native renderer instead of LDView.

### Solution suggestion
None known.

Zip file:

[rotation.zip](https://github.com/trevorsandy/lpub3d/files/11787070/rotation.zip)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

Indeed. It looks like I broke this in #718, but it is now corrected. 

The correction will be in the next release build. 

Cheers,
