### ISSUE TITLE
Abnormal rendering behavior (Native renderer)

### ISSUE THREAD

**Issue by technicbasics** [trevorsandy/lpub3d#726]
### Subject
If motors are installed on one side, the renderer has an abnormal behavior.
Both the motors and the rest of the model are no longer rendered correctly.
If the model is used as a sub-model, the model is rendered abnormally when assembled, but it is rendered correctly in the main model.
This behavior occurs with L, XL and servo motors. M motors are displayed correctly.
I have already tried different library versions without success.
Tested versions:
2.4.7
2.4.6r363, r352, r324, r306, r252
The behavior varies depending on the version.
Up to version r252 everything works correctly.
Here are some pictures.
I tested the behavior with the submodels with the Pistenbully file in the cloud.

### Environment
* Version of LPub3D - see above

### Operating system
* Windows 11, Home Edition 64bit
* Processor 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz 2.50 GHz
* RAM 16,0 GB
* Grafik NVIDIA RTX 3600, 6GB

![2 4 6r252](https://github.com/trevorsandy/lpub3d/assets/49073781/2bf1817f-2e76-4005-8bab-b91c48183c24)

![2 4 6r306](https://github.com/trevorsandy/lpub3d/assets/49073781/8b522352-5060-4485-8db3-64f6e2d57b38)

![2 4 7r0](https://github.com/trevorsandy/lpub3d/assets/49073781/2ab1f614-9700-47fa-afa0-538a6fdf5368)

![2 4 6_r363](https://github.com/trevorsandy/lpub3d/assets/49073781/6bdbd81c-7078-4438-be8d-bff3e3dbab11)

![2 4 6_r190](https://github.com/trevorsandy/lpub3d/assets/49073781/151bc3d8-1daf-4221-94bf-8049cec78394)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

I will take a look.

The problem seems to be in the cabling and cable connectors. Could you also provide the _motoren.mpd_ example model file used in the first 2 images ?

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

This was a regression caused by #718.

![AbnormalRender_01](https://github.com/trevorsandy/lpub3d/assets/13388970/ed8289e9-e55e-427a-bd76-9fd7c63ee65b)

Cheers,

**Comment by technicbasics** [comment]
Many thanks!
