### ISSUE TITLE
Step Number Placement Relative to Parts List Produces Undesired Behavior when Selecting Bottom/Left (Multistep Only)

### ISSUE THREAD

**Issue by M-Volkmuth** [trevorsandy/lpub3d#729]
### Subject
Step Number Placement Relative to Parts List Produces Undesired Behavior when Selecting Bottom/Left (Multistep Only),
More specifically, The Step Number sinks to the bottom of the Step rather than just below the PLI as expected.

### Environment
* Version of LPub3D - Release 2.4.7 Revision 5 Build 3481
* Operating system - Windows 10 x64

### Screenshots
(Note: Screenshots are from release 2.4.6, but problem persists in latest version.)

![LPubBug2](https://github.com/trevorsandy/lpub3d/assets/41386894/81869744-f567-4289-9ee4-03054e0a7b0b)

![LPubBug3](https://github.com/trevorsandy/lpub3d/assets/41386894/81d01850-9f52-49e0-90ce-356bc4cb77c6)

### Steps to reproduce
Download [Sample.txt](https://github.com/trevorsandy/lpub3d/files/11860025/Sample.txt)
Change file extension to .mpd
Load in LPub3D

### Expected behaviour
The Step Number for each step in the multistep should render just below the PLI.

### Actual behaviour
The Step Number for each step in the multistep sinks to the bottom of the Step.

### Workaround
Nothing practical. I would not like to resort to manually inserting step number text and masking the actual step numbers with the background color.

### Solution suggestion
Is there a bug in calculating the Y placement coordinate in the context of multisteps?

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

I'll take a look.

Cheers,

**Comment by M-Volkmuth** [comment]
Thanks for the update. Just checked it out.
I discovered that the problem persists if you add a Multistep divider.

**Comment by trevorsandy** [comment]
> I discovered that the problem persists if you add a Multistep divider.

Indeed. That the step number is aligned with the bottom of the tallest PLI in the divided range (multi-step row) is the default behaviour as shown in the following screenshot. As this behaviour is desired by some, it will remain in place.

![StepNumberPlacement_00](https://github.com/trevorsandy/lpub3d/assets/13388970/dcc98b33-5a18-45f6-8d5d-1c6023e8525b)

However, you can enable the behaviour you desire by manually adding the meta command `0 !LPUB MULTI_STEP JUSTIFY_Y_AXIS_OUTSIDE_PLACEMENT_MULTIPLE_RANGES GLOBAL TRUE` or from the Step Group Global Setup dialogue as shown in the following screenshot.

![StepNumberPlacement_01](https://github.com/trevorsandy/lpub3d/assets/13388970/cb7dbb82-763c-4b22-9565-3b6228048363)

![StepNumberPlacement_02](https://github.com/trevorsandy/lpub3d/assets/13388970/983700d5-3c42-4db4-aab9-89080f182ed3)

Cheers,
