### ISSUE TITLE
Native renderer scrambles submodel when using ignore section after dat files

### ISSUE THREAD

**Issue by snakebyte73** [trevorsandy/lpub3d#732]
### Subject
When using 0 !LPUB PART BEGIN IGN in a step after a submodel, the render looks very strange.
This behaviour is only when using the native renderer.
LDCad view:
![billede](https://github.com/trevorsandy/lpub3d/assets/38093610/21588b1d-e23c-4759-82a8-fd2e59ea78fb)
Wrong render:
![billede](https://github.com/trevorsandy/lpub3d/assets/38093610/8a7dc2ea-bd2a-419d-af37-ce1b659fe225)

If I move the submodel down below the ignore part everyting looks correct
LDCad view:
![billede](https://github.com/trevorsandy/lpub3d/assets/38093610/cd326ece-f71e-44b5-831f-ac0d9f025a27)
Correct render:
![billede](https://github.com/trevorsandy/lpub3d/assets/38093610/43b2b782-ad71-44d2-9ce5-f26d035448cb)

### Environment
* Version of LPub3D: 2.4.7 Rev. 5 Build 3481
* Operating system: Windows 11, X64

### Configuration
* LPub3D installation path
  - Windows: `C:\Program Files\LPub3D` [x86_64]
* Application data path
  - Windows: `%USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\`
* Registry Extract
  - Windows (installed): 
 [LPub3D.zip](https://github.com/trevorsandy/lpub3d/files/11878490/LPub3D.zip)

* Renderer configuration files
![billede](https://github.com/trevorsandy/lpub3d/assets/38093610/6c826d83-b6eb-4b72-8d5b-d354a0c81715)

### Logs
* Application Log: `[Application data path]/logs/LPub3DLog.txt`
[LPub3DLog.zip](https://github.com/trevorsandy/lpub3d/files/11878510/LPub3DLog.zip)

### Screenshots
* Configuration->Preferences->General
* Configuration->Preferences->Rendering
* Configuration->Preferences->Publishing
* Configuration->Preferences->Logging
* Configuration->Preferences->Other

![billede](https://github.com/trevorsandy/lpub3d/assets/38093610/a792e218-61c7-415d-b589-9aa53483b78f)
![billede](https://github.com/trevorsandy/lpub3d/assets/38093610/f543c325-36b7-4140-932f-42252171819b)
![billede](https://github.com/trevorsandy/lpub3d/assets/38093610/a2c61d30-b703-47e9-8246-f1ab9c807b40)
![billede](https://github.com/trevorsandy/lpub3d/assets/38093610/9bba9ec5-f27e-4ebd-a3f2-e7faab4a44a4)
![billede](https://github.com/trevorsandy/lpub3d/assets/38093610/84487f1b-bdf0-46d6-b6a8-be1a091c606c)

[TestProject 3D.zip](https://github.com/trevorsandy/lpub3d/files/11881072/TestProject.3D.zip)

### Steps to reproduce
Tell me how to reproduce this issue.
add an ignore section with a <part>.dat after adding a <part>.dat in the same step. (see screenshots)

### Expected behaviour
The render should look normal

### Actual behaviour
The Native render does something strange

### Workaround
Put the ignore section as the first thing in the step

### Solution suggestion
Share your opinion on how to achieve the expected behaviour

**Comment by snakebyte73** [comment]
I forgot to remove the custom parts from the sample file, but the error is the same..

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

![NativeRendererScrambledSubfile_01](https://github.com/trevorsandy/lpub3d/assets/13388970/3e8f8913-4d74-4344-9b23-7eb8cc4cc0ba)

Cheers,
