### ISSUE TITLE
Global Page Orientation and page background image within include file not always applied

### ISSUE THREAD

**Issue by d-j-m-0** [trevorsandy/lpub3d#735]
### Subject
I have an include file which contains common LPub3D settings applicable to my instructions. The page orientation and page background image are defined within the common file. Although they are being applied to sub-model pages, the main assembly page is not applying the values.

Screenshots:
Page 1 - Landscape orientation and background image applied to sub-model as expected.
![page_1](https://github.com/trevorsandy/lpub3d/assets/37604323/12879f0b-fbad-401d-b144-a3a909c9a31a)

Confirmation of Page Global set-up values:
![page_1_page_globals_setup](https://github.com/trevorsandy/lpub3d/assets/37604323/a573d0cd-ec62-4192-9107-3bb8248a92c9)

Page 2 - Same setting applied:
![page_2](https://github.com/trevorsandy/lpub3d/assets/37604323/85ab4d76-1e1e-48b1-8fc6-fc4a34f2bf08)

Page 3 - Orientation and background not applied:
![page_3](https://github.com/trevorsandy/lpub3d/assets/37604323/a342c735-ef85-465c-8f86-14e34af35ed3)

Page Global set-up values seem to have changed:
![page_3_page_globals_setup](https://github.com/trevorsandy/lpub3d/assets/37604323/56bb610a-322a-4ae3-98e8-e0eebc997722)

### Environment
* Version of LPub3D - 2.4.7 Revision 19 Build 3495
* Operating system - Windows 10, x86_64

### Steps to reproduce
The attached zip file contains the two LDraw files and the background image. Extract the files and open the file named avalanche_for_lpub3d in LPub3d. Navigate through each page to see the behaviour.

### Expected behaviour
The main assembly page should be using the global orientation and background values contained in the included common file.

### Actual behaviour
The page setting are being ignored/

[sample.zip](https://github.com/trevorsandy/lpub3d/files/11966410/sample.zip)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

This behaviour has been corrected.

![IncludeFile_01](https://github.com/trevorsandy/lpub3d/assets/13388970/4faf16eb-af34-4015-8e2c-568a9d4277c6)

Cheers,
