### ISSUE TITLE
LPUB won't start anymore (again)

### ISSUE THREAD

**Issue by ReneFrijhoff** [trevorsandy/lpub3d#736]
### Subject
LPUB won't start anymore again

### Environment
2.4.7.19.3495_20230703 (this had to be taken from the filename since LPUB won't start)
Windows 10 x64

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
 E:\Program Files\LPub3D

* Application data path
C:\Users\Rene\AppData\Local\LPub3D Software\LPub3D

* Registry Extract

 Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\LPub3D Software]

[HKEY_CURRENT_USER\SOFTWARE\LPub3D Software\LPub3D]

[HKEY_CURRENT_USER\SOFTWARE\LPub3D Software\LPub3D\Settings]
"LDrawDir"="E:\\LDraw"

### Steps to reproduce
It just won't start

### Expected behaviour
It should start

### Actual behaviour
It doesn't start

### Workaround
Not sure if there is one, maybe going back to a previous version?

### Solution suggestion
Don't know

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

Unfortunately, I am unable to reproduce this behaviour with the latest build - v2.4.7 r29.

If you continue to experience this behaviour on the latest release of LPub3D, you can try the following on Windows:

1. Open task manager and check for LPub3D. If found, select the toolbar action or context menu action to end the task and attempt to, once again, start LPub3D.

![AppWontStart_01](https://github.com/trevorsandy/lpub3d/assets/13388970/15da08d8-9f62-404f-8d17-f27247bec67c)

2. If you are still unable to launch the application, you can check the application configuration (for portable distribution - LPub3D.ini, for install distribution - see registry key above) and set the following key to _False_ : `LoadLastOpenedFile`.

3. If you are still unable to launch the application, download a new [portable distribution (.zip)](https://github.com/trevorsandy/lpub3d/releases/download/continuous/LPub3D_x86_64-2.4.7.29.3505_20230708.zip), extract it and attempt to start LPub3D.

If you continue to experience this behaviour on the latest release of LPub3D, do not hesitate to reopen this ticket.

If you are using a portable distribution, attach a copy of config\LPub3D Software\LPub3D.ini, if you are using an installed distribution, you can see above the registry keys you can export to provide the application configuration. Along with the configuration file, also attach a copy of your runtime log - logs\LPub3DLog.txt.

Cheers,

**Comment by ReneFrijhoff** [comment]
Even after unpacking LPub3D_x86_64-2.4.7.75.3551_20230905.zip, LPUB3D just won't run anymore. The key LoadLastOpenedFile in LPub3D.ini is by default false and no LPub3DLog.txt is created.
[LPub3D.txt](https://github.com/trevorsandy/lpub3d/files/12653146/LPub3D.txt)

**Comment by trevorsandy** [comment]
Thank you for the additional information.

The attached LPub3D.ini was not generated from a portable distribution (extracted .zip) of LPub3D. Instead, it looks like it was generated from an installed distribution (.exe). If you updated your installed distribution with the content of a portable distribution, you may be experiencing issues with user access permissions.

To rule out any permission issues, can you extract a portable distribution to your user folder (e.g. C:\Users\Rene\) and attempt to run the executable LPub3D.exe ?

If your run attempt is unsuccessful when you double-click the executable, try using the context-menu (right-click) to run the application as an Administrator.

> no LPub3DLog.txt is created

If your run attempt is still unsuccessful and no LPub3DLog.txt is generated, open a command console (cmd), change your current directory to the portable distribution LPub3D.exe location and run `LPub3D.exe > ..\runlog.txt 2>&1`.

Additionally, from the command console you can run `LPub3D.exe --version` or `LPub3D.exe --help` to check if LPub3D will successfully start.

Lastly, if your run attempt using your user command console is unsuccessful, try using an Administrator command console.

Cheers,
