### ISSUE TITLE
Submodels shown in BOM when using INSERT DISPLAY_MODEL

### ISSUE THREAD

**Issue by trevorsandy** [trevorsandy/lpub3d#739]
###  Subject
Submodels are shown as parts in the BOM when using `INSERT DISPLAY_MODEL` meta command.

### Environment
Version of LPub3D - 2.4.7
Operating system - All

### Expected behaviour
Submodels should not be present in the BOM.

### Actual behaviour
Submodels are present in the BOM

LPub3D - 2.4.7r52:
![Rock Crawler_300_DPI_page_2](https://github.com/trevorsandy/lpub3d/assets/49073781/495c631a-3317-4cb6-b307-a3e566412cf1)
![Rock Crawler_300_DPI_page_3](https://github.com/trevorsandy/lpub3d/assets/49073781/c6841a80-f8a8-47b4-8ee6-80d57af4683f)

LPub3D - 2.4.7r53 and 2.4.7r52
![2023-08-30 21_32_07-Rock Crawler ldr - LPub3D v2 4 7 r52 (Dev-release)](https://github.com/trevorsandy/lpub3d/assets/49073781/6aebb042-7804-4e07-9a67-63df12487a80)
![2023-08-30 21_32_48-Rock Crawler ldr - LPub3D v2 4 7 r52 (Dev-release)](https://github.com/trevorsandy/lpub3d/assets/49073781/c9e4a961-d802-4594-89df-f3fc337c9302)

### Solution
Fix it.

Cheers,

**Comment by trevorsandy** [comment]
This behaviour was introduced by #704. 

With #704, lines are parsed for the `INSERT DISPLAY_MODEL` command during model load. A 'display model' flag is set when this command is encountered and, incorrectly, was only reset after encountering a type 1-5 line or end of file. As a result, when a `STEP` containing this command does not have any type 1-5 lines defined (the behaviour before #704), the first submodel encountered after the display model `STEP` would be flagged as a display model. Consequently, this erroneous submodel setting would trigger a false positive for the 'is part' condition when the submodel is encountered during BOM creation.  

This behaviour has been corrected.

Before correction:
![BOM_Parts_01](https://github.com/trevorsandy/lpub3d/assets/13388970/ee2d96e4-04f8-4ab7-be2e-d1c8b00d4b96)

After correction:
![BOM_Parts_02](https://github.com/trevorsandy/lpub3d/assets/13388970/ff3fd2cd-7ae3-4288-be70-2bbd3b010f42)

Cheers,

**Comment by technicbasics** [comment]
Amazing!
Thank you very much Trevor. 👍🏻
