### ISSUE TITLE
Crash when showing BOM

### ISSUE THREAD

**Issue by LassesLego** [trevorsandy/lpub3d#742]
### Subject
When showing the BOM and clicking in the command editor the program crashes,
When showing any other side, you can edit, even the BOM.

### Environment
2.4.7 Revision 29 Build 3505 SHA 30bd4892f
Windows 10 0 22621 64-bit

### Configuration
* LPub3D installation path
  - Windows: "C:\Programfiler spesial\LPub3D_2.4.7\LPub3D_x86_64"

* Application data path
  - Windows: `%USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\`

* Registry Extract
[LPub3D_Hive.txt](https://github.com/trevorsandy/lpub3d/files/12850670/LPub3D_Hive.txt)

### Logs
[Crash.zip](https://github.com/trevorsandy/lpub3d/files/12850699/Crash.zip)

### Steps to reproduce
Have the BOM in the main window and click in the command editor

### Expected behaviour
Editing

### Actual behaviour
Crash

### Workaround
Another view in the main window

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
The Bill of Material (BOM) module is derived from the Parts List Instance (PLI). 

I have corrected reported abend behaviour when selecting a single PLI per page for a multi-step page - see #755 for details. I believe that correction will also treat this ticket and #754.

Please do not hesitate to let me know if you continue to experience this behaviour on 2.4.8 once it is released. I will be happy to revisit this ticket in such situation.

Cheers,
