### ISSUE TITLE
Create new Buildmod after one BM does not work

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#743]
### Subject
Create new Buildmod does not work

### Environment
* Version of LPub3D: 2.42. r75 (and r72 and some other versions)

### Steps to reproduce
With Buildmods enabled, somewhere in the model in some step create a first Buildmod in the Visual Editor using button of press Shift-J. This works fine.
However, in any next step or page, do the same: nothing happens.

### Expected behaviour
The second and all buildmods after that should be created.

### Actual behaviour
After creating one Buildmod, a second or other new one does not work

### Workaround
Save the file, close LPub3D, restart, op the model file

**Comment by trevorsandy** [comment]
Hi Jaco, Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by jacovandermolen** [comment]
A fix for this would be great!
I need to pick up working on instructions, so looking forward to further development.

**Comment by trevorsandy** [comment]
Hello Jaco,

As you are taking a look at the latest LPub3D [DevOps](https://github.com/trevorsandy/lpub3d-ci/releases/tag/continuous) build, do you mind running your Build Mod checks and let me know if this behaviour persists ? Many thanks.

Cheers,

**Comment by jacovandermolen** [comment]
Sure! I tested with 2.4.7.186.3891 and it does not work.
You can create a buildmod once then you have to save the file, quit LPub3D, restart it and reload the model.

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

Cheers,

**Comment by jacovandermolen** [comment]
OK, I have yesterday's (10-10-24) build 2.4.7.186.3891 and tried.
Alas, it is not working.
Here is a video of what I do to illustrate.

https://github.com/user-attachments/assets/ff5bcda5-081f-4560-9057-faeee6618821


Do I do something wrong?

**Comment by trevorsandy** [comment]
My apologies - you did nothing wrong. The milestone was not set when I closed this ticket. I'm using the new GitKraken Launchpad feature and its a bit clunky.

You'll see the correction in the next DevOps build.

Cheers,

**Comment by jacovandermolen** [comment]
OK! In LPub3D_x86_64-2.4.7.236.3941_20241016 I can create and remove Buildmods again!

Tnx for fixing this!

**Comment by trevorsandy** [comment]
Excellent.

Cheers,
