### ISSUE TITLE
Incorrect rendering of part 3023b

### ISSUE THREAD

**Issue by ReneFrijhoff** [trevorsandy/lpub3d#748]
### Subject
Rendering of part 3023b.dat incorrect

### Environment
* Version of LPub3D - Release 2.4.7 Revision 75 Build 3551 SHA b55cffe6e
* Operating system - W10 x64

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  - Windows: E:\Program Files\LPub3D
* Application data path
  - Windows: C:\Users\Rene\AppData\Local\LPub3D Software\LPub3D
* Registry Extract
  - Windows (installed): `reg export "HKEY_CURRENT_USER\Software\LPub3D Software": Doesn't exist
* Renderer configuration files
[Configuration files.zip](https://github.com/trevorsandy/lpub3d/files/13762455/Configuration.files.zip)

### Logs
[LPub3DLog.zip](https://github.com/trevorsandy/lpub3d/files/13762456/LPub3DLog.zip)
Other logs are not created

### Screenshots
* Configuration->Preferences->General
* Configuration->Preferences->Rendering
* Configuration->Preferences->Publishing
* Configuration->Preferences->Logging
* Configuration->Preferences->Other

### Steps to reproduce
Just load the file.
[3023b sample 2.zip](https://github.com/trevorsandy/lpub3d/files/13762466/3023b.sample.2.zip)
![3023b - 2](https://github.com/trevorsandy/lpub3d/assets/37920537/b3cd4e28-2b77-4df5-8ea6-78c6c4d84133)

### Expected behaviour
2 1x2 plates should be rendered (a 1x1 and a 1x3 plate are added for comparison)

### Actual behaviour
2 1x1 bricks with no stud are rendered.

### Workaround
Not found (yet).

### Solution suggestion
I don't even know what the problem is.

**Comment by ReneFrijhoff** [comment]
Sorry wrong picture is added.
![3023b - 3](https://github.com/trevorsandy/lpub3d/assets/37920537/c8c8d074-1221-443c-bfdc-800efceffbc4)

**Comment by ReneFrijhoff** [comment]
After changing the renderer from 'Native' to 'LDGLite' The error 3023b.dat not found came up in the stdout-ldglite file.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Cheers,
