### ISSUE TITLE
Random rotation of submodel midway

### ISSUE THREAD

**Issue by ReneFrijhoff** [trevorsandy/lpub3d#749]
### Subject
Random rotation of a submodel midway the submodel without a 0 ROTSTEP

### Environment
* Version of LPub3D - Release 2.4.7 Revision 75 Build 3551 SHA b66cffe6e
* Operating system - W10 64 bit

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  - Windows: E:\Program Files\LPub3D
* Application data path
  - Windows: C:\Users\Rene\AppData\Local\LPub3D Software\LPub3D
* Registry Extract
  - Windows (installed): `reg export "HKEY_CURRENT_USER\Software\LPub3D Software" Doesnt exist
* Renderer configuration files'
 [Configuration files.zip](https://github.com/trevorsandy/lpub3d/files/13770335/Configuration.files.zip)
* Log files
[LPub3DLog.zip](https://github.com/trevorsandy/lpub3d/files/13770338/LPub3DLog.zip)
Other log files don't exist.
* Screenshots
[Screenshots.zip](https://github.com/trevorsandy/lpub3d/files/13770426/Screenshots.zip)

### Steps to reproduce
Just load this file
[USS Deadalus.zip](https://github.com/trevorsandy/lpub3d/files/13770560/USS.Deadalus.zip)

### Expected behaviour
Submodel should not be rotated

### Actual behaviour
Submodel is rotated

### Workaround
Use different render from 'Native'

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
> Submodel is rotated

When I _just load_ the supplied model file, the first page is a cover page. Can you precise at what step, for you, the submodel is randomly rotated ?

Moreover, can you also provide screenshots of the expected rotation and the incorrect actual rotation ?

Cheers,

**Comment by ReneFrijhoff** [comment]
The page is literally in the screenshot (19 in the field where you can
enter a number, 18 in the field where you select from the select page box).
I can't provide a screenshot for the expected rotation as there is nothing
to rotate (and therefore it shouldn't be rotated) and a screenshot of the
incorrect actual rotation you already have. It's step 1 (correct
positioned) and step 2 (incorrect rotated where it shouldn't be rotated at
all, rotation without a ROTSTEP) on the printscreen provided.

Cheers,

Op vr 1 nov 2024 om 16:14 schreef Trevor SANDY ***@***.***>:

**Comment by ReneFrijhoff** [comment]
As an addition: it's still happening in version 2.4.8. build 3723.
[image: image.png]
[image: image.png]
[image: image.png]



Op vr 1 nov 2024 om 16:50 schreef Rene Frijhoff ***@***.***>:

**Comment by trevorsandy** [comment]
> As an addition: it's still happening in version 2.4.8. build 3723

Ok - Your attachments were not posted so I cannot see the expected rotation and the incorrect actual rotation.

Cheers,

**Comment by ReneFrijhoff** [comment]
Very strange as with the preview they where visible.

![image](https://github.com/user-attachments/assets/29447159-c1a6-4aa7-aff3-cbf5e693e867)
![image](https://github.com/user-attachments/assets/bfc3d799-9e5c-4034-a625-143c791fc260)
![image](https://github.com/user-attachments/assets/16c6663d-47c0-4aca-8305-550f1230f124)

**Comment by trevorsandy** [comment]
You have closed this ticket without any explanation. 

Can I conclude that you have resolved the random rotation behaviour ?

Cheers,
