### ISSUE TITLE
Caches are not cleared when exporting

### ISSUE THREAD

**Issue by ReneFrijhoff** [trevorsandy/lpub3d#750]
### Subject
Caches are not cleared when exporting and selecting 'Reset all caches'

### Environment
* Version of LPub3D - Release 2.4.7 Revision 75 Build 3551 SHA b66cffe6e
* Operating system - W10 64 bit

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
Windows: E:\Program Files\LPub3D
* Application data path
  - Windows: C:\Users\Rene\AppData\Local\LPub3D Software\LPub3D
* Registry Extract
  - Windows (installed): `reg export "HKEY_CURRENT_USER\Software\LPub3D Software" Doesnt exist
* Renderer configuration files
[Configuration files.zip](https://github.com/trevorsandy/lpub3d/files/13771014/Configuration.files.zip)

### Logs
* Application Log: 
[LPub3DLog.zip](https://github.com/trevorsandy/lpub3d/files/13771050/LPub3DLog.zip)

* Renderer Log: `[LDraw model path]/stdout-ldglite`
* Renderer Log: `[LDraw model path]/stderr-ldglite`
Both logs are empty

### Steps to reproduce
Just open any file and 'Export as' and select 'Reset cache'

### Expected behaviour
Cache should be cleared

### Actual behaviour
Cache is not cleared

### Workaround
Select 'Reset cache' from the 'Configuration' menu option

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

Cheers,
