### ISSUE TITLE
Crash when opening "BOM Placement" applet.

### ISSUE THREAD

**Issue by jerome-grandjanny** [trevorsandy/lpub3d#754]
### Subject
Crash with coredump when we want to open "BOM Placement" applet.

### Environment
* Version of LPub3D - 2.4.7.75 build 3551
* Operating system - Linux 4.15.0-213-generic No.224-Ubuntu SMP x86_64 GNU/Linux

### Steps to reproduce
Have the BOM in the main window and right click inside the BOM, then click on "Change Bill Of Material Placement..."

### Expected behaviour
The Bill Of Material Placement applet should pop up

### Actual behaviour
Crash

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
The Bill of Material (BOM) module is derived from the Parts List Instance (PLI). 

I have corrected reported abend behaviour when selecting a single PLI per page for a multi-step page - see #755 for details. I believe that correction will also treat this ticket and #742.

Please do not hesitate to let me know if you continue to experience this behaviour on 2.4.8 once it is released.

Cheers,
