### ISSUE TITLE
LPub3D unstable if 'Author:' value is empty in LDR-file

### ISSUE THREAD

**Issue by app4soft** [trevorsandy/lpub3d#760]
### Subject
LPub3D can't handle LDR-file (`.ldr`, `.mpd`, `.dat`) if there is no author info in the file.

### Environment
* Version of LPub3D: `2.4.7.3551`
* Operating system: Debian 12 (x86_64)

Used DEB from OBS: https://download.opensuse.org/repositories/home:/trevorsandy/Debian_12/amd64/lpub3d_2.4.7.3551-1_amd64.deb

### Configuration

* LPub3D installation path
  - Linux:  `/usr/share/lpub3d`
* Application data path
  - Linux: `~/.local/share/LPub3D Software/LPub3D/`
* Registry Extract
  - Linux: `~/.config/LPub3D Software/LPub3D.conf`

### Logs
* Application Log: `[Application data path]/logs/LPub3DLog.txt`

### Screenshots
All settings are set to default (this is "clean install" test).

### Steps to reproduce

1. Copy next code to save it as `.ldr` file:

```
0
0 Name: New Model.ldr
0 Author:

1 2 0 0 10 1 0 0 0 1 0 0 0 1 88646.dat
1 0 -10 -72 10 1 0 0 0 1 0 0 0 1 14716.dat
0 STEP
1 368 20 -80 10 1 0 0 0 1 0 0 0 1 3710.dat
1 368 20 -88 10 1 0 0 0 1 0 0 0 1 3710.dat
1 368 20 -96 10 1 0 0 0 1 0 0 0 1 3710.dat
1 23 20 -104 10 1 0 0 0 1 0 0 0 1 3710.dat
1 23 20 -112 10 1 0 0 0 1 0 0 0 1 3710.dat
1 23 20 -120 10 1 0 0 0 1 0 0 0 1 2431.dat
0 STEP
```

2. Try to open it in LPub3D.
3. Click in LPub3D code editor widget after open this file.

### Expected behaviour
LPub3D should open files saved with LeoCAD (or any other software), even there is no `0 Author: ` info in the file (even this string fully missing).

### Actual behaviour
LPub3D can't  open files saved with LeoCAD, if there is no info about author in author string (i.e., `0 Author: `) in the file (LeoCAD saves empty author info, if user not set it in preferences).

Also, if click in LPub3D code editor widget after open sample file (which appears to be empty) then LPub3D crashes.

### Workaround
Just edit LDR file in text editor and any symbol in `0 Author: ` line (i.e., `0 Author: 1` would fix issue).

### Solution suggestion
Actually, it is LPub3D bug of parsing LDR files, so parsing bug should be fixed.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I will take a look.

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected. 

Cheers,
