### ISSUE TITLE
Apple silicon arm64 builds

### ISSUE THREAD

**Issue by trevorsandy** [trevorsandy/lpub3d#761]
### Subject
Add LPub3D builds for Apple silicon arm64 (M1, M2...) processors

### Environment
* Version of LPub3D - 2.4.8
* Operating system - macOS 14+

### Solution
Add GitHub action to build and deploy Apple silicon arm64 builds.

Cheers,

**Comment by trevorsandy** [comment]
Completed.

Cheers,

**Comment by citrasusanto** [comment]
I am running a M1 with macOS Sequoia 15.0.1.

I followed the steps for installing Homebrew and libraries and didn't encounter any errors. However, when I try to check for the library, it fails.
<img width="529" alt="Screenshot 2024-10-22 at 12 22 32" src="https://github.com/user-attachments/assets/e94a60a2-c207-4f82-8c08-f16809c67e40">

I tried using quotation marks based on what I found from Googling about globbing. Another error message said something was missing here and there.
<img width="980" alt="Screenshot 2024-10-22 at 12 23 17" src="https://github.com/user-attachments/assets/50295d42-c1cd-4b96-9838-ceb43cc555d4">

I'm not familiar with the macOS filesystem. Let me know if you need me to check anything. I double-checked the version of XQuartz; it should be the latest version.
<img width="257" alt="Screenshot 2024-10-22 at 12 24 53" src="https://github.com/user-attachments/assets/0be394a4-54dd-474a-83ae-536985c0990a">

**Comment by trevorsandy** [comment]
To successfully run the `otool` command, you have to remove the escape `\` character before all the variable designators `$` - looks like you forgot the last one at `dylib\$)`. Sorry. I lifted this content from the macOS README and I forgot to remove the escape characters before posting.

Your XQuartz instance is `v2.8.5` which is later than `v2.7.11` required by LPub3D. Also, it is Universal which means it will run natively on silicon or Intel processors.

Once you've got your `otool` commands working, can you post the check output for the required libraries ?

Lastly, after you confirm the libraries are installed, Launch LPub3D and attach a zip copy of the runtime log. 

Application Log:
```shell
~/Library/Application Support/LPub3D Software/LPub3D/logs/LPub3DLog.txt
```

If you attempt to load a model file with LDView as the preferred renderer, add the follow global commands in the header of the LDraw file:

```shell
0 !LPUB SUBMODEL_DISPLAY LDVIEW_PARMS "IgnoreFramebufferObject=1"
0 !LPUB ASSEM LDVIEW_PARMS "IgnoreFramebufferObject=1"
0 !LPUB BOM LDVIEW_PARMS "IgnoreFramebufferObject=1"
0 !LPUB PLI LDVIEW_PARMS "IgnoreFramebufferObject=1"
```

Cheers,

**Comment by citrasusanto** [comment]
Finally, it is working. Here is the result.
<img width="769" alt="Screenshot 2024-10-22 at 13 43 20" src="https://github.com/user-attachments/assets/03a33144-fd84-4e8d-9c16-7b9b796a52b7">

I followed through and here is the log
[LPub3DLog.zip](https://github.com/user-attachments/files/17471767/LPub3DLog.zip)

**Comment by trevorsandy** [comment]
Ok - Thank you. Your result only presents `libPNG`, can you repeat the steps for the following libraries, substituting libpng for each library in the list below ?

- tinyxml 
- gl2ps 
- libjpeg 
- minizip 
- openexr 
- sdl2 
- libtiff

Cheers,

**Comment by citrasusanto** [comment]
sorry for late reply. here is the log
[List of installed library.txt](https://github.com/user-attachments/files/17636690/List.of.installed.library.txt)
