### ISSUE TITLE
LDView rendering fails with long (generated) file name

### ISSUE THREAD

**Issue by d-j-m-0** [trevorsandy/lpub3d#763]
### Subject
When the total length of the path for the full file name to the assembly or part image generated by LPub3D is too long, LDView spends a long time (15+ minutes) purportedly generating the image but then indicates an issue occurred when genrting the image.

### Environment
* Version of LPub3D - 2.4.7 Revision 29 Build 3505
* Operating system - Windows 10, x86_64

### Steps to reproduce
Create multiple layers of folders which are approaching 220 or so character in the total length of the path.
Create a model in that directory.
Invoke LPub3D.
Select LDView as the renderer.
When the sub-directories created by LPub3D (assem, bom, parts, submodels, tmp) are used with the LPub3D generated name for the assembly exceeds something like 256 characters, the invocation of LDView results in LDView running for a long time and then fails to generate the image.

### Expected behaviour
Display a dialog widow to indicate the total length of the path name to the files is too long. Perhaps include the file name path and the length of said path in the dialog window to help a user work out how far away from being an acceptable length the full path name is.

### Actual behaviour
LDView is invoked, runs for 15+ minutes, terminates successfully but does not generate an image.

### Workaround
Move the file to a shorter directory path (e.g. C:\temp).

### Solution suggestion
Refer to expected behaviour.

**Comment by trevorsandy** [comment]
Thank you for your enhancement request. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Your requested enhancement has been implemented.

![Long-long-file-name-message](https://github.com/user-attachments/assets/55c1db8c-18ae-4578-a2a0-5d1de6309d58)

Cheers,
