### ISSUE TITLE
Crash when clicking in the Command Editor

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#767]
### Subject
If I click in the Command Editor LPub3D crashes with dump file

### Environment
* Version of LPub3D - LPub3D_x86_64-2.4.7.186.3891_20241010
* Operating system - Windows 10 64b

### Steps to reproduce
Open a model file and edit lines in the Command Editor

![image](https://github.com/user-attachments/assets/aa36af99-fc4d-482a-bedd-92770f7fb2d6)

Dump file
[LPub3D.dmp](https://github.com/user-attachments/files/17330503/LPub3D.dmp)
Log file
[LPub3DLog.txt](https://github.com/user-attachments/files/17330509/LPub3DLog.txt)

Do you need the pdb file? It is rather large (84 Mb)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Is the abend reproducible and predictable or random ? 

If reproducible, can you detail the exact sequence of clicks/keystrokes ?

Cheers,

**Comment by jacovandermolen** [comment]
It is reproducible every time I click some line in the editor the crash occurs.

**Comment by trevorsandy** [comment]
I'm following your sequence on the source from 2.4.7.186.3891 and I just can't seem to get an AbEnd.

Using the old BuildMod Beetle LDraw model (40252LPub.mpd), I'm advancing the steps, jumping ahead, navigating backwards.... and nothing.

If you have a specific model file that is producing the behaviour above, can you share it - along with about where in the file you're seeing this behaviour if not at the first step(s) ?

Also, if you are using a portable build, can you share the LPub3D.ini at `./config/LPub3D Software/LPub3D.ini` ?

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has  been corrected.

Cheers,

**Comment by jacovandermolen** [comment]
I will have to test this more a bit in LPub3D_x86_64-2.4.7.236.3941_20241016, but it didn't occur anymore.
