### ISSUE TITLE
Incorrect preview image in the preview window

### ISSUE THREAD

**Issue by technicbasics** [trevorsandy/lpub3d#769]
### Subject
In the Continuous versions after r75, the preview image is displayed incorrectly in the preview window. The problem is that the BUffer Exchange command is interpreted incorrectly. In version r75 it still works correctly.

Here some screen shots:
r75
![2 4 7r75](https://github.com/user-attachments/assets/3fa94774-187b-4194-be75-93642d5d9e2d)

and after r75
![2 4 75r208](https://github.com/user-attachments/assets/c7af6c8c-79dd-4c30-bd9b-c54ddc5343b9)

This only affects the preview image at the beginning. The preview image is always displayed correctly throughout the rest of the assembly instructions. Even at the end of the model when it is completely assembled.
Versions tested: r99, r130, r155, r199 and r208.

![2 4 7r199_End](https://github.com/user-attachments/assets/8146ca31-8bec-4a3b-acd7-9396d694fcc1)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Is the example model file you shared with me back in June last year still relevant - this is to say, are the BufExg commands present in that example ?

Cheers,

**Comment by technicbasics** [comment]
Theoretically, the buffer exchange is also present in the June file, but I will send you the latest version from the hole model file in the next minutes to your gmail mail.

**Comment by trevorsandy** [comment]
Got it. Thanks.

Cheers,

**Comment by technicbasics** [comment]
I have sent you the files that are still missing. (Part 2)

**Comment by trevorsandy** [comment]
Ok - I've got the last download (Files Part 2).

Your document is well done! It's very nice to see you are using advanced features of LPub3D.

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected. 

![IncorrectPreview](https://github.com/user-attachments/assets/ac0ae87c-f001-4471-8a65-b3574d606589)

Cheers,

**Comment by technicbasics** [comment]
> Ok - I've got the last download (Files Part 2).
> 
> Your document is well done! It's very nice to see you are using advanced features of LPub3D.
> 
> Cheers,


Thank you for the praise.
In the next instructions that I have already created and will create, I will also use the “Include” option to quickly switch between different color schemes.
