### ISSUE TITLE
'Insert model' meta gives an error

### ISSUE THREAD

**Issue by ReneFrijhoff** [trevorsandy/lpub3d#770]
### Subject
The meta command 'Insert model' gives an error no matter where you place it and it's automatically added when using faded steps. It's also inserted at the wrong position, at the end of the main model instead after the last submodel/part. This causes the lines to be added after the BOM if that's already inserted.

### Environment
* Version of LPub3D - Release 2.4.7. Revision 75 build 3551
* Operating system - W10 X64

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  - Windows: E:\Program Files\LPub3D
* Application data path
  - Windows: `C:\Users\Rene\AppData\Local\LPub3D Software\LPub3D
* Files and logs
[INSERT MODEL.zip](https://github.com/user-attachments/files/17395007/INSERT.MODEL.zip)

### Screenshots
* Configuration->Preferences->General
![Preferences - General](https://github.com/user-attachments/assets/a8517af9-64b7-4910-99fa-78f46a57b62e)
* Configuration->Preferences->Rendering
![Preferences - Renderers](https://github.com/user-attachments/assets/0837cfde-1070-45fe-af74-49a684b5cb3a)
* Configuration->Preferences->Publishing
![Preferences - Publishing](https://github.com/user-attachments/assets/9312f969-7ccc-4b01-a6c4-baed7c699f37)
* Configuration->Preferences->Logging
![Preferences - Logging](https://github.com/user-attachments/assets/89b7e5de-005a-4248-a91c-5ae66c9c053f)
* Configuration->Preferences->Other
![Preferences - Others](https://github.com/user-attachments/assets/8ee78679-559f-4a89-a667-5524b3fc3e1c)
* Error
![Insert model](https://github.com/user-attachments/assets/65134720-4cad-4d69-8a46-1f5d24ea13d6)

MPD file - [USS Deadalus.zip](https://github.com/user-attachments/files/17397915/USS.Deadalus.zip)

### Steps to reproduce
Enable fading (I'm using the native renderer)

### Expected behaviour
No error

### Actual behaviour
Error, paging through in LPUB3D as well as exporting as a PDF, depending on whether you click Ignore or Abort it does (Ignore) or it doesn't (Abort) generate that picture. Also this error message only happens when loading the file for the first time and choosing Ignore, or every time as long as you choose Abort or closing and loading the file again.

### Workaround
Don't use fading steps or only choose Ignore, but in that case you have to do it every time you load the file.

### Solution suggestion
Sorry, no solution. In this case I don't have the knowledge.

**Comment by ReneFrijhoff** [comment]
Even in the latest DevOps build the problem exists.

Cheers,

Op wo 16 okt 2024 om 18:45 schreef Trevor SANDY ***@***.***>:

**Comment by trevorsandy** [comment]
I have confirmed the improper placement after the BOM. This behaviour will be corrected.

### Workaround
A reasonable workaround, particularly useful when exporting, is to add the following global meta command to your document.

```
0 !LPUB FINAL_MODEL_ENABLED GLOBAL FALSE
```

Cheers,

**Comment by ReneFrijhoff** [comment]
Ok, thanks for the explanation, I will try that. As fior the model file, it
seems it was the wrong version. So here it is again.

Cheers,

Op wo 16 okt 2024 om 22:11 schreef Trevor SANDY ***@***.***>:

**Comment by ReneFrijhoff** [comment]
I also found that now the lines

0 STEP

0 !LPUB INSERT COVER_PAGE BACK

are added every time I load the file.

[image: image.png]
[image: image.png]
[image: image.png]
Cheers,

Op wo 16 okt 2024 om 22:11 schreef Trevor SANDY ***@***.***>:

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

In the following example, you can see the final model is placed before several BOM pages and a back cover page.
![FadeStepsInsertModel_3](https://github.com/user-attachments/assets/921bcaa8-aec9-46d9-8309-66d39e51c83c)

Of course, this capability can be tailored per the comments preceding the `0 !LPUB INSERT MODEL` command which is stating to disable the automatic inclusion of this meta command when the model is loaded, replace `MODEL` with `DISPLAY_MODEL` - resulting with the meta command
```
0 !LPUB INSERT DISPLAY_MODEL.
```
As stated above, you can also totally suppress this behaviour with meta command:

```
0 !LPUB FINAL_MODEL_ENABLED GLOBAL FALSE
```
Or you can uncheck 'Enable Final Model Step' in either the Fade Steps or Highlight Step global setup

Global setup menu
![FadeStepsInsertModel_1](https://github.com/user-attachments/assets/3cda75cc-786d-4da0-b6ee-d0d4e2547435)
![FadeStepsInsertModel_2](https://github.com/user-attachments/assets/71cad6d7-c5e9-45d8-8a80-ca93001c3629)

> I also found that now the lines... 0 !LPUB INSERT COVER_PAGE BACK are added every time I load the file.

You can see in the third configuration screenshot you posted that the 'Generate Cover Pages' checkbox is checked. Uncheck this preference to remove the automatic generation of you front and back cover page.

![FadeStepsInsertModel_4](https://github.com/user-attachments/assets/b5c15f5b-8647-44f3-b90c-d25a11125090)

Cheers,
