### ISSUE TITLE
Increase the capability to change Edge Lines size

### ISSUE THREAD

**Issue by citrasusanto** [trevorsandy/lpub3d#772]
![image](https://github.com/user-attachments/assets/8be5804e-e0f4-4831-b98d-308e0e998f16)

I prefer the edge line settings in LPub3D version 2.4.6, but from version 2.4.7 onwards, it seems to have been reduced to 1.625. This is insufficient for my designs, especially for Duplo models, where I normally use 2.875.

My requests are:
1. Could you increase the maximum range for edge lines to 3 or 4, or allow for manual settings in the file configuration?
2. It's not essential, but could you enable the adjustment of steps in increments other than 0.125 to 0.01 in LPub3D 2.4.8?
3. Alternatively, you could implement a text box that allows users to input any desired number, rather than using a slider?

An example of how the third request might work:
![image](https://github.com/user-attachments/assets/5672edc5-dc17-4001-bf36-613a78a6a6e7)

Last Questions:
Is there a method to control the model's view to determine where it zooms in?
![image](https://github.com/user-attachments/assets/a9f3030a-e0c9-42f0-bb2d-0b6a7842a2d7)

Expected Feature: in Studio, it is located under the pan setting to adjust the viewport.
![image](https://github.com/user-attachments/assets/f25718ca-4516-4a21-a39e-91416beb1778)

**Comment by trevorsandy** [comment]
Thank you for your request. 

> Is there a method to control the model's view to determine where it zooms in?

Take a look at #412

> Could you increase the maximum range for edge lines to 3 or 4, or allow for manual settings in the file configuration?

The edge-line capability in the Native renderer is actually driven by the underlying OpenGL support. Both range and granularity are queried from OpenGL and can differ based on the OpenGL version and graphics card etc... To enable range and granularity values other than those generated by OpenGL for the particular configuration is not a wise solution.

FYI, on ARM processors, the LDView renderer (using XQuartz x11) may be unstable when using OpenGL's GLES vs the traditional GLU/GLUT. ARM platforms are usually using the newer GLES libraries. This may be contributing to the unexpected behavior of LDView on your machine. Counter to this hypothesis, is the fact that build checks are successful on GitHub macOS 14 which uses an arm64 runner. As a result, this conclusion is not yet certain as I am still investigating.

Cheers,

**Comment by trevorsandy** [comment]
I've moved the edge-line content from #753 to properly match the content with the subject of the ticket.

/-----------------------------------/
2. Rendering settings issue

The edge lines remain stuck at a thickness of 1, and they won't update even when adjusting the slider.
<img width="748" alt="Screenshot 2024-11-10 at 12 24 31" src="https://github.com/user-attachments/assets/64b185d2-04e4-432e-86ff-3b64c12f9995">

3. Rendering Result Inconsistency

There is a discrepancy between the page display and visual editor in the rendering results.
<img width="1792" alt="Screenshot 2024-11-10 at 12 09 06" src="https://github.com/user-attachments/assets/ed6e5d71-1a6c-47e8-baa0-f3b3b5544cb4">
/-----------------------------------/

In DevOps, the issue (items 2 and 3) persists, just like in the release version. Here it is.
<img width="1792" alt="Screenshot 2024-11-10 at 17 19 59" src="https://github.com/user-attachments/assets/0cbd5fbe-73ac-436a-83f4-0bc2803a40ad">
/-----------------------------------/

The color 'wash out' between the generated .png image and the viewer/editor display is concerning but I'm not experiencing this behaviour on my Linux or Windows environments and I don't have a macOS machine to test on so it'll be hit-or-miss on what the problem/solution can be.

Cheers,
/-----------------------------------/

> The color 'wash out' between the generated .png image and the viewer/editor display is concerning but I'm not experiencing this behaviour on my Linux or Windows environments and I don't have a macOS machine to test on so it'll be hit-or-miss on what the problem/solution can be.

Oh no, this is exactly what I was afraid of. 

I’d like to confirm a few things. If I installed the Intel-based version on Arm based processor (M1-M4)—could this native rendering issue be related to that? Since the application uses OpenGL and, as far as I know, Intel still supports OpenGL while Apple is pushing their own Metal graphics, I suspect the issue might be tied to OpenGL settings. Unfortunately, I’m not sure how to adjust these settings.

**Comment by trevorsandy** [comment]
> If I installed the Intel-based version on Arm based processor (M1-M4)—could this native rendering issue be related to that?

I don't think so. Rather, I believe it is more related to the use of the EGL stack versus traditional OpenGL. The problem might stem from the Native renderer shaders but this is not certain. 

You can these tests to help me better 'see' what's going on.

1. Stop on STEP 3 (to compare the image posted above) and capture the csi.ldr file from ./_your model file_/LPub3D/tmp/csi.ldr.
2. Open LeoCAD and replicate your Render Preference settings as posted above then open csi.ldr and save an image using _File_->_Save Image..._ Once completed, post the csi.png image.
3. Open LDView and replicate your edge-lines Preference settings at _Edit_->_Preferencess_->_Geometry_->_Edge Lines_ then export an image using _File_->_Save Snapshot..._ Once completed, post the csi.png image.

Here is a reference for the LDView edge lines settings:
![EdgeLines](https://github.com/user-attachments/assets/47736038-8102-4254-a4ef-6a76c4ab288d)

P.S. I could be interesting to see if you are able to manipulate the edge line thickness as you desire using both or either LeoCAD and LDView also.

Cheers,

**Comment by citrasusanto** [comment]
Hi, 

> P.S. I could be interesting to see if you are able to manipulate the edge line thickness as you desire using both or either LeoCAD and LDView also.

Yes, i could manipulate the edge line thickness from each app. Here is comparison + settings for each app
1. LeoCAD (Left - App, Right - Export image)
<img width="1680" alt="Screenshot 2024-11-14 at 19 15 13" src="https://github.com/user-attachments/assets/181dd8c9-1856-435a-ba56-391a67706639">
2. LDview (Left - App, Right - Export image)
<img width="1680" alt="Screenshot 2024-11-14 at 19 16 53" src="https://github.com/user-attachments/assets/1c7b2003-395f-4cf6-9dcd-2414bf9ed012">

Exported image only:
<img width="1440" alt="csi_ldview" src="https://github.com/user-attachments/assets/918b2978-c89d-48c5-af0b-0da9a5f5fe0f">
![csiLeoCad](https://github.com/user-attachments/assets/8bba9be9-f01e-4c5c-a707-3a0d1b3dc6e5)

**Comment by trevorsandy** [comment]
Excellent - This is a good start. If you are successfully rendering edge lines with LeoCAD, then there must be an issue with LPub3D's implementation of the edge line setting. 

I can see that your LeoCAD line width range goes well beyond 1 but in LPub3D this setting maxes out at 1. I modified the way the range is calculated to better reflect sane values as you can see in the below comparison, LeoCAD gives a line width top-of-the-range of over 2K which does not make sense for a pixel reference. Anyway, it could be good to see what is the max edge line range you are getting - it's based on your GPU.  

Here is a range comparison, and my GPU specs.

![EdgeLines_01](https://github.com/user-attachments/assets/a72021a4-fe1b-44b3-b37b-06bdaadcdcab)

![EdgeLines_02](https://github.com/user-attachments/assets/008bfa1f-e481-4af1-bcab-4b57ac6b59f8)

I'll take a look at reverting my edge line calculation the the LeoCAD default for macOS to see if this can be helpful.

Cheers,

**Comment by citrasusanto** [comment]
Here is the comparison LeoCAD - LPub3D
<img width="1259" alt="Screenshot 2024-11-15 at 08 21 28" src="https://github.com/user-attachments/assets/0218d93d-0576-4424-ba26-af14ae0a369f">

I couldn't find any detail specs from my hardware. Here is the [link](https://en.wikipedia.org/wiki/MacBook_Air_(Apple_silicon)) you could see detail specs

**Comment by trevorsandy** [comment]
This enhancement has been implemented.

![EdgeLines_03](https://github.com/user-attachments/assets/eb285af4-5ad2-4ad8-b578-d03cc54b5beb)

The default maximum granularity is set to _1.0_; however, this value may be too large for some graphics setup. The resulting behaviour could be a very short line width range whereby you are not able to set your desired line width. In such case, you can now lower the granularity value using the new input dialog. This capability will allow you to set a wider range than is possible with the default granularity.

As you can see in the macOS example above, the system specified range maximum is set to _1_ because the step/granularity value of _1_ is too high. This limitation is not acceptable if you wish to set your line width above _1_. So to treat this scenario, if you set the maximum granularity to _0.00781_. The range will approach a minimum value of _1_ and a more reasonable maximum value of _16_, allowing you to set a line width above _1_. 

Cheers,

**Comment by citrasusanto** [comment]
Is this implemented in version 2.4.8.r141.4093? I can't wait to test it out!

**Comment by trevorsandy** [comment]
> Hi, thank you for the implementation of the edge lines. I have a suggestion: instead of naming it "max slider granularity," how about using "Line Width Smoothing" or "Precision Scaling"? (easier to understand)

_Line Width Smoothing Granularity_ looks good. I'll update the _label_ and help _what's this_ help information.

Here's the actual code that populates the line width slider when you open the Preferences dialogue:

```cpp
	float Max = mOptions->Preferences.mLineWidthMaxGranularity;

#ifndef LC_OPENGLES
	if (QSurfaceFormat::defaultFormat().samples() > 1)
	{
		glGetFloatv(GL_SMOOTH_LINE_WIDTH_RANGE, mLineWidthRange);
		glGetFloatv(GL_SMOOTH_LINE_WIDTH_GRANULARITY, &mLineWidthGranularity);
	}
	else
#endif
	{
		glGetFloatv(GL_ALIASED_LINE_WIDTH_RANGE, mLineWidthRange);
		mLineWidthGranularity = Max;
	}

	ui->LineWidthSlider->setRange(0, (mLineWidthRange[1] - mLineWidthRange[0]) / qMax(Max, mLineWidthGranularity));
```

> Additionally, I tested the latest development version (v2.4.8.r157) on my M1 Mac, and while I can now control the edge lines, I’m still seeing a color "wash out" between the generated .png image and the viewer/editor display.

I have not looked at this behaviour. Seems shader-related though.

> Would you like me to create a new ticket for this, or should I continue from here?

Let's start with this:

1. Post the raw .png image file from _./your model file/LPub3D/assem_ correspending to the sample referenced above.

If you are not experiencing, 'wash out' with your LeoCAD image, and your settings are the same as those used in LPub3D, then I'll help you to perform some tests that should get closer to the source of the behaviour. When we get here, you can open a new ticket to continue.

Cheers,

**Comment by citrasusanto** [comment]
> 1. LeoCAD (Left - App, Right - Export image)
> 
> <img alt="Screenshot 2024-11-14 at 19 15 13" width="1680" src="https://private-user-images.githubusercontent.com/6107084/386190113-181dd8c9-1856-435a-ba56-391a67706639.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NTIxMjgsIm5iZiI6MTczMTc1MTgyOCwicGF0aCI6Ii82MTA3MDg0LzM4NjE5MDExMy0xODFkZDhjOS0xODU2LTQzNWEtYmE1Ni0zOTFhNjc3MDY2MzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTZUMTAxMDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmUyY2YyMTY4YzMyZTY2MDQxZDBlODBiYTA1Y2U1NjlkOTQ1OTQzMmU1YTVhMjhkNTgxYTE2YzliMWY1Mzc3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Y2XHhBSdvmHAh1S7R1Dx4edNux1ZBnsJZPtGEEVHD-U">

I think this is what you're expecting. Everything I showed in the previous post was done with macbook M1. There is no 'wash out' or color degradation in other software with similar settings for LeoCAD or LDView.

**Comment by citrasusanto** [comment]
oops, my mistake.
<img width="1665" alt="Screenshot 2024-11-16 at 17 55 49" src="https://github.com/user-attachments/assets/5c663b51-f0de-45d7-b0d6-b9147770201d">

Here is side by side comparison:
Left: LPub3D
Right: LeoCAD
Bottom: LDView

It appears that the 'wash out' issue also occurs with LeoCAD. Could this potentially be a significant problem?"

**Comment by trevorsandy** [comment]
> It appears that the 'wash out' issue also occurs with LeoCAD. Could this potentially be a significant problem?

Ok - this is good, we are progressing. As I suspected, the problem is not unique to LPub3D. I don't think it's a 'significant problem'. We simply need to track down the source of the blurred lines. I believe this could be treated with some tweaks to the shaders code but I'll have to consult with Leo to confirm.

In the mean time, could you capture, exactly, what specs your M1 graphics system possesses ?

Cheers,

**Comment by citrasusanto** [comment]
> I couldn't find any detail specs from my hardware. Here is the [link](https://en.wikipedia.org/wiki/MacBook_Air_(Apple_silicon)) you could see detail specs

Iam not really familiar with macOS system information, it do not provide detail information. Iam using Macbook Air M1 2020

**Comment by trevorsandy** [comment]
Ok - well you can always use the LDView renderer in LPub3D. In fact, it is cases like this that prompted me to package multiple renderers.

Cheers,

**Comment by trevorsandy** [comment]
Can you repeat the compare montage with stud style setting 0 (plain) ? I think this is biasing the line quality.

Cheers,

**Comment by citrasusanto** [comment]
<img width="1665" alt="Screenshot 2024-11-16 at 18 46 21" src="https://github.com/user-attachments/assets/d2c20697-de0e-464c-a627-6fd83fea537e">
I set the stud style to 0 (plain), but I can't see any difference. In LDView, I used the same image since there is no option to adjust the stud style.

> Ok - well you can always use the LDView renderer in LPub3D. In fact, it is cases like this that prompted me to package multiple renderers.

I tried adjusting the settings for rendering-LDView on macOS with latest version (2.4.8.r157). It crash every time i clicked _LDView Preferences_. I also can't change the LDView path. 

<img width="748" alt="Screenshot 2024-11-16 at 18 40 56" src="https://github.com/user-attachments/assets/eb5be28c-7f23-4364-ab93-37d7ca2a0ef2">

On windows 10, I can open the LDView preferences but I can't adjust the LDView path.

**Comment by trevorsandy** [comment]
> I tried adjusting the settings for rendering-LDView on macOS with latest version (2.4.8.r157). It crash every time i clicked LDView Preferences. I also can't change the LDView path.

This is interesting - I corrected this in #773. It's a bit strange to see the correction did not address the macOS build.

You should not change the LDView path (or any other renderer for that matter) - the path dialogue is read-only. The instance of LDView (and LDGLite and POVRay) packaged with LPub3D is tailored for LPub3D. This is why you can see features like Stud Style and Automate Edge  Color in the Preferences panel that you would not find in the standard build of LDView. Moreover, LPub3D uses the console instance of LDView on macOS, not the GUI instance. If for example you are on Windows, and still want to use your standard of LPub3D, you must place it at the path specified in the Preference dialogue - replacing the existing instance.

Cheers,

**Comment by trevorsandy** [comment]
> Is there any update on the "wash out" problem?

This behaviour is sourced from LeoCAD, so it would be better to open a new LeoCAD ticket to give this behavior proper visibility and appropriate context.

> Also, I wanted to report another bug I encountered. 

Excellent. Thank you for reporting this behaviour. Please open new tickets to give these behaviours proper visibility and appropriate context. In the mean time, I'll take a look.

If I well understand, you are reporting 2 new behaviours:

1. AbEnd on meta command _manipulation_ in the command editor
2. Parts placed after `CALLOUT` meta command do not display in the _Parts List Instance_ for the respective _STEP_

Cheers,

**Comment by citrasusanto** [comment]
> I tried adjusting the settings for rendering-LDView on macOS with latest version (2.4.8.r157). It crash every time i clicked _LDView Preferences_. I also can't change the LDView path.

Trevor, i tested the latest dev release 2.4.8 r252 in macOS. Finally Iam able to set the setting for LDView, but it appears the _wash out_ appear similar like Native renderer. Here is the screenshot.

![Screenshot 2024-12-14 at 23 28 54](https://github.com/user-attachments/assets/4a6ab0b9-495d-4c98-88f8-846322deb698)

**Comment by trevorsandy** [comment]
> Trevor, i just tested the latest dev release 2.4.8 r252 on macOS. Finally Iam able to set the settings for LDView, but it appears the wash out appearance persists, similar like Native renderer. Here is the screenshot.

Open the LPub3D.log and search for _CSI Arguments:_. If you like, you can match the .png file in the screenshot above to the actual command arguments sent to LDView to generate it. You can actually run the command portion of this log entry, if you like, to test directly the output of LDView. The value of doing this is to see if any of your command settings are contributing to the image washout. My suspicion is this is an OpenGL behaviour issue on your arm64 environment. Anyway, if you post the command, I can take a look to see if your settings can be implicated. If you can't find the command arguments in the log, just post the entire log.

> Where can i find the hotkey settings?

Try Configuration->Preferences->Shortcuts

> If there isn't, what is the shortcut to comment out a line?
Ctrl+D

Cheers,
