### ISSUE TITLE
TopOfStep modelIndex below model start

### ISSUE THREAD

**Issue by ReneFrijhoff** [trevorsandy/lpub3d#778]
**Summary**

TopOfStep modelindex [number] (name of submodel 1) - line number [number] is below model start, returned modelindex [number] (name of submodel 2 within submodel 1)

**LPub3D Version**

  - Incarnation: LPub3D Windows Installer
  - Affected build version: 2.4.8 build 3723

**Runtime Environment**

  - Operating system: Windows 10 Pro 22H2 64 bit
  - x64
  - CPU model: Intel Core i7-11700KF 3.6

**Steps to Reproduce**

 1. Load MPD file into LPUB3D
 2. Go to page 17
 3. Click in the 1st step in the command editor

**Expected Behavior**

No error

**Actual Behavior**

Error

**Output or example Input**<details>

![Error](https://github.com/user-attachments/assets/ebb6de6c-558f-43ac-b0f5-f7000efa48a1)
![Step](https://github.com/user-attachments/assets/8d9954eb-9553-4b60-a34a-81b9e91ab5ec)
[USS Deadalus.zip](https://github.com/user-attachments/files/17586454/USS.Deadalus.zip)

</details>

**Workaround**

None

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I will take a look.

FYI, your attachments were not successfully posted.

Cheers,

**Comment by ReneFrijhoff** [comment]
Re-upload files
![Error](https://github.com/user-attachments/assets/c6b4e123-c33f-4690-a084-1d5a2108caf4)
![Step](https://github.com/user-attachments/assets/3c7e9b3c-8fdd-45da-b5f2-330cc828ddb0)
[USS Deadalus.zip](https://github.com/user-attachments/files/17588420/USS.Deadalus.zip)

**Comment by ReneFrijhoff** [comment]
Files are re-uploaded.

Cheers,

Op do 31 okt 2024 om 12:26 schreef Trevor SANDY ***@***.***>:

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

Cheers,
