### ISSUE TITLE
Errors loading files with meta-commands made by older LPUB3D versions

### ISSUE THREAD

**Issue by ReneFrijhoff** [trevorsandy/lpub3d#779]
**Summary**

Errors when loading files with meta-commands made with older LPUB3D versions

**LPub3D Version**

  - Incarnation: LPub3D Windows Installer
  - Affected build version: 2.4.8 build 3723
  - Known working build version: 2.4.7

**Runtime Environment**

  - Operating system: Windows 10 Pro 22H2 64 bit
  - Hardware architecture: x64
  - CPU model: Intel Core i7-11700KF 3.6

**Steps to Reproduce**

 1. Try to load the file

**Expected Behavior**

No problems

**Actual Behavior**

errors on meta commands by older LPUB3D versions

**Output or example Input**<details>
![Old meta-command](https://github.com/user-attachments/assets/6bb2b6cb-d3df-4527-98c9-7d00ac70afc5)
</details>

**Workaround** (optional)
Manually delete the concerning lines

**Suggested Solution** (optional)
Make deletion or correction (if meta command has changed) automated.

**Comment by ReneFrijhoff** [comment]
[EagleBoosterDriveAssembly.zip](https://github.com/user-attachments/files/17586996/EagleBoosterDriveAssembly.zip)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

It looks like you are posting your screenshots and attachments into the `code markdown` section of **Output and Example Input**

The correct way to put your attachments in this section is to NOT place them inside of the ``` marks.

Cheers,

**Comment by ReneFrijhoff** [comment]
Ah, sorry and thanks.

Cheers,

Op vr 1 nov 2024 om 09:54 schreef Trevor SANDY ***@***.***>:

**Comment by trevorsandy** [comment]
This behaviour has been corrected. 

The `MODEL_PIECES` meta command was replaced with `MODEL_PARTS` in v2.4.6 r0 back on 28-09-2018 - see #116. Nevertheless, I have added this command to the 'SpecialCases' exception list so from v2.4.9, it will be silently changed when the model file is parsed.

Screenshots<details>

Correction in v2.4.9
![ModelPieces_2](https://github.com/user-attachments/assets/45ecfa41-39d3-4983-af6a-cb30d9ec8148)

Reported behaviour present in v2.4.7
![ModelPieces_1](https://github.com/user-attachments/assets/748e2528-fb17-42bb-ad7e-3afe02a77859)

</details>

Cheers,
