### ISSUE TITLE
Parts in PLI are not always drawn on model

### ISSUE THREAD

**Issue by ReneFrijhoff** [trevorsandy/lpub3d#780]
**Summary**

Parts in the PLI are not always drawn in the model

**LPub3D Version**

  - Incarnation: LPub3D Windows Installer
  - Affected build version: 2.4.8 build 3723

**Runtime Environment**

  - Operating system: Windows 10 Pro 22H2 64 bit
  - Hardware architecture: x64
  - CPU model: Intel Core i7-11700KF 3.6

**Steps to Reproduce**

 1. Load the model
 2. Go to page 48, step to next page

**Expected Behavior**

Model should be completely drawn

**Actual Behavior**

Model is only drawn for previous step without the additional part

**Output or example Input**<details>

![image](https://github.com/user-attachments/assets/c3bcd65e-6501-42ee-b76b-5454b85cddc7)
![image](https://github.com/user-attachments/assets/05d5176f-192c-4f02-8f3e-d5fc479ea6df)
![image](https://github.com/user-attachments/assets/74640ef6-dc10-4e44-88c7-3321b600ffff)

</details>

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

If you want to put your attachments within the `<details></details>` tags, do it like this:

```
**Output or example Input**<details>

![image](https://github.com/user-attachments/assets/c3bcd65e-6501-42ee-b76b-5454b85cddc7)
![image](https://github.com/user-attachments/assets/05d5176f-192c-4f02-8f3e-d5fc479ea6df)
![image](https://github.com/user-attachments/assets/74640ef6-dc10-4e44-88c7-3321b600ffff)

</details>
```

And if you want to attach some Model file example content, do it like this:

```
**Output or example Input**<details>
~~~
0 FILE uss_deadalus.ldr
0 USS Deadalus
0 Name: uss_deadalus.ldr
0 Author: Nicolai Jetzinger
0 USS Deadalus Star Gate Atlantis
0 Model and instructions modifications: Rene Frijhoff
0 Lpub3d pages: 1041
0 Lpub3d page: 1
0 !LPUB FINAL_MODEL_ENABLED GLOBAL FALSE
0 !LPUB BOM ANNOTATE FONT GLOBAL "Arial,12,-1,5,50,0,0,0,0,0,Regular"
0 !LPUB BOM PART_ELEMENTS BRICKLINK GLOBAL TRUE
~~~
</details>
```

You can also mix both attachments and model file content like this:

```
**Output or example Input**<details>
~~~
0 FILE uss_deadalus.ldr
0 USS Deadalus
0 Name: uss_deadalus.ldr
0 Author: Nicolai Jetzinger
0 USS Deadalus Star Gate Atlantis
0 Model and instructions modifications: Rene Frijhoff
0 Lpub3d pages: 1041
0 Lpub3d page: 1
0 !LPUB FINAL_MODEL_ENABLED GLOBAL FALSE
0 !LPUB BOM ANNOTATE FONT GLOBAL "Arial,12,-1,5,50,0,0,0,0,0,Regular"
0 !LPUB BOM PART_ELEMENTS BRICKLINK GLOBAL TRUE
~~~

</details>
```


The attachment result will be this:

**Output or example Input**<details>

![image](https://github.com/user-attachments/assets/c3bcd65e-6501-42ee-b76b-5454b85cddc7)
![image](https://github.com/user-attachments/assets/05d5176f-192c-4f02-8f3e-d5fc479ea6df)
![image](https://github.com/user-attachments/assets/74640ef6-dc10-4e44-88c7-3321b600ffff)

</details>

And the Model file example content result will be this:

**Output or example Input**<details>
~~~
0 FILE uss_deadalus.ldr
0 USS Deadalus
0 Name: uss_deadalus.ldr
0 Author: Nicolai Jetzinger
0 USS Deadalus Star Gate Atlantis
0 Model and instructions modifications: Rene Frijhoff
0 Lpub3d pages: 1041
0 Lpub3d page: 1
0 !LPUB FINAL_MODEL_ENABLED GLOBAL FALSE
0 !LPUB BOM ANNOTATE FONT GLOBAL "Arial,12,-1,5,50,0,0,0,0,0,Regular"
0 !LPUB BOM PART_ELEMENTS BRICKLINK GLOBAL TRUE
~~~
</details>

Cheers,

**Comment by trevorsandy** [comment]
I'm using this instance [USS Deadalus.zip](https://github.com/user-attachments/files/17588420/USS.Deadalus.zip) of your LDraw model file. 

Page 47-50 do not show the same content as pages 47-50 in the screenshots you attached in the original post. Furthermore, for me, pages 47-50 are correctly showing a PLI when parts are present in the STEP. For example, page 48 correctly shows in the PLI the 2 instances of `3023b.dat` that make up submodel `is1_sub07.ldr` - of which there are 4 instances. Page 49 then correctly shows the 4 instances of `is1_sub07.ldr` and no PLI as there are no parts in the STEP. See details below.

Pages 47-50<details>

No parts in this STEP (only submodels) so no PLI
![PartsInPli_1](https://github.com/user-attachments/assets/87977dd0-cfac-4283-aa9f-f47b2289931b)

PLI parts displayed as expected
![PartsInPli_2](https://github.com/user-attachments/assets/83e3cbb1-c06f-4305-9803-8fd0ff2b4277)

Again, no parts in this STEP (only submodels) so no PLI
![PartsInPli_3](https://github.com/user-attachments/assets/4eacb7a4-7bc6-4b5c-bdf9-c7fc2fbf074b)

</details>

FYI, when you take a screenshot, try to take the as much of the application as is relevant so more than on reference point can be captured. In the screenshots you provided, only the page number reference is visible but, as you can see, page numbers 47-50 in the shots you provided do not show the same content as page 47-50 in the attached model file you provided.

Cheers,

**Comment by ReneFrijhoff** [comment]
Did I upload the wrong version again?
Screenshots + correct version. You used the wrong version so of course it won't match. Though it's also my mistake for forgetting the file to attach.

[USS Deadalus.zip](https://github.com/user-attachments/files/17605862/USS.Deadalus.zip)

![image](https://github.com/user-attachments/assets/c7b07394-26e7-43a7-9357-0157dba4c921)
![image](https://github.com/user-attachments/assets/ff600e6f-c378-40b6-aaef-a0949f37b144)
![image](https://github.com/user-attachments/assets/5e39e278-8a35-45f8-9bfc-aa570aa91c46)

**Comment by trevorsandy** [comment]
> Did I upload the wrong version again?
> Screenshots + correct version. You used the wrong version so of course it won't match. Though it's also my mistake for forgetting the file to attach.

The subject of this ticket is a STEP's PLI parts not appearing in the STEP assembly. However, the example screenshots you posted do not show any parts in the PLI that are not accounted for in the STEP assembly.

Moreover, as I posted above and again in the details below, I am not able to reproduce the behaviour your are reporting at Pages 47-50.<details>

No parts in this STEP (only submodels) so no PLI
![PartsInPli_1](https://github.com/user-attachments/assets/87977dd0-cfac-4283-aa9f-f47b2289931b)

PLI parts displayed as expected
![PartsInPli_2](https://github.com/user-attachments/assets/83e3cbb1-c06f-4305-9803-8fd0ff2b4277)

Again, no parts in this STEP (only submodels) so no PLI
![PartsInPli_3](https://github.com/user-attachments/assets/4eacb7a4-7bc6-4b5c-bdf9-c7fc2fbf074b)

As an observation, your model file includes several instances of the following command sequence:

~~~
0 STEP
0 ROTSTEP 0 180 0 REL
1 16 0 -40 110 -1 0 0 0 1 0 0 0 -1 is1_sub02.ldr
0 STEP
0 ROTSTEP END
~~~

It is not necessary to precede the `ROTSTEP` meta command with a `STEP` command. In LPub3D, both a `STEP` and `ROTSTEP` are treated as a `STEP` so only one command is needed to designate a new STEP.

</details>

I will also take a look at the updated model file you posted.

Cheers,

**Comment by trevorsandy** [comment]
Ok - I am able to reproduce the behaviour you are reporting. Indeed, on page 48, part 6232.dat is present in the PLI but not reflected in the assembly. I will take a look.

Cheers,

**Comment by trevorsandy** [comment]
**Workaround**

In a STEP with just two pieces where one piece is a submodel and the second a part, the part must be placed first.

So this configuration will produce expected behaviour:

```
0 FILE is3.ldr
0 Internal structure 3
0 Name: is3.ldr
0 Author: Nicolai Jetzinger
1 15 0 0 -80 0 0 1 0 -1 0 1 0 0 6232.dat
1 16 0 0 0 -1 0 0 0 -1 0 0 0 1 is3_sub01.ldr
0 STEP
0
0 NOFILE
...
```

![PartsInPli_1b](https://github.com/user-attachments/assets/d784c8ae-bd5a-4e11-bbeb-37f0e846ec16)

...while this configuration will not display the part.

```
0 FILE is3.ldr
0 Internal structure 3
0 Name: is3.ldr
0 Author: Nicolai Jetzinger
1 16 0 0 0 -1 0 0 0 -1 0 0 0 1 is3_sub01.ldr
1 15 0 0 -80 0 0 1 0 -1 0 1 0 0 6232.dat
0 STEP
0
0 NOFILE
...
```

![PartsInPli_1a](https://github.com/user-attachments/assets/fd6fc96b-92f1-4a04-a686-7c41bb6aedc0)

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

Cheers,
