### ISSUE TITLE
LPub chrash on first startup

### ISSUE THREAD

**Issue by technicbasics** [trevorsandy/lpub3d#782]
**Summary**
When starting the program for the first time, it crashes unexpectedly.
The config folder is created, then the program closes.

**LPub3D Version**

2.4.8r87 32/64 Bit mobile version unzipped in admin mode
2.4.8r101 32/64 Bit mobile version unzipped in admin mode

**Runtime Environment**
Edition	Windows 11 Home
Version	23H2
Installiert am	‎07.‎10.‎2022
Betriebssystembuild	22631.4391
Leistung	Windows Feature Experience Pack 1000.22700.1047.0

Prozessor	11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz   2.50 GHz
RAM	16,0 GB
Systemtyp 64-Bit-Betriebssystem, x64-basierter Prozessor

Complete content of the program path where only the config folder was newly created:
![grafik](https://github.com/user-attachments/assets/09a4e022-c9e8-41fb-b326-fb91437509dd)

Contents of the Config folder:
![grafik](https://github.com/user-attachments/assets/3fdf7c38-0871-4506-a649-a10d74e1f948)

Contents of the LPub3D.... folder:
![grafik](https://github.com/user-attachments/assets/7d682c37-094b-4b46-9cd8-74164399e419)

Zipped Lpub3D.ini
[LPub3D.ini.zip](https://github.com/user-attachments/files/17635801/LPub3D.ini.zip)

If you need any other files, let me know.

Regards Johann

*

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Just to confirm, the application will AbEnd on initial startup after a new extract/install, or every time you launch the application, it AbEnds on startup ?

Cheers,

**Comment by technicbasics** [comment]
Every time.

05.11.2024 18:57:06 Trevor SANDY ***@***.***>:

**Comment by trevorsandy** [comment]
**Workaround**

1. Open a command console
2. Set the environment variable LPUB3D_DISABLE_UPDATE_CHECK=1 (any value is ok)
3. Launch the application from the command line

Example commands (run from LPub3D executable location):

~~~batch
SET LPUB3D_DISABLE_UPDATE_CHECK=1
.\LPub3D.exe

~~~

I will check in a fix shortly.

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

Cheers,

**Comment by technicbasics** [comment]
Many thanks.
I'll wait for the next ci-build.
Johann
