### ISSUE TITLE
Automatic restart

### ISSUE THREAD

**Issue by trevorsandy** [trevorsandy/lpub3d#790]
**Describe the solution you would expect**

Add automatic restart when LPub3D encounters an abnormal end - i.e. a CrashExit.

**Comment by trevorsandy** [comment]
This behaviour has been implemented.

Cheers,

**Comment by citrasusanto** [comment]
Hi Trevor, could you add a feature to automatically opens the last edited and takes us to the last page we were working on when not only when it is crashed but when 2nd time opened.

It would be great if this could be optional, with a toggle to turn it on or off.

**Comment by trevorsandy** [comment]
> ... could you add a feature to automatically opens the last edited and takes us to the last page we were working on when not only when it is crashed but when 2nd time opened.

This behaviour is already included in this enhancement - see commit trevorsandy/lpub3d-ci@592396481. It was _NOT_, however, included in DevOps build 2.4.8-r175. 

If you are interested, you can follow the commit history of [LPub3D DevOps](https://github.com/trevorsandy/lpub3d-ci/commits/master/).

Cheers,
