### ISSUE TITLE
Command Editor toolbar

### ISSUE THREAD

**Issue by trevorsandy** [trevorsandy/lpub3d#800]
**Describe the solution**
1. Three new tools added to the command editor toolbars
- Move line up or down
![Screenshot 2024-12-07 084136](https://github.com/user-attachments/assets/cd32d0ab-ef69-49f6-8006-a656152acb26)
- Add LPUB meta commands directly into the command editor 
![Screenshot 2024-12-07 084205](https://github.com/user-attachments/assets/805e7bfb-8afa-48b1-b5bc-9342aa306d73)
- Add user-defined and built-in LPUB meta command snippets directly into the command editor
![Screenshot 2024-12-07 084846](https://github.com/user-attachments/assets/9a418b7b-dae9-4be4-8f64-4379359706f3)
- Example 0 STEP command inserted into the command editor
![Screenshot 2024-12-07 084943](https://github.com/user-attachments/assets/9a1f7ade-ffe5-49c5-9495-f5781b21d770)
- LPUB meta command edit, insert and positioning dialogue.
![Screenshot 2024-12-07 084612](https://github.com/user-attachments/assets/3b3bef12-22fe-4005-8b23-f68e1cf0ea7f)
- LPUB meta command snippet edit dialogue
![Screenshot 2024-12-07 084706](https://github.com/user-attachments/assets/3882407a-5091-4041-9833-14dd595bc844)

**Additional context**

Docked command editor.
![Screenshot 2024-12-07 083952](https://github.com/user-attachments/assets/e05927db-7658-4e29-b593-017109b8a65e)

Detached command editor.
![Screenshot 2024-12-07 083433](https://github.com/user-attachments/assets/1a6ca8ca-507f-4898-a5c7-2c92c165c4b9)

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been implemented.

Cheers,

**Comment by technicbasics** [comment]
Wow..very cool!
