### ISSUE TITLE
MSVCP140.dll is missing message Windows 7/8/XP 

### ISSUE THREAD

**Issue by trevorsandy** [trevorsandy/lpub3d#81]
### Subject
Unable to start LPub3D. Message “The program can’t start because MSVCP140.dll is missing from your computer. Try reinstalling the program to fix this problem.” presented.

### Environment
* Version of LPub3D - v2.3.0
* Operating system - Windows 7/8/Windows XP (x86,x86_64)

### Solution
Starting with version 2.3.0, I'm using Visual C++ 2017 for x86_64 and Visual C++ 2015 for x86 platforms. The 'missing MSVCP140.dll' message is because the Microsoft Visual C++ Redistributable package for Visual C++ 2015 is not installed on your machine - likely because of the version of your operating system. The MSVCP140.dll file is part of the Visual C ++ Redistributable for Visual Studio 2015 package. (You don’t need to know this, but the package provides the components Windows needs to run C ++ applications.)

Install Microsoft Visual C ++ Redistributable package:

1) Go to the [Microsoft Visual C++ 2015 Redistributable Update 3 download page](https://www.microsoft.com/en-us/download/details.aspx?id=53840), Choose the correct language, and then click **Download**.

![screenshot - 05_09_2018 22_31_37](https://user-images.githubusercontent.com/13388970/45120752-58863500-b15f-11e8-88de-caf574eeca00.png)

2) Select the appropriate file for your version of Windows (x64 for the 64-bit version of Windows, and x86 for the 32-bit version).

If you know which version of Windows you’re running you skip ahead to step 3. Otherwise simply type **system info** in the search box on your computer and click **System Information

![screenshot - 05_09_2018 22_36_41](https://user-images.githubusercontent.com/13388970/45120813-88353d00-b15f-11e8-8a00-487829db70ed.png)
**.

The **System Type** field will tell you whether you’re running 32-bit or 64-bit Windows.

![screenshot - 05_09_2018 22_45_30](https://user-images.githubusercontent.com/13388970/45120844-a1d68480-b15f-11e8-86cf-65774fc630c0.png)

This example is running the 32-bit version of Windows, so I select the vc_redist.x86.exe file and download it by clicking **Next**.

![screenshot - 05_09_2018 22_48_22](https://user-images.githubusercontent.com/13388970/45120874-b581eb00-b15f-11e8-8c7f-918723205424.png)

3) Once the file has finished downloading, double click it, and follow the instructions to install it.

4) Restart Windows.

5) Launch LPub3D.

**Comment by trevorsandy** [comment]
Completed.

**Comment by qwertychouskie** [comment]
I hate to break it to you but...  GPL applications can't be linked the the versioned MSVCRT libraries, see https://github.com/supertuxkart/stk-code/issues/3344#issue-341287886 for details. :(

**Comment by trevorsandy** [comment]
I do not interpret what GPL describes - specifically in the excerpt you are indicating - as not supporting linking to the MSVCP140 library or any other system library for that matter.

What I understand is that one may not distribute "system" libraries in compiled form - without the source code - which is essentially the same requirement for any other open source program. Obviously, not having the MSVCP140 source breaks the GPL requirement. So it is precisely because of this requirement that I do not include the MS C++ Redistributable in my packaged distributions and, instead, provide this write-up on how to download and install it onto your system.

Cheers,
