### ISSUE TITLE
Inserting "Rotate" can cause LPub3D to crash

### ISSUE THREAD

**Issue by d-j-m-0** [trevorsandy/lpub3d#82]
### Subject
When using the 3DViewer within LPub3D to insert a rotation of a part in a sub-model, LPub3D will crash if the sub-model does not also contain a "0 STEP" command.

### Environment
* Version of LPub3D - 2.2.2 Revision 0 Build 848
* Operating system - Windows 10 Pro (10.0.17134) , x86_64

### Configuration
N/A

### Logs
N/A

### Screenshots
N/A

### Steps to reproduce
The attached zip file contains two simple models; rotate_crash.mpd and rotate_no_crash.mpd.
[rotate_crash.zip](https://github.com/trevorsandy/lpub3d/files/2355094/rotate_crash.zip)

a.1) Extract "rotate_crash.mpd"
a.2) Open it in LPub3D.
a.3) Select the "3DViewer - by LegoCAD(C)" tab.
a.4) Click on the brick in the viewer.
a.5) Select the "Rotate" toolbar icon and rotate the brick in any direction.
a.6) Click the "Insert ROTSTEP" toolbar icon.
a.7) LPub3D crashes.

b.1) Extract "rotate_no_crash.mpd"
b.2) Open it in LPub3D.
b.3) to b.6)  As per a.3 to a.6) above.
b.7) LPub3D rotates the model successfully.

### Expected behaviour
For both models, the part should be successfully rotated.

### Actual behaviour
See step a.7) above.

### Workaround
Ensure the sub-model contains a "0 STEP" command.

### Solution suggestion
N/A

**Comment by StyletX** [comment]
Hi! Pressing the button "Apply ROTSTEP" again crash Lpub3d...
v.2.3.1 Ubuntu 18.04.1

[Crash.zip](https://github.com/trevorsandy/lpub3d/files/2432528/Crash.zip)

**Comment by trevorsandy** [comment]
v2.3.1 is not yet released - the backward navigation button behaviour was broken so I did not complete the release. 

The behaviour you are experiencing is sourced from the space in the model name. Change 'exo h' to 'exo_h' to avoid the abnormal program end.

I'll take a look at treating this limitation in the next release. 2.3.1 is just about ready to release and I'd rather not delay any further.

Cheers,

**Comment by trevorsandy** [comment]
@StyletX, I went ahead and included the fix in 2.3.1.1 See #119

Cheers,
